-- CraftingOrderClassic_Locale_News_esES.lua — traductions de l'onglet « Nouveautés » (esES).
-- Extrait de _Locale_esES.lua (plafond anti-monolithe). Clé FR → texte ES, chargé APRÈS _Locale.lua.

local COC = CraftingOrderClassic
if (GetLocale and GetLocale() or "") ~= "esES" then return end
local L = COC.L

local news = {
    -- Onglet Nouveautés (changelog en jeu)
    ["Nouveautés"] = "Novedades",
    -- v1.27.2
    ["Un onglet Entrantes, et des demandes qui ne traînent plus"] =
        "Una pestaña Entrantes, y peticiones que ya no se quedan pegadas",
    ["Les demandes captées dans /commerce et /guilde restaient affichées des heures. On en voyait encore une marquée « 20h » le lendemain, bien après que le demandeur ait trouvé quelqu'un d'autre. Elles disparaissent maintenant 30 minutes après avoir été vues, comme un cri dans /commerce. Celle que tu as acceptée, elle, tient six heures : tu t'es engagé dessus."] =
        "Las peticiones captadas en /comercio y /hermandad se quedaban visibles durante horas. Al día siguiente aún se veía una marcada «20h», mucho después de que el comprador hubiera encontrado a otro. Ahora desaparecen 30 minutos después de ser vistas, como un grito en /comercio. La que has aceptado, esa aguanta seis horas, ya te has comprometido con ella.",
    ["La fenêtre métier ne fait plus non plus semblant que tu peux les honorer : elle listait une demande de gemme dont tu n'as pas la recette, bouton Accepter compris, à 190 de compétence pour une taille qui en demande 350. Elle ne montre plus que ce que tu sais vraiment faire (revérifié en direct, donc une recette apprise la fait réapparaître). Ce qu'elle masque reste dans le Carnet pour le passer à un ami capable."] =
        "La ventana de profesión tampoco finge ya que puedes cumplirlas: listaba una petición de una gema cuya receta no tienes, con botón Aceptar incluido, a 190 de habilidad para un tallado que pide 350. Ahora solo muestra lo que sabes hacer de verdad (recomprobado en vivo, así que una receta aprendida la trae de vuelta). Lo que oculta se queda en el Libro para pasárselo a un amigo capaz.",
    ["Et ces demandes du chat ont leur propre onglet Entrantes, avec un compteur à côté. Une demande lue dans /commerce ou poussée par un pair n'a rien à voir avec une vraie commande de l'addon (pas de cycle accepter-livrer, tu réponds au chuchotement à la main) : les mélanger aux onglets Tous / Guilde / Amis / Annuaire embrouillait les deux. Corrigé aussi, une commande arrivée sans métier déclenchait son alerte mais n'apparaissait dans aucune fenêtre métier ; le métier est maintenant déduit de l'objet."] =
        "Y esas peticiones del chat tienen su propia pestaña Entrantes, con un contador al lado. Una petición leída en /comercio o reenviada por otro jugador no tiene nada que ver con un pedido real del addon (sin ciclo aceptar-entregar, respondes al susurro a mano), mezclarlas con las pestañas Todos / Hermandad / Amigos / Directorio enturbiaba ambas cosas. También corregido, un pedido que llegaba sin profesión disparaba su aviso pero no aparecía en ninguna ventana de profesión; ahora la profesión se deduce del objeto.",
    -- v1.27.1
    ["Prêt pour le patch 1.15.9"] = "Listo para el parche 1.15.9",
    ["Classic Era, SoD et Hardcore passent à la 1.15.9 et à sa nouvelle interface. L'addon a été vérifié contre elle et se déclare compatible : le badge [Dispo] au-dessus des plaques fonctionne comme avant. Seule limite, décidée par Blizzard : en instance, les plaques amies sont réservées au jeu lui-même, donc pas de badge en donjon."] =
        "Classic Era, SoD y Hardcore pasan a la 1.15.9 y a su nueva interfaz. El addon se ha comprobado contra ella y se declara compatible, la insignia [Dispo] sobre las placas funciona como antes. Un límite, decisión de Blizzard: en las estancias, las placas amistosas quedan reservadas al propio juego, así que no hay insignia en las mazmorras.",
    ["Corrigé : la liste des PNJ sous une recette manquante (formateurs, vendeurs) mélangeait les deux factions, au point d'envoyer un personnage Alliance à Fossoyeuse. Les PNJ du camp d'en face sont maintenant masqués ; les monstres à butin et les PNJ neutres restent, eux servent tout le monde."] =
        "Corregido: la lista de PNJ bajo una receta que te falta (maestros, vendedores) mezclaba ambas facciones, hasta el punto de mandar a un personaje de la Alianza a Entrañas. Los PNJ del bando contrario ahora se ocultan; los monstruos de botín y los PNJ neutrales se quedan, esos atienden a todos.",
    -- v1.27.0
    ["Prévenu quand une nouvelle version sort"] = "Te avisa cuando sale una versión nueva",
    ["L'addon repère maintenant qu'il tourne en retard. Il lit la version des joueurs que tu croises sur le réseau, et dès qu'il en voit une plus récente chez plusieurs personnes différentes, il te le dit d'une ligne dans le chat et pose un point rouge sur le bouton minimap. Le point s'efface tout seul une fois que tu as mis à jour."] =
        "El addon ahora se da cuenta de si vas con una versión vieja. Lee la versión de los jugadores con los que te cruzas en la red, y en cuanto ve una más nueva en varias personas distintas, te lo dice con una línea en el chat y pone un punto rojo en el botón del minimapa. El punto se borra solo en cuanto actualizas.",
    ["Ce « plusieurs personnes différentes » est voulu : un joueur isolé ne peut pas te faire croire que tu es en retard en annonçant un faux numéro, il faut que des joueurs distincts le confirment. Et ça ne te prévient qu'une fois par version, jamais à chaque connexion. Tape /co version pour voir ta version et s'il en existe une plus récente."] =
        "Eso de « varias personas distintas » es a propósito: un jugador solo no puede hacerte creer que vas atrasado anunciando un número falso, hacen falta jugadores distintos que lo confirmen. Y solo te avisa una vez por versión, no en cada conexión. Escribe /co version para ver tu versión y si hay una más nueva.",
    -- v1.26.0
    ["Filtre n'importe quelle liste par la stat qu'elle donne"] =
        "Filtra cualquier lista por la estadística que da",
    ["Chaque liste de recettes — l'onglet Commande, la fenêtre métier, Mes artisans — reçoit un sélecteur de stat. Tu choisis Force, tu ne vois que ce qui donne de la Force : gemmes, équipements, élixirs. Le menu se remplit avec ce que le métier ouvert fabrique vraiment, donc la Cuisine ne te propose pas Puissance des sorts. Ces stats ne sont écrites nulle part, elles sont lues sur ton propre jeu — dans ta langue, et valables pour des objets que je n'ai jamais regardés, Wrath compris."] =
        "Cada lista de recetas — la pestaña Pedido, la ventana de profesión, Mis artesanos — recibe un selector de estadística. Eliges Fuerza y solo ves lo que da Fuerza: gemas, equipo, elixires. El menú se llena con lo que la profesión abierta fabrica de verdad, así que Cocina no te ofrece Poder con hechizos. Esas estadísticas no están escritas en ningún sitio, se leen de tu propio juego, así que aparecen en tu idioma y siguen funcionando con objetos que nunca he mirado, Wrath incluido.",
    ["L'alchimie se range mieux aussi : les élixirs se regroupent sous la stat qu'ils donnent, pendant que les potions de soin et de mana, les flacons et les transmutations gardent leurs propres en-têtes — « rend de la vie » n'a jamais été une stat. Sur TBC, ça sort 74 consommables du fourre-tout Divers."] =
        "La alquimia también se ordena mejor: los elixires se agrupan según la estadística que dan, mientras que las pociones de vida y maná, los frascos y las transmutaciones conservan sus propios encabezados — «restaura vida» nunca fue una estadística. En TBC eso saca 74 consumibles del montón de Varios.",
    -- v1.25.0
    ["Les gemmes se rangent par couleur, puis par ce qu'elles donnent"] =
        "Las gemas se ordenan por color y luego por lo que dan",
    ["La joaillerie versait toutes les gemmes taillées sous un seul en-tête « Gemme ». Elles se rangent maintenant par couleur de châsse, et sous chaque couleur par la stat qu'elles donnent : « Force - Audacieux », « Endurance - Solide ». Cette stat n'est pas une table écrite à la main, elle est lue sur ton propre jeu — donc dans ta langue, et valable pour des gemmes que je n'ai jamais regardées."] =
        "Joyería volcaba todas las gemas talladas bajo un único encabezado «Gema». Ahora se colocan bajo su color de ranura y, dentro de cada color, según la estadística que dan, como «Fuerza - Audaz» o «Aguante - Sólida». Esa estadística no es una tabla escrita a mano, se lee directamente de tu propio juego, por eso aparece en tu idioma y sigue funcionando con gemas que nunca he mirado.",
    ["Les gemmes méta, elles, reviennent à une simple liste : chaque taille de méta n'existe qu'en un seul exemplaire, un en-tête au-dessus n'aurait fait que répéter la ligne. Bagues, colliers, statues et figurines gardent le classement qu'ils avaient."] =
        "Las gemas meta pasan a una lista simple. De cada talla meta solo existe una gema, así que un encabezado encima no hacía más que repetir la línea de debajo. Anillos, collares, estatuas y figurillas conservan la clasificación que ya tenían.",
    ["Corrigé aussi : quand un enchanteur te demandait une pièce, l'invite ne s'affichait parfois jamais. Une première demande arrivée trop tôt, avant que tu aies équipé la pièce, armait quand même le délai de cinq secondes — et la vraie demande qui suivait passait à la trappe. Le délai ne démarre plus que sur une demande réellement affichée."] =
        "También corregido: cuando un encantador te pedía una pieza, el aviso a veces no aparecía nunca. Una primera petición que llegaba demasiado pronto, antes de que hubieras equipado la pieza, activaba igualmente la espera de cinco segundos, y la petición real que venía después se perdía. La espera ahora solo empieza cuando una petición ha pasado de verdad.",
    -- v1.24.2
    ["Les stats d'enchant parlent enfin ta langue"] =
        "Las estadísticas de encantamiento por fin hablan tu idioma",
    ["Les sous-catégories de la vue enchant (Force, Esprit, Croisé…) venaient d'un libellé interne jamais traduit : tout le monde les voyait en anglais, client français compris. Elles sont maintenant lues directement sur ton jeu, comme les noms de sorts, donc dans ta langue sans rien à traduire à la main à chaque nouvelle recette."] =
        "Las subcategorías de la vista de encantamiento (Fuerza, Espíritu, Cruzado…) venían de una etiqueta interna nunca traducida: todo el mundo las veía en inglés, cliente francés incluido. Ahora se leen directamente de tu juego, igual que los nombres de hechizos, así que aparecen en tu idioma sin nada que traducir a mano con cada receta nueva.",
    -- v1.24.1
    ["Deux minerais de plus dans les commandes de récolte"] =
        "Dos minerales más en los encargos de recolección",
    ["Le khorium et l'éternium n'apparaissaient pas comme commandables dans l'onglet Récolte. La liste des minerais était dérivée de ceux qu'on peut prospecter en gemmes, et ni l'un ni l'autre ne l'est — le même trou qui cachait déjà l'argent, l'or, le vrai-argent et le sombrefer. Les deux rejoignent la liste."] =
        "El korio y el eternio no aparecían como encargables en la pestaña Recolección. La lista de minerales se derivaba de los que se pueden prospectar en gemas, y ninguno de los dos lo es — el mismo hueco que ya escondía la plata, el oro, la veraplata y el hierro negro. Ambos se unen ahora a la lista.",
    -- v1.24.0
    ["La pièce à enchanter se pose d'un clic, et une bourse qui suit la progression"] =
        "La pieza a encantar se coloca con un clic, y una bolsa que sigue el ritmo",
    ["Depuis la v1.21.0, un enchanteur peut cliquer un emplacement de la silhouette d'échange pour te demander la pièce à enchanter. Si tu as l'addon toi aussi, ce clic affiche maintenant une invite chez toi : accepte, et ta pièce équipée se pose toute seule dans l'emplacement « ne sera pas échangé ». Rien n'est donné (cet emplacement ne peut pas changer de mains), la pose est verrouillée sur lui, et rien ne bouge sans ton clic. Sans l'addon en face, le chuchotement explicatif part comme avant."] =
        "Desde la v1.21.0, un encantador puede pulsar una casilla de la silueta de intercambio para pedirte la pieza a encantar. Si tú también usas el addon, ese clic ahora muestra un aviso en tu lado: acepta, y tu pieza equipada se coloca sola en la casilla «No se intercambiará». No entregas nada (esa casilla no puede cambiar de manos), la colocación está bloqueada en ella, y nada se mueve sin tu clic. Sin el addon enfrente, el susurro explicativo sale como antes.",
    ["La bourse d'artisan se met à jour en direct : fenêtre ouverte, chaque point de métier gagné par le personnage suivi (et chaque recette apprise) recalcule la liste de courses — plus besoin de la rouvrir pour voir la route changer."] =
        "La bolsa del artesano ahora se actualiza en vivo: con la ventana abierta, cada punto de oficio que gana el personaje seguido (y cada receta que aprende) recalcula la lista de la compra — ya no hace falta reabrirla para ver cambiar la ruta.",
    -- v1.23.0
    ["La bourse d'artisan : la liste de courses de tes guildeux, et deux corrections réseau"] =
        "La bolsa del artesano: una lista de la compra para tus compañeros de hermandad, y dos correcciones de red",
    ["L'onglet Artisans gagne un bouton sac après les icônes de métier de chaque fiche : un clic ouvre la liste de courses des matériaux qu'il te faut pour monter tes métiers, calculée en local à partir de ce que le jeu diffuse déjà (aucun nouveau trafic réseau). Les réactifs que ton propre métier sait fabriquer sont décomposés en composants de base, et les objets vendus par un PNJ sont mis de côté dans une note plutôt que d'encombrer la grille."] =
        "La pestaña Artesanos gana un botón de bolsa tras los iconos de oficio de cada ficha: un clic abre la lista de la compra de materiales que esa persona necesita para seguir subiendo, calculada en local a partir de lo que el juego ya difunde (sin tráfico de red nuevo). Los reactivos que su propio oficio sabe fabricar más barato se descomponen en componentes base, y los objetos de vendedor se apartan en una nota en vez de saturar la cuadrícula.",
    ["Coche « inclure les plans à acheter » et les recettes derrière un coût rejoignent la liste : les plans-objets comme fourniture à apporter, les plans de formateur comme simple note. Le même bloc de fournitures s'affiche maintenant sous le plan de route « quoi monter ensuite », avec le PNJ où aller (nom, zone, coordonnées) et une épingle TomTom cliquable si tu l'as installé."] =
        "Marca «incluir planos por comprar» y las recetas con coste también se suman a la lista: los planos-objeto como suministro que llevar, los planos de maestro como simple nota. El mismo bloque de suministros aparece ahora bajo la ruta «qué subir a continuación», con el PNJ al que acudir (nombre, zona, coordenadas) y un pin de TomTom pulsable si lo tienes instalado.",
    ["Une recette sans réactif au prix connu (la poussière d'enchantement, par exemple) ne fait plus sauter tout un tronçon du plan de route : elle sert maintenant de repli marqué « ? » quand rien de mieux n'est disponible. Une table de désenchantement maison alimente aussi l'infobulle des poussières, essences et éclats affichés dans ces listes."] =
        "Una receta sin reactivo con precio conocido (el polvo de encantamiento, por ejemplo) ya no elimina todo un tramo de la ruta: ahora sirve de recurso marcado con «?» cuando no hay nada mejor disponible. Una tabla de desencantamiento propia también alimenta el tooltip de polvos, esencias y fragmentos mostrados en estas listas.",
    ["Deux corrections : un compte à plusieurs personnages se voyait parfois lister lui-même comme « joignable via » son autre perso dans son propre onglet Artisans, corrigé. Et le plan de route pouvait s'arrêter avant le vrai plafond de compétence après une formation chez le maître, à cause d'une assignation Lua qui perdait silencieusement sa seconde valeur."] =
        "Dos correcciones: una cuenta con varios personajes a veces se veía a sí misma listada como «accesible vía» su propio alter en su propia pestaña Artesanos, corregido. Y la ruta podía detenerse antes del verdadero tope de habilidad justo después de un ascenso con el maestro, por una asignación múltiple de Lua que perdía en silencio su segundo valor de retorno.",
    -- v1.22.1
    ["Les alertes de commande vérifient enfin le métier, et un plan de route qui suit son propre badge"] =
        "Alertas de pedido que de verdad comprueban el oficio, y una ruta que coincide con su propia insignia",
    ["Une commande à portée large (guilde, amis, tous) déclenchait un toast même chez un joueur sans le métier, du moment qu'elle arrivait par le relais de connexion (chuchotement) plutôt que par le canal : le filtre par métier ne couvrait que le canal. Il s'applique maintenant quel que soit le chemin réseau. Le toast gagne aussi un troisième texte : une commande à portée large n'affiche plus « pour TOI », ce qui donnait l'impression fausse d'une demande personnelle."] =
        "Un pedido de alcance amplio (hermandad, amigos, todos) generaba un aviso incluso a un jugador sin el oficio, siempre que llegara por el relevo de conexión (un susurro) en vez del canal: el filtro de oficio solo cubría el canal. Ahora se aplica sin importar la vía. El aviso también gana un tercer texto: un pedido de alcance amplio ya no muestra «para TI», que sonaba como una petición personal sin serlo.",
    ["Le plan de route « quoi monter ensuite » pouvait suggérer une recette différente du badge de coût de la liste, les deux lisant des données légèrement différentes. Le plan utilise maintenant la difficulté réelle de la fenêtre métier à ton rang actuel plutôt qu'une projection, et se rafraîchit au même rythme que le badge. La commande |cFFFFFFFF/co lvldump|r affiche le détail en cas de nouveau désaccord."] =
        "La ruta «qué subir a continuación» podía sugerir una receta distinta a la insignia de coste de la lista, porque ambas leían datos ligeramente distintos. La ruta usa ahora la dificultad real de la ventana de oficio en tu rango actual en vez de una proyección, y se actualiza al mismo ritmo que la insignia. |cFFFFFFFF/co lvldump|r muestra el detalle si vuelves a ver un desacuerdo.",
    -- v1.22.0
    ["L'aide contextuelle, des dépendances qu'on ne peut plus rater, et une touche Échap qui obéit"] =
        "Ayuda contextual, dependencias imposibles de pasar por alto, y una tecla Escape que obedece",
    ["Un nouveau bouton « i » ouvre l'aide contextuelle du jeu, le même système que Blizzard utilise pour ses propres fenêtres : le fond s'assombrit et une bulle pointe directement sur ce dont il est question. Chaque onglet (Vue Métier, Commande, Récolte, Artisans, Mes artisans, Carnet) a sa propre visite guidée, donc le bouton explique ce qui est réellement affiché plutôt qu'une infobulle générique."] =
        "Un nuevo botón «i» abre la ayuda contextual del propio juego, el mismo sistema que usa Blizzard para sus ventanas: el fondo se oscurece y un globo señala directamente lo que está en cuestión. Cada pestaña (Vista de oficio, Pedido, Recolección, Artesanos, Mis artesanos, Libro) tiene su propio recorrido, así que el botón explica lo que realmente se ve en pantalla en vez de un tooltip genérico.",
    ["Lazy Gold et MTSL restent optionnels, mais rien ne signalait qu'ils manquaient. Les boutons qui en dépendent restent visibles et colorés même sans l'addon installé, et cliquer dessus sans l'avoir ouvre désormais une explication de ce qu'il fait et où le trouver, plutôt que de ne rien faire du tout."] =
        "Lazy Gold y MTSL siguen siendo opcionales, pero nada indicaba que faltaran. Los botones que los necesitan siguen visibles y coloreados tengas o no el addon instalado, y pulsar uno sin tenerlo ahora abre una breve explicación de qué hace y dónde conseguirlo, en vez de no hacer nada.",
    ["L'alerte « peut faire cette commande » se déclenchait même quand tu ne connaissais pas la recette, souvent des gemmes ou enchants dont tu avais les réactifs sans le plan. Elle vérifie maintenant tes recettes connues avant de te notifier sur tes propres commandes. Un ami en ligne sans l'addon ne s'affiche plus « Hors ligne » par erreur."] =
        "La alerta «puede hacer este pedido» saltaba incluso cuando no conocías la receta, normalmente gemas o encantamientos para los que tenías los reactivos pero no el plano. Ahora comprueba tus recetas conocidas antes de avisarte sobre tus propios pedidos. Un amigo conectado sin el addon ya no aparece como desconectado por error.",
    ["Échap laissait souvent les fenêtres de métier ouvertes, et trois rapports différents pointaient la même cause : cacher ou désactiver la souris d'une fenêtre protégée en plein combat déclenche une erreur du jeu. Les fenêtres passent maintenant par un petit relais dédié, donc Échap les ferme proprement, en combat ou non."] =
        "Escape solía dejar las ventanas de oficio abiertas la mayoría de las veces, y tres informes de fallo distintos señalaban la misma causa: ocultar o desactivar el ratón de una ventana protegida en pleno combate provoca un error del juego. Las ventanas ahora pasan por un pequeño relé dedicado, así que Escape las cierra limpiamente, en combate o no.",
    ["L'aide « quoi monter ensuite » affiche maintenant le coût par point de compétence, une pastille de prix Auctioneer, et une icône vers le PNJ qui vend une recette que tu ne connais pas encore, en plus d'un tri affiné."] =
        "La ayuda de «qué subir a continuación» ahora muestra el coste por punto de habilidad, una insignia de precio de Auctioneer, y un icono hacia el vendedor que tiene una receta que aún no conoces, además de un orden más afinado.",
    ["Cette même aide gagne un plan de route : clique le bouton carte et il déroule toute ta montée rang par rang, en choisissant à chaque étape la recette la moins chère (apprise ou achetable, plans compris) et en additionnant le coût total. Les recettes à cooldown ou avec un réactif sans prix connu sont exclues exprès, elles fausseraient le total. Demande Lazy Gold ; MTSL ajoute les prix de plans formateur et vendeur au calcul."] =
        "Esa misma ayuda ahora tiene un planificador de ruta: haz clic en el botón de mapa y recorre toda tu subida rango por rango, eligiendo en cada paso la receta más barata (aprendida o comprable, planos incluidos) y sumando el coste total. Las recetas con tiempo de reutilización o con un reactivo sin precio conocido quedan excluidas a propósito, falsearían el total. Necesita Lazy Gold; MTSL añade los precios de planos de entrenador y vendedor al cálculo.",
    -- v1.21.0
    ["L'enchant par emplacement, et un panneau d'échange qui ne cache plus rien"] =
        "Encantamientos por ranura, y un panel de intercambio que ya no esconde nada",
    ["Choisir un enchant demandait de fouiller des centaines de plans aux noms presque identiques. L'onglet Commande a maintenant une vue silhouette : clique l'emplacement à enchanter, tu obtiens ses stats, puis ses variantes de la plus forte à la plus faible. La bascule est dans la bande de filtres ; la liste reste pour tout ce qui n'a pas d'emplacement (huiles, baguettes, produits de désenchantement)."] =
        "Elegir un encantamiento obligaba a rebuscar entre cientos de planos con nombres casi idénticos. La pestaña Pedido ahora tiene una vista de silueta: haz clic en la ranura que quieres encantar y obtienes sus estadísticas y luego sus variantes, de la más fuerte a la más débil. El interruptor está en la barra de filtros; la lista sigue ahí para todo lo que no tiene ranura (aceites, varitas, productos de desencantamiento).",
    ["Le panneau d'enchant de l'échange n'affichait que 8 lignes, et le « +N autre(s) » du bas n'était pas cliquable : au-delà de la 8ᵉ place, un enchant était tout bonnement inatteignable — c'est ainsi qu'un enchanteur à qui on avait passé les réactifs ne se voyait jamais proposer la bonne recette, noyée sous les variantes de haut rang. La liste défile à la molette, et elle est classée par ce qu'on te demande : d'abord les enchants dont ton partenaire vient de poser les réactifs, puis ce que tes sacs permettent, puis le reste."] =
        "El panel de encantamiento del intercambio solo mostraba 8 líneas, y el «+N más» de abajo no se podía pulsar: a partir del noveno, un encantamiento era sencillamente inalcanzable. Así es como a un encantador al que le habían pasado los reactivos nunca se le ofrecía la receta correcta, enterrada bajo variantes de rango superior. La lista se desplaza con la rueda del ratón y está ordenada por lo que te están pidiendo: primero los encantamientos cuyos reactivos tu compañero acaba de poner sobre la mesa, luego lo que tus bolsas ya permiten, y después el resto.",
    ["Tant que la case « ne sera pas échangé » est vide, le panneau ne disparaît plus : il montre la même silhouette, avec le modèle de ton partenaire, et cliquer un emplacement lui chuchote d'y poser cette pièce. La plupart des gens qui te tendent un objet ignorent que cette case existe."] =
        "Mientras la casilla «No se intercambiará» esté vacía, el panel ya no desaparece: muestra la misma silueta, con el modelo de tu compañero dentro, y al pulsar una ranura le susurras que ponga esa pieza ahí. La mayoría de quienes te dan equipo no saben que esa casilla existe.",
    ["Deux correctifs : les enchants de poignets et de bâton de Wrath n'apparaissaient jamais dans le panneau d'échange (le jeu les écrit « Bracers » et « Staff » là où les autres extensions disent « Bracer »), et un enchant de bâton ne se propose plus que sur un vrai bâton. Le panneau ne touche plus non plus à ses boutons pendant un combat, ce que le jeu interdit."] =
        "Dos correcciones: los encantamientos de muñecas y de bastón de Wrath no aparecían nunca en el panel de intercambio (el juego los escribe «Bracers» y «Staff» donde las demás expansiones dicen «Bracer»), y un encantamiento de bastón solo se ofrece ya sobre un bastón de verdad. Además, el panel ya no toca sus botones mientras estás en combate, algo que el juego bloquea de todos modos.",
    ["Plus discret : les lignes de chat « X sait faire cette commande captée » sont désactivées par défaut — la commande est poussée aux amis capables dans tous les cas, le message n'était que du bruit. |cFFFFFFFF/co verbose|r les remet."] =
        "Más discreto: las líneas de chat «X sabe hacer ese pedido captado» están desactivadas por defecto. El pedido se envía igualmente a los amigos capaces, así que el mensaje solo era ruido. |cFFFFFFFF/co verbose|r las devuelve.",
    -- v1.20.0
    ["Enchante en un clic, trié par emplacement, et depuis l'échange"] = "Encanta con un clic, ordenado por ranura, y desde el intercambio",
    ["Le bouton « Créer » de l'Enchantement avait un vieux bug intermittent : parfois rien ne se passait, et resélectionner la recette finissait par le faire marcher. Cause trouvée : sélectionner une recette n'arme pas le bouton natif de Blizzard, notre clic sécurisé tombait donc sur un bouton désactivé. Corrigé — ça devrait marcher du premier coup, à chaque fois."] =
        "El botón «Crear» de Encantamiento tenía un viejo fallo intermitente: a veces no pasaba nada, y volver a seleccionar la receta varias veces acababa haciéndolo funcionar. Causa encontrada: seleccionar una receta no activa el botón nativo de Blizzard, así que nuestro clic seguro caía en un botón desactivado. Corregido: ahora debería funcionar a la primera, siempre.",
    ["Les recettes d'enchantement ne s'entassent plus dans un fourre-tout « Autres/Divers » : elles se rangent par emplacement (Poignets, Torse, Main gauche…) puis par stat de base (Force, Esprit, Déviation), le nom raccourci à la stat seule puisque l'emplacement est déjà dans l'en-tête."] =
        "Las recetas de encantamiento ya no se amontonan en un cajón «Otros/Varios»: se ordenan por ranura (muñecas, torso, mano izquierda…) y luego por estadística base (fuerza, espíritu, desviación), con el nombre recortado a solo la estadística ya que la ranura está en el encabezado.",
    ["Sélectionner un enchant d'équipement affiche un bouton « Enchanter équipé » à côté de Créer : un clic l'applique directement sur la pièce que tu portes, sans avoir à cibler."] =
        "Al seleccionar un encantamiento de equipo aparece un botón «Encantar equipado» junto a Crear: un clic lo aplica directamente sobre la pieza que llevas puesta, sin tener que apuntar.",
    ["Et quand quelqu'un te tend un objet à enchanter en échange, le poser dans la case « ne sera pas échangé » ouvre un petit panneau listant tes enchants pour cet emplacement, prêts à lancer sans fouiller ta fenêtre de métier (qui doit rester ouverte : le jeu ne renseigne tes recettes connues que pendant qu'elle l'est)."] =
        "Y cuando alguien te da un objeto para encantar en un intercambio, ponerlo en la casilla «no se intercambiará» abre un pequeño panel con tus encantamientos para esa ranura, listos para lanzar sin rebuscar en tu ventana de profesión (que debe seguir abierta: el juego solo informa de tus recetas conocidas mientras lo está).",
    -- v1.19.1
    ["Correctif : l'icône « dispo » remarche sur la nouvelle UI des plaques"] = "Corrección: el icono de disponibilidad vuelve a funcionar en la nueva interfaz de placas",
    ["Sur le client TBC (et bientôt Era/Saison de la Découverte à la 1.15.9), l'icône « recherche de travail » au-dessus de la plaque d'un artisan cessait de s'afficher quand son statut changeait : la nouvelle interface de plaques a renommé un champ interne que l'addon lisait. Corrigé. Elle reste invisible en instance (donjon, raid) : le jeu verrouille les plaques amies aux addons là-bas, rien à faire de notre côté."] =
        "En el cliente de TBC (y pronto en Era/Temporada del Descubrimiento con el parche 1.15.9), el icono de «buscar trabajo» sobre la placa de un artesano dejaba de mostrarse cuando cambiaba su estado: la nueva interfaz de placas renombró un campo interno que leía el complemento. Corregido. Sigue sin verse dentro de una instancia (mazmorra, banda): el juego bloquea las placas amistosas a los complementos ahí, no hay nada que podamos hacer al respecto.",
    -- v1.19.0
    ["Propose des recettes précises, diffuse tes réactifs, et le LFW marche même sans l'addon"] = "Recetas en tu oferta, un botón para compartir, y LFW sin el complemento",
    ["« Chercher du travail » propose maintenant des recettes précises, pas seulement des réactifs : coche des plans dans la liste et qui te consulte voit « propose : Bouclier de fer, Gilet de mailles de cuivre » à côté de ce que tu fournis déjà."] =
        "«Buscar trabajo» ahora te deja indicar recetas concretas, no solo reactivos. Marca planos en la lista de recetas y quien consulte tu oferta ve «ofrece: Escudo de hierro, Chaleco de malla de cobre» junto a los materiales que ya aportas.",
    ["Un bouton « Diffuser » envoie la liste de réactifs d'une recette ou d'une commande dans un canal au choix (guilde, dire, groupe/raid, un canal numéroté), avec le lien de chaque objet — une liste de courses en un clic, depuis la vue métier, la carte de commande ou le panneau de publication."] =
        "Un botón «Compartir» envía la lista de reactivos de una receta o un encargo a un canal a elegir (gremio, decir, grupo/banda, un canal numerado), con el enlace de cada objeto — una lista de la compra con un clic, desde la ventana de profesión, la ficha del encargo o el panel de publicación.",
    ["Le LFW marche même sans l'addon : tape « LFW enchantement » en Commerce ou Général et tu apparais comme dispo, avec la même icône de plaque qu'un joueur qui a Crafting Order. Plus une correction : une recette déjà apprise ne s'affichait plus en double avec MissingTradeSkillsList."] =
        "Buscar trabajo funciona incluso sin el complemento: escribe «LFW encantamiento» en Comercio o General y apareces como disponible, con el mismo icono de placa que alguien con Crafting Order. Además, una corrección: una receta ya aprendida dejaba de aparecer duplicada con MissingTradeSkillsList.",
    -- v1.18.0
    ["Chercher du travail : dis ce que tu offres, et trie par progression"] = "Buscar trabajo, ahora con oferta, y ordenar por lo que te sube de nivel",
    ["« Chercher du travail » ne se contente plus de te signaler dispo. Clique l'engrenage à côté du bouton et dis ce que tu proposes : tu fournis les composants de base, tu fournis tel réactif précis, une commission fixe par craft, ou seulement les plans qui te font gagner un point de compétence. Ça s'affiche sur ta ligne [Dispo] et dans l'infobulle au-dessus de ta tête, avec une pièce s'il y a une commission et un sac si tu fournis des compos."] =
        "«Buscar trabajo» hace más que marcarte como disponible. Pulsa el engranaje junto al botón y di qué ofreces: pones los componentes básicos, aportas un reactivo concreto, una comisión fija por objeto, o solo los planos que te dan un punto de habilidad. Aparece en tu línea [Dispo] y en la información sobre tu cabeza, con una moneda si hay comisión y una bolsa si aportas materiales.",
    ["L'icône « dispo » au-dessus de la plaque d'un artisan marche maintenant sur Era et Saison de la Découverte, plus seulement sur le client TBC. Active les plaques des amis (nameplateShowFriends) et l'icône du métier flotte au-dessus de qui cherche du travail à côté de toi."] =
        "El icono de «disponible» sobre la placa de un artesano ya funciona en Era y Temporada del Descubrimiento, no solo en el cliente de Burning Crusade. Activa las placas de amigos (nameplateShowFriends) y el icono de profesión flota sobre quien busca trabajo cerca de ti.",
    ["Les recettes se trient par ce qui te fait encore progresser : un troisième bouton outil remonte en tête les plans qui donnent un point, d'orange à gris. Les commandes ont le même « ce qui me fait monter d'abord », avec un liseré de difficulté sur le côté de chaque ligne. Plus quelques corrections au passage."] =
        "Las recetas se ordenan por lo que aún te sube de nivel: un tercer botón de herramienta sube los planos que dan un punto de habilidad, de naranja a gris. Los encargos tienen el mismo «lo que me sube primero», con un ribete de dificultad en el lateral de cada línea. Además de unas cuantas correcciones de paso.",
    -- v1.17.1
    ["Correctif : erreur au login en « Chercher du travail »"] = "Corregido: error al conectar con «Buscar trabajo»",
    ["Si tu avais activé « Chercher du travail », te connecter ou faire /reload pouvait déclencher une erreur rouge : l'addon annonçait ta disponibilité avant que le jeu n'autorise un addon à parler sur le canal. L'annonce attend maintenant ton prochain clic ou ta prochaine touche — plus d'erreur, et les autres te voient toujours dispo."] =
        "Si tenías activado «Buscar trabajo», conectarte o hacer /reload podía provocar un error rojo: el addon anunciaba tu disponibilidad antes de que el juego permita a un addon hablar en el canal. El anuncio ahora espera a tu siguiente clic o tecla — sin más errores, y los demás siguen viéndote disponible.",
    -- v1.17.0
    ["L'interface passe au style natif de WoW"] = "La ventana ahora combina con el juego",
    ["La fenêtre n'a plus son habillage doré maison : elle emprunte le cadre du jeu (barre de titre, portrait rond, onglets, boutons). Elle se fond dans l'interface au lieu de ressembler à un addon posé par-dessus, et rien n'a bougé de ce que tu connais."] = "La ventana ha cambiado su aspecto dorado propio por el marco del juego (barra de título, retrato redondo, pestañas arriba, botones). Ahora se integra en la interfaz en vez de parecer un addon añadido por encima, y nada se ha movido de lo que ya conoces.",
    ["La vue métier est refaite, avec une colonne Commandes en liste : une ligne par commande (demandeur, objet voulu, prix), et le clic ouvre la carte complète (composants fournis, coût des réactifs, Accepter / Refuser / Chuchoter) avec une croix pour revenir à la liste. Et les sous-catégories de récolte (Peaux, Écailles, Herbes, Poissons) sont enfin traduites hors client français."] = "La ventana de profesión se ha rehecho, con la columna de pedidos como lista: una línea por pedido (solicitante, objeto deseado, precio), y al hacer clic se abre la ficha completa (componentes aportados, coste de reactivos, Aceptar / Rechazar / Susurrar) con una cruz para volver a la lista. Y las subcategorías de recolección (Pieles, Escamas, Hierbas, Peces) por fin están traducidas fuera de un cliente francés.",
    -- v1.15.1
    ["Tes commandes n'appartiennent qu'à toi"] = "Tus pedidos son solo tuyos",
    ["Recettes triées, et où est l'or"] = "Recetas ordenadas, y dónde está el oro",
    ["Fini le fourre-tout « Consommable » : les recettes sont regroupées par type (potions de soin, de mana, élixirs, flacons, transmutations…) et triées du plus haut niveau au plus bas. Une potion qui rend vie ET mana apparaît sous les deux. Le même classement s'applique partout — Commande, Mes artisans, et les métiers de récolte (minerais, herbes, cuirs, poissons)."] = "Se acabó el cajón de sastre \"Consumible\": las recetas se agrupan por tipo (pociones de curación, de maná, elixires, frascos, transmutaciones…) y se ordenan del nivel más alto al más bajo. Una poción que restaura vida Y maná aparece en ambas. La misma agrupación se aplica en todas partes — Pedir, Mis artesanos y las profesiones de recolección (minerales, hierbas, cueros, peces).",
    ["Si tu as Lazy Gold, chaque recette affiche sa rentabilité (pièces, étoiles au-delà de mille pièces d'or ; rien pour une perte). La pièce d'or au-dessus de la liste trie par profit, le bouton « 123 » bascule en valeurs exactes. L'onglet Commande a les deux boutons, plus la valeur HV et le coût des réactifs sur chaque commande entrante."] = "Si usas Lazy Gold, cada receta muestra su rentabilidad (monedas, estrellas más allá de mil de oro; nada si hay pérdida). La moneda de oro sobre la lista ordena por beneficio, el botón \"123\" cambia a valores exactos. La pestaña Pedir tiene ambos botones, más el valor de subasta y el coste de los reactivos en cada pedido entrante.",
    ["Dans l'annuaire, les métiers passent en icônes : un artisan avec un plan vraiment rentable a un contour doré, le survol nomme le plan, le clic ouvre la Commande déjà ciblée. « Mes artisans » gagne « Tous les plans du royaume » : tous tes persos (même faction) fusionnés et triés par profit — d'un coup d'œil, quel reroll fait des sous. Et si tu as MissingTradeSkillsList, un bouton montre tes recettes non apprises en rouge, avec leur source au clic."] = "En el directorio, las profesiones pasan a iconos: un artesano con un plan realmente rentable tiene un borde dorado, al pasar el cursor se nombra el plan, al hacer clic se abre Pedir ya dirigido a él. Mis artesanos gana \"Todos los planos del reino\": todos tus personajes (misma facción) fusionados y ordenados por beneficio — de un vistazo, qué alter gana dinero. Y si usas MissingTradeSkillsList, un botón muestra tus recetas no aprendidas en rojo, con su origen al hacer clic.",
    ["Les identifiants de commande étaient devinables : n'importe qui pouvait réécrire la tienne (acheteur, prix, quantité). C'est fermé : seul son auteur peut la modifier. Le relais entre joueurs, lui, continue de fonctionner — c'est comme ça qu'une commande atteint quelqu'un que le canal n'a jamais touché."] =
        "Los identificadores de pedido se podían adivinar, y cualquiera podía reescribir el tuyo (comprador, precio, cantidad). Eso está cerrado: solo quien publicó un pedido puede modificarlo. El relevo entre jugadores sigue funcionando, que es como un pedido llega a alguien a quien el canal nunca alcanzó.",
    ["On ne peut plus te faire mettre en sourdine en postant de fausses commandes en ton nom, et un acheteur dont les commandes sont relayées en rafale n'est plus muté par erreur. « X a refusé ta commande » et le rappel « tu sais le faire » ne se rejouent plus en boucle, et rien ne passe d'un joueur que tu as mis en sourdine."] =
        "Nadie puede conseguir que te silencien publicando pedidos falsos en tu nombre, y un comprador cuyos pedidos se retransmiten en ráfaga ya no se silencia por error. «X ha rechazado tu pedido» y el aviso «sabes hacerlo» ya no se repiten en bucle, y no pasa nada de alguien a quien has silenciado.",
    ["La vue métier n'affiche plus les commandes privées destinées à quelqu'un d'autre, ni les expirées. Ton compteur de crafts livrés ne peut plus être gonflé par un tiers. Et croiser un artisan coûte deux fois moins de messages : le bonjour porte maintenant tes métiers, ce qui règle aussi les artisans qui s'affichaient sans aucun métier."] =
        "La ventana de profesión ya no muestra pedidos privados destinados a otra persona, ni los caducados. Tu contador de encargos entregados no puede inflarlo un tercero. Y cruzarte con un artesano cuesta la mitad de mensajes: el saludo ahora lleva tus profesiones, lo que también arregla los artesanos que aparecían sin ninguna profesión.",
    -- v1.15.0
    ["Recherche de travail : signale que tu es dispo"] = "Buscar trabajo: avisa que estás disponible",
    ["Ouvre un métier et clique « Chercher du travail » : tout le royaume sait que tu es dispo, une icône d'artisan s'affiche au-dessus de ta tête pour ceux qui passent, et tu apparais « [Dispo] » dans leur annuaire. Ça s'éteint tout seul au bout d'un moment si tu oublies."] =
        "Abre una profesión y haz clic en «Buscar trabajo»: todo el reino sabe que estás disponible, un icono de artesano aparece sobre tu cabeza para quien pase, y sales como «[Busca]» en su directorio. Se apaga solo al cabo de un rato si lo olvidas.",
    ["Au passage : les deux fenêtres ne s'emmêlent plus (un clic la ramène au premier plan), l'annuaire a un bouton partenaire et se limite à ta faction (pas d'échange cross-faction sur Classic), et un artisan ne s'affiche plus avec un métier qui n'est pas le sien."] =
        "De paso: las dos ventanas ya no se enredan (un clic la trae al frente), el directorio tiene un botón de socio y se limita a tu facción (sin comercio entre facciones en Classic), y un artesano ya no muestra una profesión que no es suya.",
    -- (clés v1.8.0/v1.7.0/v1.7.1/v1.6.0/v1.5.0/v1.4.0 retirées : ces versions ne sont plus listées dans l'onglet Nouveautés)
    -- Onglet Nouveautés — v1.13.0
    ["Modération : mutes avec raison, temporaires, liste de confiance"] = "Moderación: silencios con motivo, temporales, lista de confianza",
    ["Un mute porte désormais une raison et une date, et peut être temporaire : |cFFFFFFFF/co mute Bob 1h spammeur|r se lève tout seul au bout d'une heure (|cFFFFFFFF/co mute|r seul liste les mutés avec raison et temps restant). Et |cFFFFFFFF/co trust <nom>|r marque un joueur de confiance, jamais mis en sourdine automatiquement — le mute manuel restant toujours possible."] =
        "Un silencio ahora lleva un motivo y una fecha, y puede ser temporal: |cFFFFFFFF/co mute Bob 1h spammer|r se levanta solo tras una hora (|cFFFFFFFF/co mute|r solo lista a los silenciados con motivo y tiempo restante). Y |cFFFFFFFF/co trust <nombre>|r marca a un jugador como de confianza, nunca silenciado automáticamente — el silencio manual sigue disponible.",
    -- (clés v1.12.1 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    -- Onglet Nouveautés — v1.12.0
    ["Les recettes de la Saison de la Découverte"] = "Recetas de la Temporada de Descubrimientos",
    ["304 recettes de la Saison de la Découverte entrent au catalogue : 80 en Travail du cuir, 65 en Forge, 57 en Couture, 48 en Enchantement, 29 en Ingénierie, 16 en Alchimie, plus la Cuisine, le Secourisme et le Minage. Elles apparaissent dans l'onglet Commande, avec leurs réactifs et leur palier d'apprentissage."] =
        "304 recetas de la Temporada de Descubrimientos entran en el catálogo: 80 de Peletería, 65 de Herrería, 57 de Sastrería, 48 de Encantamiento, 29 de Ingeniería, 16 de Alquimia, más Cocina, Primeros auxilios y Minería. Aparecen en la pestaña Pedido, con sus reactivos y su nivel de aprendizaje.",
    ["Elles ne se chargent que sur un royaume Saison de la Découverte. Sur un royaume Era classique, rien ne change : l'addon voit exactement le même jeu de recettes qu'avant, et les recettes que tes amis t'ont déjà partagées restent lisibles."] =
        "Solo se cargan en un reino de la Temporada de Descubrimientos. En un reino Era normal no cambia nada: el addon ve exactamente el mismo conjunto de recetas que antes, y las recetas que tus amigos ya te compartieron siguen siendo legibles.",
    -- Onglet Nouveautés — v1.11.0
    ["Annuler une commande publique atteint tout le royaume"] = "Cancelar un pedido público ahora llega a todo el reino",
    ["Une commande publique voyage sur le canal du royaume depuis la v1.10.0, mais pas son annulation : un artisan que tu n'as jamais croisé la voyait « ouverte » pendant six heures, l'acceptait, et farmait les réactifs pour rien. L'annulation part désormais sur le même canal."] =
        "Un pedido público viaja por el canal del reino desde la v1.10.0, pero su cancelación no. Un artesano que nunca has cruzado lo veía « abierto » durante seis horas, lo aceptaba y reunía los reactivos para nada. La cancelación sale ahora por el mismo canal.",
    ["Poster et annuler ne perdent plus de messages. Le canal exige un clic ou une touche et n'accepte qu'une ligne par seconde : un |cFFFFFFFF/co post|r tapé au chat, ou deux commandes postées dans la même seconde, disparaissaient sans trace. Ces lignes patientent maintenant dans une file et partent à ton prochain clic."] =
        "Publicar y cancelar ya no pierden mensajes. El canal necesita un clic o una tecla para llevar una línea, y acepta una línea por segundo: un |cFFFFFFFF/co post|r escrito en el chat, o dos pedidos publicados en el mismo segundo, desaparecían sin rastro. Esas líneas ahora esperan en una cola y salen en tu siguiente clic.",
    ["Seules les commandes NOUVELLES et les ANNULATIONS voyagent sur le canal, et seulement les publiques. Guilde, amis et commandes nommées restent privées ; les acceptations restent entre les deux joueurs concernés."] =
        "Solo los pedidos NUEVOS y las CANCELACIONES viajan por el canal, y solo los públicos. Los pedidos de hermandad, de amigos y con destinatario siguen siendo privados; las aceptaciones quedan entre los dos jugadores implicados.",
    -- Onglet Nouveautés — v1.10.2
    ["Correctif : erreur en combat dans la vue métier"] = "Corrección: un error en combate en la vista de profesión",
    ["Sélectionner une recette pendant un combat ne provoque plus d'erreur bloquée : le bouton « Créer » est un bouton sécurisé, que le jeu interdit de masquer en plein combat. L'addon attend maintenant la fin du combat pour l'afficher ou le masquer."] =
        "Seleccionar una receta durante el combate ya no provoca un error bloqueado. El botón Crear es un botón seguro, y el juego prohíbe ocultarlo en pleno combate. El addon espera ahora al final del combate para mostrarlo u ocultarlo.",
    -- Onglet Nouveautés — v1.14.0
    ["Un panneau pour gérer les mis en sourdine"] = "Un panel para gestionar a los silenciados",
    ["L'onglet Artisans a maintenant une section « En sourdine » : chaque joueur muté y apparaît avec sa raison et le temps restant (ou « permanent »), avec un bouton pour le rétablir directement — plus besoin de deviner qui est encore muté."] =
        "La pestaña Artesanos ahora tiene una sección «Silenciados»: cada jugador silenciado aparece con su motivo y el tiempo restante (o «permanente»), con un botón para reactivarlo directamente — sin adivinar quién sigue silenciado.",
    -- (clés v1.9.0 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    ["VU"] = "VISTO",
    ["vu crafter (sans l'addon)"] = "visto fabricando (sin el addon)",
    ["vu crafter"] = "visto fabricando",
    ["%d+ · vu crafter"] = "%d+ · visto fabricando",
    -- Cooldowns de recettes (transmutations & co)
    ["%s : prête"] = "%s: lista",
    ["%s : dans %s"] = "%s: en %s",
    ["(estimé)"] = "(estimado)",
    ["Transmutation"] = "Transmutación",
    ["%dj"] = "%dd", ["%dh"] = "%dh", ["%dmin"] = "%dmin",
    -- Relais partenaire
    ["via %s · il y a %s"] = "vía %s · hace %s",
    ["RELAIS"] = "RELEVO",
    -- Rerolls (identité joueur multi-persos, /co alts — opt-in)
    ["rerolls : ACTIVÉS — ta liste de persos est annoncée au réseau."] =
        "alters: ACTIVADOS — tu lista de personajes se anuncia a la red.",
    ["rerolls : désactivés — rien n'est annoncé (opt-in : /co alts on)."] =
        "alters: desactivados — no se anuncia nada (opt-in: /co alts on).",
    ["perso principal (vitrine) : %s"] = "personaje principal (escaparate): %s",
    ["persos du compte (%s) : %s"] = "personajes de la cuenta (%s): %s",
    ["le lien n'est vérifié chez les autres qu'après une connexion de CHAQUE perso (addon actif)."] =
        "los demás solo verifican el vínculo cuando CADA personaje se ha conectado una vez (addon activo).",
    ["rerolls activés — perso principal : %s (changer : /co alts main <nom>)"] =
        "alters activados — personaje principal: %s (cambiar: /co alts main <nombre>)",
    ["rerolls désactivés — dissolution annoncée au réseau."] =
        "alters desactivados — disolución anunciada a la red.",
    ["perso inconnu sur ce compte : %s (connecte-le une fois avec l'addon)"] =
        "personaje desconocido en esta cuenta: %s (conéctalo una vez con el addon)",
    ["regrouper tes rerolls (opt-in) : liste annoncée, commandes routées vers ton perso connecté"] =
        "agrupar tus alters (opt-in): lista anunciada, pedidos dirigidos a tu personaje conectado",
    ["commande nommée pour %s : connecte ce perso, ou active /co alts on pour accepter d'ici."] =
        "pedido dirigido a %s: conecta ese personaje, o activa /co alts on para aceptar desde aquí.",
    ["|cFFFFCC00commande pour ton reroll %s|r de |cFFFFFFFF%s|r : %s%s%s"] =
        "|cFFFFCC00pedido para tu alter %s|r de |cFFFFFFFF%s|r: %s%s%s",
    ["En ligne via %s"] = "En línea vía %s",
    ["reroll : %s (%s)"] = "alter: %s (%s)",
}

for k, v in pairs(news) do L[k] = v end
