-- CraftingOrderClassic_Locale_News_enUS.lua — traductions de l'onglet « Nouveautés » (enUS/enGB).
-- Extrait de _Locale_enUS.lua : l'onglet Nouveautés grossit à chaque release et faisait déborder le
-- plafond anti-monolithe. Isolé ici, il a de la marge (fenêtre glissante côté UI_News). Même contrat :
-- clé FR → texte EN, chargé APRÈS _Locale.lua, early-return hors locale.

local COC = CraftingOrderClassic
local loc = GetLocale and GetLocale() or "enUS"
if loc ~= "enUS" and loc ~= "enGB" then return end
local L = COC.L

local news = {
    -- Onglet Nouveautés (changelog en jeu)
    ["Nouveautés"] = "What's New",
    -- v1.27.2
    ["Un onglet Entrantes, et des demandes qui ne traînent plus"] =
        "An Incoming tab, and requests that don't linger",
    ["Les demandes captées dans /commerce et /guilde restaient affichées des heures. On en voyait encore une marquée « 20h » le lendemain, bien après que le demandeur ait trouvé quelqu'un d'autre. Elles disparaissent maintenant 30 minutes après avoir été vues, comme un cri dans /commerce. Celle que tu as acceptée, elle, tient six heures : tu t'es engagé dessus."] =
        "Requests picked up from /trade and /guild used to hang around for hours. One would still read \"20h\" the next day, long after the buyer had found someone else. They now disappear 30 minutes after they're seen, the way a shout in /trade works. One you've accepted sticks around six hours, since you've committed to it.",
    ["La fenêtre métier ne fait plus non plus semblant que tu peux les honorer : elle listait une demande de gemme dont tu n'as pas la recette, bouton Accepter compris, à 190 de compétence pour une taille qui en demande 350. Elle ne montre plus que ce que tu sais vraiment faire (revérifié en direct, donc une recette apprise la fait réapparaître). Ce qu'elle masque reste dans le Carnet pour le passer à un ami capable."] =
        "The profession window also stopped pretending you could fill them. It listed a request for a gem you have no recipe for, Accept button and all, at skill 190 for a cut that needs 350. It now only shows what you can really craft (rechecked live, so a recipe you learn brings the request back). Whatever it hides stays in the Ledger for you to hand off to a capable friend.",
    ["Et ces demandes du chat ont leur propre onglet Entrantes, avec un compteur à côté. Une demande lue dans /commerce ou poussée par un pair n'a rien à voir avec une vraie commande de l'addon (pas de cycle accepter-livrer, tu réponds au chuchotement à la main) : les mélanger aux onglets Tous / Guilde / Amis / Annuaire embrouillait les deux. Corrigé aussi, une commande arrivée sans métier déclenchait son alerte mais n'apparaissait dans aucune fenêtre métier ; le métier est maintenant déduit de l'objet."] =
        "And those chat requests get their own Incoming tab, with a count next to it. A request read off /trade or forwarded by a peer is nothing like a real addon order (no accept-deliver cycle, you answer them in whisper by hand), so mixing them into the All / Guild / Friends / Directory tabs muddied both. Also fixed, an order that arrived without a profession fired its alert but showed up in no profession window; the profession is now worked out from the item.",
    -- v1.27.1
    ["Prêt pour le patch 1.15.9"] = "Ready for patch 1.15.9",
    ["Classic Era, SoD et Hardcore passent à la 1.15.9 et à sa nouvelle interface. L'addon a été vérifié contre elle et se déclare compatible : le badge [Dispo] au-dessus des plaques fonctionne comme avant. Seule limite, décidée par Blizzard : en instance, les plaques amies sont réservées au jeu lui-même, donc pas de badge en donjon."] =
        "Classic Era, SoD and Hardcore move to 1.15.9 and its new interface. The addon has been checked against it and marks itself compatible, the [LFW] badge above nameplates works like before. One limit, Blizzard's call: inside instances, friendly nameplates belong to the game itself, so no badge in dungeons.",
    ["Corrigé : la liste des PNJ sous une recette manquante (formateurs, vendeurs) mélangeait les deux factions, au point d'envoyer un personnage Alliance à Fossoyeuse. Les PNJ du camp d'en face sont maintenant masqués ; les monstres à butin et les PNJ neutres restent, eux servent tout le monde."] =
        "Fixed: the NPC list under a missing recipe (trainers, vendors) mixed both factions, to the point of sending an Alliance character to the Undercity. NPCs from the other side are now hidden; loot mobs and neutral NPCs stay, they serve everyone.",
    -- v1.27.0
    ["Prévenu quand une nouvelle version sort"] = "Tells you when a new version is out",
    ["L'addon repère maintenant qu'il tourne en retard. Il lit la version des joueurs que tu croises sur le réseau, et dès qu'il en voit une plus récente chez plusieurs personnes différentes, il te le dit d'une ligne dans le chat et pose un point rouge sur le bouton minimap. Le point s'efface tout seul une fois que tu as mis à jour."] =
        "The addon now notices when you're running behind. It reads the version off other players you cross paths with on the network, and once it's seen a newer one from a few different people, it drops a single line in chat and puts a red dot on the minimap button. The dot clears itself once you update.",
    ["Ce « plusieurs personnes différentes » est voulu : un joueur isolé ne peut pas te faire croire que tu es en retard en annonçant un faux numéro, il faut que des joueurs distincts le confirment. Et ça ne te prévient qu'une fois par version, jamais à chaque connexion. Tape /co version pour voir ta version et s'il en existe une plus récente."] =
        "That \"few different people\" part is on purpose. One player can't spoof you into thinking you're behind by broadcasting a fake number, it takes separate players to corroborate it. And it only tells you once per version, never every login. Type /co version to see what you're on and whether there's something newer.",
    -- v1.26.0
    ["Filtre n'importe quelle liste par la stat qu'elle donne"] =
        "Filter any craft list by the stat it gives",
    ["Chaque liste de recettes — l'onglet Commande, la fenêtre métier, Mes artisans — reçoit un sélecteur de stat. Tu choisis Force, tu ne vois que ce qui donne de la Force : gemmes, équipements, élixirs. Le menu se remplit avec ce que le métier ouvert fabrique vraiment, donc la Cuisine ne te propose pas Puissance des sorts. Ces stats ne sont écrites nulle part, elles sont lues sur ton propre jeu — dans ta langue, et valables pour des objets que je n'ai jamais regardés, Wrath compris."] =
        "Every recipe list, the Order tab, the profession window and My Artisans, gets a stat picker. Pick Strength and you see only what gives Strength, gems, gear, elixirs. The menu is built from what the open profession actually makes, so Cooking won't offer you Spell Power. None of those stats are typed out anywhere, they're read off your own client, so they show up in your language and keep working on items I've never looked at, Wrath included.",
    ["L'alchimie se range mieux aussi : les élixirs se regroupent sous la stat qu'ils donnent, pendant que les potions de soin et de mana, les flacons et les transmutations gardent leurs propres en-têtes — « rend de la vie » n'a jamais été une stat. Sur TBC, ça sort 74 consommables du fourre-tout Divers."] =
        "Alchemy sorts better too. Elixirs group under the stat they give, while healing and mana potions, flasks and transmutes keep their own headings, since \"restores health\" was never a stat. On TBC that pulled 74 loose consumables out of the Misc pile.",
    -- v1.25.0
    ["Les gemmes se rangent par couleur, puis par ce qu'elles donnent"] =
        "Cut gems sort by color, then by what they give",
    ["La joaillerie versait toutes les gemmes taillées sous un seul en-tête « Gemme ». Elles se rangent maintenant par couleur de châsse, et sous chaque couleur par la stat qu'elles donnent : « Force - Audacieux », « Endurance - Solide ». Cette stat n'est pas une table écrite à la main, elle est lue sur ton propre jeu — donc dans ta langue, et valable pour des gemmes que je n'ai jamais regardées."] =
        "Jewelcrafting dumped every cut gem under a single \"Gem\" heading. Gems now sit under their socket color, and under that, under the stat they give, so you get \"Strength - Bold\" and \"Stamina - Solid\". That stat isn't a list I typed out, it's read off your own client, which is why it shows up in your language and why it'll keep working on gems I've never looked at.",
    ["Les gemmes méta, elles, reviennent à une simple liste : chaque taille de méta n'existe qu'en un seul exemplaire, un en-tête au-dessus n'aurait fait que répéter la ligne. Bagues, colliers, statues et figurines gardent le classement qu'ils avaient."] =
        "Meta gems get a plain list instead. Every meta cut is a single gem, so a heading above each one just repeated the line underneath it. Rings, necklaces, statues and figurines keep sorting the way they always did.",
    ["Corrigé aussi : quand un enchanteur te demandait une pièce, l'invite ne s'affichait parfois jamais. Une première demande arrivée trop tôt, avant que tu aies équipé la pièce, armait quand même le délai de cinq secondes — et la vraie demande qui suivait passait à la trappe. Le délai ne démarre plus que sur une demande réellement affichée."] =
        "Also fixed: when an enchanter asked you for a piece, the prompt sometimes never showed up. A first request that arrived a moment too early, before you'd equipped the piece, still armed the five second cooldown, so the real request that followed got swallowed. The cooldown now only starts once a request has actually gone through.",
    -- v1.24.2
    ["Les stats d'enchant parlent enfin ta langue"] =
        "Enchant stat names finally speak your language",
    ["Les sous-catégories de la vue enchant (Force, Esprit, Croisé…) venaient d'un libellé interne jamais traduit : tout le monde les voyait en anglais, client français compris. Elles sont maintenant lues directement sur ton jeu, comme les noms de sorts, donc dans ta langue sans rien à traduire à la main à chaque nouvelle recette."] =
        "The subcategory names in the enchant view (Strength, Spirit, Crusader, and so on) were stuck in English for everyone, French clients included, because they came from an internal label the addon never translated. They're now read straight from your game client, the same way spell names already are, so they show up in your own language with no manual translation as new enchants get added.",
    -- v1.24.1
    ["Deux minerais de plus dans les commandes de récolte"] =
        "Two more ores in gathering orders",
    ["Le khorium et l'éternium n'apparaissaient pas comme commandables dans l'onglet Récolte. La liste des minerais était dérivée de ceux qu'on peut prospecter en gemmes, et ni l'un ni l'autre ne l'est — le même trou qui cachait déjà l'argent, l'or, le vrai-argent et le sombrefer. Les deux rejoignent la liste."] =
        "Khorium and Eternium ore weren't showing up as orderable in the Gather tab. The mining list was built from what's prospectable into gems, and neither one is, the same gap that used to hide Silver, Gold, Truesilver and Dark Iron. Both join that list now.",
    -- v1.24.0
    ["La pièce à enchanter se pose d'un clic, et une bourse qui suit la progression"] =
        "The piece to enchant places itself in one click, and a pouch that keeps up",
    ["Depuis la v1.21.0, un enchanteur peut cliquer un emplacement de la silhouette d'échange pour te demander la pièce à enchanter. Si tu as l'addon toi aussi, ce clic affiche maintenant une invite chez toi : accepte, et ta pièce équipée se pose toute seule dans l'emplacement « ne sera pas échangé ». Rien n'est donné (cet emplacement ne peut pas changer de mains), la pose est verrouillée sur lui, et rien ne bouge sans ton clic. Sans l'addon en face, le chuchotement explicatif part comme avant."] =
        "Since v1.21.0, an enchanter can click a slot on the trade silhouette to ask for the piece to enchant. If you run the addon too, that click now shows a prompt on your side: accept, and your equipped piece places itself in the \"will not be traded\" slot. Nothing is given away (that slot can't change hands), the placement is locked to it, and nothing moves without your click. No addon on the other side, and the explanatory whisper goes out as before.",
    ["La bourse d'artisan se met à jour en direct : fenêtre ouverte, chaque point de métier gagné par le personnage suivi (et chaque recette apprise) recalcule la liste de courses — plus besoin de la rouvrir pour voir la route changer."] =
        "The artisan pouch now updates live: with the window open, every skill point the tracked character gains (and every recipe they learn) recomputes the shopping list, no reopening needed to see the route change.",
    -- v1.23.0
    ["La bourse d'artisan : la liste de courses de tes guildeux, et deux corrections réseau"] =
        "The artisan pouch: a shopping list for your guildmates, and two networking fixes",
    ["L'onglet Artisans gagne un bouton sac après les icônes de métier de chaque fiche : un clic ouvre la liste de courses des matériaux qu'il te faut pour monter tes métiers, calculée en local à partir de ce que le jeu diffuse déjà (aucun nouveau trafic réseau). Les réactifs que ton propre métier sait fabriquer sont décomposés en composants de base, et les objets vendus par un PNJ sont mis de côté dans une note plutôt que d'encombrer la grille."] =
        "The Artisans tab gets a bag button after each entry's profession icons: click it and a shopping list opens for the materials that person needs to keep leveling, worked out locally from what the game already broadcasts (no new network traffic). Reagents their own profession can make from something cheaper get broken down into base components, and vendor items get pulled into a plain note instead of cluttering the grid.",
    ["Coche « inclure les plans à acheter » et les recettes derrière un coût rejoignent la liste : les plans-objets comme fourniture à apporter, les plans de formateur comme simple note. Le même bloc de fournitures s'affiche maintenant sous le plan de route « quoi monter ensuite », avec le PNJ où aller (nom, zone, coordonnées) et une épingle TomTom cliquable si tu l'as installé."] =
        "Check \"include recipes to buy\" and plans behind a gold cost join the list too: purchasable plan items as something to hand over, trainer plans as a note. The same supply block now shows up under the \"what to level next\" route planner, with the vendor to visit (name, zone, coordinates) and a clickable TomTom pin if you have it installed.",
    ["Une recette sans réactif au prix connu (la poussière d'enchantement, par exemple) ne fait plus sauter tout un tronçon du plan de route : elle sert maintenant de repli marqué « ? » quand rien de mieux n'est disponible. Une table de désenchantement maison alimente aussi l'infobulle des poussières, essences et éclats affichés dans ces listes."] =
        "A recipe with no priced reagent, Enchanting dust being the usual offender, no longer knocks a whole stretch out of the route plan: it's now used as a fallback marked with a \"?\" when nothing better is available. A curated disenchant table also backs the tooltip on any dust, essence or shard shown in these lists.",
    ["Deux corrections : un compte à plusieurs personnages se voyait parfois lister lui-même comme « joignable via » son autre perso dans son propre onglet Artisans, corrigé. Et le plan de route pouvait s'arrêter avant le vrai plafond de compétence après une formation chez le maître, à cause d'une assignation Lua qui perdait silencieusement sa seconde valeur."] =
        "Two fixes: an account with more than one character sometimes saw itself listed as reachable \"via\" its own alt in its own Artisans tab, fixed. And the route planner could stop short of a profession's real skill cap right after a trainer promotion, because a Lua multi-assignment quietly dropped its second return value.",
    -- v1.22.1
    ["Les alertes de commande vérifient enfin le métier, et un plan de route qui suit son propre badge"] =
        "Order alerts that actually check the profession, and a route plan that matches its own badge",
    ["Une commande à portée large (guilde, amis, tous) déclenchait un toast même chez un joueur sans le métier, du moment qu'elle arrivait par le relais de connexion (chuchotement) plutôt que par le canal : le filtre par métier ne couvrait que le canal. Il s'applique maintenant quel que soit le chemin réseau. Le toast gagne aussi un troisième texte : une commande à portée large n'affiche plus « pour TOI », ce qui donnait l'impression fausse d'une demande personnelle."] =
        "A broad order (guild, friends, everyone) could toast a player who doesn't even have the profession, as long as it arrived through the login relay (a whisper) instead of the channel: the profession filter only covered the channel. It now applies no matter which path the order took. The toast also gets a third text: a broad order no longer reads \"for YOU,\" which read like a personal request when it wasn't one.",
    ["Le plan de route « quoi monter ensuite » pouvait suggérer une recette différente du badge de coût de la liste, les deux lisant des données légèrement différentes. Le plan utilise maintenant la difficulté réelle de la fenêtre métier à ton rang actuel plutôt qu'une projection, et se rafraîchit au même rythme que le badge. La commande |cFFFFFFFF/co lvldump|r affiche le détail en cas de nouveau désaccord."] =
        "The \"what to level next\" route planner could suggest a different recipe than the list's own cost badge, since the two were reading slightly different data. The route now uses the profession window's real difficulty at your current rank instead of a projection, and refreshes on the same clock as the badge. |cFFFFFFFF/co lvldump|r prints the details if you ever spot a mismatch again.",
    -- v1.22.0
    ["L'aide contextuelle, des dépendances qu'on ne peut plus rater, et une touche Échap qui obéit"] =
        "Contextual help, unmissable dependencies, and an Escape key that behaves",
    ["Un nouveau bouton « i » ouvre l'aide contextuelle du jeu, le même système que Blizzard utilise pour ses propres fenêtres : le fond s'assombrit et une bulle pointe directement sur ce dont il est question. Chaque onglet (Vue Métier, Commande, Récolte, Artisans, Mes artisans, Carnet) a sa propre visite guidée, donc le bouton explique ce qui est réellement affiché plutôt qu'une infobulle générique."] =
        "A new \"i\" button opens the game's own contextual help, the same system Blizzard uses for its own windows: the background dims and a callout points straight at whatever's in question. Every tab (Profession view, Order, Gather, Artisans, My Artisans, Ledger) has its own tour, so the button explains what's actually on screen instead of a generic tooltip.",
    ["Lazy Gold et MTSL restent optionnels, mais rien ne signalait qu'ils manquaient. Les boutons qui en dépendent restent visibles et colorés même sans l'addon installé, et cliquer dessus sans l'avoir ouvre désormais une explication de ce qu'il fait et où le trouver, plutôt que de ne rien faire du tout."] =
        "Lazy Gold and MTSL stay optional, but there was no sign either one was missing. The buttons that need them stay visible and colored whether or not you have the addon installed, and clicking one without it now pops a short explanation of what it does and where to get it, instead of doing nothing.",
    ["L'alerte « peut faire cette commande » se déclenchait même quand tu ne connaissais pas la recette, souvent des gemmes ou enchants dont tu avais les réactifs sans le plan. Elle vérifie maintenant tes recettes connues avant de te notifier sur tes propres commandes. Un ami en ligne sans l'addon ne s'affiche plus « Hors ligne » par erreur."] =
        "The \"can craft that\" alert fired even when you didn't actually know the recipe, usually gems or enchants you had the reagents for but not the plan. It now checks your known recipes before nagging you about your own orders. A friend who's online without the addon no longer shows up as offline by mistake.",
    ["Échap laissait souvent les fenêtres de métier ouvertes, et trois rapports différents pointaient la même cause : cacher ou désactiver la souris d'une fenêtre protégée en plein combat déclenche une erreur du jeu. Les fenêtres passent maintenant par un petit relais dédié, donc Échap les ferme proprement, en combat ou non."] =
        "Escape used to leave profession windows open more often than not, and three separate bug reports pointed at the same cause: hiding or disabling mouse input on a protected window mid-combat throws a game error. Windows now route through a small proxy frame instead, so Escape closes them cleanly whether or not you're in combat.",
    ["L'aide « quoi monter ensuite » affiche maintenant le coût par point de compétence, une pastille de prix Auctioneer, et une icône vers le PNJ qui vend une recette que tu ne connais pas encore, en plus d'un tri affiné."] =
        "The \"what to level next\" helper now shows cost per skill point, an Auctioneer price badge, and an icon pointing at the vendor who sells a recipe you don't know yet, on top of a slightly smarter sort.",
    ["Cette même aide gagne un plan de route : clique le bouton carte et il déroule toute ta montée rang par rang, en choisissant à chaque étape la recette la moins chère (apprise ou achetable, plans compris) et en additionnant le coût total. Les recettes à cooldown ou avec un réactif sans prix connu sont exclues exprès, elles fausseraient le total. Demande Lazy Gold ; MTSL ajoute les prix de plans formateur et vendeur au calcul."] =
        "That same helper gets a route planner now: click the map button and it walks your whole climb rank by rank, picking the cheapest recipe at each step (learned or buyable, plans included) and totaling the cost. Recipes with a cooldown or a reagent with no known price are left out on purpose, they'd throw the total off. Needs Lazy Gold; MTSL adds trainer and vendor plan prices to the mix.",
    -- v1.21.0
    ["L'enchant par emplacement, et un panneau d'échange qui ne cache plus rien"] =
        "Enchants by slot, and a trade panel that stops hiding things",
    ["Choisir un enchant demandait de fouiller des centaines de plans aux noms presque identiques. L'onglet Commande a maintenant une vue silhouette : clique l'emplacement à enchanter, tu obtiens ses stats, puis ses variantes de la plus forte à la plus faible. La bascule est dans la bande de filtres ; la liste reste pour tout ce qui n'a pas d'emplacement (huiles, baguettes, produits de désenchantement)."] =
        "Picking an enchant meant scrolling hundreds of plans with near-identical names. The Order tab has a character-silhouette view now: click the slot you want enchanted, get that slot's stats, then its variants from strongest to weakest. Toggle it from the filter bar; the plan list stays for everything that has no slot (oils, wands, disenchant products).",
    ["Le panneau d'enchant de l'échange n'affichait que 8 lignes, et le « +N autre(s) » du bas n'était pas cliquable : au-delà de la 8ᵉ place, un enchant était tout bonnement inatteignable — c'est ainsi qu'un enchanteur à qui on avait passé les réactifs ne se voyait jamais proposer la bonne recette, noyée sous les variantes de haut rang. La liste défile à la molette, et elle est classée par ce qu'on te demande : d'abord les enchants dont ton partenaire vient de poser les réactifs, puis ce que tes sacs permettent, puis le reste."] =
        "The trade enchant panel only ever drew 8 rows, and the \"+N more\" line at the bottom wasn't clickable: past the eighth entry, an enchant was simply unreachable. That's how an enchanter who'd been handed the reagents never got offered the right recipe, buried under higher-rank variants. The list scrolls now, and it's ordered by what you're being asked for: enchants whose reagents your partner just put on the table come first, then what your bags can already make, then the rest.",
    ["Tant que la case « ne sera pas échangé » est vide, le panneau ne disparaît plus : il montre la même silhouette, avec le modèle de ton partenaire, et cliquer un emplacement lui chuchote d'y poser cette pièce. La plupart des gens qui te tendent un objet ignorent que cette case existe."] =
        "While the \"will not be traded\" slot is empty, the panel no longer vanishes: it shows the same silhouette, with your trade partner's model in it, and clicking a slot whispers them to drop that piece in. Most people who hand you gear have no idea that slot exists.",
    ["Deux correctifs : les enchants de poignets et de bâton de Wrath n'apparaissaient jamais dans le panneau d'échange (le jeu les écrit « Bracers » et « Staff » là où les autres extensions disent « Bracer »), et un enchant de bâton ne se propose plus que sur un vrai bâton. Le panneau ne touche plus non plus à ses boutons pendant un combat, ce que le jeu interdit."] =
        "Two fixes: Wrath's wrist and staff enchants never showed up in the trade panel (the game spells them \"Bracers\" and \"Staff\" where other expansions say \"Bracer\"), and a staff enchant only offers itself on an actual staff now. The panel also stops touching its buttons while you're in combat, which the game blocks outright.",
    ["Plus discret : les lignes de chat « X sait faire cette commande captée » sont désactivées par défaut — la commande est poussée aux amis capables dans tous les cas, le message n'était que du bruit. |cFFFFFFFF/co verbose|r les remet."] =
        "Quieter now: \"X can craft that captured order\" chat lines are off by default. The order still gets pushed to capable friends either way, so the message was noise. |cFFFFFFFF/co verbose|r brings it back.",
    -- v1.20.0
    ["Enchante en un clic, trié par emplacement, et depuis l'échange"] = "One-click enchants, sorted by slot, right from the trade window",
    ["Le bouton « Créer » de l'Enchantement avait un vieux bug intermittent : parfois rien ne se passait, et resélectionner la recette finissait par le faire marcher. Cause trouvée : sélectionner une recette n'arme pas le bouton natif de Blizzard, notre clic sécurisé tombait donc sur un bouton désactivé. Corrigé — ça devrait marcher du premier coup, à chaque fois."] =
        "The enchanting Create button had a long-standing intermittent bug: sometimes it just wouldn't fire, and re-selecting the recipe a few times eventually got it working. Root cause found: selecting a recipe doesn't actually arm Blizzard's native create button, so our secure click was landing on a disabled button. Fixed. Should just work now, every time.",
    ["Les recettes d'enchantement ne s'entassent plus dans un fourre-tout « Autres/Divers » : elles se rangent par emplacement (Poignets, Torse, Main gauche…) puis par stat de base (Force, Esprit, Déviation), le nom raccourci à la stat seule puisque l'emplacement est déjà dans l'en-tête."] =
        "Enchant recipes no longer pile up in a single Other/Misc bucket: they're grouped by slot (Wrist, Chest, Off-Hand...) then by base stat (Strength, Spirit, Deflection), with the name trimmed to just the stat since the slot's already in the header.",
    ["Sélectionner un enchant d'équipement affiche un bouton « Enchanter équipé » à côté de Créer : un clic l'applique directement sur la pièce que tu portes, sans avoir à cibler."] =
        "Selecting an equip-slot enchant now shows an \"Enchant equipped\" button next to Create: one click casts it on the item you're wearing in that slot, no manual targeting.",
    ["Et quand quelqu'un te tend un objet à enchanter en échange, le poser dans la case « ne sera pas échangé » ouvre un petit panneau listant tes enchants pour cet emplacement, prêts à lancer sans fouiller ta fenêtre de métier (qui doit rester ouverte : le jeu ne renseigne tes recettes connues que pendant qu'elle l'est)."] =
        "And when someone hands you gear to enchant over trade, dropping it in the \"will not be traded\" slot now pops a small panel listing every enchant you know for that slot, ready to cast without hunting through your profession window (which still needs to be open: the game only reports your known recipes while it's up).",
    -- v1.19.1
    ["Correctif : l'icône « dispo » remarche sur la nouvelle UI des plaques"] = "Fix: the availability badge works again on the newer nameplate UI",
    ["Sur le client TBC (et bientôt Era/Saison de la Découverte à la 1.15.9), l'icône « recherche de travail » au-dessus de la plaque d'un artisan cessait de s'afficher quand son statut changeait : la nouvelle interface de plaques a renommé un champ interne que l'addon lisait. Corrigé. Elle reste invisible en instance (donjon, raid) : le jeu verrouille les plaques amies aux addons là-bas, rien à faire de notre côté."] =
        "On the TBC client (and soon Era/Season of Discovery with patch 1.15.9), the \"looking for work\" badge over a crafter's nameplate stopped showing up when their status changed: the newer nameplate UI renamed an internal field the addon was reading. Fixed. It still won't show inside an instance (dungeon, raid): the game locks friendly nameplates away from addons there, nothing we can do about that one.",
    -- v1.19.0
    ["Propose des recettes précises, diffuse tes réactifs, et le LFW marche même sans l'addon"] = "Recipes in your offer, a share button, and LFW without the addon",
    ["« Chercher du travail » propose maintenant des recettes précises, pas seulement des réactifs : coche des plans dans la liste et qui te consulte voit « propose : Bouclier de fer, Gilet de mailles de cuivre » à côté de ce que tu fournis déjà."] =
        "\"Look for work\" now lets you name exact recipes, not just reagents. Check off plans in the recipe list and whoever's browsing your offer sees \"offers: Iron Buckler, Copper Chain Vest\" next to whatever mats you're already listing.",
    ["Un bouton « Diffuser » envoie la liste de réactifs d'une recette ou d'une commande dans un canal au choix (guilde, dire, groupe/raid, un canal numéroté), avec le lien de chaque objet — une liste de courses en un clic, depuis la vue métier, la carte de commande ou le panneau de publication."] =
        "A \"Share\" button sends a recipe's or an order's reagent list to a channel of your choice (guild, say, party/raid, a numbered channel), with a link for every item — a shopping list in one click, from the profession window, the order card, or the posting panel.",
    ["Le LFW marche même sans l'addon : tape « LFW enchantement » en Commerce ou Général et tu apparais comme dispo, avec la même icône de plaque qu'un joueur qui a Crafting Order. Plus une correction : une recette déjà apprise ne s'affichait plus en double avec MissingTradeSkillsList."] =
        "Look for work works even without the addon: type \"LFW enchanting\" in Trade or General and you show up as available, same nameplate icon as anyone running Crafting Order. Plus a fix: a recipe you'd already learned no longer got listed twice with MissingTradeSkillsList.",
    -- v1.18.0
    ["Chercher du travail : dis ce que tu offres, et trie par progression"] = "Look for work, now with an offer, and sort by what levels you",
    ["« Chercher du travail » ne se contente plus de te signaler dispo. Clique l'engrenage à côté du bouton et dis ce que tu proposes : tu fournis les composants de base, tu fournis tel réactif précis, une commission fixe par craft, ou seulement les plans qui te font gagner un point de compétence. Ça s'affiche sur ta ligne [Dispo] et dans l'infobulle au-dessus de ta tête, avec une pièce s'il y a une commission et un sac si tu fournis des compos."] =
        "\"Look for work\" does more than flag you as available. Click the gear next to the button and say what you're offering: you'll bring the basic reagents, you'll supply a specific component, a flat tip per craft, or only jobs that give you a skill point. It shows on your [Dispo] line and in the tooltip over your head, with a coin if there's a tip and a bag when you're providing mats.",
    ["L'icône « dispo » au-dessus de la plaque d'un artisan marche maintenant sur Era et Saison de la Découverte, plus seulement sur le client TBC. Active les plaques des amis (nameplateShowFriends) et l'icône du métier flotte au-dessus de qui cherche du travail à côté de toi."] =
        "The \"available\" icon over a crafter's nameplate works on Era and Season of Discovery now, not just the Burning Crusade client. Turn on friend nameplates (nameplateShowFriends) and the profession icon floats over anyone near you who's looking for work.",
    ["Les recettes se trient par ce qui te fait encore progresser : un troisième bouton outil remonte en tête les plans qui donnent un point, d'orange à gris. Les commandes ont le même « ce qui me fait monter d'abord », avec un liseré de difficulté sur le côté de chaque ligne. Plus quelques corrections au passage."] =
        "Recipes sort by what still levels you: a third tool button lifts the plans that give a skill point to the top, orange to grey. Orders get the same \"levels me first,\" with a difficulty tint down the side of each line. Plus a few fixes along the way.",
    -- v1.17.1
    ["Correctif : erreur au login en « Chercher du travail »"] = "Fixed a login error while looking for work",
    ["Si tu avais activé « Chercher du travail », te connecter ou faire /reload pouvait déclencher une erreur rouge : l'addon annonçait ta disponibilité avant que le jeu n'autorise un addon à parler sur le canal. L'annonce attend maintenant ton prochain clic ou ta prochaine touche — plus d'erreur, et les autres te voient toujours dispo."] =
        "If you had \"Look for work\" on, connecting or reloading could throw a red error: the addon announced your availability before the game lets an addon talk on the channel. The announcement now waits for your next click or keypress — no more error, and others still see you're available.",
    -- v1.17.0
    ["L'interface passe au style natif de WoW"] = "The window matches the game now",
    ["La fenêtre n'a plus son habillage doré maison : elle emprunte le cadre du jeu (barre de titre, portrait rond, onglets, boutons). Elle se fond dans l'interface au lieu de ressembler à un addon posé par-dessus, et rien n'a bougé de ce que tu connais."] = "The window dropped its custom gold skin for the game's own frame (title bar, round portrait, tabs across the top, buttons). It reads as part of the interface instead of something bolted on top, and nothing moved that you'd have to relearn.",
    ["La vue métier est refaite, avec une colonne Commandes en liste : une ligne par commande (demandeur, objet voulu, prix), et le clic ouvre la carte complète (composants fournis, coût des réactifs, Accepter / Refuser / Chuchoter) avec une croix pour revenir à la liste. Et les sous-catégories de récolte (Peaux, Écailles, Herbes, Poissons) sont enfin traduites hors client français."] = "The profession window was rebuilt, with the orders column as a list: one line per order (requester, the item they want, price), and clicking opens the full card (supplied components, reagent cost, Accept / Decline / Whisper) with a close button back to the list. And the gathering sub-headings (Hides, Scales, Herbs, Fish) are finally translated outside a French client.",
    -- v1.15.1
    ["Tes commandes n'appartiennent qu'à toi"] = "Your orders are yours",
    ["Recettes triées, et où est l'or"] = "Sorted recipes, and where the gold is",
    ["Fini le fourre-tout « Consommable » : les recettes sont regroupées par type (potions de soin, de mana, élixirs, flacons, transmutations…) et triées du plus haut niveau au plus bas. Une potion qui rend vie ET mana apparaît sous les deux. Le même classement s'applique partout — Commande, Mes artisans, et les métiers de récolte (minerais, herbes, cuirs, poissons)."] = "No more catch-all \"Consumable\": recipes are grouped by type (healing potions, mana potions, elixirs, flasks, transmutes…) and sorted highest rank to lowest. A potion that restores both health and mana shows under both. The same grouping applies everywhere — the Order tab, My Artisans, and the gathering professions (ores, herbs, leathers, fish).",
    ["Si tu as Lazy Gold, chaque recette affiche sa rentabilité (pièces, étoiles au-delà de mille pièces d'or ; rien pour une perte). La pièce d'or au-dessus de la liste trie par profit, le bouton « 123 » bascule en valeurs exactes. L'onglet Commande a les deux boutons, plus la valeur HV et le coût des réactifs sur chaque commande entrante."] = "If you run Lazy Gold, every recipe shows its profit (coins, stars past a thousand gold; nothing for a loss). The gold coin above the list sorts by profit, the \"123\" button switches to exact amounts. The Order tab gets both buttons, plus the auction value and reagent cost on every incoming order.",
    ["Dans l'annuaire, les métiers passent en icônes : un artisan avec un plan vraiment rentable a un contour doré, le survol nomme le plan, le clic ouvre la Commande déjà ciblée. « Mes artisans » gagne « Tous les plans du royaume » : tous tes persos (même faction) fusionnés et triés par profit — d'un coup d'œil, quel reroll fait des sous. Et si tu as MissingTradeSkillsList, un bouton montre tes recettes non apprises en rouge, avec leur source au clic."] = "In the directory, professions became icons: a crafter with a genuinely profitable plan gets a gold border, hover names the plan, click opens the Order tab already aimed at them. My Artisans gains \"All realm crafts\": every character (same faction) merged and ranked by profit — at a glance, which alt is making money. And if you run MissingTradeSkillsList, a button shows your unlearned recipes in red, with their source on click.",
    ["Les identifiants de commande étaient devinables : n'importe qui pouvait réécrire la tienne (acheteur, prix, quantité). C'est fermé : seul son auteur peut la modifier. Le relais entre joueurs, lui, continue de fonctionner — c'est comme ça qu'une commande atteint quelqu'un que le canal n'a jamais touché."] =
        "Order ids were guessable, and anyone could rewrite yours (buyer, price, quantity). That's closed: only the person who posted an order can change it. Relaying between players still works, which is how an order reaches someone the channel never touched.",
    ["On ne peut plus te faire mettre en sourdine en postant de fausses commandes en ton nom, et un acheteur dont les commandes sont relayées en rafale n'est plus muté par erreur. « X a refusé ta commande » et le rappel « tu sais le faire » ne se rejouent plus en boucle, et rien ne passe d'un joueur que tu as mis en sourdine."] =
        "Nobody can get you muted by posting fake orders under your name, and a buyer whose orders get relayed in a burst is no longer muted by mistake. \"X declined your order\" and the \"you can craft this\" nudge no longer replay on a loop, and nothing gets through from someone you've muted.",
    ["La vue métier n'affiche plus les commandes privées destinées à quelqu'un d'autre, ni les expirées. Ton compteur de crafts livrés ne peut plus être gonflé par un tiers. Et croiser un artisan coûte deux fois moins de messages : le bonjour porte maintenant tes métiers, ce qui règle aussi les artisans qui s'affichaient sans aucun métier."] =
        "The profession window no longer shows private orders meant for someone else, nor expired ones. Your delivered count can't be padded by a stranger. And crossing paths with an artisan costs half the messages it used to: saying hello now carries your professions, which also fixes artisans showing up with no professions at all.",
    -- v1.15.0
    ["Recherche de travail : signale que tu es dispo"] = "Looking for work: flag yourself as available",
    ["Ouvre un métier et clique « Chercher du travail » : tout le royaume sait que tu es dispo, une icône d'artisan s'affiche au-dessus de ta tête pour ceux qui passent, et tu apparais « [Dispo] » dans leur annuaire. Ça s'éteint tout seul au bout d'un moment si tu oublies."] =
        "Open a profession and click \"Look for work\": the whole realm knows you're available, an artisan icon shows over your head for anyone passing by, and you appear as \"[LFW]\" in their directory. It lapses on its own after a while if you forget.",
    ["Au passage : les deux fenêtres ne s'emmêlent plus (un clic la ramène au premier plan), l'annuaire a un bouton partenaire et se limite à ta faction (pas d'échange cross-faction sur Classic), et un artisan ne s'affiche plus avec un métier qui n'est pas le sien."] =
        "Along the way: the two windows no longer tangle (a click brings one to the front), the directory has a partner button and sticks to your faction (no cross-faction trading on Classic), and an artisan no longer shows a profession that isn't theirs.",
    -- (clés v1.8.0/v1.7.0/v1.7.1/v1.6.0/v1.5.0/v1.4.0 retirées : ces versions ne sont plus listées dans l'onglet Nouveautés)
    -- Onglet Nouveautés — v1.13.0
    ["Modération : mutes avec raison, temporaires, liste de confiance"] = "Moderation: mutes with a reason, temporary mutes, a trust list",
    ["Un mute porte désormais une raison et une date, et peut être temporaire : |cFFFFFFFF/co mute Bob 1h spammeur|r se lève tout seul au bout d'une heure (|cFFFFFFFF/co mute|r seul liste les mutés avec raison et temps restant). Et |cFFFFFFFF/co trust <nom>|r marque un joueur de confiance, jamais mis en sourdine automatiquement — le mute manuel restant toujours possible."] =
        "A mute now carries a reason and a date, and can be temporary: |cFFFFFFFF/co mute Bob 1h spammer|r lifts itself after an hour (|cFFFFFFFF/co mute|r alone lists muted players with reason and time left). And |cFFFFFFFF/co trust <name>|r marks a player as trusted, never auto-muted — manual muting still available.",
    -- (clés v1.12.1 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    -- Onglet Nouveautés — v1.12.0
    ["Les recettes de la Saison de la Découverte"] = "Season of Discovery recipes",
    ["304 recettes de la Saison de la Découverte entrent au catalogue : 80 en Travail du cuir, 65 en Forge, 57 en Couture, 48 en Enchantement, 29 en Ingénierie, 16 en Alchimie, plus la Cuisine, le Secourisme et le Minage. Elles apparaissent dans l'onglet Commande, avec leurs réactifs et leur palier d'apprentissage."] =
        "304 Season of Discovery recipes join the catalogue: 80 for Leatherworking, 65 for Blacksmithing, 57 for Tailoring, 48 for Enchanting, 29 for Engineering, 16 for Alchemy, plus Cooking, First Aid and Mining. They show up in the Order tab, with their reagents and skill levels.",
    ["Elles ne se chargent que sur un royaume Saison de la Découverte. Sur un royaume Era classique, rien ne change : l'addon voit exactement le même jeu de recettes qu'avant, et les recettes que tes amis t'ont déjà partagées restent lisibles."] =
        "They load only on a Season of Discovery realm. On a regular Era realm nothing changes: the addon sees exactly the recipe set it saw before, and the recipes your friends already shared with you stay readable.",
    -- Onglet Nouveautés — v1.11.0
    ["Annuler une commande publique atteint tout le royaume"] = "Cancelling a public order now reaches the whole realm",
    ["Une commande publique voyage sur le canal du royaume depuis la v1.10.0, mais pas son annulation : un artisan que tu n'as jamais croisé la voyait « ouverte » pendant six heures, l'acceptait, et farmait les réactifs pour rien. L'annulation part désormais sur le même canal."] =
        "A public order has travelled the realm channel since v1.10.0, but its cancellation did not. A crafter you have never met kept seeing it as open for up to six hours, could accept it, and gathered the reagents for nothing. Cancelling now goes out on the same channel.",
    ["Poster et annuler ne perdent plus de messages. Le canal exige un clic ou une touche et n'accepte qu'une ligne par seconde : un |cFFFFFFFF/co post|r tapé au chat, ou deux commandes postées dans la même seconde, disparaissaient sans trace. Ces lignes patientent maintenant dans une file et partent à ton prochain clic."] =
        "Posting and cancelling no longer lose messages. The channel needs a click or a keypress to carry a line, and takes one line per second: a |cFFFFFFFF/co post|r typed in chat, or two orders posted in the same second, used to vanish without a trace. Those lines now wait in a queue and go out on your next click.",
    ["Seules les commandes NOUVELLES et les ANNULATIONS voyagent sur le canal, et seulement les publiques. Guilde, amis et commandes nommées restent privées ; les acceptations restent entre les deux joueurs concernés."] =
        "Only new orders and cancellations ever travel the channel, and only public ones. Guild, friends and named orders stay private; acceptances stay between the two players involved.",
    -- Onglet Nouveautés — v1.10.2
    ["Correctif : erreur en combat dans la vue métier"] = "Fix: an in-combat error in the profession view",
    ["Sélectionner une recette pendant un combat ne provoque plus d'erreur bloquée : le bouton « Créer » est un bouton sécurisé, que le jeu interdit de masquer en plein combat. L'addon attend maintenant la fin du combat pour l'afficher ou le masquer."] =
        "Picking a recipe during combat no longer throws a blocked-action error. The Create button is a secure button, and the game forbids hiding one mid-combat. The addon now waits until combat ends to show or hide it.",
    -- Onglet Nouveautés — v1.14.0
    ["Un panneau pour gérer les mis en sourdine"] = "A panel to manage who you've muted",
    ["L'onglet Artisans a maintenant une section « En sourdine » : chaque joueur muté y apparaît avec sa raison et le temps restant (ou « permanent »), avec un bouton pour le rétablir directement — plus besoin de deviner qui est encore muté."] =
        "The Artisans tab now has a Muted section: every muted player shows up with their reason and time left (or \"permanent\"), with a button to unmute them right there — no more guessing who's still muted.",
    -- (clés v1.9.0 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    ["VU"] = "SEEN",
    ["vu crafter (sans l'addon)"] = "seen crafting (no addon)",
    ["vu crafter"] = "seen crafting",
    ["%d+ · vu crafter"] = "%d+ · seen crafting",
    -- Cooldowns de recettes (transmutations & co)
    ["%s : prête"] = "%s: ready",
    ["%s : dans %s"] = "%s: in %s",
    ["(estimé)"] = "(estimated)",
    ["Transmutation"] = "Transmute",
    ["%dj"] = "%dd", ["%dh"] = "%dh", ["%dmin"] = "%dmin",
    -- Relais partenaire (fiche d'un artisan hors ligne servie par un contact de confiance)
    ["via %s · il y a %s"] = "via %s · %s ago",
    ["RELAIS"] = "RELAYED",
    -- Rerolls (identité joueur multi-persos, /co alts — opt-in)
    ["rerolls : ACTIVÉS — ta liste de persos est annoncée au réseau."] =
        "alts: ENABLED — your character list is announced to the network.",
    ["rerolls : désactivés — rien n'est annoncé (opt-in : /co alts on)."] =
        "alts: disabled — nothing is announced (opt-in: /co alts on).",
    ["perso principal (vitrine) : %s"] = "main character (front): %s",
    ["persos du compte (%s) : %s"] = "account characters (%s): %s",
    ["le lien n'est vérifié chez les autres qu'après une connexion de CHAQUE perso (addon actif)."] =
        "others only verify the link after EACH character has logged in once (addon running).",
    ["rerolls activés — perso principal : %s (changer : /co alts main <nom>)"] =
        "alts enabled — main character: %s (change: /co alts main <name>)",
    ["rerolls désactivés — dissolution annoncée au réseau."] =
        "alts disabled — dissolution announced to the network.",
    ["perso inconnu sur ce compte : %s (connecte-le une fois avec l'addon)"] =
        "unknown character on this account: %s (log it in once with the addon)",
    ["regrouper tes rerolls (opt-in) : liste annoncée, commandes routées vers ton perso connecté"] =
        "group your alts (opt-in): list announced, orders routed to your online character",
    ["commande nommée pour %s : connecte ce perso, ou active /co alts on pour accepter d'ici."] =
        "order named for %s: log that character in, or enable /co alts on to accept from here.",
    ["|cFFFFCC00commande pour ton reroll %s|r de |cFFFFFFFF%s|r : %s%s%s"] =
        "|cFFFFCC00order for your alt %s|r from |cFFFFFFFF%s|r: %s%s%s",
    ["En ligne via %s"] = "Online via %s",
    ["reroll : %s (%s)"] = "alt: %s (%s)",
}

for k, v in pairs(news) do L[k] = v end
