-- CraftingOrderClassic_Locale_News_enUS.lua — traductions de l'onglet « Nouveautés » (enUS/enGB).
-- Extrait de _Locale_enUS.lua : l'onglet Nouveautés grossit à chaque release et faisait déborder le
-- plafond anti-monolithe. Isolé ici, il a de la marge (fenêtre glissante côté UI_News). Même contrat :
-- clé FR → texte EN, chargé APRÈS _Locale.lua, early-return hors locale.

local COC = CraftingOrderClassic
local loc = GetLocale and GetLocale() or "enUS"
if loc ~= "enUS" and loc ~= "enGB" then return end
local L = COC.L

local news = {
    -- Onglet Nouveautés (changelog en jeu)
    ["Nouveautés"] = "What's New",
    -- v1.30.0
    ["La cuisine, le secourisme et la pêche comptent comme des métiers"] =
        "Cooking, First Aid and Fishing count as professions",
    ["L'annuaire faisait comme si ces trois-là n'existaient pas. Tu pouvais commander une pile de nourriture depuis l'onglet Commande, mais rien ne te disait QUI est cuisinier : pas d'icône sur sa ligne, pas de pastille pour filtrer, rien dans l'infobulle quand tu le survolais. Ils comptent maintenant comme les autres, et un clic droit sur un joueur propose « Commander Cuisine » comme il propose la forge. La pêche, elle, reste une récolte : elle s'affiche et se filtre, mais elle se commande depuis l'onglet Récolte, comme l'herboristerie."] =
        "The directory acted like those three didn't exist. You could order a stack of food from the Post tab, but nothing told you who the cooks were: no icon on their row, no pill to filter by, nothing in the tooltip when you hovered them. They count like the rest now, and right-clicking a player offers 'Order Cooking' the way it offers Blacksmithing. Fishing stays a gathering skill, so it shows up and filters, but you order fish from the Gather tab the way you do herbs.",
    ["Leur montée suit aussi : la bourse d'artisan et le suivi à l'écran nomment ton prochain point de cuisine ou de secourisme exactement comme ils le font déjà pour un métier principal. Une exception est volontaire : voir quelqu'un cuisiner au feu de camp ne l'ajoute toujours pas à l'annuaire, une capitale l'enterrerait sous des gens qui ne sont pas vraiment cuisiniers. Un cuisinier qui a l'addon apparaît normalement, par ses propres niveaux de métier."] =
        "Leveling them follows. The artisan pouch and the on-screen tracker name your next cooking or first aid point exactly as they already do for a primary profession. One exception is deliberate: seeing someone cook at a campfire still doesn't add them to the directory, because a capital city would bury it under people who aren't really cooks. A cook running the addon shows up normally, from their own skill levels.",
    -- v1.29.0
    ["Tes commandes à l'écran, et un journal pour les lire"] =
        "Orders on screen, and a journal to read them in",
    ["Les commandes que tu as acceptées s'affichent à l'écran, comme les quêtes suivies. L'objet que tu t'es engagé à faire, et dessous chaque réactif avec ce que tu as sur ce qu'il te faut : « Balle de soie 2/4 ». Quand le dernier tombe dans tes sacs, la ligne passe au blanc et la commande remonte en tête sous « Prêt à livrer ». Rien à ouvrir, rien à aller vérifier. Glisse n'importe quelle ligne pour déplacer le tout, /co track si tu n'en veux pas."] =
        "The orders you've accepted sit on screen the way tracked quests do. The item you agreed to make, and under it every reagent with what you've got against what you need, like 'Bolt of Silk Cloth 2/4'. When the last one drops into your bags the line turns white and the order climbs to the top under 'Ready to deliver'. Nothing to open, nothing to go and check. Drag any line to move the whole thing, /co track if you'd rather not have it.",
    ["Il suit aussi ta montée de métier. Pour chaque métier encore en progression, il nomme LA recette qui achète ton prochain point le moins cher, liste ses réactifs de la même façon, et te dit quel plan acheter et à qui quand la route la moins chère passe par un plan que tu n'as pas encore."] =
        "It follows your leveling as well. For each profession still climbing, it names the single recipe that buys your next skill point for the least gold, lists its reagents the same way, and tells you which plan to buy and from whom when the cheapest route runs through one you don't own yet.",
    ["Tu peux donner un nom et une histoire à une commande. Un second bouton à côté de Poster l'ouvre comme une fiche de quête sur parchemin, où tu écris un titre et quelques lignes. Les artisans qui la voient lisent « Le fardeau du forgeron » plutôt que « Heaume de thorium enchanté », avec ton texte dessous. C'est la même commande, elle se lit juste comme une quête."] =
        "You can give an order a name and a story. A second button next to Post opens it as a quest sheet on parchment, where you write a title and a few lines. The crafters who see it read 'The blacksmith's burden' rather than 'Enchanted Thorium Helm', with your text underneath. Same order, it just reads like a quest.",
    ["Et il y a un journal. /co journal ouvre une fenêtre parchemin où tes commandes et tes vraies quêtes partagent une seule liste, groupées par section et par zone, avec le texte complet de celle que tu cliques. Il lit le journal de quêtes du jeu sans y écrire, donc ta propre fenêtre de quête garde ce que tu avais sélectionné. Il montre aussi toutes les quêtes d'une zone d'un coup, là où le journal du jeu s'arrête à six."] =
        "And there's a journal. /co journal opens a parchment window where your orders and your real quests share one list, grouped by section and by zone, with the full text of whichever you click. It reads the game's quest log without writing to it, so your own quest window keeps whatever you had selected. It shows every quest in a zone at once, too, where the game's log stops at six.",
    ["Un correctif de joaillerie au passage : un en-tête de taille comme « Endurance - Solide » disparaissait de la fenêtre métier quand tu ne connaissais qu'une seule gemme de cette taille, alors que l'onglet Commande l'affichait. Les deux vues classent pareil maintenant."] =
        "One Jewelcrafting fix while I was in there. A cut header like 'Stamina - Solid' vanished from the profession window when you only knew one gem of that cut, even though the Order tab still showed it. Both views group the same way now.",
    -- v1.28.0
    ["Le plan de route suit chaque point, et sait quand une recette est finie"] =
        "The leveling route keeps up, and knows when a recipe's done",
    ["Le plan de route prenait du retard : tu gagnais un point et il gardait l'ancien plan jusqu'à ce qu'autre chose le réveille — pire en Enchantement, où le jeu ne donne jamais ton rang en direct à l'addon. Il suit maintenant chaque point à l'instant où tu le gagnes. Il sait aussi quand une recette passe grise : il lisait la couleur en direct à ton rang courant mais projetait les rangs suivants d'après les données, si bien qu'une recette que tu voyais grise était encore comptée, et conseillée, un rang plus loin. Grise, c'est fini : elle disparaît des étapes ET du total, pas seulement de la première ligne."] =
        "The Leveling Route used to lag behind: you'd gain a point and it kept the old plan until something else nudged it — worst on Enchanting, where the game never hands the addon your live skill. It follows every point now, the moment you earn it. It also learned when a recipe goes grey: it read the live colour at your current rank but projected the ranks ahead from data, so a recipe you could see greyed out in your list still got counted, and recommended, a rank later. Grey is grey for good now: it drops out of the steps and the total, not just the top line.",
    ["La fenêtre de route a rattrapé la bourse d'artisan : une case pour inclure ou non les plans à acheter, un vrai en-tête avec l'icône du métier et ton rang, et un bandeau « Étapes » repliable pour que la liste de courses ne passe plus sous le bas de la fenêtre. Et au plafond entraîné, elle ne se contente plus de hausser les épaules : elle explique comment débloquer le palier suivant — l'entraîner chez ton formateur, ou acheter le livre de rang pour les Premiers soins — et pointe le PNJ où aller, filtré à ta faction."] =
        "The route window caught up with the artisan pouch: a box to fold the buyable recipes in or out, a proper header with the profession's icon and your rank, and a collapsible Steps band so the shopping list stops getting pushed off the bottom of the small window. And at your trained cap it no longer just shrugs: it tells you how to open the next tier — train it at your trainer, or buy the rank book for First Aid — and points you at the NPC to visit, filtered to your faction.",
    -- v1.27.2
    ["Un onglet Entrantes, et des demandes qui ne traînent plus"] =
        "An Incoming tab, and requests that don't linger",
    ["Les demandes captées dans /commerce et /guilde restaient affichées des heures. On en voyait encore une marquée « 20h » le lendemain, bien après que le demandeur ait trouvé quelqu'un d'autre. Elles disparaissent maintenant 30 minutes après avoir été vues, comme un cri dans /commerce. Celle que tu as acceptée, elle, tient six heures : tu t'es engagé dessus."] =
        "Requests picked up from /trade and /guild used to hang around for hours. One would still read \"20h\" the next day, long after the buyer had found someone else. They now disappear 30 minutes after they're seen, the way a shout in /trade works. One you've accepted sticks around six hours, since you've committed to it.",
    ["La fenêtre métier ne fait plus non plus semblant que tu peux les honorer : elle listait une demande de gemme dont tu n'as pas la recette, bouton Accepter compris, à 190 de compétence pour une taille qui en demande 350. Elle ne montre plus que ce que tu sais vraiment faire (revérifié en direct, donc une recette apprise la fait réapparaître). Ce qu'elle masque reste dans le Carnet pour le passer à un ami capable."] =
        "The profession window also stopped pretending you could fill them. It listed a request for a gem you have no recipe for, Accept button and all, at skill 190 for a cut that needs 350. It now only shows what you can really craft (rechecked live, so a recipe you learn brings the request back). Whatever it hides stays in the Ledger for you to hand off to a capable friend.",
    ["Et ces demandes du chat ont leur propre onglet Entrantes, avec un compteur à côté. Une demande lue dans /commerce ou poussée par un pair n'a rien à voir avec une vraie commande de l'addon (pas de cycle accepter-livrer, tu réponds au chuchotement à la main) : les mélanger aux onglets Tous / Guilde / Amis / Annuaire embrouillait les deux. Corrigé aussi, une commande arrivée sans métier déclenchait son alerte mais n'apparaissait dans aucune fenêtre métier ; le métier est maintenant déduit de l'objet."] =
        "And those chat requests get their own Incoming tab, with a count next to it. A request read off /trade or forwarded by a peer is nothing like a real addon order (no accept-deliver cycle, you answer them in whisper by hand), so mixing them into the All / Guild / Friends / Directory tabs muddied both. Also fixed, an order that arrived without a profession fired its alert but showed up in no profession window; the profession is now worked out from the item.",
    -- v1.27.1
    ["Prêt pour le patch 1.15.9"] = "Ready for patch 1.15.9",
    ["Classic Era, SoD et Hardcore passent à la 1.15.9 et à sa nouvelle interface. L'addon a été vérifié contre elle et se déclare compatible : le badge [Dispo] au-dessus des plaques fonctionne comme avant. Seule limite, décidée par Blizzard : en instance, les plaques amies sont réservées au jeu lui-même, donc pas de badge en donjon."] =
        "Classic Era, SoD and Hardcore move to 1.15.9 and its new interface. The addon has been checked against it and marks itself compatible, the [LFW] badge above nameplates works like before. One limit, Blizzard's call: inside instances, friendly nameplates belong to the game itself, so no badge in dungeons.",
    ["Corrigé : la liste des PNJ sous une recette manquante (formateurs, vendeurs) mélangeait les deux factions, au point d'envoyer un personnage Alliance à Fossoyeuse. Les PNJ du camp d'en face sont maintenant masqués ; les monstres à butin et les PNJ neutres restent, eux servent tout le monde."] =
        "Fixed: the NPC list under a missing recipe (trainers, vendors) mixed both factions, to the point of sending an Alliance character to the Undercity. NPCs from the other side are now hidden; loot mobs and neutral NPCs stay, they serve everyone.",
    -- v1.27.0
    ["Prévenu quand une nouvelle version sort"] = "Tells you when a new version is out",
    ["L'addon repère maintenant qu'il tourne en retard. Il lit la version des joueurs que tu croises sur le réseau, et dès qu'il en voit une plus récente chez plusieurs personnes différentes, il te le dit d'une ligne dans le chat et pose un point rouge sur le bouton minimap. Le point s'efface tout seul une fois que tu as mis à jour."] =
        "The addon now notices when you're running behind. It reads the version off other players you cross paths with on the network, and once it's seen a newer one from a few different people, it drops a single line in chat and puts a red dot on the minimap button. The dot clears itself once you update.",
    ["Ce « plusieurs personnes différentes » est voulu : un joueur isolé ne peut pas te faire croire que tu es en retard en annonçant un faux numéro, il faut que des joueurs distincts le confirment. Et ça ne te prévient qu'une fois par version, jamais à chaque connexion. Tape /co version pour voir ta version et s'il en existe une plus récente."] =
        "That \"few different people\" part is on purpose. One player can't spoof you into thinking you're behind by broadcasting a fake number, it takes separate players to corroborate it. And it only tells you once per version, never every login. Type /co version to see what you're on and whether there's something newer.",
    -- v1.26.0
    ["Filtre n'importe quelle liste par la stat qu'elle donne"] =
        "Filter any craft list by the stat it gives",
    ["Chaque liste de recettes — l'onglet Commande, la fenêtre métier, Mes artisans — reçoit un sélecteur de stat. Tu choisis Force, tu ne vois que ce qui donne de la Force : gemmes, équipements, élixirs. Le menu se remplit avec ce que le métier ouvert fabrique vraiment, donc la Cuisine ne te propose pas Puissance des sorts. Ces stats ne sont écrites nulle part, elles sont lues sur ton propre jeu — dans ta langue, et valables pour des objets que je n'ai jamais regardés, Wrath compris."] =
        "Every recipe list, the Order tab, the profession window and My Artisans, gets a stat picker. Pick Strength and you see only what gives Strength, gems, gear, elixirs. The menu is built from what the open profession actually makes, so Cooking won't offer you Spell Power. None of those stats are typed out anywhere, they're read off your own client, so they show up in your language and keep working on items I've never looked at, Wrath included.",
    ["L'alchimie se range mieux aussi : les élixirs se regroupent sous la stat qu'ils donnent, pendant que les potions de soin et de mana, les flacons et les transmutations gardent leurs propres en-têtes — « rend de la vie » n'a jamais été une stat. Sur TBC, ça sort 74 consommables du fourre-tout Divers."] =
        "Alchemy sorts better too. Elixirs group under the stat they give, while healing and mana potions, flasks and transmutes keep their own headings, since \"restores health\" was never a stat. On TBC that pulled 74 loose consumables out of the Misc pile.",
    -- v1.25.0
    ["Les gemmes se rangent par couleur, puis par ce qu'elles donnent"] =
        "Cut gems sort by color, then by what they give",
    ["La joaillerie versait toutes les gemmes taillées sous un seul en-tête « Gemme ». Elles se rangent maintenant par couleur de châsse, et sous chaque couleur par la stat qu'elles donnent : « Force - Audacieux », « Endurance - Solide ». Cette stat n'est pas une table écrite à la main, elle est lue sur ton propre jeu — donc dans ta langue, et valable pour des gemmes que je n'ai jamais regardées."] =
        "Jewelcrafting dumped every cut gem under a single \"Gem\" heading. Gems now sit under their socket color, and under that, under the stat they give, so you get \"Strength - Bold\" and \"Stamina - Solid\". That stat isn't a list I typed out, it's read off your own client, which is why it shows up in your language and why it'll keep working on gems I've never looked at.",
    ["Les gemmes méta, elles, reviennent à une simple liste : chaque taille de méta n'existe qu'en un seul exemplaire, un en-tête au-dessus n'aurait fait que répéter la ligne. Bagues, colliers, statues et figurines gardent le classement qu'ils avaient."] =
        "Meta gems get a plain list instead. Every meta cut is a single gem, so a heading above each one just repeated the line underneath it. Rings, necklaces, statues and figurines keep sorting the way they always did.",
    ["Corrigé aussi : quand un enchanteur te demandait une pièce, l'invite ne s'affichait parfois jamais. Une première demande arrivée trop tôt, avant que tu aies équipé la pièce, armait quand même le délai de cinq secondes — et la vraie demande qui suivait passait à la trappe. Le délai ne démarre plus que sur une demande réellement affichée."] =
        "Also fixed: when an enchanter asked you for a piece, the prompt sometimes never showed up. A first request that arrived a moment too early, before you'd equipped the piece, still armed the five second cooldown, so the real request that followed got swallowed. The cooldown now only starts once a request has actually gone through.",
    -- v1.24.2
    ["Les stats d'enchant parlent enfin ta langue"] =
        "Enchant stat names finally speak your language",
    ["Les sous-catégories de la vue enchant (Force, Esprit, Croisé…) venaient d'un libellé interne jamais traduit : tout le monde les voyait en anglais, client français compris. Elles sont maintenant lues directement sur ton jeu, comme les noms de sorts, donc dans ta langue sans rien à traduire à la main à chaque nouvelle recette."] =
        "The subcategory names in the enchant view (Strength, Spirit, Crusader, and so on) were stuck in English for everyone, French clients included, because they came from an internal label the addon never translated. They're now read straight from your game client, the same way spell names already are, so they show up in your own language with no manual translation as new enchants get added.",
    -- v1.24.1
    ["Deux minerais de plus dans les commandes de récolte"] =
        "Two more ores in gathering orders",
    ["Le khorium et l'éternium n'apparaissaient pas comme commandables dans l'onglet Récolte. La liste des minerais était dérivée de ceux qu'on peut prospecter en gemmes, et ni l'un ni l'autre ne l'est — le même trou qui cachait déjà l'argent, l'or, le vrai-argent et le sombrefer. Les deux rejoignent la liste."] =
        "Khorium and Eternium ore weren't showing up as orderable in the Gather tab. The mining list was built from what's prospectable into gems, and neither one is, the same gap that used to hide Silver, Gold, Truesilver and Dark Iron. Both join that list now.",
    -- v1.24.0
    ["La pièce à enchanter se pose d'un clic, et une bourse qui suit la progression"] =
        "The piece to enchant places itself in one click, and a pouch that keeps up",
    ["Depuis la v1.21.0, un enchanteur peut cliquer un emplacement de la silhouette d'échange pour te demander la pièce à enchanter. Si tu as l'addon toi aussi, ce clic affiche maintenant une invite chez toi : accepte, et ta pièce équipée se pose toute seule dans l'emplacement « ne sera pas échangé ». Rien n'est donné (cet emplacement ne peut pas changer de mains), la pose est verrouillée sur lui, et rien ne bouge sans ton clic. Sans l'addon en face, le chuchotement explicatif part comme avant."] =
        "Since v1.21.0, an enchanter can click a slot on the trade silhouette to ask for the piece to enchant. If you run the addon too, that click now shows a prompt on your side: accept, and your equipped piece places itself in the \"will not be traded\" slot. Nothing is given away (that slot can't change hands), the placement is locked to it, and nothing moves without your click. No addon on the other side, and the explanatory whisper goes out as before.",
    ["La bourse d'artisan se met à jour en direct : fenêtre ouverte, chaque point de métier gagné par le personnage suivi (et chaque recette apprise) recalcule la liste de courses — plus besoin de la rouvrir pour voir la route changer."] =
        "The artisan pouch now updates live: with the window open, every skill point the tracked character gains (and every recipe they learn) recomputes the shopping list, no reopening needed to see the route change.",
    -- v1.23.0
    ["La bourse d'artisan : la liste de courses de tes guildeux, et deux corrections réseau"] =
        "The artisan pouch: a shopping list for your guildmates, and two networking fixes",
    ["L'onglet Artisans gagne un bouton sac après les icônes de métier de chaque fiche : un clic ouvre la liste de courses des matériaux qu'il te faut pour monter tes métiers, calculée en local à partir de ce que le jeu diffuse déjà (aucun nouveau trafic réseau). Les réactifs que ton propre métier sait fabriquer sont décomposés en composants de base, et les objets vendus par un PNJ sont mis de côté dans une note plutôt que d'encombrer la grille."] =
        "The Artisans tab gets a bag button after each entry's profession icons: click it and a shopping list opens for the materials that person needs to keep leveling, worked out locally from what the game already broadcasts (no new network traffic). Reagents their own profession can make from something cheaper get broken down into base components, and vendor items get pulled into a plain note instead of cluttering the grid.",
    ["Coche « inclure les plans à acheter » et les recettes derrière un coût rejoignent la liste : les plans-objets comme fourniture à apporter, les plans de formateur comme simple note. Le même bloc de fournitures s'affiche maintenant sous le plan de route « quoi monter ensuite », avec le PNJ où aller (nom, zone, coordonnées) et une épingle TomTom cliquable si tu l'as installé."] =
        "Check \"include recipes to buy\" and plans behind a gold cost join the list too: purchasable plan items as something to hand over, trainer plans as a note. The same supply block now shows up under the \"what to level next\" route planner, with the vendor to visit (name, zone, coordinates) and a clickable TomTom pin if you have it installed.",
    ["Une recette sans réactif au prix connu (la poussière d'enchantement, par exemple) ne fait plus sauter tout un tronçon du plan de route : elle sert maintenant de repli marqué « ? » quand rien de mieux n'est disponible. Une table de désenchantement maison alimente aussi l'infobulle des poussières, essences et éclats affichés dans ces listes."] =
        "A recipe with no priced reagent, Enchanting dust being the usual offender, no longer knocks a whole stretch out of the route plan: it's now used as a fallback marked with a \"?\" when nothing better is available. A curated disenchant table also backs the tooltip on any dust, essence or shard shown in these lists.",
    ["Deux corrections : un compte à plusieurs personnages se voyait parfois lister lui-même comme « joignable via » son autre perso dans son propre onglet Artisans, corrigé. Et le plan de route pouvait s'arrêter avant le vrai plafond de compétence après une formation chez le maître, à cause d'une assignation Lua qui perdait silencieusement sa seconde valeur."] =
        "Two fixes: an account with more than one character sometimes saw itself listed as reachable \"via\" its own alt in its own Artisans tab, fixed. And the route planner could stop short of a profession's real skill cap right after a trainer promotion, because a Lua multi-assignment quietly dropped its second return value.",
    -- v1.22.1
    ["Les alertes de commande vérifient enfin le métier, et un plan de route qui suit son propre badge"] =
        "Order alerts that actually check the profession, and a route plan that matches its own badge",
    ["Une commande à portée large (guilde, amis, tous) déclenchait un toast même chez un joueur sans le métier, du moment qu'elle arrivait par le relais de connexion (chuchotement) plutôt que par le canal : le filtre par métier ne couvrait que le canal. Il s'applique maintenant quel que soit le chemin réseau. Le toast gagne aussi un troisième texte : une commande à portée large n'affiche plus « pour TOI », ce qui donnait l'impression fausse d'une demande personnelle."] =
        "A broad order (guild, friends, everyone) could toast a player who doesn't even have the profession, as long as it arrived through the login relay (a whisper) instead of the channel: the profession filter only covered the channel. It now applies no matter which path the order took. The toast also gets a third text: a broad order no longer reads \"for YOU,\" which read like a personal request when it wasn't one.",
    ["Le plan de route « quoi monter ensuite » pouvait suggérer une recette différente du badge de coût de la liste, les deux lisant des données légèrement différentes. Le plan utilise maintenant la difficulté réelle de la fenêtre métier à ton rang actuel plutôt qu'une projection, et se rafraîchit au même rythme que le badge. La commande |cFFFFFFFF/co lvldump|r affiche le détail en cas de nouveau désaccord."] =
        "The \"what to level next\" route planner could suggest a different recipe than the list's own cost badge, since the two were reading slightly different data. The route now uses the profession window's real difficulty at your current rank instead of a projection, and refreshes on the same clock as the badge. |cFFFFFFFF/co lvldump|r prints the details if you ever spot a mismatch again.",
    -- v1.22.0
    ["L'aide contextuelle, des dépendances qu'on ne peut plus rater, et une touche Échap qui obéit"] =
        "Contextual help, unmissable dependencies, and an Escape key that behaves",
    ["Un nouveau bouton « i » ouvre l'aide contextuelle du jeu, le même système que Blizzard utilise pour ses propres fenêtres : le fond s'assombrit et une bulle pointe directement sur ce dont il est question. Chaque onglet (Vue Métier, Commande, Récolte, Artisans, Mes artisans, Carnet) a sa propre visite guidée, donc le bouton explique ce qui est réellement affiché plutôt qu'une infobulle générique."] =
        "A new \"i\" button opens the game's own contextual help, the same system Blizzard uses for its own windows: the background dims and a callout points straight at whatever's in question. Every tab (Profession view, Order, Gather, Artisans, My Artisans, Ledger) has its own tour, so the button explains what's actually on screen instead of a generic tooltip.",
    ["Lazy Gold et MTSL restent optionnels, mais rien ne signalait qu'ils manquaient. Les boutons qui en dépendent restent visibles et colorés même sans l'addon installé, et cliquer dessus sans l'avoir ouvre désormais une explication de ce qu'il fait et où le trouver, plutôt que de ne rien faire du tout."] =
        "Lazy Gold and MTSL stay optional, but there was no sign either one was missing. The buttons that need them stay visible and colored whether or not you have the addon installed, and clicking one without it now pops a short explanation of what it does and where to get it, instead of doing nothing.",
    ["L'alerte « peut faire cette commande » se déclenchait même quand tu ne connaissais pas la recette, souvent des gemmes ou enchants dont tu avais les réactifs sans le plan. Elle vérifie maintenant tes recettes connues avant de te notifier sur tes propres commandes. Un ami en ligne sans l'addon ne s'affiche plus « Hors ligne » par erreur."] =
        "The \"can craft that\" alert fired even when you didn't actually know the recipe, usually gems or enchants you had the reagents for but not the plan. It now checks your known recipes before nagging you about your own orders. A friend who's online without the addon no longer shows up as offline by mistake.",
    ["Échap laissait souvent les fenêtres de métier ouvertes, et trois rapports différents pointaient la même cause : cacher ou désactiver la souris d'une fenêtre protégée en plein combat déclenche une erreur du jeu. Les fenêtres passent maintenant par un petit relais dédié, donc Échap les ferme proprement, en combat ou non."] =
        "Escape used to leave profession windows open more often than not, and three separate bug reports pointed at the same cause: hiding or disabling mouse input on a protected window mid-combat throws a game error. Windows now route through a small proxy frame instead, so Escape closes them cleanly whether or not you're in combat.",
    ["L'aide « quoi monter ensuite » affiche maintenant le coût par point de compétence, une pastille de prix Auctioneer, et une icône vers le PNJ qui vend une recette que tu ne connais pas encore, en plus d'un tri affiné."] =
        "The \"what to level next\" helper now shows cost per skill point, an Auctioneer price badge, and an icon pointing at the vendor who sells a recipe you don't know yet, on top of a slightly smarter sort.",
    ["Cette même aide gagne un plan de route : clique le bouton carte et il déroule toute ta montée rang par rang, en choisissant à chaque étape la recette la moins chère (apprise ou achetable, plans compris) et en additionnant le coût total. Les recettes à cooldown ou avec un réactif sans prix connu sont exclues exprès, elles fausseraient le total. Demande Lazy Gold ; MTSL ajoute les prix de plans formateur et vendeur au calcul."] =
        "That same helper gets a route planner now: click the map button and it walks your whole climb rank by rank, picking the cheapest recipe at each step (learned or buyable, plans included) and totaling the cost. Recipes with a cooldown or a reagent with no known price are left out on purpose, they'd throw the total off. Needs Lazy Gold; MTSL adds trainer and vendor plan prices to the mix.",
    -- v1.21.0
    ["L'enchant par emplacement, et un panneau d'échange qui ne cache plus rien"] =
        "Enchants by slot, and a trade panel that stops hiding things",
    ["Choisir un enchant demandait de fouiller des centaines de plans aux noms presque identiques. L'onglet Commande a maintenant une vue silhouette : clique l'emplacement à enchanter, tu obtiens ses stats, puis ses variantes de la plus forte à la plus faible. La bascule est dans la bande de filtres ; la liste reste pour tout ce qui n'a pas d'emplacement (huiles, baguettes, produits de désenchantement)."] =
        "Picking an enchant meant scrolling hundreds of plans with near-identical names. The Order tab has a character-silhouette view now: click the slot you want enchanted, get that slot's stats, then its variants from strongest to weakest. Toggle it from the filter bar; the plan list stays for everything that has no slot (oils, wands, disenchant products).",
    ["Le panneau d'enchant de l'échange n'affichait que 8 lignes, et le « +N autre(s) » du bas n'était pas cliquable : au-delà de la 8ᵉ place, un enchant était tout bonnement inatteignable — c'est ainsi qu'un enchanteur à qui on avait passé les réactifs ne se voyait jamais proposer la bonne recette, noyée sous les variantes de haut rang. La liste défile à la molette, et elle est classée par ce qu'on te demande : d'abord les enchants dont ton partenaire vient de poser les réactifs, puis ce que tes sacs permettent, puis le reste."] =
        "The trade enchant panel only ever drew 8 rows, and the \"+N more\" line at the bottom wasn't clickable: past the eighth entry, an enchant was simply unreachable. That's how an enchanter who'd been handed the reagents never got offered the right recipe, buried under higher-rank variants. The list scrolls now, and it's ordered by what you're being asked for: enchants whose reagents your partner just put on the table come first, then what your bags can already make, then the rest.",
    ["Tant que la case « ne sera pas échangé » est vide, le panneau ne disparaît plus : il montre la même silhouette, avec le modèle de ton partenaire, et cliquer un emplacement lui chuchote d'y poser cette pièce. La plupart des gens qui te tendent un objet ignorent que cette case existe."] =
        "While the \"will not be traded\" slot is empty, the panel no longer vanishes: it shows the same silhouette, with your trade partner's model in it, and clicking a slot whispers them to drop that piece in. Most people who hand you gear have no idea that slot exists.",
    ["Deux correctifs : les enchants de poignets et de bâton de Wrath n'apparaissaient jamais dans le panneau d'échange (le jeu les écrit « Bracers » et « Staff » là où les autres extensions disent « Bracer »), et un enchant de bâton ne se propose plus que sur un vrai bâton. Le panneau ne touche plus non plus à ses boutons pendant un combat, ce que le jeu interdit."] =
        "Two fixes: Wrath's wrist and staff enchants never showed up in the trade panel (the game spells them \"Bracers\" and \"Staff\" where other expansions say \"Bracer\"), and a staff enchant only offers itself on an actual staff now. The panel also stops touching its buttons while you're in combat, which the game blocks outright.",
    ["Plus discret : les lignes de chat « X sait faire cette commande captée » sont désactivées par défaut — la commande est poussée aux amis capables dans tous les cas, le message n'était que du bruit. |cFFFFFFFF/co verbose|r les remet."] =
        "Quieter now: \"X can craft that captured order\" chat lines are off by default. The order still gets pushed to capable friends either way, so the message was noise. |cFFFFFFFF/co verbose|r brings it back.",
    -- v1.20.0
    ["Enchante en un clic, trié par emplacement, et depuis l'échange"] = "One-click enchants, sorted by slot, right from the trade window",
    ["Le bouton « Créer » de l'Enchantement avait un vieux bug intermittent : parfois rien ne se passait, et resélectionner la recette finissait par le faire marcher. Cause trouvée : sélectionner une recette n'arme pas le bouton natif de Blizzard, notre clic sécurisé tombait donc sur un bouton désactivé. Corrigé — ça devrait marcher du premier coup, à chaque fois."] =
        "The enchanting Create button had a long-standing intermittent bug: sometimes it just wouldn't fire, and re-selecting the recipe a few times eventually got it working. Root cause found: selecting a recipe doesn't actually arm Blizzard's native create button, so our secure click was landing on a disabled button. Fixed. Should just work now, every time.",
    ["Les recettes d'enchantement ne s'entassent plus dans un fourre-tout « Autres/Divers » : elles se rangent par emplacement (Poignets, Torse, Main gauche…) puis par stat de base (Force, Esprit, Déviation), le nom raccourci à la stat seule puisque l'emplacement est déjà dans l'en-tête."] =
        "Enchant recipes no longer pile up in a single Other/Misc bucket: they're grouped by slot (Wrist, Chest, Off-Hand...) then by base stat (Strength, Spirit, Deflection), with the name trimmed to just the stat since the slot's already in the header.",
    ["Sélectionner un enchant d'équipement affiche un bouton « Enchanter équipé » à côté de Créer : un clic l'applique directement sur la pièce que tu portes, sans avoir à cibler."] =
        "Selecting an equip-slot enchant now shows an \"Enchant equipped\" button next to Create: one click casts it on the item you're wearing in that slot, no manual targeting.",
    ["Et quand quelqu'un te tend un objet à enchanter en échange, le poser dans la case « ne sera pas échangé » ouvre un petit panneau listant tes enchants pour cet emplacement, prêts à lancer sans fouiller ta fenêtre de métier (qui doit rester ouverte : le jeu ne renseigne tes recettes connues que pendant qu'elle l'est)."] =
        "And when someone hands you gear to enchant over trade, dropping it in the \"will not be traded\" slot now pops a small panel listing every enchant you know for that slot, ready to cast without hunting through your profession window (which still needs to be open: the game only reports your known recipes while it's up).",
    -- v1.19.1
    ["Correctif : l'icône « dispo » remarche sur la nouvelle UI des plaques"] = "Fix: the availability badge works again on the newer nameplate UI",
    ["Sur le client TBC (et bientôt Era/Saison de la Découverte à la 1.15.9), l'icône « recherche de travail » au-dessus de la plaque d'un artisan cessait de s'afficher quand son statut changeait : la nouvelle interface de plaques a renommé un champ interne que l'addon lisait. Corrigé. Elle reste invisible en instance (donjon, raid) : le jeu verrouille les plaques amies aux addons là-bas, rien à faire de notre côté."] =
        "On the TBC client (and soon Era/Season of Discovery with patch 1.15.9), the \"looking for work\" badge over a crafter's nameplate stopped showing up when their status changed: the newer nameplate UI renamed an internal field the addon was reading. Fixed. It still won't show inside an instance (dungeon, raid): the game locks friendly nameplates away from addons there, nothing we can do about that one.",
    -- v1.19.0
    ["Propose des recettes précises, diffuse tes réactifs, et le LFW marche même sans l'addon"] = "Recipes in your offer, a share button, and LFW without the addon",
    ["« Chercher du travail » propose maintenant des recettes précises, pas seulement des réactifs : coche des plans dans la liste et qui te consulte voit « propose : Bouclier de fer, Gilet de mailles de cuivre » à côté de ce que tu fournis déjà."] =
        "\"Look for work\" now lets you name exact recipes, not just reagents. Check off plans in the recipe list and whoever's browsing your offer sees \"offers: Iron Buckler, Copper Chain Vest\" next to whatever mats you're already listing.",
    ["Un bouton « Diffuser » envoie la liste de réactifs d'une recette ou d'une commande dans un canal au choix (guilde, dire, groupe/raid, un canal numéroté), avec le lien de chaque objet — une liste de courses en un clic, depuis la vue métier, la carte de commande ou le panneau de publication."] =
        "A \"Share\" button sends a recipe's or an order's reagent list to a channel of your choice (guild, say, party/raid, a numbered channel), with a link for every item — a shopping list in one click, from the profession window, the order card, or the posting panel.",
    ["Le LFW marche même sans l'addon : tape « LFW enchantement » en Commerce ou Général et tu apparais comme dispo, avec la même icône de plaque qu'un joueur qui a Crafting Order. Plus une correction : une recette déjà apprise ne s'affichait plus en double avec MissingTradeSkillsList."] =
        "Look for work works even without the addon: type \"LFW enchanting\" in Trade or General and you show up as available, same nameplate icon as anyone running Crafting Order. Plus a fix: a recipe you'd already learned no longer got listed twice with MissingTradeSkillsList.",
    -- v1.18.0
    ["Chercher du travail : dis ce que tu offres, et trie par progression"] = "Look for work, now with an offer, and sort by what levels you",
    ["« Chercher du travail » ne se contente plus de te signaler dispo. Clique l'engrenage à côté du bouton et dis ce que tu proposes : tu fournis les composants de base, tu fournis tel réactif précis, une commission fixe par craft, ou seulement les plans qui te font gagner un point de compétence. Ça s'affiche sur ta ligne [Dispo] et dans l'infobulle au-dessus de ta tête, avec une pièce s'il y a une commission et un sac si tu fournis des compos."] =
        "\"Look for work\" does more than flag you as available. Click the gear next to the button and say what you're offering: you'll bring the basic reagents, you'll supply a specific component, a flat tip per craft, or only jobs that give you a skill point. It shows on your [Dispo] line and in the tooltip over your head, with a coin if there's a tip and a bag when you're providing mats.",
    ["L'icône « dispo » au-dessus de la plaque d'un artisan marche maintenant sur Era et Saison de la Découverte, plus seulement sur le client TBC. Active les plaques des amis (nameplateShowFriends) et l'icône du métier flotte au-dessus de qui cherche du travail à côté de toi."] =
        "The \"available\" icon over a crafter's nameplate works on Era and Season of Discovery now, not just the Burning Crusade client. Turn on friend nameplates (nameplateShowFriends) and the profession icon floats over anyone near you who's looking for work.",
    ["Les recettes se trient par ce qui te fait encore progresser : un troisième bouton outil remonte en tête les plans qui donnent un point, d'orange à gris. Les commandes ont le même « ce qui me fait monter d'abord », avec un liseré de difficulté sur le côté de chaque ligne. Plus quelques corrections au passage."] =
        "Recipes sort by what still levels you: a third tool button lifts the plans that give a skill point to the top, orange to grey. Orders get the same \"levels me first,\" with a difficulty tint down the side of each line. Plus a few fixes along the way.",
    -- v1.17.1
    ["Correctif : erreur au login en « Chercher du travail »"] = "Fixed a login error while looking for work",
    ["Si tu avais activé « Chercher du travail », te connecter ou faire /reload pouvait déclencher une erreur rouge : l'addon annonçait ta disponibilité avant que le jeu n'autorise un addon à parler sur le canal. L'annonce attend maintenant ton prochain clic ou ta prochaine touche — plus d'erreur, et les autres te voient toujours dispo."] =
        "If you had \"Look for work\" on, connecting or reloading could throw a red error: the addon announced your availability before the game lets an addon talk on the channel. The announcement now waits for your next click or keypress — no more error, and others still see you're available.",
    -- v1.17.0
    ["L'interface passe au style natif de WoW"] = "The window matches the game now",
    ["La fenêtre n'a plus son habillage doré maison : elle emprunte le cadre du jeu (barre de titre, portrait rond, onglets, boutons). Elle se fond dans l'interface au lieu de ressembler à un addon posé par-dessus, et rien n'a bougé de ce que tu connais."] = "The window dropped its custom gold skin for the game's own frame (title bar, round portrait, tabs across the top, buttons). It reads as part of the interface instead of something bolted on top, and nothing moved that you'd have to relearn.",
    ["La vue métier est refaite, avec une colonne Commandes en liste : une ligne par commande (demandeur, objet voulu, prix), et le clic ouvre la carte complète (composants fournis, coût des réactifs, Accepter / Refuser / Chuchoter) avec une croix pour revenir à la liste. Et les sous-catégories de récolte (Peaux, Écailles, Herbes, Poissons) sont enfin traduites hors client français."] = "The profession window was rebuilt, with the orders column as a list: one line per order (requester, the item they want, price), and clicking opens the full card (supplied components, reagent cost, Accept / Decline / Whisper) with a close button back to the list. And the gathering sub-headings (Hides, Scales, Herbs, Fish) are finally translated outside a French client.",
    -- v1.15.1
    ["Tes commandes n'appartiennent qu'à toi"] = "Your orders are yours",
    ["Recettes triées, et où est l'or"] = "Sorted recipes, and where the gold is",
    ["Fini le fourre-tout « Consommable » : les recettes sont regroupées par type (potions de soin, de mana, élixirs, flacons, transmutations…) et triées du plus haut niveau au plus bas. Une potion qui rend vie ET mana apparaît sous les deux. Le même classement s'applique partout — Commande, Mes artisans, et les métiers de récolte (minerais, herbes, cuirs, poissons)."] = "No more catch-all \"Consumable\": recipes are grouped by type (healing potions, mana potions, elixirs, flasks, transmutes…) and sorted highest rank to lowest. A potion that restores both health and mana shows under both. The same grouping applies everywhere — the Order tab, My Artisans, and the gathering professions (ores, herbs, leathers, fish).",
    ["Si tu as Lazy Gold, chaque recette affiche sa rentabilité (pièces, étoiles au-delà de mille pièces d'or ; rien pour une perte). La pièce d'or au-dessus de la liste trie par profit, le bouton « 123 » bascule en valeurs exactes. L'onglet Commande a les deux boutons, plus la valeur HV et le coût des réactifs sur chaque commande entrante."] = "If you run Lazy Gold, every recipe shows its profit (coins, stars past a thousand gold; nothing for a loss). The gold coin above the list sorts by profit, the \"123\" button switches to exact amounts. The Order tab gets both buttons, plus the auction value and reagent cost on every incoming order.",
    ["Dans l'annuaire, les métiers passent en icônes : un artisan avec un plan vraiment rentable a un contour doré, le survol nomme le plan, le clic ouvre la Commande déjà ciblée. « Mes artisans » gagne « Tous les plans du royaume » : tous tes persos (même faction) fusionnés et triés par profit — d'un coup d'œil, quel reroll fait des sous. Et si tu as MissingTradeSkillsList, un bouton montre tes recettes non apprises en rouge, avec leur source au clic."] = "In the directory, professions became icons: a crafter with a genuinely profitable plan gets a gold border, hover names the plan, click opens the Order tab already aimed at them. My Artisans gains \"All realm crafts\": every character (same faction) merged and ranked by profit — at a glance, which alt is making money. And if you run MissingTradeSkillsList, a button shows your unlearned recipes in red, with their source on click.",
    ["Les identifiants de commande étaient devinables : n'importe qui pouvait réécrire la tienne (acheteur, prix, quantité). C'est fermé : seul son auteur peut la modifier. Le relais entre joueurs, lui, continue de fonctionner — c'est comme ça qu'une commande atteint quelqu'un que le canal n'a jamais touché."] =
        "Order ids were guessable, and anyone could rewrite yours (buyer, price, quantity). That's closed: only the person who posted an order can change it. Relaying between players still works, which is how an order reaches someone the channel never touched.",
    ["On ne peut plus te faire mettre en sourdine en postant de fausses commandes en ton nom, et un acheteur dont les commandes sont relayées en rafale n'est plus muté par erreur. « X a refusé ta commande » et le rappel « tu sais le faire » ne se rejouent plus en boucle, et rien ne passe d'un joueur que tu as mis en sourdine."] =
        "Nobody can get you muted by posting fake orders under your name, and a buyer whose orders get relayed in a burst is no longer muted by mistake. \"X declined your order\" and the \"you can craft this\" nudge no longer replay on a loop, and nothing gets through from someone you've muted.",
    ["La vue métier n'affiche plus les commandes privées destinées à quelqu'un d'autre, ni les expirées. Ton compteur de crafts livrés ne peut plus être gonflé par un tiers. Et croiser un artisan coûte deux fois moins de messages : le bonjour porte maintenant tes métiers, ce qui règle aussi les artisans qui s'affichaient sans aucun métier."] =
        "The profession window no longer shows private orders meant for someone else, nor expired ones. Your delivered count can't be padded by a stranger. And crossing paths with an artisan costs half the messages it used to: saying hello now carries your professions, which also fixes artisans showing up with no professions at all.",
    -- v1.15.0
    ["Recherche de travail : signale que tu es dispo"] = "Looking for work: flag yourself as available",
    ["Ouvre un métier et clique « Chercher du travail » : tout le royaume sait que tu es dispo, une icône d'artisan s'affiche au-dessus de ta tête pour ceux qui passent, et tu apparais « [Dispo] » dans leur annuaire. Ça s'éteint tout seul au bout d'un moment si tu oublies."] =
        "Open a profession and click \"Look for work\": the whole realm knows you're available, an artisan icon shows over your head for anyone passing by, and you appear as \"[LFW]\" in their directory. It lapses on its own after a while if you forget.",
    ["Au passage : les deux fenêtres ne s'emmêlent plus (un clic la ramène au premier plan), l'annuaire a un bouton partenaire et se limite à ta faction (pas d'échange cross-faction sur Classic), et un artisan ne s'affiche plus avec un métier qui n'est pas le sien."] =
        "Along the way: the two windows no longer tangle (a click brings one to the front), the directory has a partner button and sticks to your faction (no cross-faction trading on Classic), and an artisan no longer shows a profession that isn't theirs.",
    -- (clés v1.8.0/v1.7.0/v1.7.1/v1.6.0/v1.5.0/v1.4.0 retirées : ces versions ne sont plus listées dans l'onglet Nouveautés)
    -- Onglet Nouveautés — v1.13.0
    ["Modération : mutes avec raison, temporaires, liste de confiance"] = "Moderation: mutes with a reason, temporary mutes, a trust list",
    ["Un mute porte désormais une raison et une date, et peut être temporaire : |cFFFFFFFF/co mute Bob 1h spammeur|r se lève tout seul au bout d'une heure (|cFFFFFFFF/co mute|r seul liste les mutés avec raison et temps restant). Et |cFFFFFFFF/co trust <nom>|r marque un joueur de confiance, jamais mis en sourdine automatiquement — le mute manuel restant toujours possible."] =
        "A mute now carries a reason and a date, and can be temporary: |cFFFFFFFF/co mute Bob 1h spammer|r lifts itself after an hour (|cFFFFFFFF/co mute|r alone lists muted players with reason and time left). And |cFFFFFFFF/co trust <name>|r marks a player as trusted, never auto-muted — manual muting still available.",
    -- (clés v1.12.1 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    -- Onglet Nouveautés — v1.12.0
    ["Les recettes de la Saison de la Découverte"] = "Season of Discovery recipes",
    ["304 recettes de la Saison de la Découverte entrent au catalogue : 80 en Travail du cuir, 65 en Forge, 57 en Couture, 48 en Enchantement, 29 en Ingénierie, 16 en Alchimie, plus la Cuisine, le Secourisme et le Minage. Elles apparaissent dans l'onglet Commande, avec leurs réactifs et leur palier d'apprentissage."] =
        "304 Season of Discovery recipes join the catalogue: 80 for Leatherworking, 65 for Blacksmithing, 57 for Tailoring, 48 for Enchanting, 29 for Engineering, 16 for Alchemy, plus Cooking, First Aid and Mining. They show up in the Order tab, with their reagents and skill levels.",
    ["Elles ne se chargent que sur un royaume Saison de la Découverte. Sur un royaume Era classique, rien ne change : l'addon voit exactement le même jeu de recettes qu'avant, et les recettes que tes amis t'ont déjà partagées restent lisibles."] =
        "They load only on a Season of Discovery realm. On a regular Era realm nothing changes: the addon sees exactly the recipe set it saw before, and the recipes your friends already shared with you stay readable.",
    -- Onglet Nouveautés — v1.11.0
    ["Annuler une commande publique atteint tout le royaume"] = "Cancelling a public order now reaches the whole realm",
    ["Une commande publique voyage sur le canal du royaume depuis la v1.10.0, mais pas son annulation : un artisan que tu n'as jamais croisé la voyait « ouverte » pendant six heures, l'acceptait, et farmait les réactifs pour rien. L'annulation part désormais sur le même canal."] =
        "A public order has travelled the realm channel since v1.10.0, but its cancellation did not. A crafter you have never met kept seeing it as open for up to six hours, could accept it, and gathered the reagents for nothing. Cancelling now goes out on the same channel.",
    ["Poster et annuler ne perdent plus de messages. Le canal exige un clic ou une touche et n'accepte qu'une ligne par seconde : un |cFFFFFFFF/co post|r tapé au chat, ou deux commandes postées dans la même seconde, disparaissaient sans trace. Ces lignes patientent maintenant dans une file et partent à ton prochain clic."] =
        "Posting and cancelling no longer lose messages. The channel needs a click or a keypress to carry a line, and takes one line per second: a |cFFFFFFFF/co post|r typed in chat, or two orders posted in the same second, used to vanish without a trace. Those lines now wait in a queue and go out on your next click.",
    ["Seules les commandes NOUVELLES et les ANNULATIONS voyagent sur le canal, et seulement les publiques. Guilde, amis et commandes nommées restent privées ; les acceptations restent entre les deux joueurs concernés."] =
        "Only new orders and cancellations ever travel the channel, and only public ones. Guild, friends and named orders stay private; acceptances stay between the two players involved.",
    -- Onglet Nouveautés — v1.10.2
    ["Correctif : erreur en combat dans la vue métier"] = "Fix: an in-combat error in the profession view",
    ["Sélectionner une recette pendant un combat ne provoque plus d'erreur bloquée : le bouton « Créer » est un bouton sécurisé, que le jeu interdit de masquer en plein combat. L'addon attend maintenant la fin du combat pour l'afficher ou le masquer."] =
        "Picking a recipe during combat no longer throws a blocked-action error. The Create button is a secure button, and the game forbids hiding one mid-combat. The addon now waits until combat ends to show or hide it.",
    -- Onglet Nouveautés — v1.14.0
    ["Un panneau pour gérer les mis en sourdine"] = "A panel to manage who you've muted",
    ["L'onglet Artisans a maintenant une section « En sourdine » : chaque joueur muté y apparaît avec sa raison et le temps restant (ou « permanent »), avec un bouton pour le rétablir directement — plus besoin de deviner qui est encore muté."] =
        "The Artisans tab now has a Muted section: every muted player shows up with their reason and time left (or \"permanent\"), with a button to unmute them right there — no more guessing who's still muted.",
    -- (clés v1.9.0 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    ["VU"] = "SEEN",
    ["vu crafter (sans l'addon)"] = "seen crafting (no addon)",
    ["vu crafter"] = "seen crafting",
    ["%d+ · vu crafter"] = "%d+ · seen crafting",
    -- Cooldowns de recettes (transmutations & co)
    ["%s : prête"] = "%s: ready",
    ["%s : dans %s"] = "%s: in %s",
    ["(estimé)"] = "(estimated)",
    ["Transmutation"] = "Transmute",
    ["%dj"] = "%dd", ["%dh"] = "%dh", ["%dmin"] = "%dmin",
    -- Relais partenaire (fiche d'un artisan hors ligne servie par un contact de confiance)
    ["via %s · il y a %s"] = "via %s · %s ago",
    ["RELAIS"] = "RELAYED",
    -- Rerolls (identité joueur multi-persos, /co alts — opt-in)
    ["rerolls : ACTIVÉS — ta liste de persos est annoncée au réseau."] =
        "alts: ENABLED — your character list is announced to the network.",
    ["rerolls : désactivés — rien n'est annoncé (opt-in : /co alts on)."] =
        "alts: disabled — nothing is announced (opt-in: /co alts on).",
    ["perso principal (vitrine) : %s"] = "main character (front): %s",
    ["persos du compte (%s) : %s"] = "account characters (%s): %s",
    ["le lien n'est vérifié chez les autres qu'après une connexion de CHAQUE perso (addon actif)."] =
        "others only verify the link after EACH character has logged in once (addon running).",
    ["rerolls activés — perso principal : %s (changer : /co alts main <nom>)"] =
        "alts enabled — main character: %s (change: /co alts main <name>)",
    ["rerolls désactivés — dissolution annoncée au réseau."] =
        "alts disabled — dissolution announced to the network.",
    ["perso inconnu sur ce compte : %s (connecte-le une fois avec l'addon)"] =
        "unknown character on this account: %s (log it in once with the addon)",
    ["regrouper tes rerolls (opt-in) : liste annoncée, commandes routées vers ton perso connecté"] =
        "group your alts (opt-in): list announced, orders routed to your online character",
    ["commande nommée pour %s : connecte ce perso, ou active /co alts on pour accepter d'ici."] =
        "order named for %s: log that character in, or enable /co alts on to accept from here.",
    ["|cFFFFCC00commande pour ton reroll %s|r de |cFFFFFFFF%s|r : %s%s%s"] =
        "|cFFFFCC00order for your alt %s|r from |cFFFFFFFF%s|r: %s%s%s",
    ["En ligne via %s"] = "Online via %s",
    ["reroll : %s (%s)"] = "alt: %s (%s)",
    -- v1.31.0
    ["Les cercles d'artisans, posés sur les communautés WoW"] =
        "Crafting circles, built on WoW communities",
    ["Le canal du royaume n'a ni mémoire ni liste de membres : qui n'était pas connecté quand tu as posté n'a rien vu, et chaque session recommence à chercher qui est là. Une communauté WoW répond aux deux. Marque-la avec /co circle et ses membres apparaissent sous « Cercle » dans l'onglet Artisans, avec leur présence, y compris ceux qui sont hors ligne. C'est toi qui crées la communauté et qui invites : un cercle est un petit groupe que tu as choisi, pas le royaume entier."] =
        "The realm channel has no memory and no member list: anyone who wasn't logged in when you posted never saw it, and every session starts by working out again who's around. A WoW community answers both. Mark one with /co circle and its members appear under Circle in the Artisans tab, with their presence, including the ones who are offline. You create the community and you invite who you want: a circle is a small group you picked, not the whole realm.",
    ["Rien n'est posté dans la communauté et rien n'en est lu. Ce qu'une communauté peut réellement porter a été mesuré avant qu'on s'appuie dessus, et c'est étroit : le texte d'un message de club est illisible depuis un addon, et un message addon envoyé sur son canal est accepté puis jeté. Le cercle te donne donc la liste et qui est en ligne ; les commandes et les niveaux de métier continuent de circuler exactement comme avant."] =
        "Nothing gets posted to the community and nothing is read out of it. What a community can actually carry was measured before anything was built on it, and the answer is narrow: the text of a club message can't be read from an addon, and an addon message sent to its channel is accepted and then dropped. So the circle gives you the roster and who's online; orders and skill levels keep travelling exactly as they did.",
    ["Les métiers ne viennent pas non plus de la communauté : ces champs-là ne sont remplis que pour un roster de guilde. Un membre de cercle affiche ses métiers quand il répond à l'addon, comme tout le monde."] =
        "Professions don't come from the community either: those fields only get filled in for guild rosters. A circle member shows their professions once they answer the addon, like anyone else.",
    -- v1.31.1
    ["Les nouveaux venus apparaissent tout seuls"] =
        "New installs show up on their own",
    ["Quelqu'un qui venait d'installer l'addon restait invisible tant qu'il ne cliquait pas « Rafraîchir l'annuaire » — ce que personne ne pense à faire devant un annuaire qui a l'air vide, et avoir l'air vide était justement le problème."] =
        "Someone who had just installed the addon stayed invisible until they clicked Refresh directory, which nobody thinks to do in front of a directory that looks empty, and looking empty was the whole problem.",
    ["À la connexion, l'addon ne s'annonçait que sur le canal caché du royaume, le moins fiable de ses moyens d'atteindre les autres. L'annonce qui touche vraiment les inconnus n'a le droit de partir que juste après un clic ou une touche : à la connexion il n'y avait donc aucun moment pour l'envoyer, et elle était jetée au lieu d'être gardée. Elle attend maintenant, et part à ton premier clic ou ta première touche — quelques secondes, sans que tu fasses quoi que ce soit. La connexion sonde aussi directement les joueurs autour de toi, ce que le bouton « Rafraîchir » faisait déjà et pas elle."] =
        "Logging in only announced you on the hidden realm channel, the least reliable of the ways the addon has of reaching people. The announcement that actually finds strangers is only allowed out right after you click or press a key: at login there was no moment to send it, so it was dropped rather than kept for later. It waits now, and goes out on your first click or keypress, a few seconds, without you doing anything. Logging in also pings the players around you directly, which the Refresh button already did and login didn't.",
    -- v1.32.0
    ["Forever lit enfin tes métiers et tes recettes"] =
        "Forever finally reads your professions and recipes",
    ["Sur WoW: Forever, l'addon ne voyait pas tes métiers : Forever tourne sur l'API du jeu moderne, et les fonctions qui lisaient tes compétences n'y existent pas. Rien ne plantait. L'annuaire t'annonçait simplement sans aucun métier, le clic droit disait que tu n'en avais pas, et « Mes artisans » restait vide. Tes recettes connues et leurs temps de recharge avaient le même problème. Tout est lu à la manière de Forever maintenant."] =
        "On WoW: Forever the addon couldn't see your professions. Forever runs the modern game's API, and the calls it used to read your skills aren't there. Nothing errored. The directory just announced you with no professions, right-click said you had none, and My Artisans stayed empty. Your known recipes and their cooldowns had the same problem. All of it is read the Forever way now.",
    ["Quand quelqu'un te cible dans l'onglet Commande, il voit ce que tu sais vraiment faire, plus une estimation. Et l'estimation elle-même était trop généreuse : une recette sans niveau connu comptait comme atteignable, si bien qu'un couturier niveau 13 se voyait proposer des pièces Stormcloth qui demandent le niveau 40. Un niveau inconnu veut dire « pas proposé » désormais."] =
        "When someone targets you in the Order tab, they see what you actually know, not an estimate. And the estimate was too generous anyway: a recipe with no known level counted as reachable, so a level 13 tailor got offered Stormcloth gear that needs level 40. Unknown now means not offered.",
    ["La liste des recettes est celle de Forever : 2512 recettes tirées des pages Forever de Wowhead, au lieu des 1230 de vanilla. Forever a déplacé des choses, et les potions de soin sont maintenant en Secourisme, plus en Alchimie."] =
        "The recipe list is Forever's own, 2512 recipes from Wowhead's Forever pages instead of vanilla's 1230. Forever moved things around, so the healing potions are under First Aid now, not Alchemy.",
    ["Sur Forever, le clic droit sur le bouton de la minimap ouvre la fenêtre des métiers du jeu. Les métiers de tes rerolls se consultent désormais depuis « Mes artisans » (clic droit sur un métier). /co mute accepte les noms en prénom et nom, entre guillemets si l'addon n'a pas encore croisé le joueur."] =
        "On Forever, right-clicking the minimap button opens the game's Professions window. Your alts' professions now live in My Artisans (right-click a profession). /co mute takes first and last names, in quotes if the addon hasn't met that player yet.",
    -- v1.32.1
    ["La fenêtre de métier de Forever cesse de se plaindre"] =
        "Forever's professions window stops complaining",
    ["Sur WoW: Forever, la colonne des commandes s'invite dans la fenêtre de métier du jeu. Elle y est l'hôte d'un cadre que le jeu protège, et presque tout ce qu'elle y faisait était refusé dès que tu étais en combat : ouvrir ou fermer la fenêtre pendant un combat déclenchait une volée d'erreurs « action bloquée », avec l'addon nommé au passage. La colonne ne touche plus au cadre pendant le combat, et reprend sa place à la fin."] =
        "On WoW: Forever, the orders column sits inside the game's own professions window. It's a guest in a frame the game protects, and nearly everything it did there was refused once you were in combat. Opening or closing the window mid-fight threw a wall of blocked-action errors, with the addon named in each one. The column leaves the frame alone during combat now, and takes its place back when the fight ends.",
    ["Elle s'affiche aussi quand il faut. Il fallait deux passages : la fenêtre s'ouvre sur la page d'ensemble, où il n'y a aucun métier courant et donc rien à lister, si bien que la première visite semblait vide. Elle apparaît maintenant dès que tu es sur un métier, du premier coup."] =
        "It also shows up when it should. It used to take two trips: the window opens on the overview page, where there's no current profession and nothing to list, so the first visit looked empty. It now appears as soon as you're on a profession, first time.",
    ["Le reste : on ne peut plus la sortir de la fenêtre en la tirant, sa place appartient à son hôte ; les onglets de métier de Blizzard ne recouvrent plus son dernier onglet ; /co prof cuisine ouvre la Cuisine au lieu de la page d'ensemble ; et l'aide contextuelle n'entoure plus que ce qui est réellement affiché."] =
        "The rest: you can't drag it out of the window any more, its place belongs to its host; Blizzard's profession tabs no longer cover its last tab; /co prof cooking opens Cooking instead of the overview page; and the help overlay only outlines what's actually on screen.",
    -- v1.32.2
    ["Tes barres d'action ne se bloquent plus en combat"] =
        "Your action bars stop getting blocked in combat",
    ["Sur WoW: Forever, passer d'un onglet à l'autre dans la fenêtre de métier pendant un combat faisait refuser au jeu tout geste sur tes barres d'action, avec l'addon nommé à chaque fois. La fenêtre de métier n'y était pour rien. Deux petites pièces de l'addon l'étaient : ses menus déroulants et son aide « i » empruntaient des systèmes que le jeu partage avec sa propre interface, et s'en servir une seule fois suffisait à marquer cette interface à notre nom jusqu'au prochain rechargement. Les deux sont faits maison maintenant : même rendu, et le jeu n'a plus rien à redire."] =
        "On WoW: Forever, switching tabs in the professions window mid-fight made the game refuse to touch your action bars, and it named the addon every time. The professions window wasn't the problem. Two small pieces of the addon were: its dropdown menus and the help overlay behind its i button borrowed systems the game shares with its own interface, and using them once was enough to mark that interface as ours until the next reload. Both are built in-house now. They look the same, and the game has nothing left to object to.",
    ["La colonne des commandes peut aussi se poser à côté de la fenêtre de métier plutôt que dedans : /co accole passe d'un mode à l'autre. Dedans reste le mode par défaut."] =
        "The orders column can also sit next to the professions window instead of inside it. /co accole switches between the two, and inside stays the default.",
    ["Petites retouches : une longue liste de stats ne sort plus par le bas de l'écran, et chaque liste prend la largeur de sa plus longue entrée ; la liste des canaux de la fenêtre de partage des composants s'ouvre au-dessus d'elle et non plus dessous ; et l'aide suit la fenêtre si le jeu la déplace pendant qu'elle est ouverte."] =
        "Smaller fixes: a long stat list no longer runs off the bottom of the screen, and each list is as wide as its longest entry; the channel list in the reagent-sharing window opens on top of that window instead of behind it; and the help overlay follows the window if the game moves it while the help is open.",
    -- v1.33.0
    ["D'où vient une recette, sans MTSL"] = "Where recipes come from, without MTSL",
    ["L'addon ne réclame plus MTSL. Sa base décrit Vanilla et TBC, or Forever a refait les tables d'objets dessous : 894 objets-recette qui n'existent que là, 173 disparus de Classic, et 24 identifiants communs qui désignent aujourd'hui un tout autre objet. Un annuaire périmé est pire qu'un annuaire absent, parce qu'il répond avec assurance. Les sources de recettes viennent maintenant de nos propres données, tirées des pages Forever de Wowhead."] =
        "The addon doesn't ask for MTSL anymore. Its database describes Vanilla and TBC, and Forever rewrote the item tables underneath it: 894 recipe items that exist nowhere else, 173 from Classic that are gone, and 24 shared ids that now point at a completely different item. An out-of-date directory is worse than no directory at all, because it answers with confidence. Recipe sources come from the addon's own data now, generated from Wowhead's Forever pages.",
    ["Survole une recette que tu n'as pas apprise : elle te dit si le plan tombe en butin, s'il se vend ou s'il vient d'une quête, et elle nomme le PNJ et la zone quand elle les connaît. Sur Forever, le jeu le dit mieux que nous : sa formulation l'emporte dès qu'il en a une. Une recette de formateur est une déduction et non un fait, alors elle porte un « ? » plutôt que de faire semblant."] =
        "Hover a recipe you haven't learned and it tells you whether the plan drops, is sold, or comes from a quest, and it names the vendor and the zone when it knows them. On Forever the game says it better than we can, so its wording wins whenever it has one. A trainer recipe is a deduction rather than something we read, so it carries a question mark instead of pretending otherwise.",
    ["Le Plan de route remarche sur Forever, chiffré sur ton dernier scan Auctionator (Lazy Gold reste sur l'Era). Et la colonne des commandes change de contenu au lieu d'ouvrir des fenêtres par-dessus elle : trois onglets en haut, Commandes, Plan de route et Manquantes. Manquantes liste toutes les recettes que tu n'as pas apprises avec le rang qu'elles demandent, grisées tant que tu ne peux pas les prendre."] =
        "The leveling route works on Forever again, priced from your last Auctionator scan (Lazy Gold still handles Era). And the orders column changes what it shows instead of opening windows on top of itself: three tabs at the top, Orders, Leveling route and Missing. Missing lists every recipe you haven't learned with the level it needs, greyed out until you can take it.",
    ["Corrections : sur Forever la colonne comptait comme connues des recettes non apprises, et la route, les badges et ce que les autres artisans voyaient de toi reposaient là-dessus ; les prix sortaient vides ; la carte d'une commande sélectionnée était dessinée pour une fenêtre moitié plus large que la colonne, donc sa croix, son prix et le bord droit du panneau des composants étaient coupés ; une commande d'enchantement affichait « ? » au lieu de son nom."] =
        "Fixes: on Forever the column counted recipes you hadn't learned as if you knew them, and the route, the badges and what other crafters saw of you were all built on that; prices came out blank; the card for a selected order was drawn for a window half again as wide as the column, so its close button, its price and the right edge of the components panel were cut off; an enchanting order showed a question mark instead of its name.",
    ["L'onglet Manquantes te dit enfin où aller"] =
        "The Missing tab finally tells you where to go",
    ["Survoler une recette que tu n'as pas te donnait son nom et son rang, c'est-à-dire ce que la ligne affichait déjà. Tu as maintenant l'infobulle de l'objet lui-même, puis ce qu'il te manque en points de métier, si la recette rapporte encore quelque chose à ton rang, et d'où vient le plan."] =
        "Hovering a recipe you haven't learned gave you its name and its rank, which is what the line already showed you. You get the game's own item tooltip now, then how much skill you're short, whether the recipe still earns you a point at your rank, and where the plan comes from.",
    ["Ce dernier point a beaucoup changé. L'addon connaissait un seul nom par plan et rien de son camp : « Recipe: Gingerbread Cookie » envoyait tout le monde chez Wulmort Jinglepocket, à Forgefer, Horde comprise. 1565 recettes nomment quelqu'un contre 337 avant, le marchand affiché est de ta faction, 719 donnent le prix réel du marchand sans aucun addon de prix, et 846 PNJ ont des coordonnées : un clic pose un repère, ce qui ne marchait plus depuis MTSL."] =
        "That last part got a lot better. The addon knew one name per plan and nothing about which side that name was on, so \"Recipe: Gingerbread Cookie\" sent everyone to Wulmort Jinglepocket in Ironforge, Horde included. 1565 recipes name someone now, against 337 before, the vendor you're shown is on your faction, 719 give the price the merchant actually charges with no price addon installed, and 846 npcs come with coordinates, so clicking the line drops a waypoint. That hasn't worked since MTSL left.",
    ["Les formateurs. Aucune page ne dit « ça s'apprend au formateur » : l'addon le déduisait de l'absence d'objet-recette et affichait un point d'interrogation, sur 788 recettes. Wowhead le publie en fait sur la page du sort et pas celle de l'objet, ce qui en a nommé 398. Et quand tu parles à un formateur de métier, l'addon note ce qu'il enseigne et où il se tient : le point d'interrogation disparaît et tu récupères ses coordonnées. Si ta fenêtre de formateur filtre ce qu'elle affiche, il te le dit au lieu de n'en moissonner qu'un tiers en silence."] =
        "Then there are trainers. No page anywhere says \"you learn this one from a trainer\", so the addon deduced it from the absence of a recipe item and showed a question mark, on 788 recipes. Wowhead does publish it, on the spell's page rather than the item's, which named 398 of them. And when you talk to a profession trainer, the addon writes down what he teaches and where he stands, so the question mark goes away and you get his coordinates. If your trainer window is filtering what it shows you, it says so instead of quietly harvesting a third of the list.",
    ["Corrigé : un plantage en donjon (le client rend des valeurs « secrètes » pour certaines données d'unité, et l'une d'elles finissait en clé de table trois appels plus loin, dans une fonction d'annuaire qui n'avait aucune raison de se méfier d'un nom), et le changement d'onglet de métier qui laissait la liste d'un métier avec les infobulles d'un autre."] =
        "Fixed: a crash in dungeons (the client hands back \"secret\" values for some unit data, and one was ending up as a table key three calls later, in an address-book function that had no reason to distrust a name), and changing profession tab leaving one profession's list with another profession's tooltips.",
    -- v1.35.1
    ["Un niveau qu'on ne connaît pas n'est pas un niveau 0"] =
        "A skill level we don't know isn't zero",
    ["La vue Manquantes plaçait huit recettes de Couture en tête de liste en te disant qu'elles étaient à ta portée, affichées « niveau requis 0 ». 29 recettes réparties sur six métiers n'ont aucun niveau dans les données, et l'addon lisait cette absence comme un zéro — qui se classe en tête et passe tous les tests de « peux-tu l'apprendre »."] =
        "The Missing view put eight Tailoring recipes at the top of the list and told you they were within reach, all reading \"required skill 0\". Twenty-nine recipes across six professions carry no skill level in the data, and the addon read that absence as a zero, which sorts first and passes every \"can you learn this yet\" test there is.",
    ["Elles affichent « ? » maintenant, elles descendent en fin de liste, et l'addon ne les dit ni à ta portée ni hors de portée, puisqu'il l'ignore. L'infobulle le dit franchement. Les niveaux eux-mêmes manquent toujours : c'est un travail de données, pas d'affichage."] =
        "They show a \"?\" now, they sit at the bottom of the list, and the addon says neither that they're in reach nor that they're out of it, because it doesn't know. The tooltip says as much. The levels themselves are still missing: that's a data job, not a display one.",
    -- v1.35.0
    ["Enchanter la pièce d'un autre, depuis l'échange"] =
        "Enchanting someone else's gear over the trade window",
    ["Le panneau flottant d'enchantement a disparu : sur Forever, la fenêtre de métier se dessinait exactement par-dessus. Son rôle revient à la colonne de métier, qui passe en mode Échange dès qu'un échange s'ouvre avec ton Enchantement affiché — la silhouette du partenaire, la pièce qu'il a posée dans l'emplacement « ne sera pas échangé », et ce que ses composants désignent."] =
        "The floating enchant panel is gone. On Forever the profession window was drawn right on top of it. What it was for now lives in the profession column, which switches to trade mode as soon as a trade opens with Enchanting up: your partner, the piece they put in the slot that isn't traded, and what their reagents point to.",
    ["Clique un emplacement de la silhouette : il reçoit la demande de poser cette pièce (chuchotement, plus une invite d'un clic s'il a l'addon), et la liste de recettes de Blizzard se filtre sur cet emplacement. La main droite coche « Arme » et « Arme à deux mains » à la fois, faute de savoir ce qu'il tient."] =
        "Click a slot on the silhouette and they get asked for that piece, by whisper and by a prompt they can click if they run the addon, while Blizzard's own recipe list narrows to that slot. The main hand ticks Weapon and 2H Weapon both, since nothing tells the addon yet what they're carrying.",
    ["Dès qu'une pièce est posée, la liste suit la pièce elle-même plutôt que ta demande. À la fin de l'échange elle retrouve tes filtres d'avant, y compris celui que tu avais posé toi-même, et la colonne revient sur l'onglet que tu regardais."] =
        "Once something is on the table the list follows the item itself rather than what you asked for. End the trade and it goes back to the filters you had before, including one you'd set yourself, and the column returns to the tab you were on.",
    ["S'il pose aussi des composants, la colonne nomme l'enchantement qu'ils désignent — elle lit ce qu'il pose, jamais tes sacs, et se tait quand plusieurs enchantements collent. Et si un échange s'ouvre alors que ton Enchantement est fermé, un onglet apparaît au bord droit de la fenêtre d'échange pour l'ouvrir."] =
        "If they put reagents down as well, the column names the enchant those reagents point to. It reads what they place, never what's in your bags, and it keeps quiet when several enchants fit. And if a trade opens while Enchanting is closed, a tab appears on the right edge of the trade window to open it.",
    -- v1.34.1
    ["Plus d'erreur en entrant en ville"] =
        "No more error when you walk into town",
    ["Avec la détection des artisans sans l'addon activée (/co crafters on), chaque entrée en ville déclenchait une erreur « action interdite » au nom de l'addon. Sur Forever, le jeu n'autorise plus les addons à écouter le journal de combat, et l'addon s'y abonnait quand même. C'est fini : la détection passe désormais par les messages de fabrication du chat (« Untel crée … »), qui restent ouverts aux addons."] =
        "With crafter spotting turned on (/co crafters on), walking into a city threw an 'action forbidden' error with the addon's name on it. On Forever, addons aren't allowed to listen to the combat log anymore, and the addon kept trying. It doesn't now. Spotting crafters who don't run the addon goes through the 'X creates Y' messages in chat instead, which addons can still read.",
    ["Le panneau d'enchantement qui s'ouvre à côté de la fenêtre d'échange disait toujours « Ouvre ta fenêtre d'Enchantement », même ouverte : il cherchait une fenêtre qui n'existe pas sur Forever. Il liste maintenant tes enchantements pour la pièce posée, classés comme avant, et il remarque quand tu ouvres l'Enchantement en plein échange. Cliquer une ligne ne lance pas encore l'enchantement."] =
        "The enchanting panel next to the trade window always told you to open your Enchanting window, even when it was open, because it was looking for a window Forever doesn't have. It lists your enchants for the item on the table now, ranked the same way as before, and it notices when you open Enchanting in the middle of a trade. Clicking a line doesn't cast the enchant yet.",
    ["Sous le capot : l'addon ne transporte plus rien du code de Classic Era (cette version reste figée en 1.30.0), et il lit ton journal de quêtes directement dans le jeu, sans passer par les copies des anciennes fonctions que Questie installe quand il est présent."] =
        "Under the hood, the addon no longer carries any Classic Era code (that version stays frozen at 1.30.0), and it reads your quest log straight from the game instead of going through the stand-ins for the old functions that Questie installs when it's there.",
}

for k, v in pairs(news) do L[k] = v end
