-- CraftingOrderClassic_Locale_News_esES.lua — traductions de l'onglet « Nouveautés » (esES).
-- Extrait de _Locale_esES.lua (plafond anti-monolithe). Clé FR » texte ES, chargé APRÈS _Locale.lua.

local COC = CraftingOrderClassic
if (GetLocale and GetLocale() or "") ~= "esES" then return end
local L = COC.L

local news = {
    -- Onglet Nouveautés (changelog en jeu)
    ["Nouveautés"] = "Novedades",
    -- v1.49.0
    ["Une commande de guilde peut aller sur le Discord de ta guilde"] = "Un pedido de hermandad puede ir al Discord de tu hermandad",
    ["Si le chef de ta guilde a relié le chat de guilde à un salon Discord, le formulaire de commande propose une ligne « Toute la guilde + Discord » sous « Toute la guilde ». Choisis-la : ta commande part à ta guilde comme d'habitude, et sa ligne arrive aussi dans le salon Discord de la guilde, pour ceux qui le lisent sur leur téléphone. Discord n'affiche que ton nom Discord, alors la ligne porte celui de ton personnage (« @Ton Nom »)."] =
        "Si el maestro de tu hermandad ha vinculado el chat de hermandad a un canal de Discord, el formulario de pedido ofrece una línea «Toda la hermandad + Discord» bajo «Toda la hermandad». Elígela: tu pedido va a tu hermandad como siempre, y su línea llega además al canal de Discord de la hermandad, para quienes lo leen en el móvil. Discord solo muestra tu nombre de Discord, así que la línea lleva el de tu personaje («@Tu Nombre»).",
    ["La ligne n'apparaît que si le chef a coché, en reliant Discord, la case qui sépare le chat Discord du chat de guilde (clic droit sur la guilde dans la fenêtre Guilde et communautés, puis les réglages de guilde, puis les réglages Discord). Une ligne par minute au plus, et « Toute la guilde » seule ne poste jamais sur Discord."] =
        "La línea solo aparece si el maestro marcó, al vincular Discord, la casilla que separa el chat de Discord del chat de hermandad (clic derecho en la hermandad en la ventana Hermandad y comunidades, luego los ajustes de hermandad, luego los ajustes de Discord). Una línea por minuto como máximo, y «Toda la hermandad» sola nunca publica en Discord.",
    ["Choisir à qui envoyer ta commande se fait maintenant dans une seule liste : « Tous (avec l'addon) » en haut avec sa case « Annoncer en Commerce », puis toute la guilde ou tous les amis selon la liste affichée, puis les artisans. La case Commerce ne vaut que pour « Tous (avec l'addon) » et se grise ailleurs."] =
        "Elegir a quién envías tu pedido se hace ahora en una sola lista: «Todos con el addon» arriba con su casilla «Anunciar en Comercio», luego toda la hermandad o todos los amigos según la lista mostrada, y luego los artesanos. La casilla de Comercio solo vale para «Todos con el addon» y se ve gris en lo demás.",
    -- v1.48.0
    ["Signale un bug ou propose une idée depuis le jeu"] = "Informa de un error o propón una idea desde el juego",
    ["Un bug, une idée ? Clique sur le petit scarabée bleu à côté du « i », en haut de la fenêtre (ou sur le bouton en haut de l'onglet Aide, ou tape /co bug). Choisis Bug ou Idée : l'addon te donne un lien déjà sélectionné. Fais Ctrl+C, colle-le dans ton navigateur, et le formulaire GitHub s'ouvre avec la version de l'addon et du jeu déjà remplie. Rien sur ton personnage n'y figure."] =
        "¿Un error, una idea? Haz clic en el pequeño escarabajo azul junto a la «i», arriba en la ventana (o en el botón de arriba de la pestaña Ayuda, o escribe /co bug). Elige Error o Idea: el addon te da un enlace ya seleccionado. Pulsa Ctrl+C, pégalo en tu navegador y el formulario de GitHub se abre con la versión del addon y del juego ya rellenada. No incluye nada sobre tu personaje.",
    ["Pas de compte GitHub ? Le troisième choix donne la page CurseForge de l'addon, pour y laisser un commentaire."] =
        "¿Sin cuenta de GitHub? La tercera opción te da la página de CurseForge del addon, para dejar un comentario.",
    -- v1.47.0
    ["Ta recherche de travail et tes commandes publiques vont plus loin"] = "Tu búsqueda de trabajo y tus pedidos públicos llegan más lejos",
    ["Certains joueurs de l'addon ne voyaient toujours ni ta recherche de travail ni tes commandes pour tous : le canal de l'addon n'atteint pas tout le monde, et les présentations de la v1.46.0 n'aident que ceux déjà connectés quand tu arrives. Maintenant, là où ton canal n'arrive pas, l'addon demande à un joueur de l'addon que tu connais (un ami ou un membre de ta guilde d'abord) de les répéter à tous ceux que son propre canal atteint. Ils les voient comme les autres, avec « via <nom> » dans l'infobulle d'une recherche de travail."] =
        "Algunos usuarios del addon seguían sin ver tu búsqueda de trabajo ni tus pedidos para todos: el canal del addon no llega a todo el mundo, y las presentaciones de la v1.46.0 solo ayudan a quienes ya están conectados cuando entras. Ahora, donde tu canal no llega, el addon pide a un usuario del addon que conoces (primero un amigo o alguien de tu hermandad) que los repita a todos los que alcanza su propio canal. Esos jugadores los ven como los demás, con «vía <nombre>» en la descripción emergente de una búsqueda de trabajo.",
    ["Une ligne répétée par un autre pourrait être inventée, alors l'addon vérifie. Quand tu cliques sur Chuchoter pour un artisan dont la recherche de travail t'est arrivée ainsi, il demande d'abord en coulisse à cet artisan si c'est vrai. S'il dit non, la ligne disparaît et celui qui l'a répétée est ignoré pendant un jour. Une commande répétée se vérifie comme avant, à la première acceptation : si l'acheteur ne l'a pas, elle passe annulée."] =
        "Una línea repetida por otro podría ser inventada, así que el addon la comprueba. Cuando pulsas Susurrar en un artesano cuya búsqueda de trabajo te llegó así, primero le pregunta en segundo plano si es cierto. Si dice que no, la línea desaparece y quien la repitió queda ignorado durante un día. Un pedido repetido se comprueba como antes, cuando alguien lo acepta por primera vez: si el comprador no lo tiene, aparece como cancelado.",
    ["Ça reste léger : un seul joueur par canal, ta recherche de travail répétée au plus toutes les 15 minutes, une commande au plus toutes les deux heures, et rien quand tu es en instance. Ça ne marche qu'entre joueurs qui ont cette version."] =
        "Sigue siendo ligero: un solo jugador por canal, tu búsqueda de trabajo repetida como mucho cada 15 minutos, un pedido como mucho cada dos horas, y nada mientras estás en una estancia. Solo funciona entre jugadores que tienen esta versión.",
    -- v1.46.0
    ["Plus d'artisans trouvés, même ceux que tu n'as jamais croisés"] = "Más artesanos encontrados, incluso los que nunca te has cruzado",
    ["Certains joueurs de l'addon restaient invisibles pour toi, même en jouant à côté : tu ne les trouvais qu'en les croisant, en les ciblant ou en groupe. Maintenant, quand l'un d'eux se connecte, un joueur de l'addon qui vous connaît tous les deux fait les présentations, et vos deux addons se disent bonjour en coulisse. Il apparaît dans ton onglet Artisans avec ses métiers, et ses commandes et sa recherche de travail t'arrivent comme pour n'importe quel artisan connu. Rien à régler."] =
        "Algunos jugadores del addon seguían siendo invisibles para ti, incluso jugando a tu lado: solo los encontrabas al cruzártelos, al seleccionarlos o en grupo. Ahora, cuando uno de ellos se conecta, un jugador del addon que os conoce a los dos hace las presentaciones, y vuestros addons se saludan entre bastidores. Aparece en tu pestaña Artesanos con sus profesiones, y sus pedidos y su búsqueda de trabajo te llegan como los de cualquier artesano conocido. Nada que configurar.",
    ["Ça reste discret : une présentation par connexion, un bonjour court de chaque côté, et pas plus d'une fois toutes les six heures pour le même joueur. Plus il y a de joueurs à jour, plus tu verras de monde."] =
        "Sigue siendo discreto: una presentación por conexión, un saludo corto en cada sentido y no más de una vez cada seis horas para el mismo jugador. Cuantos más jugadores actualicen, a más gente verás.",
    ["Dans l'onglet Artisans, les métiers principaux d'un artisan s'affichent maintenant avant la Cuisine, la Pêche et le Secourisme."] =
        "En la pestaña Artesanos, las profesiones principales de un artesano aparecen ahora antes de Cocina, Pesca y Primeros auxilios.",
    -- v1.45.0
    ["Le /1 te revient, et l'addon découvre les royaumes cachés"] = "El /1 vuelve a ser tuyo, y el addon descubre los reinos ocultos",
    ["Sur un perso tout neuf, le canal caché de l'addon pouvait passer avant le canal Général du jeu et prendre le /1, que le jeu lui gardait ensuite : taper /1 écrivait dans un canal caché. L'addon rend maintenant le /1 au premier canal du jeu dès qu'il y en a un, sur les nouveaux persos comme sur ceux déjà touchés."] =
        "En un personaje recién creado, el canal oculto del addon podía entrar antes que el canal General del juego y quedarse con el /1, y el juego conservaba ese número: escribir /1 enviaba el mensaje a un canal oculto. Ahora el addon devuelve el /1 al primer canal del juego en cuanto existe uno, tanto en personajes nuevos como en los ya afectados.",
    ["Sur Forever, un chuchotement n'arrive qu'au nom complet « Prénom Nom ». Juste après un groupe, ou sur un clic droit, l'addon disait parfois bonjour au seul prénom, ou à « Unknown » : le bonjour se perdait, et une erreur « No player named » pouvait suivre deux minutes plus tard. Il attend maintenant le nom complet, et le menu du clic droit lit aussi le nom de famille."] =
        "En Forever, un susurro solo llega al nombre completo «Nombre Apellido». Justo después de agruparte, o al hacer clic derecho en un jugador, el addon a veces saludaba solo al nombre, o a «Unknown»: el saludo se perdía y un error «No player named» podía aparecer dos minutos después. Ahora espera al nombre completo, y el menú del clic derecho también lee el apellido.",
    ["Si tu as accepté ou livré une commande que son acheteur n'a plus (expirée, effacée, ou qui n'a jamais été la sienne), son addon prévient maintenant le tien, et la commande passe annulée au lieu de rester en attente pour rien. Il suffit que l'acheteur ait cette version."] =
        "Si aceptaste o entregaste un pedido que su comprador ya no tiene (caducado, borrado o que nunca fue suyo), su addon ahora avisa al tuyo, y el pedido aparece como cancelado en lugar de quedarse esperando para nada. Basta con que el comprador tenga esta versión.",
    ["Avec le suivi affiché à l'écran, l'addon recalculait toutes les deux minutes les recettes de chaque métier suivi, et sa mémoire grimpait sans arrêt. Il ne le refait plus qu'en quittant l'hôtel des ventes ou un marchand, là où les prix changent, et sinon toutes les 15 minutes."] =
        "Con el seguimiento en pantalla visible, el addon recalculaba cada dos minutos las recetas de cada profesión seguida, y su memoria no paraba de subir. Ahora solo lo hace al salir de la casa de subastas o de un vendedor, donde cambian los precios, y si no cada 15 minutos.",
    ["Forever a toujours des royaumes, cachés : le jeu range chaque compte sur l'un d'eux sans le dire. Le canal de découverte de l'addon n'atteint que les joueurs de ton royaume, et le canal Commerce aussi, donc tes annonces et ta ligne LFW. Ton royaume part maintenant avec le bonjour de l'addon. Rien ne change encore à l'écran : c'est la première étape pour présenter les joueurs d'un royaume à l'autre."] =
        "Forever sigue teniendo reinos, pero ocultos: el juego coloca cada cuenta en uno sin decírtelo. El canal de descubrimiento del addon solo llega a los jugadores de tu reino, y el canal de Comercio también, así que tus anuncios y tu línea LFW igual. Ahora tu reino viaja con el saludo del addon. En pantalla todavía no cambia nada: es el primer paso para presentar a los jugadores de un reino a otro.",
    -- v1.44.2
    ["Des cooldowns justes, et les longues listes de recettes arrivent entières"] = "Tiempos de reutilización correctos, y las listas largas de recetas llegan completas",
    ["L'addon annonçait des transmutations ou l'Étoffe lunaire « prêtes » chez des artisans qui ne connaissaient même pas ces recettes. La fenêtre de métier liste aussi les recettes que tu n'as pas apprises, et l'addon prenait leur cooldown pour le tien. Il ne suit plus que les recettes que tu connais, et efface au chargement les faux cooldowns déjà notés, pour tous tes persos. Ceux qu'envoie un joueur pas encore à jour sont écartés quand son niveau de métier est trop bas pour connaître la recette."] =
        "El addon anunciaba transmutaciones o el Paño lunar «listos» en artesanos que ni siquiera conocían esas recetas. La ventana de profesión también lista las recetas que no has aprendido, y el addon tomaba su tiempo de reutilización por el tuyo. Ahora solo sigue las recetas que conoces, y al cargar borra los tiempos falsos ya guardados, para todos tus personajes. Los que envía un jugador sin la actualización se descartan cuando su nivel de profesión es demasiado bajo para conocer la receta.",
    ["Le jeu coupe sans prévenir tout message d'addon de plus de 255 caractères. Au-delà d'une centaine de recettes dans un métier, la liste de ce qu'un artisan sait faire arrivait tronquée chez les autres, parfois avec à la fin une recette qu'il ne connaît pas. Elle part maintenant en plusieurs messages, un par palier du métier (Apprenti, Compagnon, Expert, Artisan), et arrive entière. Une liste courte part toujours en un seul message."] =
        "El juego corta sin avisar cualquier mensaje de addon de más de 255 caracteres. A partir de unas cien recetas en una profesión, la lista de lo que un artesano sabe hacer llegaba recortada a los demás, a veces con una receta que no conoce al final. Ahora sale en varios mensajes, uno por rango (Aprendiz, Oficial, Experto, Artesano), y llega completa. Una lista corta sigue saliendo en un solo mensaje.",
    ["Chez un joueur qui n'a pas encore la mise à jour, rien ne change tant que ta liste tient en un message. Au-delà, il n'en verra qu'une partie jusqu'à sa mise à jour."] =
        "Con un jugador que aún no tiene la actualización, nada cambia mientras tu lista quepa en un mensaje. Más allá, solo verá una parte hasta que actualice.",
    -- v1.44.1
    ["Fini le spam « No player named »"] = "Se acabó el spam de «No player named»",
    ["Quand un joueur de l'addon se déconnectait, ton chat pouvait se remplir de « No player named 'X' is currently playing. » deux minutes plus tard, encore et encore : l'addon continuait de lui envoyer tes commandes et ta fiche. Le jeu signale un message envoyé à un absent avec environ deux minutes de retard, et l'addon ne l'attendait que 15 secondes. Il attend maintenant cinq minutes : l'erreur reste cachée et l'addon cesse d'écrire à celui qui est parti."] =
        "Cuando otro usuario del addon se desconectaba, tu chat podía llenarse de «No player named 'X' is currently playing.» dos minutos después, una y otra vez: el addon seguía enviándole tus pedidos y tu perfil. El juego avisa de un mensaje enviado a alguien desconectado con unos dos minutos de retraso, y el addon solo lo esperaba 15 segundos. Ahora espera cinco minutos: el error queda oculto y el addon deja de escribir a quien se fue.",
    ["L'addon envoie aussi beaucoup moins : quand un joueur te dit bonjour, tes commandes ne partent plus qu'à lui, et plus à tous tes contacts. En montant un métier, ta fiche part au plus une fois par minute au lieu de partir à chaque point."] =
        "El addon también envía mucho menos: cuando un jugador te saluda, tus pedidos solo le llegan a él, no a todos tus contactos. Mientras subes una profesión, tu perfil sale como mucho una vez por minuto en lugar de tras cada punto.",
    ["Seul effet de bord : si tu chuchotes toi-même un joueur déconnecté que l'addon a contacté dans ces cinq minutes, l'erreur de ton chuchotement est cachée aussi."] =
        "Único efecto secundario: si susurras tú mismo a un jugador desconectado al que el addon contactó en esos cinco minutos, el error de tu susurro también queda oculto.",
    -- v1.44.0
    ["Ta ligne LFW porte le lien de ton métier"] = "Tu línea LFW enlaza tu profesión",
    ["Quand tu cherches du travail, la ligne que l'addon poste sur Trade (Services) porte maintenant le lien de ton métier, juste après son nom. N'importe qui clique dessus et voit tes recettes, même sans l'addon. L'addon prend le lien chaque fois que tu ouvres ta fenêtre de métier et le garde : un /co lfw tapé fenêtre fermée part avec le dernier lien connu. Un métier jamais ouvert depuis la mise à jour part avec son nom seul, comme avant."] =
        "Cuando buscas trabajo, la línea que el addon publica en Comercio (Servicios) lleva ahora el enlace de tu profesión justo después de su nombre. Cualquiera puede hacer clic y ver tus recetas, tenga o no el addon. El addon toma el enlace cada vez que abres tu ventana de profesión y lo guarda: un /co lfw escrito con la ventana cerrada sale con el último enlace conocido. Una profesión que no has abierto desde la actualización sale solo con su nombre, como antes.",
    ["Chercher du travail ne provoque plus d'erreur Lua en combat de boss : pendant la rencontre, le jeu cache si tu es absent, et l'addon butait dessus. Il saute simplement ce rafraîchissement et reprend après le combat."] =
        "Buscar trabajo ya no provoca un error de Lua en los combates contra jefes. Durante el encuentro el juego oculta si estás ausente, y el addon tropezaba con ello. Ahora se salta esa actualización y sigue después del combate.",
    ["Une commande nommée pour un de tes rerolls ouvrait la vue de ce reroll, même quand le perso sur lequel tu joues connaît aussi la recette. Maintenant, si tu sais la faire, c'est ta fenêtre de métier qui s'ouvre. La vue du reroll ne s'ouvre plus que si lui seul connaît la recette."] =
        "Un pedido dirigido a uno de tus alters abría la vista de ese alter, aunque el personaje con el que juegas también conociera la receta. Ahora, si sabes hacerlo, se abre tu propia ventana de profesión. La vista del alter solo se abre cuando es el único que conoce la receta.",
    -- v1.43.0
    ["Une icône quand une commande t'attend"] = "Un icono cuando un pedido te espera",
    ["Quand une commande t'attend, l'icône de son métier s'affiche à côté de la minicarte, près de la lettre du courrier, avec le nombre de commandes. Survole-la pour voir qui demande quoi, clique pour ouvrir la bonne fenêtre. Elle s'éteint quand tu as tout accepté ou refusé."] =
        "Cuando un pedido te espera, el icono de su profesión aparece junto al minimapa, al lado de la carta del correo, con el número de pedidos. Pasa el ratón por encima para ver quién pide qué, y haz clic para abrir la ventana adecuada. Desaparece cuando lo has aceptado o rechazado todo.",
    ["Elle compte aussi les commandes nommées pour tes rerolls, et les commandes publiques qu'un de tes persos sait faire. La couleur du nombre dit d'où vient la commande : bleu pour toi, vert pour ta guilde ou tes amis, jaune pour tous (le mode daltonien du jeu passe à une palette adaptée). Le clic va vers le perso qui connaît la recette : ta fenêtre de métier, la vue de ton reroll, ou une fenêtre qui dit où l'apprendre."] =
        "También cuenta los pedidos dirigidos a tus alters y los pedidos públicos cuya receta conoce alguno de tus personajes. El color del número dice de dónde viene el pedido: azul para ti, verde para tu hermandad o tus amigos, amarillo para todos (el modo daltónico del juego cambia a una paleta pensada para él). El clic lleva al personaje que conoce la receta: tu ventana de profesión, la vista de tu alter, o una ventanita que te dice dónde aprenderla.",
    -- v1.42.1
    ["Les métiers remarchent après le patch du 2 octobre"] = "Las profesiones vuelven a funcionar tras el parche del 2 de octubre",
    ["Le patch du 2 octobre (build 70170) a changé le numéro par lequel le jeu indique quelle version de WoW tourne. L'addon ne le reconnaissait pas et éteignait tout ce qui touche aux métiers : plus de colonne Commandes à côté de la fenêtre de métier, plus de bouton Enchantement sur la fenêtre d'échange. Il reconnaît maintenant les deux numéros, rien à faire de ton côté."] =
        "El parche del 2 de octubre (build 70170) cambió el número con el que el juego indica qué versión de WoW se está ejecutando. El addon no lo reconocía y apagaba todo lo relacionado con las profesiones: sin columna de pedidos junto a la ventana de profesión, sin botón de Encantamiento en la ventana de comercio. Ahora reconoce ambos números, no tienes que hacer nada.",
    -- v1.42.0
    ["Tu choisis ce qui te prévient"] = "Tú eliges qué te avisa",
    ["En bas des « Canaux surveillés » de l'onglet Artisans, un groupe « Notifications » règle chaque alerte : les demandes lues dans le chat (« WTB [objet] »), les commandes des autres joueurs de l'addon, le suivi de tes commandes (remise, reçue, refusée) et le message à la connexion."] =
        "Al final de los canales vigilados, en la pestaña Artesanos, un grupo «Notificaciones» regula cada aviso: las solicitudes leídas en el chat («WTB [objeto]»), los pedidos de otros jugadores del addon, el seguimiento de tus pedidos (entregado, recibido, rechazado) y el mensaje al conectar.",
    ["Pour les commandes, tu choisis aussi la portée : toutes, seulement guilde, amis et celles pour toi, ou seulement celles à ton nom. C'est le réglage de /co notify, qui a enfin sa case."] =
        "Para los pedidos también eliges el alcance: todos, solo hermandad, amigos y los tuyos, o solo los que llevan tu nombre. Es el ajuste de /co notify, por fin con su casilla.",
    ["« Façon de prévenir » coupe à part la ligne dans le chat, le bandeau et le son. Une case décochée ne cache aucune commande : tout reste dans le Carnet et la vue métier."] =
        "«Cómo avisar» desactiva por separado la línea en el chat, el aviso en pantalla y el sonido. Una casilla desmarcada no oculta ningún pedido: todo sigue en el Libro y en la vista de profesión.",
    -- v1.41.1
    ["Plus d'erreurs pendant les combats de boss"] = "Se acabaron los errores en los combates contra jefes",
    ["Pendant un combat de boss, Forever cache aux addons qui a écrit une ligne du chat et ce qu'elle dit. L'addon levait alors une erreur à chaque ligne reçue sur un canal, Général compris ; il les laisse passer sans bruit. La liste des membres de tes communautés, cachée elle aussi, ne fait plus d'erreur et ne retire plus personne de ton annuaire."] =
        "Durante un combate contra un jefe, Forever oculta a los addons quién escribió una línea del chat y qué dice. El addon lanzaba un error por cada línea que llegaba a un canal, General incluido; ahora las deja pasar sin ruido. Las listas de miembros de tus comunidades también quedan ocultas, y ya no provocan errores ni quitan a nadie de tu directorio.",
    ["Aussi : « Poster » et « /co refresh » n'écrivent plus de ligne « CLNK1 » sur le canal CraftLinkNet. L'addon y dit bonjour par un message d'addon, qui ne s'affiche pas dans le chat."] =
        "Además: «Publicar» y /co refresh ya no escriben una línea CLNK1 en el canal CraftLinkNet. El addon saluda allí con un mensaje de addon, que no aparece en el chat.",
    -- v1.41.0
    ["Tu choisis où l'addon cherche les artisans"] = "Tú eliges dónde busca artesanos el addon",
    ["L'onglet Artisans a une liste « Canaux surveillés » : les canaux de Commerce, la discussion de guilde, la salle de découverte, tes communautés et les joueurs autour de toi. Coche ceux où l'addon doit chercher des artisans. Hors d'une ville, les canaux de Commerce sont grisés et ton choix est gardé."] =
        "La pestaña Artesanos tiene una lista «Canales vigilados»: los canales de Comercio, el chat de hermandad, la sala de descubrimiento, tus comunidades y los jugadores a tu alrededor. Marca aquellos donde el addon debe buscar artesanos. Fuera de una ciudad, los canales de Comercio aparecen en gris y tu elección se conserva.",
    ["À ta première connexion après la mise à jour, un panneau te montre ces cases une fois, avec une phrase par groupe. Le bouton « Configurer » de l'onglet Artisans le rouvre."] =
        "La primera vez que te conectas tras actualizar, un panel te muestra estas casillas una vez, con una frase por grupo. El botón «Configurar» de la pestaña Artesanos lo vuelve a abrir.",
    ["Trade, Trade (Services) et Trade (Local) se règlent maintenant un par un. Un seul défaut change : l'addon ne lit plus les lignes « LFW » sur le canal Général, sauf si tu le coches. Une communauté se coche dans la même liste."] =
        "Comercio, Comercio (Servicios) y Comercio (local) tienen ahora cada uno su casilla. Cambia un valor por defecto: el addon ya no lee las líneas «LFW» en el canal General, salvo que lo marques. Una comunidad se marca en la misma lista.",
    ["L'onglet Artisans se lit mieux : « Chuchoter » n'est rouge que pour un joueur joignable, les icônes de métier restent en couleur, un joueur hors ligne a son nom en gris, et l'étiquette de source ne s'affiche que lorsqu'elle apprend quelque chose. La bande « Annuaire » s'appelle « Croisés », et « Rafraîchir l'annuaire » est passé en bas de la fenêtre."] =
        "La pestaña Artesanos se lee mejor: «Susurrar» solo está en rojo para un jugador al que puedes llegar, los iconos de profesión siguen en color, el nombre de un jugador desconectado está en gris, y la etiqueta de origen solo aparece cuando aporta algo. El filtro «Directorio» se llama ahora «Vistos», y «Actualizar directorio» pasó a la parte inferior de la ventana.",
    ["Aussi : si l'addon se charge sans sa bibliothèque, par exemple pendant la copie d'une mise à jour, il le dit et propose « /reload » au lieu de planter à chaque survol d'un joueur."] =
        "Además: si el addon se carga sin su biblioteca, por ejemplo mientras se copia una actualización, lo dice y propone «/reload» en vez de dar un error cada vez que pasas el ratón sobre un jugador.",
    -- v1.30.0
    ["La cuisine, le secourisme et la pêche comptent comme des métiers"] =
        "Cocina, Primeros auxilios y Pesca cuentan como profesiones",
    ["L'annuaire faisait comme si ces trois-là n'existaient pas. Tu pouvais commander une pile de nourriture depuis l'onglet Commande, mais rien ne te disait QUI est cuisinier : pas d'icône sur sa ligne, pas de pastille pour filtrer, rien dans l'infobulle quand tu le survolais. Ils comptent maintenant comme les autres, et un clic droit sur un joueur propose « Commander Cuisine » comme il propose la forge. La pêche, elle, reste une récolte : elle s'affiche et se filtre, mais elle se commande depuis l'onglet Récolte, comme l'herboristerie."] =
        "El directorio hacía como si esas tres no existieran. Podías encargar una pila de comida desde la pestaña Encargo, pero nada te decía QUIÉN cocina: ningún icono en su línea, ninguna pastilla para filtrar, nada en la información al pasar por encima. Ahora cuentan como las demás, y un clic derecho sobre un jugador ofrece «Encargar Cocina» igual que ofrece Herrería. La Pesca sigue siendo recolección: se muestra y se filtra, pero el pescado se encarga desde la pestaña Recolección, igual que las hierbas.",
    ["Leur montée suit aussi : la bourse d'artisan et le suivi à l'écran nomment ton prochain point de cuisine ou de secourisme exactement comme ils le font déjà pour un métier principal. Une exception est volontaire : voir quelqu'un cuisiner au feu de camp ne l'ajoute toujours pas à l'annuaire, une capitale l'enterrerait sous des gens qui ne sont pas vraiment cuisiniers. Un cuisinier qui a l'addon apparaît normalement, par ses propres niveaux de métier."] =
        "Su progresión también sigue: la bolsa de artesano y el seguimiento en pantalla nombran tu próximo punto de cocina o de primeros auxilios igual que ya lo hacen con una profesión principal. Una excepción es deliberada: ver a alguien cocinar en una hoguera sigue sin añadirlo al directorio, porque una capital lo enterraría bajo gente que no cocina de verdad. Un cocinero con el addon aparece con normalidad, por sus propios niveles de profesión.",
    -- v1.29.0
    ["Tes commandes à l'écran, et un journal pour les lire"] =
        "Tus pedidos en pantalla, y un diario para leerlos",
    ["Les commandes que tu as acceptées s'affichent à l'écran, comme les quêtes suivies. L'objet que tu t'es engagé à faire, et dessous chaque réactif avec ce que tu as sur ce qu'il te faut : « Balle de soie 2/4 ». Quand le dernier tombe dans tes sacs, la ligne passe au blanc et la commande remonte en tête sous « Prêt à livrer ». Rien à ouvrir, rien à aller vérifier. Glisse n'importe quelle ligne pour déplacer le tout, /co track si tu n'en veux pas."] =
        "Los pedidos que has aceptado aparecen en pantalla, igual que las misiones seguidas. El objeto que te comprometiste a hacer, y debajo cada reactivo con lo que tienes frente a lo que necesitas, como 'Bala de tela de seda 2/4'. Cuando el último cae en tus bolsas la línea se vuelve blanca y el pedido sube arriba bajo 'Listo para entregar'. Nada que abrir, nada que ir a comprobar. Arrastra cualquier línea para mover el conjunto, /co track si prefieres no tenerlo.",
    ["Il suit aussi ta montée de métier. Pour chaque métier encore en progression, il nomme LA recette qui achète ton prochain point le moins cher, liste ses réactifs de la même façon, et te dit quel plan acheter et à qui quand la route la moins chère passe par un plan que tu n'as pas encore."] =
        "También sigue tu progresión de profesión. Para cada profesión que aún sube, nombra la receta que compra tu próximo punto de habilidad más barato, lista sus reactivos igual, y te dice qué receta comprar y a quién cuando la ruta más barata pasa por una que todavía no tienes.",
    ["Tu peux donner un nom et une histoire à une commande. Un second bouton à côté de Poster l'ouvre comme une fiche de quête sur parchemin, où tu écris un titre et quelques lignes. Les artisans qui la voient lisent « Le fardeau du forgeron » plutôt que « Heaume de thorium enchanté », avec ton texte dessous. C'est la même commande, elle se lit juste comme une quête."] =
        "Puedes dar nombre e historia a un pedido. Un segundo botón junto a Publicar lo abre como una hoja de misión en pergamino, donde escribes un título y unas líneas. Los artesanos que lo ven leen 'La carga del herrero' en vez de 'Yelmo de torio encantado', con tu texto debajo. El mismo pedido, solo que se lee como una misión.",
    ["Et il y a un journal. /co journal ouvre une fenêtre parchemin où tes commandes et tes vraies quêtes partagent une seule liste, groupées par section et par zone, avec le texte complet de celle que tu cliques. Il lit le journal de quêtes du jeu sans y écrire, donc ta propre fenêtre de quête garde ce que tu avais sélectionné. Il montre aussi toutes les quêtes d'une zone d'un coup, là où le journal du jeu s'arrête à six."] =
        "Y hay un diario. /co journal abre una ventana de pergamino donde tus pedidos y tus misiones reales comparten una lista, agrupados por sección y por zona, con el texto completo de lo que pulses. Lee el registro de misiones del juego sin escribir en él, así que tu propia ventana de misiones conserva lo que tenías seleccionado. Además muestra todas las misiones de una zona de golpe, donde el registro del juego se detiene en seis.",
    ["Un correctif de joaillerie au passage : un en-tête de taille comme « Endurance - Solide » disparaissait de la fenêtre métier quand tu ne connaissais qu'une seule gemme de cette taille, alors que l'onglet Commande l'affichait. Les deux vues classent pareil maintenant."] =
        "Una corrección de joyería de paso. Un encabezado de talla como 'Aguante - Sólido' desaparecía de la ventana de profesión cuando solo conocías una gema de esa talla, aunque la pestaña Pedido sí la mostraba. Ahora ambas vistas agrupan igual.",
    -- v1.28.0
    ["Le plan de route suit chaque point, et sait quand une recette est finie"] =
        "La ruta de subida sigue cada punto y sabe cuándo una receta está acabada",
    ["Le plan de route prenait du retard : tu gagnais un point et il gardait l'ancien plan jusqu'à ce qu'autre chose le réveille — pire en Enchantement, où le jeu ne donne jamais ton rang en direct à l'addon. Il suit maintenant chaque point à l'instant où tu le gagnes. Il sait aussi quand une recette passe grise : il lisait la couleur en direct à ton rang courant mais projetait les rangs suivants d'après les données, si bien qu'une recette que tu voyais grise était encore comptée, et conseillée, un rang plus loin. Grise, c'est fini : elle disparaît des étapes ET du total, pas seulement de la première ligne."] =
        "La ruta de subida se quedaba atrás: ganabas un punto y mantenía el plan antiguo hasta que otra cosa la despertaba — peor en Encantamiento, donde el juego nunca le da al addon tu nivel en directo. Ahora sigue cada punto en el instante en que lo ganas. También aprendió cuándo una receta se vuelve gris: leía el color en directo en tu nivel actual pero proyectaba los niveles siguientes según los datos, así que una receta que veías gris en tu lista aún se contaba, y se recomendaba, un nivel más allá. Gris es gris para siempre ahora: desaparece de los pasos Y del total, no solo de la primera línea.",
    ["La fenêtre de route a rattrapé la bourse d'artisan : une case pour inclure ou non les plans à acheter, un vrai en-tête avec l'icône du métier et ton rang, et un bandeau « Étapes » repliable pour que la liste de courses ne passe plus sous le bas de la fenêtre. Et au plafond entraîné, elle ne se contente plus de hausser les épaules : elle explique comment débloquer le palier suivant — l'entraîner chez ton formateur, ou acheter le livre de rang pour les Premiers soins — et pointe le PNJ où aller, filtré à ta faction."] =
        "La ventana de ruta alcanzó a la bolsa de artesano: una casilla para incluir o no las recetas a comprar, una cabecera de verdad con el icono de la profesión y tu nivel, y una banda «Pasos» plegable para que la lista de la compra ya no quede empujada bajo el borde inferior de la ventana. Y al tope entrenado ya no se encoge de hombros: explica cómo desbloquear el siguiente nivel — entrenarlo con tu maestro, o comprar el libro de rango para Primeros Auxilios — y te señala el PNJ a visitar, filtrado según tu facción.",
    -- v1.27.2
    ["Un onglet Entrantes, et des demandes qui ne traînent plus"] =
        "Una pestaña Entrantes, y peticiones que ya no se quedan pegadas",
    ["Les demandes captées dans /commerce et /guilde restaient affichées des heures. On en voyait encore une marquée « 20h » le lendemain, bien après que le demandeur ait trouvé quelqu'un d'autre. Elles disparaissent maintenant 30 minutes après avoir été vues, comme un cri dans /commerce. Celle que tu as acceptée, elle, tient six heures : tu t'es engagé dessus."] =
        "Las peticiones captadas en /comercio y /hermandad se quedaban visibles durante horas. Al día siguiente aún se veía una marcada «20h», mucho después de que el comprador hubiera encontrado a otro. Ahora desaparecen 30 minutos después de ser vistas, como un grito en /comercio. La que has aceptado, esa aguanta seis horas, ya te has comprometido con ella.",
    ["La fenêtre métier ne fait plus non plus semblant que tu peux les honorer : elle listait une demande de gemme dont tu n'as pas la recette, bouton Accepter compris, à 190 de compétence pour une taille qui en demande 350. Elle ne montre plus que ce que tu sais vraiment faire (revérifié en direct, donc une recette apprise la fait réapparaître). Ce qu'elle masque reste dans le Carnet pour le passer à un ami capable."] =
        "La ventana de profesión tampoco finge ya que puedes cumplirlas: listaba una petición de una gema cuya receta no tienes, con botón Aceptar incluido, a 190 de habilidad para un tallado que pide 350. Ahora solo muestra lo que sabes hacer de verdad (recomprobado en vivo, así que una receta aprendida la trae de vuelta). Lo que oculta se queda en el Libro para pasárselo a un amigo capaz.",
    ["Et ces demandes du chat ont leur propre onglet Entrantes, avec un compteur à côté. Une demande lue dans /commerce ou poussée par un pair n'a rien à voir avec une vraie commande de l'addon (pas de cycle accepter-livrer, tu réponds au chuchotement à la main) : les mélanger aux onglets Tous / Guilde / Amis / Annuaire embrouillait les deux. Corrigé aussi, une commande arrivée sans métier déclenchait son alerte mais n'apparaissait dans aucune fenêtre métier ; le métier est maintenant déduit de l'objet."] =
        "Y esas peticiones del chat tienen su propia pestaña Entrantes, con un contador al lado. Una petición leída en /comercio o reenviada por otro jugador no tiene nada que ver con un pedido real del addon (sin ciclo aceptar-entregar, respondes al susurro a mano), mezclarlas con las pestañas Todos / Hermandad / Amigos / Directorio enturbiaba ambas cosas. También corregido, un pedido que llegaba sin profesión disparaba su aviso pero no aparecía en ninguna ventana de profesión; ahora la profesión se deduce del objeto.",
    -- v1.27.1
    ["Prêt pour le patch 1.15.9"] = "Listo para el parche 1.15.9",
    ["Classic Era, SoD et Hardcore passent à la 1.15.9 et à sa nouvelle interface. L'addon a été vérifié contre elle et se déclare compatible : le badge [Dispo] au-dessus des plaques fonctionne comme avant. Seule limite, décidée par Blizzard : en instance, les plaques amies sont réservées au jeu lui-même, donc pas de badge en donjon."] =
        "Classic Era, SoD y Hardcore pasan a la 1.15.9 y a su nueva interfaz. El addon se ha comprobado contra ella y se declara compatible, la insignia [Dispo] sobre las placas funciona como antes. Un límite, decisión de Blizzard: en las estancias, las placas amistosas quedan reservadas al propio juego, así que no hay insignia en las mazmorras.",
    ["Corrigé : la liste des PNJ sous une recette manquante (formateurs, vendeurs) mélangeait les deux factions, au point d'envoyer un personnage Alliance à Fossoyeuse. Les PNJ du camp d'en face sont maintenant masqués ; les monstres à butin et les PNJ neutres restent, eux servent tout le monde."] =
        "Corregido: la lista de PNJ bajo una receta que te falta (maestros, vendedores) mezclaba ambas facciones, hasta el punto de mandar a un personaje de la Alianza a Entrañas. Los PNJ del bando contrario ahora se ocultan; los monstruos de botín y los PNJ neutrales se quedan, esos atienden a todos.",
    -- v1.27.0
    ["Prévenu quand une nouvelle version sort"] = "Te avisa cuando sale una versión nueva",
    ["L'addon repère maintenant qu'il tourne en retard. Il lit la version des joueurs que tu croises sur le réseau, et dès qu'il en voit une plus récente chez plusieurs personnes différentes, il te le dit d'une ligne dans le chat et pose un point rouge sur le bouton minimap. Le point s'efface tout seul une fois que tu as mis à jour."] =
        "El addon ahora se da cuenta de si vas con una versión vieja. Lee la versión de los jugadores con los que te cruzas en la red, y en cuanto ve una más nueva en varias personas distintas, te lo dice con una línea en el chat y pone un punto rojo en el botón del minimapa. El punto se borra solo en cuanto actualizas.",
    ["Ce « plusieurs personnes différentes » est voulu : un joueur isolé ne peut pas te faire croire que tu es en retard en annonçant un faux numéro, il faut que des joueurs distincts le confirment. Et ça ne te prévient qu'une fois par version, jamais à chaque connexion. Tape /co version pour voir ta version et s'il en existe une plus récente."] =
        "Eso de « varias personas distintas » es a propósito: un jugador solo no puede hacerte creer que vas atrasado anunciando un número falso, hacen falta jugadores distintos que lo confirmen. Y solo te avisa una vez por versión, no en cada conexión. Escribe /co version para ver tu versión y si hay una más nueva.",
    -- v1.26.0
    ["Filtre n'importe quelle liste par la stat qu'elle donne"] =
        "Filtra cualquier lista por la estadística que da",
    ["Chaque liste de recettes — l'onglet Commande, la fenêtre métier, Mes artisans — reçoit un sélecteur de stat. Tu choisis Force, tu ne vois que ce qui donne de la Force : gemmes, équipements, élixirs. Le menu se remplit avec ce que le métier ouvert fabrique vraiment, donc la Cuisine ne te propose pas Puissance des sorts. Ces stats ne sont écrites nulle part, elles sont lues sur ton propre jeu — dans ta langue, et valables pour des objets que je n'ai jamais regardés, Wrath compris."] =
        "Cada lista de recetas — la pestaña Pedido, la ventana de profesión, Mis artesanos — recibe un selector de estadística. Eliges Fuerza y solo ves lo que da Fuerza: gemas, equipo, elixires. El menú se llena con lo que la profesión abierta fabrica de verdad, así que Cocina no te ofrece Poder con hechizos. Esas estadísticas no están escritas en ningún sitio, se leen de tu propio juego, así que aparecen en tu idioma y siguen funcionando con objetos que nunca he mirado, Wrath incluido.",
    ["L'alchimie se range mieux aussi : les élixirs se regroupent sous la stat qu'ils donnent, pendant que les potions de soin et de mana, les flacons et les transmutations gardent leurs propres en-têtes — « rend de la vie » n'a jamais été une stat. Sur TBC, ça sort 74 consommables du fourre-tout Divers."] =
        "La alquimia también se ordena mejor: los elixires se agrupan según la estadística que dan, mientras que las pociones de vida y maná, los frascos y las transmutaciones conservan sus propios encabezados — «restaura vida» nunca fue una estadística. En TBC eso saca 74 consumibles del montón de Varios.",
    -- v1.25.0
    ["Les gemmes se rangent par couleur, puis par ce qu'elles donnent"] =
        "Las gemas se ordenan por color y luego por lo que dan",
    ["La joaillerie versait toutes les gemmes taillées sous un seul en-tête « Gemme ». Elles se rangent maintenant par couleur de châsse, et sous chaque couleur par la stat qu'elles donnent : « Force - Audacieux », « Endurance - Solide ». Cette stat n'est pas une table écrite à la main, elle est lue sur ton propre jeu — donc dans ta langue, et valable pour des gemmes que je n'ai jamais regardées."] =
        "Joyería volcaba todas las gemas talladas bajo un único encabezado «Gema». Ahora se colocan bajo su color de ranura y, dentro de cada color, según la estadística que dan, como «Fuerza - Audaz» o «Aguante - Sólida». Esa estadística no es una tabla escrita a mano, se lee directamente de tu propio juego, por eso aparece en tu idioma y sigue funcionando con gemas que nunca he mirado.",
    ["Les gemmes méta, elles, reviennent à une simple liste : chaque taille de méta n'existe qu'en un seul exemplaire, un en-tête au-dessus n'aurait fait que répéter la ligne. Bagues, colliers, statues et figurines gardent le classement qu'ils avaient."] =
        "Las gemas meta pasan a una lista simple. De cada talla meta solo existe una gema, así que un encabezado encima no hacía más que repetir la línea de debajo. Anillos, collares, estatuas y figurillas conservan la clasificación que ya tenían.",
    ["Corrigé aussi : quand un enchanteur te demandait une pièce, l'invite ne s'affichait parfois jamais. Une première demande arrivée trop tôt, avant que tu aies équipé la pièce, armait quand même le délai de cinq secondes — et la vraie demande qui suivait passait à la trappe. Le délai ne démarre plus que sur une demande réellement affichée."] =
        "También corregido: cuando un encantador te pedía una pieza, el aviso a veces no aparecía nunca. Una primera petición que llegaba demasiado pronto, antes de que hubieras equipado la pieza, activaba igualmente la espera de cinco segundos, y la petición real que venía después se perdía. La espera ahora solo empieza cuando una petición ha pasado de verdad.",
    -- v1.24.2
    ["Les stats d'enchant parlent enfin ta langue"] =
        "Las estadísticas de encantamiento por fin hablan tu idioma",
    ["Les sous-catégories de la vue enchant (Force, Esprit, Croisé…) venaient d'un libellé interne jamais traduit : tout le monde les voyait en anglais, client français compris. Elles sont maintenant lues directement sur ton jeu, comme les noms de sorts, donc dans ta langue sans rien à traduire à la main à chaque nouvelle recette."] =
        "Las subcategorías de la vista de encantamiento (Fuerza, Espíritu, Cruzado…) venían de una etiqueta interna nunca traducida: todo el mundo las veía en inglés, cliente francés incluido. Ahora se leen directamente de tu juego, igual que los nombres de hechizos, así que aparecen en tu idioma sin nada que traducir a mano con cada receta nueva.",
    -- v1.24.1
    ["Deux minerais de plus dans les commandes de récolte"] =
        "Dos minerales más en los encargos de recolección",
    ["Le khorium et l'éternium n'apparaissaient pas comme commandables dans l'onglet Récolte. La liste des minerais était dérivée de ceux qu'on peut prospecter en gemmes, et ni l'un ni l'autre ne l'est — le même trou qui cachait déjà l'argent, l'or, le vrai-argent et le sombrefer. Les deux rejoignent la liste."] =
        "El korio y el eternio no aparecían como encargables en la pestaña Recolección. La lista de minerales se derivaba de los que se pueden prospectar en gemas, y ninguno de los dos lo es — el mismo hueco que ya escondía la plata, el oro, la veraplata y el hierro negro. Ambos se unen ahora a la lista.",
    -- v1.24.0
    ["La pièce à enchanter se pose d'un clic, et une bourse qui suit la progression"] =
        "La pieza a encantar se coloca con un clic, y una bolsa que sigue el ritmo",
    ["Depuis la v1.21.0, un enchanteur peut cliquer un emplacement de la silhouette d'échange pour te demander la pièce à enchanter. Si tu as l'addon toi aussi, ce clic affiche maintenant une invite chez toi : accepte, et ta pièce équipée se pose toute seule dans l'emplacement « ne sera pas échangé ». Rien n'est donné (cet emplacement ne peut pas changer de mains), la pose est verrouillée sur lui, et rien ne bouge sans ton clic. Sans l'addon en face, le chuchotement explicatif part comme avant."] =
        "Desde la v1.21.0, un encantador puede pulsar una casilla de la silueta de intercambio para pedirte la pieza a encantar. Si tú también usas el addon, ese clic ahora muestra un aviso en tu lado: acepta, y tu pieza equipada se coloca sola en la casilla «No se intercambiará». No entregas nada (esa casilla no puede cambiar de manos), la colocación está bloqueada en ella, y nada se mueve sin tu clic. Sin el addon enfrente, el susurro explicativo sale como antes.",
    ["La bourse d'artisan se met à jour en direct : fenêtre ouverte, chaque point de métier gagné par le personnage suivi (et chaque recette apprise) recalcule la liste de courses — plus besoin de la rouvrir pour voir la route changer."] =
        "La bolsa del artesano ahora se actualiza en vivo: con la ventana abierta, cada punto de oficio que gana el personaje seguido (y cada receta que aprende) recalcula la lista de la compra — ya no hace falta reabrirla para ver cambiar la ruta.",
    -- v1.23.0
    ["La bourse d'artisan : la liste de courses de tes guildeux, et deux corrections réseau"] =
        "La bolsa del artesano: una lista de la compra para tus compañeros de hermandad, y dos correcciones de red",
    ["L'onglet Artisans gagne un bouton sac après les icônes de métier de chaque fiche : un clic ouvre la liste de courses des matériaux qu'il te faut pour monter tes métiers, calculée en local à partir de ce que le jeu diffuse déjà (aucun nouveau trafic réseau). Les réactifs que ton propre métier sait fabriquer sont décomposés en composants de base, et les objets vendus par un PNJ sont mis de côté dans une note plutôt que d'encombrer la grille."] =
        "La pestaña Artesanos gana un botón de bolsa tras los iconos de oficio de cada ficha: un clic abre la lista de la compra de materiales que esa persona necesita para seguir subiendo, calculada en local a partir de lo que el juego ya difunde (sin tráfico de red nuevo). Los reactivos que su propio oficio sabe fabricar más barato se descomponen en componentes base, y los objetos de vendedor se apartan en una nota en vez de saturar la cuadrícula.",
    ["Coche « inclure les plans à acheter » et les recettes derrière un coût rejoignent la liste : les plans-objets comme fourniture à apporter, les plans de formateur comme simple note. Le même bloc de fournitures s'affiche maintenant sous le plan de route « quoi monter ensuite », avec le PNJ où aller (nom, zone, coordonnées) et une épingle TomTom cliquable si tu l'as installé."] =
        "Marca «incluir planos por comprar» y las recetas con coste también se suman a la lista: los planos-objeto como suministro que llevar, los planos de maestro como simple nota. El mismo bloque de suministros aparece ahora bajo la ruta «qué subir a continuación», con el PNJ al que acudir (nombre, zona, coordenadas) y un pin de TomTom pulsable si lo tienes instalado.",
    ["Une recette sans réactif au prix connu (la poussière d'enchantement, par exemple) ne fait plus sauter tout un tronçon du plan de route : elle sert maintenant de repli marqué « ? » quand rien de mieux n'est disponible. Une table de désenchantement maison alimente aussi l'infobulle des poussières, essences et éclats affichés dans ces listes."] =
        "Una receta sin reactivo con precio conocido (el polvo de encantamiento, por ejemplo) ya no elimina todo un tramo de la ruta: ahora sirve de recurso marcado con «?» cuando no hay nada mejor disponible. Una tabla de desencantamiento propia también alimenta el tooltip de polvos, esencias y fragmentos mostrados en estas listas.",
    ["Deux corrections : un compte à plusieurs personnages se voyait parfois lister lui-même comme « joignable via » son autre perso dans son propre onglet Artisans, corrigé. Et le plan de route pouvait s'arrêter avant le vrai plafond de compétence après une formation chez le maître, à cause d'une assignation Lua qui perdait silencieusement sa seconde valeur."] =
        "Dos correcciones: una cuenta con varios personajes a veces se veía a sí misma listada como «accesible vía» su propio alter en su propia pestaña Artesanos, corregido. Y la ruta podía detenerse antes del verdadero tope de habilidad justo después de un ascenso con el maestro, por una asignación múltiple de Lua que perdía en silencio su segundo valor de retorno.",
    -- (clés v1.22.1 retirées à la v1.49.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.22.0 retirées à la v1.48.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.21.0 retirées à la v1.47.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.20.0 retirées à la v1.46.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.19.1 et v1.19.0 retirées à la v1.45.0 : versions sorties de la fenêtre glissante de l'onglet)
    -- (clés v1.18.0 et v1.17.1 retirées à la v1.44.2 : versions sorties de la fenêtre glissante de l'onglet)
    -- (clés v1.17.0 retirées à la v1.44.1 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.8.0/v1.7.0/v1.7.1/v1.6.0/v1.5.0/v1.4.0 retirées : ces versions ne sont plus listées dans l'onglet Nouveautés)
    -- (clés v1.13.0 retirées à la v1.41.1 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.12.1 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    -- (clés v1.12.0, v1.11.0 et v1.10.2 retirées à la v1.41.0 : versions sorties de la fenêtre glissante de l'onglet)
    -- (clés v1.16.0 retirées à la v1.44.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.15.1 retirées à la v1.43.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.15.0 retirées à la v1.42.1 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.14.0 retirées à la v1.42.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.9.0 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    ["VU"] = "VISTO",
    ["vu crafter (sans l'addon)"] = "visto fabricando (sin el addon)",
    ["vu crafter"] = "visto fabricando",
    ["%d+ · vu crafter"] = "%d+ · visto fabricando",
    -- Cooldowns de recettes (transmutations & co)
    ["%s : prête"] = "%s: lista",
    ["%s : dans %s"] = "%s: en %s",
    ["(estimé)"] = "(estimado)",
    ["Transmutation"] = "Transmutación",
    ["%dj"] = "%dd", ["%dh"] = "%dh", ["%dmin"] = "%dmin",
    -- Relais partenaire
    ["via %s · il y a %s"] = "vía %s · hace %s",
    ["RELAIS"] = "RELEVO",
    -- Rerolls (identité joueur multi-persos, /co alts — opt-in)
    ["rerolls : ACTIVÉS — ta liste de persos est annoncée au réseau."] =
        "alters: ACTIVADOS — tu lista de personajes se anuncia a la red.",
    ["rerolls : désactivés — rien n'est annoncé (opt-in : /co alts on)."] =
        "alters: desactivados — no se anuncia nada (opt-in: /co alts on).",
    ["perso principal (vitrine) : %s"] = "personaje principal (escaparate): %s",
    ["persos du compte (%s) : %s"] = "personajes de la cuenta (%s): %s",
    ["le lien n'est vérifié chez les autres qu'après une connexion de CHAQUE perso (addon actif)."] =
        "los demás solo verifican el vínculo cuando CADA personaje se ha conectado una vez (addon activo).",
    ["rerolls activés — perso principal : %s (changer : /co alts main <nom>)"] =
        "alters activados — personaje principal: %s (cambiar: /co alts main <nombre>)",
    ["rerolls désactivés — dissolution annoncée au réseau."] =
        "alters desactivados — disolución anunciada a la red.",
    ["perso inconnu sur ce compte : %s (connecte-le une fois avec l'addon)"] =
        "personaje desconocido en esta cuenta: %s (conéctalo una vez con el addon)",
    ["regrouper tes rerolls (opt-in) : liste annoncée, commandes routées vers ton perso connecté"] =
        "agrupar tus alters (opt-in): lista anunciada, pedidos dirigidos a tu personaje conectado",
    ["commande nommée pour %s : connecte ce perso, ou active /co alts on pour accepter d'ici."] =
        "pedido dirigido a %s: conecta ese personaje, o activa /co alts on para aceptar desde aquí.",
    ["|cFFFFCC00commande pour ton reroll %s|r de |cFFFFFFFF%s|r : %s%s%s"] =
        "|cFFFFCC00pedido para tu alter %s|r de |cFFFFFFFF%s|r: %s%s%s",
    ["En ligne via %s"] = "En línea vía %s",
    ["reroll : %s (%s)"] = "alter: %s (%s)",
    -- v1.31.0
    ["Les cercles d'artisans, posés sur les communautés WoW"] =
        "Círculos de artesanos, apoyados en las comunidades de WoW",
    ["Le canal du royaume n'a ni mémoire ni liste de membres : qui n'était pas connecté quand tu as posté n'a rien vu, et chaque session recommence à chercher qui est là. Une communauté WoW répond aux deux. Marque-la avec /co circle et ses membres apparaissent sous « Cercle » dans l'onglet Artisans, avec leur présence, y compris ceux qui sont hors ligne. C'est toi qui crées la communauté et qui invites : un cercle est un petit groupe que tu as choisi, pas le royaume entier."] =
        "El canal del reino no tiene memoria ni lista de miembros: quien no estaba conectado cuando publicaste no vio nada, y cada sesión vuelve a empezar buscando quién anda por ahí. Una comunidad de WoW resuelve ambas cosas. Márcala con /co circle y sus miembros aparecen bajo « Círculo » en la pestaña Artesanos, con su presencia, incluidos los que están desconectados. Tú creas la comunidad y tú invitas a quien quieres: un círculo es un grupo pequeño que has elegido, no el reino entero.",
    ["Rien n'est posté dans la communauté et rien n'en est lu. Ce qu'une communauté peut réellement porter a été mesuré avant qu'on s'appuie dessus, et c'est étroit : le texte d'un message de club est illisible depuis un addon, et un message addon envoyé sur son canal est accepté puis jeté. Le cercle te donne donc la liste et qui est en ligne ; les commandes et les niveaux de métier continuent de circuler exactement comme avant."] =
        "No se publica nada en la comunidad ni se lee nada de ella. Lo que una comunidad puede llevar de verdad se midió antes de apoyarse en ella, y es poco: el texto de un mensaje de club no se puede leer desde un addon, y un mensaje de addon enviado a su canal se acepta y luego se descarta. Así que el círculo te da la lista y quién está conectado; los pedidos y los niveles de profesión siguen viajando igual que antes.",
    ["Les métiers ne viennent pas non plus de la communauté : ces champs-là ne sont remplis que pour un roster de guilde. Un membre de cercle affiche ses métiers quand il répond à l'addon, comme tout le monde."] =
        "Las profesiones tampoco vienen de la comunidad: esos campos solo se rellenan para las listas de hermandad. Un miembro del círculo muestra sus profesiones cuando responde al addon, como todo el mundo.",
    -- v1.31.1
    ["Les nouveaux venus apparaissent tout seuls"] =
        "Los recién llegados aparecen solos",
    ["Quelqu'un qui venait d'installer l'addon restait invisible tant qu'il ne cliquait pas « Rafraîchir l'annuaire » — ce que personne ne pense à faire devant un annuaire qui a l'air vide, et avoir l'air vide était justement le problème."] =
        "Quien acababa de instalar el addon seguía invisible hasta que pulsaba « Actualizar directorio », algo que nadie piensa en hacer ante un directorio que parece vacío, y parecer vacío era justo el problema.",
    ["À la connexion, l'addon ne s'annonçait que sur le canal caché du royaume, le moins fiable de ses moyens d'atteindre les autres. L'annonce qui touche vraiment les inconnus n'a le droit de partir que juste après un clic ou une touche : à la connexion il n'y avait donc aucun moment pour l'envoyer, et elle était jetée au lieu d'être gardée. Elle attend maintenant, et part à ton premier clic ou ta première touche — quelques secondes, sans que tu fasses quoi que ce soit. La connexion sonde aussi directement les joueurs autour de toi, ce que le bouton « Rafraîchir » faisait déjà et pas elle."] =
        "Al conectarte, el addon solo te anunciaba en el canal oculto del reino, el menos fiable de sus medios para llegar a los demás. El anuncio que sí alcanza a los desconocidos solo puede salir justo después de un clic o una tecla: al conectarte no había momento para enviarlo, así que se descartaba en vez de guardarse. Ahora espera y sale con tu primer clic o tecla, unos segundos, sin que hagas nada. La conexión también sondea directamente a los jugadores a tu alrededor, algo que el botón Actualizar ya hacía y la conexión no.",
    -- v1.32.0
    ["Forever lit enfin tes métiers et tes recettes"] =
        "Forever por fin lee tus profesiones y recetas",
    ["Sur WoW: Forever, l'addon ne voyait pas tes métiers : Forever tourne sur l'API du jeu moderne, et les fonctions qui lisaient tes compétences n'y existent pas. Rien ne plantait. L'annuaire t'annonçait simplement sans aucun métier, le clic droit disait que tu n'en avais pas, et « Mes artisans » restait vide. Tes recettes connues et leurs temps de recharge avaient le même problème. Tout est lu à la manière de Forever maintenant."] =
        "En WoW: Forever el addon no veía tus profesiones. Forever funciona con la API del juego moderno, y las funciones que leían tus habilidades no existen allí. No salía ningún error. El directorio simplemente te anunciaba sin profesiones, el clic derecho decía que no tenías ninguna y «Mis artesanos» se quedaba vacío. Tus recetas conocidas y sus tiempos de reutilización tenían el mismo problema. Ahora todo se lee a la manera de Forever.",
    ["Quand quelqu'un te cible dans l'onglet Commande, il voit ce que tu sais vraiment faire, plus une estimation. Et l'estimation elle-même était trop généreuse : une recette sans niveau connu comptait comme atteignable, si bien qu'un couturier niveau 13 se voyait proposer des pièces Stormcloth qui demandent le niveau 40. Un niveau inconnu veut dire « pas proposé » désormais."] =
        "Cuando alguien te elige en la pestaña Pedir, ve lo que sabes hacer de verdad, ya no una estimación. Y la estimación era demasiado generosa: una receta sin nivel conocido contaba como alcanzable, así que a un sastre de nivel 13 se le ofrecían piezas de Stormcloth que piden nivel 40. Ahora, nivel desconocido significa que no se ofrece.",
    ["La liste des recettes est celle de Forever : 2512 recettes tirées des pages Forever de Wowhead, au lieu des 1230 de vanilla. Forever a déplacé des choses, et les potions de soin sont maintenant en Secourisme, plus en Alchimie."] =
        "La lista de recetas es la de Forever: 2512 recetas sacadas de las páginas de Forever de Wowhead en lugar de las 1230 de vanilla. Forever ha movido cosas, y las pociones de sanación están ahora en Primeros auxilios, no en Alquimia.",
    ["Sur Forever, le clic droit sur le bouton de la minimap ouvre la fenêtre des métiers du jeu. Les métiers de tes rerolls se consultent désormais depuis « Mes artisans » (clic droit sur un métier). /co mute accepte les noms en prénom et nom, entre guillemets si l'addon n'a pas encore croisé le joueur."] =
        "En Forever, el clic derecho en el botón del minimapa abre la ventana de profesiones del juego. Las profesiones de tus alters se consultan ahora en «Mis artesanos» (clic derecho sobre una profesión). /co mute acepta nombre y apellido, entre comillas si el addon aún no ha visto a ese jugador.",
    -- v1.32.1
    ["La fenêtre de métier de Forever cesse de se plaindre"] =
        "La ventana de profesiones de Forever deja de quejarse",
    ["Sur WoW: Forever, la colonne des commandes s'invite dans la fenêtre de métier du jeu. Elle y est l'hôte d'un cadre que le jeu protège, et presque tout ce qu'elle y faisait était refusé dès que tu étais en combat : ouvrir ou fermer la fenêtre pendant un combat déclenchait une volée d'erreurs « action bloquée », avec l'addon nommé au passage. La colonne ne touche plus au cadre pendant le combat, et reprend sa place à la fin."] =
        "En WoW: Forever, la columna de pedidos se instala dentro de la ventana de profesiones del juego. Allí es huésped de un marco que el juego protege, y casi todo lo que hacía se rechazaba en cuanto entrabas en combate. Abrir o cerrar la ventana en plena pelea lanzaba una tanda de errores de acción bloqueada, con el addon señalado por su nombre. Ahora la columna no toca el marco durante el combate y recupera su sitio al terminar.",
    ["Elle s'affiche aussi quand il faut. Il fallait deux passages : la fenêtre s'ouvre sur la page d'ensemble, où il n'y a aucun métier courant et donc rien à lister, si bien que la première visite semblait vide. Elle apparaît maintenant dès que tu es sur un métier, du premier coup."] =
        "También aparece cuando debe. Antes hacían falta dos intentos: la ventana abre en la página de resumen, donde no hay profesión actual y por tanto nada que listar, así que la primera visita parecía vacía. Ahora aparece en cuanto estás en una profesión, a la primera.",
    ["Le reste : on ne peut plus la sortir de la fenêtre en la tirant, sa place appartient à son hôte ; les onglets de métier de Blizzard ne recouvrent plus son dernier onglet ; /co prof cuisine ouvre la Cuisine au lieu de la page d'ensemble ; et l'aide contextuelle n'entoure plus que ce qui est réellement affiché."] =
        "Lo demás: ya no se puede sacar de la ventana arrastrándola, su sitio pertenece a su anfitrión; las pestañas de profesión de Blizzard ya no tapan su última pestaña; /co prof cocina abre Cocina en vez de la página de resumen; y la ayuda solo rodea lo que está realmente en pantalla.",
    -- v1.32.2
    ["Tes barres d'action ne se bloquent plus en combat"] =
        "Tus barras de acción ya no se bloquean en combate",
    ["Sur WoW: Forever, passer d'un onglet à l'autre dans la fenêtre de métier pendant un combat faisait refuser au jeu tout geste sur tes barres d'action, avec l'addon nommé à chaque fois. La fenêtre de métier n'y était pour rien. Deux petites pièces de l'addon l'étaient : ses menus déroulants et son aide « i » empruntaient des systèmes que le jeu partage avec sa propre interface, et s'en servir une seule fois suffisait à marquer cette interface à notre nom jusqu'au prochain rechargement. Les deux sont faits maison maintenant : même rendu, et le jeu n'a plus rien à redire."] =
        "En WoW: Forever, cambiar de pestaña en la ventana de profesiones en pleno combate hacía que el juego se negara a tocar tus barras de acción, y nombraba al addon cada vez. La ventana de profesiones no tenía la culpa. La tenían dos piezas pequeñas del addon: sus menús desplegables y la ayuda de su botón i usaban sistemas que el juego comparte con su propia interfaz, y usarlos una sola vez bastaba para marcar esa interfaz como nuestra hasta la siguiente recarga. Ahora los dos son de fabricación propia: se ven igual y el juego ya no tiene nada que objetar.",
    ["La colonne des commandes peut aussi se poser à côté de la fenêtre de métier plutôt que dedans : /co accole passe d'un mode à l'autre. Dedans reste le mode par défaut."] =
        "La columna de pedidos también puede colocarse junto a la ventana de profesiones en lugar de dentro: /co accole alterna entre los dos modos. Dentro sigue siendo el modo por defecto.",
    ["Petites retouches : une longue liste de stats ne sort plus par le bas de l'écran, et chaque liste prend la largeur de sa plus longue entrée ; la liste des canaux de la fenêtre de partage des composants s'ouvre au-dessus d'elle et non plus dessous ; et l'aide suit la fenêtre si le jeu la déplace pendant qu'elle est ouverte."] =
        "Pequeños arreglos: una lista larga de estadísticas ya no se sale por abajo de la pantalla, y cada lista es tan ancha como su entrada más larga; la lista de canales de la ventana para compartir componentes se abre encima de esa ventana y no detrás; y la ayuda sigue a la ventana si el juego la mueve mientras está abierta.",
    -- v1.33.0
    ["D'où vient une recette, sans MTSL"] = "De dónde viene una receta, sin MTSL",
    ["L'addon ne réclame plus MTSL. Sa base décrit Vanilla et TBC, or Forever a refait les tables d'objets dessous : 894 objets-recette qui n'existent que là, 173 disparus de Classic, et 24 identifiants communs qui désignent aujourd'hui un tout autre objet. Un annuaire périmé est pire qu'un annuaire absent, parce qu'il répond avec assurance. Les sources de recettes viennent maintenant de nos propres données, tirées des pages Forever de Wowhead."] =
        "El addon ya no pide MTSL. Su base describe Vanilla y TBC, pero Forever rehízo las tablas de objetos por debajo: 894 objetos-receta que solo existen allí, 173 de Classic que han desaparecido, y 24 identificadores comunes que hoy designan un objeto completamente distinto. Un directorio caducado es peor que ninguno, porque responde con seguridad. Las fuentes de recetas salen ahora de nuestros propios datos, generados desde las páginas Forever de Wowhead.",
    ["Survole une recette que tu n'as pas apprise : elle te dit si le plan tombe en butin, s'il se vend ou s'il vient d'une quête, et elle nomme le PNJ et la zone quand elle les connaît. Sur Forever, le jeu le dit mieux que nous : sa formulation l'emporte dès qu'il en a une. Une recette de formateur est une déduction et non un fait, alors elle porte un « ? » plutôt que de faire semblant."] =
        "Pasa el ratón por una receta que no hayas aprendido: te dice si el plano cae como botín, se vende o viene de una misión, y nombra al PNJ y la zona cuando los conoce. En Forever el juego lo dice mejor que nosotros, así que su redacción gana en cuanto tiene una. Una receta de entrenador es una deducción y no un hecho, así que lleva un signo de interrogación en vez de fingir lo contrario.",
    ["Le Plan de route remarche sur Forever, chiffré sur ton dernier scan Auctionator (Lazy Gold reste sur l'Era). Et la colonne des commandes change de contenu au lieu d'ouvrir des fenêtres par-dessus elle : trois onglets en haut, Commandes, Plan de route et Manquantes. Manquantes liste toutes les recettes que tu n'as pas apprises avec le rang qu'elles demandent, grisées tant que tu ne peux pas les prendre."] =
        "La ruta de subida vuelve a funcionar en Forever, calculada con tu último escaneo de Auctionator (Lazy Gold sigue para Era). Y la columna de pedidos cambia de contenido en vez de abrir ventanas encima: tres pestañas arriba, Pedidos, Ruta de subida y Faltantes. Faltantes lista todas las recetas que no has aprendido con el nivel que piden, en gris hasta que puedas cogerlas.",
    ["Corrections : sur Forever la colonne comptait comme connues des recettes non apprises, et la route, les badges et ce que les autres artisans voyaient de toi reposaient là-dessus ; les prix sortaient vides ; la carte d'une commande sélectionnée était dessinée pour une fenêtre moitié plus large que la colonne, donc sa croix, son prix et le bord droit du panneau des composants étaient coupés ; une commande d'enchantement affichait « ? » au lieu de son nom."] =
        "Correcciones: en Forever la columna contaba como conocidas recetas no aprendidas, y la ruta, las insignias y lo que los demás artesanos veían de ti se apoyaban en eso; los precios salían vacíos; la ficha de un pedido seleccionado estaba dibujada para una ventana bastante más ancha que la columna, así que su aspa, su precio y el borde derecho del panel de componentes quedaban cortados; un pedido de encantamiento mostraba un signo de interrogación en vez de su nombre.",
    ["L'onglet Manquantes te dit enfin où aller"] =
        "La pestaña Faltantes por fin te dice adónde ir",
    ["Survoler une recette que tu n'as pas te donnait son nom et son rang, c'est-à-dire ce que la ligne affichait déjà. Tu as maintenant l'infobulle de l'objet lui-même, puis ce qu'il te manque en points de métier, si la recette rapporte encore quelque chose à ton rang, et d'où vient le plan."] =
        "Pasar el ratón por una receta que no tienes te daba su nombre y su rango, es decir lo que la línea ya mostraba. Ahora aparece primero el tooltip del objeto del propio juego, y debajo cuánta habilidad te falta, si la receta todavía da un punto a tu rango, y de dónde sale el plano.",
    ["Ce dernier point a beaucoup changé. L'addon connaissait un seul nom par plan et rien de son camp : « Recipe: Gingerbread Cookie » envoyait tout le monde chez Wulmort Jinglepocket, à Forgefer, Horde comprise. 1565 recettes nomment quelqu'un contre 337 avant, le marchand affiché est de ta faction, 719 donnent le prix réel du marchand sans aucun addon de prix, et 846 PNJ ont des coordonnées : un clic pose un repère, ce qui ne marchait plus depuis MTSL."] =
        "Eso último ha cambiado mucho. El addon conocía un solo nombre por plano y nada sobre su bando, así que «Recipe: Gingerbread Cookie» mandaba a todo el mundo a Wulmort Jinglepocket en Forjaz, Horda incluida. 1565 recetas nombran a alguien frente a 337 antes, el vendedor que ves es de tu facción, 719 dan el precio real del mercader sin ningún addon de precios, y 846 PNJ traen coordenadas: un clic deja un punto de ruta, algo que no funcionaba desde que se fue MTSL.",
    ["Les formateurs. Aucune page ne dit « ça s'apprend au formateur » : l'addon le déduisait de l'absence d'objet-recette et affichait un point d'interrogation, sur 788 recettes. Wowhead le publie en fait sur la page du sort et pas celle de l'objet, ce qui en a nommé 398. Et quand tu parles à un formateur de métier, l'addon note ce qu'il enseigne et où il se tient : le point d'interrogation disparaît et tu récupères ses coordonnées. Si ta fenêtre de formateur filtre ce qu'elle affiche, il te le dit au lieu de n'en moissonner qu'un tiers en silence."] =
        "Y los maestros. Ninguna página dice «esto se aprende con el maestro»: el addon lo deducía de la ausencia de objeto-receta y mostraba un interrogante, en 788 recetas. Wowhead sí lo publica, en la página del hechizo y no en la del objeto, lo que dio nombre a 398. Y cuando hablas con un maestro de profesión, el addon anota qué enseña y dónde está: el interrogante desaparece y te quedas con sus coordenadas. Si tu ventana de maestro está filtrando lo que muestra, te lo dice en vez de recoger solo un tercio en silencio.",
    ["Corrigé : un plantage en donjon (le client rend des valeurs « secrètes » pour certaines données d'unité, et l'une d'elles finissait en clé de table trois appels plus loin, dans une fonction d'annuaire qui n'avait aucune raison de se méfier d'un nom), et le changement d'onglet de métier qui laissait la liste d'un métier avec les infobulles d'un autre."] =
        "Corregido: un cuelgue en mazmorras (el cliente devuelve valores «secretos» para ciertos datos de unidad, y uno acababa de clave de tabla tres llamadas más tarde, en una función de directorio que no tenía por qué desconfiar de un nombre), y el cambio de pestaña de profesión que dejaba la lista de una profesión con los tooltips de otra.",
    -- v1.35.1
    ["Un niveau qu'on ne connaît pas n'est pas un niveau 0"] =
        "Un nivel que no conocemos no es un cero",
    ["La vue Manquantes plaçait huit recettes de Couture en tête de liste en te disant qu'elles étaient à ta portée, affichées « niveau requis 0 ». 29 recettes réparties sur six métiers n'ont aucun niveau dans les données, et l'addon lisait cette absence comme un zéro — qui se classe en tête et passe tous les tests de « peux-tu l'apprendre »."] =
        "La vista Faltantes ponía ocho recetas de Sastrería al principio de la lista y las declaraba a tu alcance, todas con «nivel requerido 0». 29 recetas de seis profesiones no tienen ningún nivel en los datos, y el addon leía esa ausencia como un cero, que se ordena primero y supera cualquier prueba de «¿ya puedes aprenderlo?».",
    ["Elles affichent « ? » maintenant, elles descendent en fin de liste, et l'addon ne les dit ni à ta portée ni hors de portée, puisqu'il l'ignore. L'infobulle le dit franchement. Les niveaux eux-mêmes manquent toujours : c'est un travail de données, pas d'affichage."] =
        "Ahora muestran «?», bajan al final de la lista, y el addon no dice ni que están a tu alcance ni que no lo están, porque no lo sabe. La descripción lo dice. Los niveles en sí siguen faltando: eso es trabajo de datos, no de presentación.",
    -- v1.35.0
    ["Enchanter la pièce d'un autre, depuis l'échange"] =
        "Encantar el objeto de otro, desde la ventana de intercambio",
    ["Le panneau flottant d'enchantement a disparu : sur Forever, la fenêtre de métier se dessinait exactement par-dessus. Son rôle revient à la colonne de métier, qui passe en mode Échange dès qu'un échange s'ouvre avec ton Enchantement affiché — la silhouette du partenaire, la pièce qu'il a posée dans l'emplacement « ne sera pas échangé », et ce que ses composants désignent."] =
        "El panel flotante de encantamiento ha desaparecido: en Forever, la ventana de profesión se dibujaba justo encima. Su papel pasa a la columna de profesión, que entra en modo Intercambio en cuanto se abre un intercambio con tu Encantamiento abierto — tu compañero, el objeto que ha puesto en la ranura que no se intercambia, y a qué apuntan sus materiales.",
    ["Clique un emplacement de la silhouette : il reçoit la demande de poser cette pièce (chuchotement, plus une invite d'un clic s'il a l'addon), et la liste de recettes de Blizzard se filtre sur cet emplacement. La main droite coche « Arme » et « Arme à deux mains » à la fois, faute de savoir ce qu'il tient."] =
        "Haz clic en una ranura de la silueta: recibe la petición de poner ese objeto (susurro, más un aviso de un clic si tiene el addon), y la lista de recetas de Blizzard se filtra por esa ranura. La mano derecha marca «Arma» y «Arma a dos manos» a la vez, porque aún no sabemos qué lleva.",
    ["Dès qu'une pièce est posée, la liste suit la pièce elle-même plutôt que ta demande. À la fin de l'échange elle retrouve tes filtres d'avant, y compris celui que tu avais posé toi-même, et la colonne revient sur l'onglet que tu regardais."] =
        "En cuanto hay algo en la mesa, la lista sigue al objeto en sí y no a tu petición. Al terminar el intercambio recupera los filtros que tenías antes, incluido el que hubieras puesto tú, y la columna vuelve a la pestaña que mirabas.",
    ["S'il pose aussi des composants, la colonne nomme l'enchantement qu'ils désignent — elle lit ce qu'il pose, jamais tes sacs, et se tait quand plusieurs enchantements collent. Et si un échange s'ouvre alors que ton Enchantement est fermé, un onglet apparaît au bord droit de la fenêtre d'échange pour l'ouvrir."] =
        "Si además pone materiales, la columna nombra el encantamiento al que apuntan. Lee lo que él pone, nunca tus bolsas, y calla cuando encajan varios encantamientos. Y si se abre un intercambio con el Encantamiento cerrado, aparece una pestaña en el borde derecho de la ventana de intercambio para abrirlo.",
    -- v1.34.1
    ["Plus d'erreur en entrant en ville"] =
        "Se acabó el error al entrar en una ciudad",
    ["Avec la détection des artisans sans l'addon activée (/co crafters on), chaque entrée en ville déclenchait une erreur « action interdite » au nom de l'addon. Sur Forever, le jeu n'autorise plus les addons à écouter le journal de combat, et l'addon s'y abonnait quand même. C'est fini : la détection passe désormais par les messages de fabrication du chat (« Untel crée … »), qui restent ouverts aux addons."] =
        "Con la detección de artesanos activada (/co crafters on), cada entrada en una ciudad provocaba un error de «acción prohibida» con el nombre del addon. En Forever los addons ya no pueden escuchar el registro de combate, y el addon lo seguía intentando. Ya no: la detección pasa ahora por los mensajes de fabricación del chat («X crea Y»), que los addons sí pueden leer.",
    ["Le panneau d'enchantement qui s'ouvre à côté de la fenêtre d'échange disait toujours « Ouvre ta fenêtre d'Enchantement », même ouverte : il cherchait une fenêtre qui n'existe pas sur Forever. Il liste maintenant tes enchantements pour la pièce posée, classés comme avant, et il remarque quand tu ouvres l'Enchantement en plein échange. Cliquer une ligne ne lance pas encore l'enchantement."] =
        "El panel de encantamiento que se abre junto a la ventana de comercio siempre decía «Abre tu ventana de Encantamiento», aunque estuviera abierta: buscaba una ventana que no existe en Forever. Ahora muestra tus encantamientos para la pieza colocada, ordenados como antes, y se da cuenta cuando abres Encantamiento en mitad de un intercambio. Hacer clic en una línea todavía no lanza el encantamiento.",
    ["Sous le capot : l'addon ne transporte plus rien du code de Classic Era (cette version reste figée en 1.30.0), et il lit ton journal de quêtes directement dans le jeu, sans passer par les copies des anciennes fonctions que Questie installe quand il est présent."] =
        "Por dentro: el addon ya no lleva nada del código de Classic Era (esa versión sigue congelada en la 1.30.0) y lee tu registro de misiones directamente del juego, en vez de pasar por las copias de las funciones antiguas que Questie instala cuando está presente.",

    -- v1.36.0
    ["Ce qui rapporte, et dire au royaume que tu es dispo"] =
        "Lo que renta, y decirle al reino que estas libre",
    ["La colonne de métier gagne un onglet, Profit : ce que tu sais faire qui vaut la peine d'être fait, la plus grosse marge en haut, avec le prix de vente face au coût des composants. Un clic sur une ligne amène la recette dans la liste de Blizzard. L'onglet n'apparaît que si Auctionator tourne, puisque les prix viennent de lui, et il le dit au lieu de t'afficher un zéro."] =
        "La columna de profesion gana una pestana, Profit. Lista lo que sabes hacer y merece la pena hacer, mayor margen primero, con el precio de venta frente al coste de los reactivos. Un clic en una linea lleva la receta a la lista de Blizzard. La pestana solo aparece si Auctionator esta activo, porque de ahi vienen los precios, y lo dice en vez de mostrarte un cero.",
    ["« Chercher du travail » est revenu. Sur Forever le bouton avait disparu avec l'ancienne fenêtre à trois colonnes : il ne restait que /co lfw, et plus aucun moyen de régler ton offre. C'est maintenant une bande en bas de la colonne, qui affiche « Dispo — Forge » dans toutes les vues. Oublier qu'on est annoncé est exactement ce que le minuteur d'expiration existe pour rattraper."] =
        "'Buscar trabajo' ha vuelto. En Forever el boton habia desaparecido con la antigua ventana de tres columnas, quedaba solo /co lfw y ninguna forma de cambiar tu oferta. Ahora es una banda en la parte inferior de la columna, que muestra 'Disponible, Herreria' en todas las vistas. Olvidar que estas anunciado es justo la razon por la que el anuncio caduca solo.",
    ["À côté, le bouton Offre ouvre ce que tu proposes : les composants de base, une commission par craft, ne prendre que ce qui te fait progresser, les réactifs que tu fournis. Nouveau, tu coches aussi les recettes précises que tu proposes, et qui te consulte les voit par leur nom. La liste des réactifs se limite désormais à ce que tu sais crafter — un travailleur du cuir à 82 ne se voit plus proposer de la Vigne de sang."] =
        "Al lado, un boton Oferta abre lo que estas dispuesto a hacer. Poner los reactivos de vendedor, una comision fija por fabricacion, aceptar solo trabajo que te suba la habilidad, que reactivos aportas. Nuevo, marcas tambien las recetas concretas que ofreces, y quien te consulta las ve por su nombre. Esa lista de reactivos solo muestra lo que de verdad puedes fabricar, asi que a un peletero de 82 ya no se le ofrece Vid sangrienta.",
    ["Recharge ton interface et tu revois les annonces des autres en quelques secondes. Avant, personne ne se ré-annonçait à ton arrivée : tu pouvais rester devant un radar vide pendant huit minutes sans le savoir."] =
        "Recarga la interfaz y los anuncios de los demas vuelven en segundos. Antes nadie se reanunciaba cuando llegabas, asi que podias estar ocho minutos frente a un radar vacio sin saberlo.",
    ["Plus petit. Le bouton d'aide « i » se posait sur la dernière languette et lui volait ses clics. L'onglet « Plan de route » s'appelle « Route », ce qui a fait la place au reste. Et l'addon relève le niveau qu'un formateur exige, donc les recettes affichées « ? » se remplissent à mesure que tu passes les voir."] =
        "Cosas menores. El boton de ayuda 'i' se posaba sobre la ultima pestana y le robaba los clics. La pestana 'Ruta de subida' se llama 'Ruta', que es lo que ha hecho sitio al resto. Y el addon lee el nivel que exige un maestro, asi que las recetas con '?' se rellenan segun las visitas.",

    -- v1.36.1
    ["Une icône dans la liste des addons"] =
        "Un icono en la lista de addons",
    ["L'addon a enfin sa propre icône dans la liste des addons, à la place du point d'interrogation. Rien d'autre ne change."] =
        "El addon por fin tiene su propio icono en la lista de addons, en lugar del signo de interrogación. Nada más cambia.",
    -- v1.36.2
    ["Les commandes trouvent leur destinataire"] =
        "Los pedidos llegan a quien deben",
    ["Sur WoW Forever, chaque personnage a un nom de famille, et le jeu te désigne partout par « Prénom Nom ». L'addon t'appelait par ton prénom seul et ne se reconnaissait plus : une commande à ton nom arrivait puis était ignorée, une commande postée sur le canal était rejetée comme si quelqu'un postait à la place d'un autre, et tu pouvais te retrouver dans ta propre liste d'artisans. C'est réparé, y compris pour les commandes des joueurs restés en 1.36.1."] =
        "En WoW Forever cada personaje tiene apellido, y el juego te llama 'Nombre Apellido' en todas partes. El addon seguía usando solo tu nombre y dejó de reconocerse: un pedido a tu nombre llegaba y se ignoraba, un pedido publicado en el canal se descartaba como si alguien publicara en nombre de otro, y podías aparecer en tu propia lista de artesanos. Corregido, también para los pedidos de jugadores que siguen en la 1.36.1.",
    ["Une ligne du canal Commerce comme « dont need fire wand: [Lesser Magic Wand] » n'est plus prise pour une demande."] =
        "Una línea del canal de Comercio como 'dont need fire wand: [Lesser Magic Wand]' ya no se toma por una petición.",
    -- v1.39.1
    ["Les commandes envoyées par courrier se terminent seules"] =
        "Los pedidos enviados por correo se cierran solos",
    ["Quand un artisan t'envoie ta commande par courrier, prendre l'objet dans ta boîte aux lettres la marque reçue, comme quand tu le ramasses. L'artisan est crédité tout de suite. Avant, elle restait « Remise » et il fallait cliquer « J'ai reçu » dans le Carnet."] =
        "Cuando un artesano te envía tu pedido por correo, sacar el objeto del buzón lo marca como recibido, igual que al despojarlo. El artesano recibe el crédito al momento. Antes se quedaba en 'Entregado' y había que pulsar 'Recibido' en el Libro.",
    ["Côté artisan, « Remplir depuis commande » pouvait joindre une pile entière à une commande plus petite : une commande de 1 partait avec 9. Il coupe maintenant la bonne quantité dans tes sacs et ne joint qu'elle ; sans case libre pour la coupe, le chat te dit combien séparer toi-même."] =
        "Del lado del artesano, 'Rellenar desde pedido' podía adjuntar una pila entera a un pedido más pequeño: un pedido de 1 salía con 9. Ahora separa la cantidad justa en tus bolsas y solo adjunta eso; sin hueco libre para separar, el chat te dice cuántos separar tú mismo.",
    -- v1.39.0
    ["La fenêtre prend l'allure du jeu"] =
        "La ventana se parece al juego",
    ["Les onglets de la fenêtre passent sur son bord droit, en icônes, comme dans la fenêtre de métier. Survole-les pour lire leur nom ; le titre dit où tu es, et l'icône du Carnet compte tes commandes en cours."] =
        "Las pestañas de la ventana pasan a su borde derecho, como iconos, igual que en la ventana de profesión. Pasa el ratón por encima para leer su nombre; el título dice dónde estás, y el icono del Libro cuenta tus pedidos abiertos.",
    ["Toutes les listes et les pages défilent avec la barre fine du jeu, qui se cache quand tout tient : ressources de Récolte, Carnet, Aide, Nouveautés, et les vues Commandes, Route, Manquantes et Profit de la fenêtre de métier. Chaque bloc est posé dans un encart, comme dans la fenêtre de métier."] =
        "Todas las listas y páginas se desplazan con la barra fina del juego, que se oculta cuando todo cabe: recursos de Recolección, Libro, Ayuda, Novedades, y las vistas Pedidos, Ruta, Faltantes y Beneficio de la ventana de profesión. Cada bloque va en un recuadro, como en la ventana de profesión.",
    ["Dans Commande, la commission est la case or, argent, cuivre du jeu, et la quantité a des flèches. Le Carnet se trie : clique l'en-tête d'une colonne, reclique pour inverser. Le Journal et la fiche « Poster en quête » prennent le cadre du journal de quêtes du jeu, livre et parchemin."] =
        "En Pedido, la comisión es la casilla de oro, plata y cobre del juego, y la cantidad tiene flechas. El Libro se ordena: haz clic en el encabezado de una columna, otra vez para invertir. El Diario y la hoja 'Publicar como misión' usan el marco del registro de misiones del juego, con libro y pergamino.",
    ["Les panneaux de l'échange et du courrier prennent l'allure de ces fenêtres. Le courrier ne liste plus que ce qui se poste : un enchantement se fait à l'échange, où l'onglet Enchantement brille quand une commande d'enchant acceptée te lie à ton partenaire. L'Aide est réécrite, et ses flèches affichées en carrés sont réparées."] =
        "Los paneles del comercio y del correo se parecen ahora a esas ventanas. El correo solo lista lo que se puede enviar: un encantamiento se hace en el comercio, donde la pestaña Encantamiento brilla cuando un pedido de encantamiento aceptado te une a tu compañero. La Ayuda está reescrita, y sus flechas que se veían como cuadrados están arregladas.",
    -- v1.38.0
    ["Un signe quand une mise à jour est là"] =
        "Una señal cuando hay una actualización",
    ["Quand le réseau signale une nouvelle version, le logo de Crafting Order apparaît en haut de la minicarte, là où Blizzard pose la lettre du courrier. Survole-le pour voir quelle version est sortie et laquelle tu as, clique pour le détail dans le chat. Il disparaît une fois la mise à jour faite."] =
        "Cuando la red avisa de una versión nueva, el logo de Crafting Order aparece en la parte superior del minimapa, donde Blizzard muestra la carta del correo. Pasa el ratón por encima para ver qué versión ha salido y cuál tienes; un clic muestra los detalles en el chat. Desaparece en cuanto actualizas.",
    -- v1.37.0
    ["Les artisans se retrouvent dans une communauté"] =
        "Los artesanos se reúnen en una comunidad",
    ["Sur WoW Forever, le canal caché de l'addon, CraftLinkNet, est découpé en salles : deux joueurs côte à côte pouvaient ne jamais voir leurs commandes. L'addon ne l'utilise plus, et le quitte si tu y es encore. Les artisans se retrouvent dans la communauté « Crafting Order PVE », une par camp."] =
        "En WoW Forever el canal oculto del addon, CraftLinkNet, se divide en salas separadas: dos jugadores uno al lado del otro podían no ver nunca sus pedidos. El addon ya no lo usa, y lo abandona si sigues dentro. Los artesanos se reúnen ahora en la comunidad 'Crafting Order PVE', una por facción.",
    ["Sans cercle d'artisans, tu reçois à la connexion un whisper de toi-même avec un lien Rejoindre. Clique dessus, puis Rejoindre dans la fenêtre qui s'ouvre : l'addon en fait ton cercle tout seul. « /co circle nolink » coupe ce rappel."] =
        "Sin círculo de artesanos, al conectarte recibes un susurro de ti mismo con un enlace para unirte. Haz clic en él y luego en Unirse en la ventana que se abre: el addon la convierte en tu círculo por sí solo. '/co circle nolink' desactiva este aviso.",
    ["Tout ce qui passait par le canal part en whisper aux joueurs de l'addon en ligne : ton profil, les commandes et leurs annulations, la recherche de travail. Les joueurs restés en 1.36 ne te joignent plus que par les amis, la guilde, un cercle commun ou une commande à leur nom : dis-leur de mettre à jour."] =
        "Todo lo que pasaba por el canal va ahora por susurro a los usuarios del addon conectados: tu perfil, los pedidos y sus cancelaciones, la búsqueda de trabajo. Los jugadores que siguen en la 1.36 solo te alcanzan por amigos, hermandad, un círculo común o un pedido a su nombre: diles que actualicen.",
    ["L'onglet Artisans a une ligne par communauté, à son nom, et un joueur passe hors ligne dès que la communauté le dit parti. La ligne Confédération n'apparaît que si GreenWall tourne."] =
        "La pestaña Artesanos tiene una línea por comunidad, con su nombre, y un jugador pasa a desconectado en cuanto la comunidad dice que se ha ido. La línea Confederación solo aparece si GreenWall está activo.",
    ["Aussi : les listes de Commande, Récolte, Artisans et Mes artisans défilent comme celle des métiers de Blizzard ; un artisan choisi depuis Artisans arrive sélectionné dans Commande ; le bouton d'aide passe au-dessus du portrait et ne se cache plus derrière la Route ; Manquantes n'affiche plus l'exemplaire de l'autre camp d'une recette jumelle ; la Route puise dans tes sacs avant l'hôtel des ventes ; ouvrir le lien de métier d'un autre joueur ne range plus ses recettes dans les tiennes."] =
        "Además: las listas de Pedido, Recolección, Artesanos y Mis artesanos se desplazan como la lista de profesiones de Blizzard; un artesano elegido desde Artesanos llega seleccionado en Pedido; el botón de ayuda está sobre el retrato y ya no se esconde detrás de la Ruta; Faltantes ya no muestra el ejemplar de la otra facción de una receta gemela; la Ruta usa tus bolsas antes que la casa de subastas; abrir el enlace de profesión de otro jugador ya no guarda sus recetas entre las tuyas.",
    -- v1.40.0
    ["Tes commandes sur Commerce, et l'addon sans communauté"] =
        "Tus pedidos en Comercio, y el addon sin comunidad",
    ["Coche « Annoncer en Commerce » en postant une commande à tous : l'addon écrit aussi une ligne sur Trade (Services), dans une capitale, que tout le monde lit. Les joueurs de l'addon, même inconnus, reçoivent la vraie commande en quelques secondes ; les autres peuvent te chuchoter. Clic droit sur la commande dans le Carnet pour la rappeler, une fois par quart d'heure."] =
        "Marca «Anunciar en Comercio» al publicar un pedido para todos: el addon escribe también una línea en Comercio (Servicios), en una capital, que todos pueden leer. Los usuarios del addon, incluso desconocidos, reciben el pedido real en segundos; los demás pueden susurrarte. Clic derecho sobre el pedido en el Libro para repetirlo, una vez cada cuarto de hora.",
    ["La même case, dans l'offre de « Chercher du travail », annonce ta dispo : une ligne « LFW » sur Trade (Services) quand tu l'actives, et les joueurs de l'addon reçoivent ton profil."] =
        "La misma casilla, en la oferta de «Buscar trabajo», anuncia tu disponibilidad: una línea «LFW» en Comercio (Servicios) cuando la activas, y los usuarios del addon reciben tu perfil.",
    ["L'addon marche sans la communauté Crafting Order PVE et ne t'en envoie plus le lien. Les artisans se trouvent par les amis, la guilde, tes cercles, les annonces sur Commerce et la salle de découverte, où les joueurs de l'addon se disent bonjour (« /co channel room off » pour la quitter)."] =
        "El addon funciona sin la comunidad Crafting Order PVE y ya no te envía su enlace. Los artesanos se encuentran por amigos, hermandad, tus círculos, los anuncios en Comercio y la sala de descubrimiento, donde los usuarios del addon se saludan («/co channel room off» para salir).",
    ["Aussi : l'addon ne crie plus de ping, que Forever refusait sans rien dire ; « /co note » prépare le texte de tes métiers à coller dans ta note de membre d'une communauté, et l'onglet Artisans affiche la note des autres."] =
        "Además: el addon ya no grita un ping, que Forever rechazaba en silencio; «/co note» prepara el texto de tus profesiones para pegarlo en tu nota de miembro de una comunidad, y la pestaña Artesanos muestra las notas de los demás.",
}

for k, v in pairs(news) do L[k] = v end
