-- CraftingOrderClassic_Locale_News_deDE.lua — traductions de l'onglet « Nouveautés » (deDE).
-- Extrait de _Locale_deDE.lua (plafond anti-monolithe). Clé FR » texte DE, chargé APRÈS _Locale.lua.

local COC = CraftingOrderClassic
if (GetLocale and GetLocale() or "") ~= "deDE" then return end
local L = COC.L

local news = {
    -- Onglet Nouveautés (changelog en jeu)
    ["Nouveautés"] = "Neues",
    -- v1.48.0
    ["Signale un bug ou propose une idée depuis le jeu"] = "Fehler melden oder Idee vorschlagen, direkt aus dem Spiel",
    ["Un bug, une idée ? Clique sur le petit scarabée bleu à côté du « i », en haut de la fenêtre (ou sur le bouton en haut de l'onglet Aide, ou tape /co bug). Choisis Bug ou Idée : l'addon te donne un lien déjà sélectionné. Fais Ctrl+C, colle-le dans ton navigateur, et le formulaire GitHub s'ouvre avec la version de l'addon et du jeu déjà remplie. Rien sur ton personnage n'y figure."] =
        "Ein Fehler, eine Idee? Klick auf den kleinen blauen Käfer neben dem „i“ oben im Fenster (oder auf den Knopf oben im Hilfe-Reiter, oder tippe /co bug). Wähle Fehler oder Idee: Das Addon gibt dir einen bereits markierten Link. Drück Strg+C, füge ihn in deinen Browser ein, und das GitHub-Formular öffnet sich mit bereits eingetragener Addon- und Spielversion. Nichts über deinen Charakter steht darin.",
    ["Pas de compte GitHub ? Le troisième choix donne la page CurseForge de l'addon, pour y laisser un commentaire."] =
        "Kein GitHub-Konto? Die dritte Wahl führt zur CurseForge-Seite des Addons, wo du einen Kommentar hinterlassen kannst.",
    -- v1.47.0
    ["Ta recherche de travail et tes commandes publiques vont plus loin"] = "Deine Arbeitssuche und öffentlichen Aufträge reichen weiter",
    ["Certains joueurs de l'addon ne voyaient toujours ni ta recherche de travail ni tes commandes pour tous : le canal de l'addon n'atteint pas tout le monde, et les présentations de la v1.46.0 n'aident que ceux déjà connectés quand tu arrives. Maintenant, là où ton canal n'arrive pas, l'addon demande à un joueur de l'addon que tu connais (un ami ou un membre de ta guilde d'abord) de les répéter à tous ceux que son propre canal atteint. Ils les voient comme les autres, avec « via <nom> » dans l'infobulle d'une recherche de travail."] =
        "Manche Addon-Nutzer sahen deine Arbeitssuche und deine Aufträge für alle immer noch nicht: Der Kanal des Addons erreicht nicht jeden, und die Vorstellungen aus v1.46.0 helfen nur denen, die schon online sind, wenn du dich einloggst. Jetzt bittet das Addon dort, wo dein Kanal nicht hinkommt, einen Addon-Nutzer, den du kennst (zuerst Freunde oder Gildenmitglieder), sie allen zu wiederholen, die sein eigener Kanal erreicht. Diese Spieler sehen sie wie alle anderen, mit „via <Name>“ im Tooltip einer Arbeitssuche.",
    ["Une ligne répétée par un autre pourrait être inventée, alors l'addon vérifie. Quand tu cliques sur Chuchoter pour un artisan dont la recherche de travail t'est arrivée ainsi, il demande d'abord en coulisse à cet artisan si c'est vrai. S'il dit non, la ligne disparaît et celui qui l'a répétée est ignoré pendant un jour. Une commande répétée se vérifie comme avant, à la première acceptation : si l'acheteur ne l'a pas, elle passe annulée."] =
        "Eine von jemand anderem wiederholte Zeile könnte erfunden sein, deshalb prüft das Addon sie. Wenn du bei einem Handwerker, dessen Arbeitssuche dich so erreicht hat, auf Flüstern klickst, fragt es ihn zuerst im Hintergrund, ob sie stimmt. Sagt er nein, verschwindet die Zeile, und wer sie wiederholt hat, wird einen Tag lang ignoriert. Ein wiederholter Auftrag wird wie bisher geprüft, sobald ihn jemand annimmt: Hat der Käufer ihn nicht, wird er als storniert angezeigt.",
    ["Ça reste léger : un seul joueur par canal, ta recherche de travail répétée au plus toutes les 15 minutes, une commande au plus toutes les deux heures, et rien quand tu es en instance. Ça ne marche qu'entre joueurs qui ont cette version."] =
        "Es bleibt sparsam: ein Spieler pro Kanal, deine Arbeitssuche höchstens alle 15 Minuten wiederholt, ein Auftrag höchstens alle zwei Stunden, und nichts, solange du in einer Instanz bist. Es funktioniert nur zwischen Spielern mit dieser Version.",
    -- v1.46.0
    ["Plus d'artisans trouvés, même ceux que tu n'as jamais croisés"] = "Mehr Handwerker gefunden, auch solche, denen du nie begegnet bist",
    ["Certains joueurs de l'addon restaient invisibles pour toi, même en jouant à côté : tu ne les trouvais qu'en les croisant, en les ciblant ou en groupe. Maintenant, quand l'un d'eux se connecte, un joueur de l'addon qui vous connaît tous les deux fait les présentations, et vos deux addons se disent bonjour en coulisse. Il apparaît dans ton onglet Artisans avec ses métiers, et ses commandes et sa recherche de travail t'arrivent comme pour n'importe quel artisan connu. Rien à régler."] =
        "Manche Addon-Nutzer blieben für dich unsichtbar, selbst wenn sie direkt neben dir spielten: Du fandest sie nur, wenn du ihnen begegnet bist, sie ins Ziel genommen oder mit ihnen gruppiert hast. Jetzt stellt beim Einloggen eines von ihnen ein Addon-Nutzer, der euch beide kennt, euch einander vor, und eure Addons grüßen sich im Hintergrund. Er erscheint in deinem Handwerker-Reiter mit seinen Berufen, und seine Aufträge und seine Arbeitssuche erreichen dich wie bei jedem bekannten Handwerker. Nichts einzustellen.",
    ["Ça reste discret : une présentation par connexion, un bonjour court de chaque côté, et pas plus d'une fois toutes les six heures pour le même joueur. Plus il y a de joueurs à jour, plus tu verras de monde."] =
        "Das bleibt unauffällig: eine Vorstellung pro Login, ein kurzer Gruß in jede Richtung und höchstens einmal alle sechs Stunden für denselben Spieler. Je mehr Spieler aktualisieren, desto mehr Leute siehst du.",
    ["Dans l'onglet Artisans, les métiers principaux d'un artisan s'affichent maintenant avant la Cuisine, la Pêche et le Secourisme."] =
        "Im Handwerker-Reiter erscheinen die Hauptberufe eines Handwerkers jetzt vor Kochkunst, Angeln und Erster Hilfe.",
    -- v1.45.0
    ["Le /1 te revient, et l'addon découvre les royaumes cachés"] = "/1 gehört wieder dir, und das Addon lernt die versteckten Realms kennen",
    ["Sur un perso tout neuf, le canal caché de l'addon pouvait passer avant le canal Général du jeu et prendre le /1, que le jeu lui gardait ensuite : taper /1 écrivait dans un canal caché. L'addon rend maintenant le /1 au premier canal du jeu dès qu'il y en a un, sur les nouveaux persos comme sur ceux déjà touchés."] =
        "Bei einem ganz neuen Charakter konnte der versteckte Kanal des Addons vor dem Allgemein-Kanal des Spiels beitreten und /1 belegen, und das Spiel behielt diese Nummer bei: Wer /1 tippte, schrieb in einen versteckten Kanal. Das Addon gibt /1 jetzt an den ersten Kanal des Spiels zurück, sobald es einen gibt, bei neuen Charakteren wie bei bereits betroffenen.",
    ["Sur Forever, un chuchotement n'arrive qu'au nom complet « Prénom Nom ». Juste après un groupe, ou sur un clic droit, l'addon disait parfois bonjour au seul prénom, ou à « Unknown » : le bonjour se perdait, et une erreur « No player named » pouvait suivre deux minutes plus tard. Il attend maintenant le nom complet, et le menu du clic droit lit aussi le nom de famille."] =
        "Auf Forever kommt ein Flüstern nur beim vollen Namen „Vorname Nachname“ an. Direkt nach einer Gruppe oder bei einem Rechtsklick grüßte das Addon manchmal nur den Vornamen oder „Unknown“: Der Gruß ging verloren, und zwei Minuten später konnte ein „No player named“-Fehler folgen. Es wartet jetzt auf den vollen Namen, und das Rechtsklickmenü liest auch den Nachnamen.",
    ["Si tu as accepté ou livré une commande que son acheteur n'a plus (expirée, effacée, ou qui n'a jamais été la sienne), son addon prévient maintenant le tien, et la commande passe annulée au lieu de rester en attente pour rien. Il suffit que l'acheteur ait cette version."] =
        "Wenn du einen Auftrag angenommen oder geliefert hast, den der Käufer nicht mehr hat (abgelaufen, gelöscht oder nie von ihm), sagt sein Addon das jetzt deinem, und der Auftrag erscheint als storniert, statt umsonst offen zu bleiben. Nur der Käufer braucht diese Version.",
    ["Avec le suivi affiché à l'écran, l'addon recalculait toutes les deux minutes les recettes de chaque métier suivi, et sa mémoire grimpait sans arrêt. Il ne le refait plus qu'en quittant l'hôtel des ventes ou un marchand, là où les prix changent, et sinon toutes les 15 minutes."] =
        "Mit eingeblendeter Bildschirmverfolgung berechnete das Addon alle zwei Minuten die Rezepte jedes verfolgten Berufs neu, und sein Speicher stieg ständig. Jetzt tut es das nur noch, wenn du das Auktionshaus oder einen Händler verlässt, wo sich die Preise ändern, und sonst alle 15 Minuten.",
    ["Forever a toujours des royaumes, cachés : le jeu range chaque compte sur l'un d'eux sans le dire. Le canal de découverte de l'addon n'atteint que les joueurs de ton royaume, et le canal Commerce aussi, donc tes annonces et ta ligne LFW. Ton royaume part maintenant avec le bonjour de l'addon. Rien ne change encore à l'écran : c'est la première étape pour présenter les joueurs d'un royaume à l'autre."] =
        "Forever hat weiterhin Realms, nur versteckt: Das Spiel setzt jedes Konto auf einen davon, ohne es zu sagen. Der Entdeckungskanal des Addons erreicht nur Spieler deines Realms, und der Handelskanal ebenso, also auch deine Ankündigungen und deine LFW-Zeile. Dein Realm geht jetzt mit dem Gruß des Addons mit. Auf dem Bildschirm ändert sich noch nichts: Es ist der erste Schritt, um Spieler über Realms hinweg vorzustellen.",
    -- v1.44.2
    ["Des cooldowns justes, et les longues listes de recettes arrivent entières"] = "Richtige Abklingzeiten, und lange Rezeptlisten kommen vollständig an",
    ["L'addon annonçait des transmutations ou l'Étoffe lunaire « prêtes » chez des artisans qui ne connaissaient même pas ces recettes. La fenêtre de métier liste aussi les recettes que tu n'as pas apprises, et l'addon prenait leur cooldown pour le tien. Il ne suit plus que les recettes que tu connais, et efface au chargement les faux cooldowns déjà notés, pour tous tes persos. Ceux qu'envoie un joueur pas encore à jour sont écartés quand son niveau de métier est trop bas pour connaître la recette."] =
        "Das Addon meldete Transmutationen oder Mondstoff als „bereit“ bei Handwerkern, die diese Rezepte gar nicht kannten. Das Berufsfenster listet auch Rezepte, die du nicht gelernt hast, und das Addon hielt ihre Abklingzeit für deine. Es verfolgt jetzt nur noch Rezepte, die du kennst, und löscht beim Laden die schon gespeicherten falschen Abklingzeiten, für alle deine Charaktere. Abklingzeiten von Spielern ohne das Update werden verworfen, wenn ihre Berufsstufe zu niedrig ist, um das Rezept zu kennen.",
    ["Le jeu coupe sans prévenir tout message d'addon de plus de 255 caractères. Au-delà d'une centaine de recettes dans un métier, la liste de ce qu'un artisan sait faire arrivait tronquée chez les autres, parfois avec à la fin une recette qu'il ne connaît pas. Elle part maintenant en plusieurs messages, un par palier du métier (Apprenti, Compagnon, Expert, Artisan), et arrive entière. Une liste courte part toujours en un seul message."] =
        "Das Spiel kürzt jede Addon-Nachricht über 255 Zeichen ohne Warnung. Ab etwa hundert Rezepten in einem Beruf kam die Liste dessen, was ein Handwerker herstellen kann, bei allen anderen abgeschnitten an, manchmal mit einem Rezept am Ende, das er nicht kennt. Sie geht jetzt in mehreren Nachrichten raus, eine pro Stufe (Lehrling, Geselle, Experte, Fachmann), und kommt vollständig an. Eine kurze Liste geht weiterhin als eine einzige Nachricht raus.",
    ["Chez un joueur qui n'a pas encore la mise à jour, rien ne change tant que ta liste tient en un message. Au-delà, il n'en verra qu'une partie jusqu'à sa mise à jour."] =
        "Bei einem Spieler ohne das Update ändert sich nichts, solange deine Liste in eine Nachricht passt. Darüber hinaus sieht er nur einen Teil davon, bis er aktualisiert.",
    -- v1.44.1
    ["Fini le spam « No player named »"] = "Schluss mit dem „No player named“-Spam",
    ["Quand un joueur de l'addon se déconnectait, ton chat pouvait se remplir de « No player named 'X' is currently playing. » deux minutes plus tard, encore et encore : l'addon continuait de lui envoyer tes commandes et ta fiche. Le jeu signale un message envoyé à un absent avec environ deux minutes de retard, et l'addon ne l'attendait que 15 secondes. Il attend maintenant cinq minutes : l'erreur reste cachée et l'addon cesse d'écrire à celui qui est parti."] =
        "Wenn sich ein anderer Addon-Nutzer abmeldete, konnte sich dein Chat zwei Minuten später mit „No player named 'X' is currently playing.“ füllen, immer wieder: Das Addon schickte ihm weiter deine Aufträge und dein Profil. Das Spiel meldet eine Nachricht an jemanden, der offline ist, erst etwa zwei Minuten später, und das Addon wartete nur 15 Sekunden darauf. Jetzt wartet es fünf Minuten: Der Fehler bleibt verborgen, und das Addon schreibt dem Abgemeldeten nicht mehr.",
    ["L'addon envoie aussi beaucoup moins : quand un joueur te dit bonjour, tes commandes ne partent plus qu'à lui, et plus à tous tes contacts. En montant un métier, ta fiche part au plus une fois par minute au lieu de partir à chaque point."] =
        "Das Addon sendet außerdem viel weniger: Wenn dich ein Spieler grüßt, gehen deine Aufträge nur noch an ihn statt an alle deine Kontakte. Beim Leveln eines Berufs geht dein Profil höchstens einmal pro Minute raus statt nach jedem Punkt.",
    ["Seul effet de bord : si tu chuchotes toi-même un joueur déconnecté que l'addon a contacté dans ces cinq minutes, l'erreur de ton chuchotement est cachée aussi."] =
        "Einziger Nebeneffekt: Wenn du selbst einen abgemeldeten Spieler anflüsterst, den das Addon in diesen fünf Minuten kontaktiert hat, bleibt auch der Fehler zu deinem Flüstern verborgen.",
    -- v1.44.0
    ["Ta ligne LFW porte le lien de ton métier"] = "Deine LFW-Zeile verlinkt deinen Beruf",
    ["Quand tu cherches du travail, la ligne que l'addon poste sur Trade (Services) porte maintenant le lien de ton métier, juste après son nom. N'importe qui clique dessus et voit tes recettes, même sans l'addon. L'addon prend le lien chaque fois que tu ouvres ta fenêtre de métier et le garde : un /co lfw tapé fenêtre fermée part avec le dernier lien connu. Un métier jamais ouvert depuis la mise à jour part avec son nom seul, comme avant."] =
        "Wenn du Arbeit suchst, trägt die Zeile, die das Addon in Handel (Dienstleistungen) postet, jetzt direkt nach dem Namen den Link zu deinem Beruf. Jeder kann ihn anklicken und deine Rezepte sehen, auch ohne das Addon. Das Addon übernimmt den Link jedes Mal, wenn du dein Berufsfenster öffnest, und behält ihn: Ein /co lfw bei geschlossenem Fenster geht mit dem zuletzt bekannten Link raus. Ein Beruf, den du seit dem Update nicht geöffnet hast, geht wie bisher nur mit seinem Namen raus.",
    ["Chercher du travail ne provoque plus d'erreur Lua en combat de boss : pendant la rencontre, le jeu cache si tu es absent, et l'addon butait dessus. Il saute simplement ce rafraîchissement et reprend après le combat."] =
        "Die Arbeitssuche löst im Bosskampf keinen Lua-Fehler mehr aus. Während der Begegnung verbirgt das Spiel, ob du abwesend bist, und das Addon stolperte darüber. Jetzt lässt es diese Aktualisierung einfach aus und macht nach dem Kampf weiter.",
    ["Une commande nommée pour un de tes rerolls ouvrait la vue de ce reroll, même quand le perso sur lequel tu joues connaît aussi la recette. Maintenant, si tu sais la faire, c'est ta fenêtre de métier qui s'ouvre. La vue du reroll ne s'ouvre plus que si lui seul connaît la recette."] =
        "Ein Auftrag, der an einen deiner Twinks gerichtet war, öffnete dessen Ansicht, auch wenn dein gespielter Charakter das Rezept ebenfalls kennt. Jetzt öffnet sich dein eigenes Berufsfenster, wenn du es herstellen kannst. Die Ansicht des Twinks öffnet sich nur noch, wenn nur er das Rezept kennt.",
    -- v1.43.0
    ["Une icône quand une commande t'attend"] = "Ein Symbol, wenn ein Auftrag auf dich wartet",
    ["Quand une commande t'attend, l'icône de son métier s'affiche à côté de la minicarte, près de la lettre du courrier, avec le nombre de commandes. Survole-la pour voir qui demande quoi, clique pour ouvrir la bonne fenêtre. Elle s'éteint quand tu as tout accepté ou refusé."] =
        "Wartet ein Auftrag auf dich, erscheint das Symbol seines Berufs an der Minikarte, neben dem Briefsymbol, mit der Zahl der Aufträge. Fahr mit der Maus darüber, um zu sehen, wer was will, und klick, um das passende Fenster zu öffnen. Es verschwindet, sobald du alles angenommen oder abgelehnt hast.",
    ["Elle compte aussi les commandes nommées pour tes rerolls, et les commandes publiques qu'un de tes persos sait faire. La couleur du nombre dit d'où vient la commande : bleu pour toi, vert pour ta guilde ou tes amis, jaune pour tous (le mode daltonien du jeu passe à une palette adaptée). Le clic va vers le perso qui connaît la recette : ta fenêtre de métier, la vue de ton reroll, ou une fenêtre qui dit où l'apprendre."] =
        "Es zählt auch Aufträge, die an deine Twinks gerichtet sind, und öffentliche Aufträge, deren Rezept einer deiner Charaktere kennt. Die Farbe der Zahl zeigt, woher der Auftrag kommt: blau für dich, grün für deine Gilde oder Freunde, gelb für alle (im Farbenblindmodus des Spiels eine passende Palette). Der Klick führt zu dem Charakter, der das Rezept kennt: dein Berufsfenster, die Ansicht deines Twinks oder ein kleines Fenster, das sagt, wo man es lernt.",
    -- v1.42.1
    ["Les métiers remarchent après le patch du 2 octobre"] = "Berufe funktionieren nach dem Patch vom 2. Oktober wieder",
    ["Le patch du 2 octobre (build 70170) a changé le numéro par lequel le jeu indique quelle version de WoW tourne. L'addon ne le reconnaissait pas et éteignait tout ce qui touche aux métiers : plus de colonne Commandes à côté de la fenêtre de métier, plus de bouton Enchantement sur la fenêtre d'échange. Il reconnaît maintenant les deux numéros, rien à faire de ton côté."] =
        "Der Patch vom 2. Oktober (Build 70170) hat die Nummer geändert, mit der das Spiel angibt, welche WoW-Version läuft. Das Addon erkannte sie nicht und schaltete alles rund um Berufe ab: keine Auftragsspalte neben dem Berufsfenster, kein Verzauberkunst-Knopf am Handelsfenster. Jetzt kennt es beide Nummern, du musst nichts tun.",
    -- v1.42.0
    ["Tu choisis ce qui te prévient"] = "Du bestimmst, was dich benachrichtigt",
    ["En bas des « Canaux surveillés » de l'onglet Artisans, un groupe « Notifications » règle chaque alerte : les demandes lues dans le chat (« WTB [objet] »), les commandes des autres joueurs de l'addon, le suivi de tes commandes (remise, reçue, refusée) et le message à la connexion."] =
        "Unten in den überwachten Kanälen im Handwerker-Reiter regelt eine Gruppe „Benachrichtigungen“ jeden Hinweis: im Chat gelesene Anfragen („WTB [Gegenstand]“), Aufträge anderer Addon-Nutzer, der Verlauf deiner eigenen Aufträge (übergeben, erhalten, abgelehnt) und die Nachricht beim Einloggen.",
    ["Pour les commandes, tu choisis aussi la portée : toutes, seulement guilde, amis et celles pour toi, ou seulement celles à ton nom. C'est le réglage de /co notify, qui a enfin sa case."] =
        "Bei Aufträgen wählst du auch die Reichweite: alle, nur Gilde, Freunde und die für dich, oder nur die auf deinen Namen. Das ist die Einstellung von /co notify, jetzt endlich mit Kästchen.",
    ["« Façon de prévenir » coupe à part la ligne dans le chat, le bandeau et le son. Une case décochée ne cache aucune commande : tout reste dans le Carnet et la vue métier."] =
        "„Art der Benachrichtigung“ schaltet Chatzeile, Banner und Ton einzeln ab. Ein abgewähltes Kästchen versteckt keinen Auftrag: alles bleibt im Auftragsbuch und in der Berufsansicht.",
    -- v1.41.1
    ["Plus d'erreurs pendant les combats de boss"] = "Keine Fehler mehr in Bosskämpfen",
    ["Pendant un combat de boss, Forever cache aux addons qui a écrit une ligne du chat et ce qu'elle dit. L'addon levait alors une erreur à chaque ligne reçue sur un canal, Général compris ; il les laisse passer sans bruit. La liste des membres de tes communautés, cachée elle aussi, ne fait plus d'erreur et ne retire plus personne de ton annuaire."] =
        "Während eines Bosskampfs verbirgt Forever vor Addons, wer eine Chatzeile geschrieben hat und was darin steht. Das Addon warf bei jeder Zeile, die in einem Kanal ankam, einen Fehler, auch im Allgemein-Kanal; jetzt lässt es sie still vorbeiziehen. Die Mitgliederlisten deiner Gemeinschaften sind ebenfalls verborgen und verursachen keinen Fehler mehr und entfernen niemanden mehr aus deinem Verzeichnis.",
    ["Aussi : « Poster » et « /co refresh » n'écrivent plus de ligne « CLNK1 » sur le canal CraftLinkNet. L'addon y dit bonjour par un message d'addon, qui ne s'affiche pas dans le chat."] =
        "Außerdem: „Erstellen“ und /co refresh schreiben keine CLNK1-Zeile mehr in den Kanal CraftLinkNet. Das Addon grüßt dort mit einer Addon-Nachricht, die im Chat nicht erscheint.",
    -- v1.41.0
    ["Tu choisis où l'addon cherche les artisans"] = "Du bestimmst, wo das Addon nach Handwerkern sucht",
    ["L'onglet Artisans a une liste « Canaux surveillés » : les canaux de Commerce, la discussion de guilde, la salle de découverte, tes communautés et les joueurs autour de toi. Coche ceux où l'addon doit chercher des artisans. Hors d'une ville, les canaux de Commerce sont grisés et ton choix est gardé."] =
        "Der Reiter „Handwerker“ hat eine Liste „Beobachtete Kanäle“: die Handelskanäle, der Gildenchat, der Entdeckungsraum, deine Gemeinschaften und die Spieler um dich herum. Hake die an, in denen das Addon nach Handwerkern suchen soll. Außerhalb einer Stadt sind die Handelskanäle ausgegraut, und deine Wahl bleibt erhalten.",
    ["À ta première connexion après la mise à jour, un panneau te montre ces cases une fois, avec une phrase par groupe. Le bouton « Configurer » de l'onglet Artisans le rouvre."] =
        "Beim ersten Einloggen nach dem Update zeigt dir ein Fenster diese Kästchen einmal, mit einem Satz pro Gruppe. Der Knopf „Einrichten“ im Reiter „Handwerker“ öffnet es erneut.",
    ["Trade, Trade (Services) et Trade (Local) se règlent maintenant un par un. Un seul défaut change : l'addon ne lit plus les lignes « LFW » sur le canal Général, sauf si tu le coches. Une communauté se coche dans la même liste."] =
        "Handel, Handel (Dienstleistungen) und Handel (Lokal) haben jetzt je ein eigenes Kästchen. Eine Voreinstellung ändert sich: Das Addon liest „LFW“-Zeilen im Allgemein-Kanal nicht mehr, außer du hakst ihn an. Eine Gemeinschaft wird in derselben Liste angehakt.",
    ["L'onglet Artisans se lit mieux : « Chuchoter » n'est rouge que pour un joueur joignable, les icônes de métier restent en couleur, un joueur hors ligne a son nom en gris, et l'étiquette de source ne s'affiche que lorsqu'elle apprend quelque chose. La bande « Annuaire » s'appelle « Croisés », et « Rafraîchir l'annuaire » est passé en bas de la fenêtre."] =
        "Der Reiter „Handwerker“ liest sich besser: „Flüstern“ ist nur bei erreichbaren Spielern rot, Berufssymbole bleiben farbig, der Name eines Offline-Spielers ist grau, und das Herkunftsetikett erscheint nur, wenn es etwas aussagt. Der Filter „Verzeichnis“ heißt jetzt „Getroffen“, und „Verzeichnis aktualisieren“ sitzt unten im Fenster.",
    ["Aussi : si l'addon se charge sans sa bibliothèque, par exemple pendant la copie d'une mise à jour, il le dit et propose « /reload » au lieu de planter à chaque survol d'un joueur."] =
        "Außerdem: Lädt das Addon ohne seine Bibliothek, etwa während ein Update kopiert wird, sagt es das und schlägt „/reload“ vor, statt bei jedem Überfahren eines Spielers einen Fehler zu werfen.",
    -- v1.30.0
    ["La cuisine, le secourisme et la pêche comptent comme des métiers"] =
        "Kochkunst, Erste Hilfe und Angeln zählen als Berufe",
    ["L'annuaire faisait comme si ces trois-là n'existaient pas. Tu pouvais commander une pile de nourriture depuis l'onglet Commande, mais rien ne te disait QUI est cuisinier : pas d'icône sur sa ligne, pas de pastille pour filtrer, rien dans l'infobulle quand tu le survolais. Ils comptent maintenant comme les autres, et un clic droit sur un joueur propose « Commander Cuisine » comme il propose la forge. La pêche, elle, reste une récolte : elle s'affiche et se filtre, mais elle se commande depuis l'onglet Récolte, comme l'herboristerie."] =
        "Das Verzeichnis tat so, als gäbe es diese drei nicht. Du konntest im Bestellen-Tab einen Stapel Essen bestellen, aber nichts verriet dir, WER überhaupt kocht: kein Symbol in seiner Zeile, kein Knopf zum Filtern, nichts im Tooltip, wenn du über ihn gefahren bist. Jetzt zählen sie wie alle anderen, und ein Rechtsklick auf einen Spieler bietet «Kochkunst bestellen» genauso an wie Schmiedekunst. Angeln bleibt ein Sammelberuf: Es wird angezeigt und gefiltert, bestellt wird es aber im Sammeln-Tab, so wie Kräuter.",
    ["Leur montée suit aussi : la bourse d'artisan et le suivi à l'écran nomment ton prochain point de cuisine ou de secourisme exactement comme ils le font déjà pour un métier principal. Une exception est volontaire : voir quelqu'un cuisiner au feu de camp ne l'ajoute toujours pas à l'annuaire, une capitale l'enterrerait sous des gens qui ne sont pas vraiment cuisiniers. Un cuisinier qui a l'addon apparaît normalement, par ses propres niveaux de métier."] =
        "Das Hochleveln zieht mit: Der Handwerkerbeutel und die Verfolgung am Bildschirm nennen deinen nächsten Punkt in Kochkunst oder Erster Hilfe genauso wie bei einem Hauptberuf. Eine Ausnahme ist gewollt: Wer am Lagerfeuer kocht, landet weiterhin nicht im Verzeichnis, denn eine Hauptstadt würde es unter Leuten begraben, die gar keine echten Köche sind. Ein Koch mit dem Addon taucht ganz normal auf, über seine eigenen Berufsstufen.",
    -- v1.29.0
    ["Tes commandes à l'écran, et un journal pour les lire"] =
        "Deine Aufträge auf dem Bildschirm, und ein Journal zum Nachlesen",
    ["Les commandes que tu as acceptées s'affichent à l'écran, comme les quêtes suivies. L'objet que tu t'es engagé à faire, et dessous chaque réactif avec ce que tu as sur ce qu'il te faut : « Balle de soie 2/4 ». Quand le dernier tombe dans tes sacs, la ligne passe au blanc et la commande remonte en tête sous « Prêt à livrer ». Rien à ouvrir, rien à aller vérifier. Glisse n'importe quelle ligne pour déplacer le tout, /co track si tu n'en veux pas."] =
        "Die Aufträge, die du angenommen hast, stehen jetzt auf dem Bildschirm, so wie verfolgte Quests. Der Gegenstand, den du zugesagt hast, und darunter jedes Material mit dem, was du hast, gegen das, was du brauchst, etwa 'Ballen Seidenstoff 2/4'. Sobald das letzte in deine Taschen fällt, wird die Zeile weiß und der Auftrag steigt unter 'Lieferbereit' nach oben. Nichts zu öffnen, nichts nachzusehen. Ziehe eine beliebige Zeile, um das Ganze zu verschieben, /co track wenn du es lieber nicht möchtest.",
    ["Il suit aussi ta montée de métier. Pour chaque métier encore en progression, il nomme LA recette qui achète ton prochain point le moins cher, liste ses réactifs de la même façon, et te dit quel plan acheter et à qui quand la route la moins chère passe par un plan que tu n'as pas encore."] =
        "Es verfolgt auch deinen Berufsfortschritt. Für jeden Beruf, der noch steigt, nennt es genau das Rezept, das deinen nächsten Fertigkeitspunkt am günstigsten bringt, listet dessen Materialien genauso auf und sagt dir, welches Rezept du bei wem kaufen musst, wenn der günstigste Weg über eines führt, das dir noch fehlt.",
    ["Tu peux donner un nom et une histoire à une commande. Un second bouton à côté de Poster l'ouvre comme une fiche de quête sur parchemin, où tu écris un titre et quelques lignes. Les artisans qui la voient lisent « Le fardeau du forgeron » plutôt que « Heaume de thorium enchanté », avec ton texte dessous. C'est la même commande, elle se lit juste comme une quête."] =
        "Du kannst einem Auftrag einen Namen und eine Geschichte geben. Eine zweite Schaltfläche neben Posten öffnet ihn als Questbogen auf Pergament, wo du einen Titel und ein paar Zeilen schreibst. Die Handwerker lesen dann 'Die Last des Schmieds' statt 'Verzauberter Thoriumhelm', mit deinem Text darunter. Derselbe Auftrag, er liest sich nur wie eine Quest.",
    ["Et il y a un journal. /co journal ouvre une fenêtre parchemin où tes commandes et tes vraies quêtes partagent une seule liste, groupées par section et par zone, avec le texte complet de celle que tu cliques. Il lit le journal de quêtes du jeu sans y écrire, donc ta propre fenêtre de quête garde ce que tu avais sélectionné. Il montre aussi toutes les quêtes d'une zone d'un coup, là où le journal du jeu s'arrête à six."] =
        "Und es gibt ein Journal. /co journal öffnet ein Pergamentfenster, in dem deine Aufträge und deine echten Quests eine Liste teilen, nach Abschnitt und Gebiet gruppiert, mit dem vollen Text dessen, was du anklickst. Es liest das Questlog des Spiels, ohne hineinzuschreiben, dein eigenes Questfenster behält also seine Auswahl. Außerdem zeigt es alle Quests eines Gebiets auf einmal, wo das Log des Spiels bei sechs aufhört.",
    ["Un correctif de joaillerie au passage : un en-tête de taille comme « Endurance - Solide » disparaissait de la fenêtre métier quand tu ne connaissais qu'une seule gemme de cette taille, alors que l'onglet Commande l'affichait. Les deux vues classent pareil maintenant."] =
        "Eine Juwelenschleifer-Korrektur nebenbei. Eine Schliff-Überschrift wie 'Ausdauer - Solide' verschwand aus dem Berufsfenster, wenn du nur einen Edelstein dieses Schliffs kanntest, obwohl der Auftrag-Reiter sie zeigte. Beide Ansichten gruppieren jetzt gleich.",
    -- v1.28.0
    ["Le plan de route suit chaque point, et sait quand une recette est finie"] =
        "Die Aufstiegsroute bleibt am Ball und weiß, wann ein Rezept fertig ist",
    ["Le plan de route prenait du retard : tu gagnais un point et il gardait l'ancien plan jusqu'à ce qu'autre chose le réveille — pire en Enchantement, où le jeu ne donne jamais ton rang en direct à l'addon. Il suit maintenant chaque point à l'instant où tu le gagnes. Il sait aussi quand une recette passe grise : il lisait la couleur en direct à ton rang courant mais projetait les rangs suivants d'après les données, si bien qu'une recette que tu voyais grise était encore comptée, et conseillée, un rang plus loin. Grise, c'est fini : elle disparaît des étapes ET du total, pas seulement de la première ligne."] =
        "Die Aufstiegsroute hinkte hinterher: Du hast einen Punkt bekommen, und sie zeigte den alten Plan, bis etwas anderes sie anstieß — am schlimmsten bei Verzauberkunst, wo das Spiel dem Addon nie deinen aktuellen Skill direkt gibt. Sie folgt jetzt jedem Punkt, in dem Moment, in dem du ihn bekommst. Sie erkennt auch, wann ein Rezept grau wird: Sie las die Live-Farbe auf deinem aktuellen Rang, projizierte die folgenden Ränge aber aus den Daten, sodass ein Rezept, das du in deiner Liste grau sahst, einen Rang später noch mitgezählt und empfohlen wurde. Grau ist jetzt endgültig grau: Es verschwindet aus den Schritten UND der Summe, nicht nur aus der ersten Zeile.",
    ["La fenêtre de route a rattrapé la bourse d'artisan : une case pour inclure ou non les plans à acheter, un vrai en-tête avec l'icône du métier et ton rang, et un bandeau « Étapes » repliable pour que la liste de courses ne passe plus sous le bas de la fenêtre. Et au plafond entraîné, elle ne se contente plus de hausser les épaules : elle explique comment débloquer le palier suivant — l'entraîner chez ton formateur, ou acheter le livre de rang pour les Premiers soins — et pointe le PNJ où aller, filtré à ta faction."] =
        "Das Routenfenster hat zum Handwerksbeutel aufgeschlossen: ein Kästchen, um kaufbare Rezepte ein- oder auszublenden, eine richtige Kopfzeile mit dem Berufssymbol und deinem Rang, und ein einklappbares Band «Schritte», damit die Einkaufsliste nicht mehr unter den unteren Fensterrand rutscht. Und am antrainierten Höchstwert zuckt sie nicht mehr nur mit den Schultern: Sie erklärt, wie du die nächste Stufe freischaltest — beim Lehrer antrainieren oder für Erste Hilfe das Rangbuch kaufen — und weist dir den NSC, den du aufsuchen musst, gefiltert nach deiner Fraktion.",
    -- v1.27.2
    ["Un onglet Entrantes, et des demandes qui ne traînent plus"] =
        "Ein Reiter „Eingehend“, und Anfragen, die nicht mehr hängenbleiben",
    ["Les demandes captées dans /commerce et /guilde restaient affichées des heures. On en voyait encore une marquée « 20h » le lendemain, bien après que le demandeur ait trouvé quelqu'un d'autre. Elles disparaissent maintenant 30 minutes après avoir été vues, comme un cri dans /commerce. Celle que tu as acceptée, elle, tient six heures : tu t'es engagé dessus."] =
        "Aus /handel und /gilde aufgeschnappte Anfragen blieben stundenlang stehen. Eine zeigte am nächsten Tag noch „20h“, längst nachdem der Besteller jemand anderen gefunden hatte. Sie verschwinden jetzt 30 Minuten, nachdem sie gesehen wurden, so wie ein Ruf im Handelskanal. Eine angenommene bleibt sechs Stunden, du hast dich ja darauf festgelegt.",
    ["La fenêtre métier ne fait plus non plus semblant que tu peux les honorer : elle listait une demande de gemme dont tu n'as pas la recette, bouton Accepter compris, à 190 de compétence pour une taille qui en demande 350. Elle ne montre plus que ce que tu sais vraiment faire (revérifié en direct, donc une recette apprise la fait réapparaître). Ce qu'elle masque reste dans le Carnet pour le passer à un ami capable."] =
        "Das Berufsfenster tut auch nicht mehr so, als könntest du sie erfüllen: Es listete eine Anfrage nach einem Edelstein, dessen Rezept du nicht kennst, samt Annehmen-Knopf, bei Fertigkeit 190 für einen Schliff, der 350 braucht. Es zeigt jetzt nur noch, was du wirklich herstellen kannst (live geprüft, ein gelerntes Rezept bringt die Anfrage also zurück). Was es ausblendet, bleibt im Auftragsbuch, um es an einen fähigen Freund weiterzugeben.",
    ["Et ces demandes du chat ont leur propre onglet Entrantes, avec un compteur à côté. Une demande lue dans /commerce ou poussée par un pair n'a rien à voir avec une vraie commande de l'addon (pas de cycle accepter-livrer, tu réponds au chuchotement à la main) : les mélanger aux onglets Tous / Guilde / Amis / Annuaire embrouillait les deux. Corrigé aussi, une commande arrivée sans métier déclenchait son alerte mais n'apparaissait dans aucune fenêtre métier ; le métier est maintenant déduit de l'objet."] =
        "Und diese Chat-Anfragen bekommen einen eigenen Reiter „Eingehend“ mit einem Zähler daneben. Eine im Handelskanal gelesene oder von einem Mitspieler weitergereichte Anfrage hat nichts mit einem echten Addon-Auftrag zu tun (kein Annehmen-Liefern-Zyklus, du antwortest von Hand per Flüstern), sie in die Reiter Alle / Gilde / Freunde / Verzeichnis zu mischen verwischte beides. Ebenfalls behoben: Ein Auftrag, der ohne Beruf ankam, löste seine Meldung aus, tauchte aber in keinem Berufsfenster auf; der Beruf wird jetzt aus dem Gegenstand ermittelt.",
    -- v1.27.1
    ["Prêt pour le patch 1.15.9"] = "Bereit für Patch 1.15.9",
    ["Classic Era, SoD et Hardcore passent à la 1.15.9 et à sa nouvelle interface. L'addon a été vérifié contre elle et se déclare compatible : le badge [Dispo] au-dessus des plaques fonctionne comme avant. Seule limite, décidée par Blizzard : en instance, les plaques amies sont réservées au jeu lui-même, donc pas de badge en donjon."] =
        "Classic Era, SoD und Hardcore wechseln auf 1.15.9 und die neue Oberfläche. Das Addon wurde dagegen geprüft und meldet sich kompatibel, das [Sucht]-Abzeichen über den Namensplaketten funktioniert wie bisher. Eine Grenze, von Blizzard so entschieden: In Instanzen gehören freundliche Namensplaketten dem Spiel selbst, also kein Abzeichen im Dungeon.",
    ["Corrigé : la liste des PNJ sous une recette manquante (formateurs, vendeurs) mélangeait les deux factions, au point d'envoyer un personnage Alliance à Fossoyeuse. Les PNJ du camp d'en face sont maintenant masqués ; les monstres à butin et les PNJ neutres restent, eux servent tout le monde."] =
        "Behoben: Die NSC-Liste unter einem fehlenden Rezept (Lehrer, Händler) mischte beide Fraktionen, ein Allianz-Charakter konnte glatt nach Unterstadt geschickt werden. NSCs der Gegenseite werden jetzt ausgeblendet; Beute-Mobs und neutrale NSCs bleiben, die bedienen alle.",
    -- v1.27.0
    ["Prévenu quand une nouvelle version sort"] = "Sagt dir Bescheid, wenn eine neue Version da ist",
    ["L'addon repère maintenant qu'il tourne en retard. Il lit la version des joueurs que tu croises sur le réseau, et dès qu'il en voit une plus récente chez plusieurs personnes différentes, il te le dit d'une ligne dans le chat et pose un point rouge sur le bouton minimap. Le point s'efface tout seul une fois que tu as mis à jour."] =
        "Das Addon merkt jetzt, wenn du eine alte Version läufst. Es liest die Version der Spieler, denen du im Netzwerk begegnest, und sobald es eine neuere bei mehreren verschiedenen Leuten gesehen hat, sagt es dir per Chatzeile Bescheid und setzt einen roten Punkt auf den Minimap-Knopf. Der Punkt verschwindet von selbst, sobald du aktualisiert hast.",
    ["Ce « plusieurs personnes différentes » est voulu : un joueur isolé ne peut pas te faire croire que tu es en retard en annonçant un faux numéro, il faut que des joueurs distincts le confirment. Et ça ne te prévient qu'une fois par version, jamais à chaque connexion. Tape /co version pour voir ta version et s'il en existe une plus récente."] =
        "Das „mehrere verschiedene Leute\" ist Absicht: ein einzelner Spieler kann dir keine falsche Versionsnummer vorgaukeln, es braucht die Bestätigung durch getrennte Spieler. Und es meldet sich nur einmal pro Version, nicht bei jedem Login. Tippe /co version, um deine Version zu sehen und ob es eine neuere gibt.",
    -- v1.26.0
    ["Filtre n'importe quelle liste par la stat qu'elle donne"] =
        "Filtere jede Rezeptliste nach dem Wert, den sie gibt",
    ["Chaque liste de recettes — l'onglet Commande, la fenêtre métier, Mes artisans — reçoit un sélecteur de stat. Tu choisis Force, tu ne vois que ce qui donne de la Force : gemmes, équipements, élixirs. Le menu se remplit avec ce que le métier ouvert fabrique vraiment, donc la Cuisine ne te propose pas Puissance des sorts. Ces stats ne sont écrites nulle part, elles sont lues sur ton propre jeu — dans ta langue, et valables pour des objets que je n'ai jamais regardés, Wrath compris."] =
        "Jede Rezeptliste — der Auftrags-Reiter, das Berufsfenster, Meine Handwerker — bekommt einen Wert-Auswähler. Wähle Stärke und du siehst nur, was Stärke gibt: Edelsteine, Ausrüstung, Elixiere. Das Menü füllt sich mit dem, was der offene Beruf wirklich herstellt, Kochkunst bietet dir also keine Zaubermacht an. Diese Werte stehen nirgends geschrieben, sie werden von deinem Client gelesen, also in deiner Sprache und auch bei Gegenständen, die ich nie angesehen habe, Wrath inbegriffen.",
    ["L'alchimie se range mieux aussi : les élixirs se regroupent sous la stat qu'ils donnent, pendant que les potions de soin et de mana, les flacons et les transmutations gardent leurs propres en-têtes — « rend de la vie » n'a jamais été une stat. Sur TBC, ça sort 74 consommables du fourre-tout Divers."] =
        "Auch die Alchemie sortiert sich besser: Elixiere gruppieren sich nach dem Wert, den sie geben, während Heil- und Manatränke, Fläschchen und Transmutationen ihre eigenen Überschriften behalten — „stellt Leben wieder her“ war nie ein Wert. Auf TBC holt das 74 lose Verbrauchsgegenstände aus dem Sonstiges-Haufen.",
    -- v1.25.0
    ["Les gemmes se rangent par couleur, puis par ce qu'elles donnent"] =
        "Edelsteine sortieren sich nach Farbe und danach, was sie geben",
    ["La joaillerie versait toutes les gemmes taillées sous un seul en-tête « Gemme ». Elles se rangent maintenant par couleur de châsse, et sous chaque couleur par la stat qu'elles donnent : « Force - Audacieux », « Endurance - Solide ». Cette stat n'est pas une table écrite à la main, elle est lue sur ton propre jeu — donc dans ta langue, et valable pour des gemmes que je n'ai jamais regardées."] =
        "Juwelenschleifen warf alle geschliffenen Steine unter eine einzige Überschrift „Edelstein“. Die Steine stehen jetzt unter ihrer Sockelfarbe und darunter nach dem Wert, den sie geben, also „Stärke - Kühn“ oder „Ausdauer - Massiv“. Dieser Wert ist keine von Hand getippte Tabelle, er wird direkt von deinem Client gelesen, deshalb erscheint er in deiner Sprache und funktioniert auch bei Steinen, die ich nie angesehen habe.",
    ["Les gemmes méta, elles, reviennent à une simple liste : chaque taille de méta n'existe qu'en un seul exemplaire, un en-tête au-dessus n'aurait fait que répéter la ligne. Bagues, colliers, statues et figurines gardent le classement qu'ils avaient."] =
        "Meta-Steine bekommen stattdessen eine schlichte Liste. Jeden Meta-Schliff gibt es nur ein einziges Mal, eine Überschrift darüber hätte also nur die Zeile darunter wiederholt. Ringe, Halsketten, Statuen und Figuren werden weiter wie bisher sortiert.",
    ["Corrigé aussi : quand un enchanteur te demandait une pièce, l'invite ne s'affichait parfois jamais. Une première demande arrivée trop tôt, avant que tu aies équipé la pièce, armait quand même le délai de cinq secondes — et la vraie demande qui suivait passait à la trappe. Le délai ne démarre plus que sur une demande réellement affichée."] =
        "Ebenfalls behoben: Wenn ein Verzauberer dich um ein Ausrüstungsteil bat, erschien die Abfrage manchmal gar nicht. Eine erste Anfrage, die zu früh eintraf, bevor du das Teil angelegt hattest, setzte trotzdem die Sperre von fünf Sekunden, und die eigentliche Anfrage danach ging verloren. Die Sperre startet jetzt erst, wenn eine Anfrage wirklich durchgekommen ist.",
    -- v1.24.2
    ["Les stats d'enchant parlent enfin ta langue"] =
        "Verzauberungs-Werte sprechen endlich deine Sprache",
    ["Les sous-catégories de la vue enchant (Force, Esprit, Croisé…) venaient d'un libellé interne jamais traduit : tout le monde les voyait en anglais, client français compris. Elles sont maintenant lues directement sur ton jeu, comme les noms de sorts, donc dans ta langue sans rien à traduire à la main à chaque nouvelle recette."] =
        "Die Unterkategorien der Verzauberungsansicht (Stärke, Willenskraft, Kreuzritter …) stammten aus einer internen Bezeichnung, die nie übersetzt wurde: alle sahen sie auf Englisch, auch auf dem französischen Client. Sie werden jetzt direkt von deinem Client gelesen, genau wie Zaubernamen, also in deiner eigenen Sprache, ohne dass bei jedem neuen Verzauberungsrezept von Hand übersetzt werden muss.",
    -- v1.24.1
    ["Deux minerais de plus dans les commandes de récolte"] =
        "Zwei weitere Erze bei Sammelaufträgen",
    ["Le khorium et l'éternium n'apparaissaient pas comme commandables dans l'onglet Récolte. La liste des minerais était dérivée de ceux qu'on peut prospecter en gemmes, et ni l'un ni l'autre ne l'est — le même trou qui cachait déjà l'argent, l'or, le vrai-argent et le sombrefer. Les deux rejoignent la liste."] =
        "Khorium- und Eterniumerz erschienen im Sammeln-Tab nicht als bestellbar. Die Erzliste wurde aus dem abgeleitet, was sich zu Edelsteinen aufbereiten lässt, und keins von beiden lässt sich das — dieselbe Lücke, die schon Silber, Gold, Echtsilber und Dunkeleisen versteckt hatte. Beide sind jetzt Teil der Liste.",
    -- v1.24.0
    ["La pièce à enchanter se pose d'un clic, et une bourse qui suit la progression"] =
        "Das zu verzaubernde Teil legt sich mit einem Klick ein, und ein Beutel, der Schritt hält",
    ["Depuis la v1.21.0, un enchanteur peut cliquer un emplacement de la silhouette d'échange pour te demander la pièce à enchanter. Si tu as l'addon toi aussi, ce clic affiche maintenant une invite chez toi : accepte, et ta pièce équipée se pose toute seule dans l'emplacement « ne sera pas échangé ». Rien n'est donné (cet emplacement ne peut pas changer de mains), la pose est verrouillée sur lui, et rien ne bouge sans ton clic. Sans l'addon en face, le chuchotement explicatif part comme avant."] =
        "Seit v1.21.0 kann ein Verzauberer einen Platz der Handels-Silhouette anklicken, um dich um das zu verzaubernde Teil zu bitten. Wenn du das Addon ebenfalls nutzt, zeigt dieser Klick jetzt bei dir eine Anfrage an: Bestätige, und dein angelegtes Teil legt sich von selbst in den Platz „Wird nicht gehandelt“. Nichts wird hergegeben (dieser Platz kann den Besitzer nicht wechseln), das Einlegen ist fest auf ihn beschränkt, und ohne deinen Klick bewegt sich nichts. Ohne Addon auf der Gegenseite geht der erklärende Flüsterton wie bisher raus.",
    ["La bourse d'artisan se met à jour en direct : fenêtre ouverte, chaque point de métier gagné par le personnage suivi (et chaque recette apprise) recalcule la liste de courses — plus besoin de la rouvrir pour voir la route changer."] =
        "Der Handwerkerbeutel aktualisiert sich jetzt live: Bei offenem Fenster berechnet jeder Fertigkeitspunkt des verfolgten Charakters (und jedes gelernte Rezept) die Einkaufsliste neu — kein erneutes Öffnen mehr nötig, um die Route sich ändern zu sehen.",
    -- v1.23.0
    ["La bourse d'artisan : la liste de courses de tes guildeux, et deux corrections réseau"] =
        "Der Handwerkerbeutel: eine Einkaufsliste für deine Gildenmitglieder, und zwei Netzwerkkorrekturen",
    ["L'onglet Artisans gagne un bouton sac après les icônes de métier de chaque fiche : un clic ouvre la liste de courses des matériaux qu'il te faut pour monter tes métiers, calculée en local à partir de ce que le jeu diffuse déjà (aucun nouveau trafic réseau). Les réactifs que ton propre métier sait fabriquer sont décomposés en composants de base, et les objets vendus par un PNJ sont mis de côté dans une note plutôt que d'encombrer la grille."] =
        "Der Reiter Handwerker bekommt nach den Berufssymbolen jedes Eintrags eine Beutel-Schaltfläche: ein Klick öffnet die Einkaufsliste der Materialien, die diese Person zum Weiterlernen braucht, lokal berechnet aus dem, was das Spiel ohnehin schon überträgt (kein neuer Netzwerkverkehr). Reagenzien, die der eigene Beruf selbst günstiger herstellen kann, werden in Grundkomponenten zerlegt, und Verkäufer-Gegenstände werden als schlichte Notiz ausgelagert, statt das Raster zu überladen.",
    ["Coche « inclure les plans à acheter » et les recettes derrière un coût rejoignent la liste : les plans-objets comme fourniture à apporter, les plans de formateur comme simple note. Le même bloc de fournitures s'affiche maintenant sous le plan de route « quoi monter ensuite », avec le PNJ où aller (nom, zone, coordonnées) et une épingle TomTom cliquable si tu l'as installé."] =
        "Aktiviere „Rezepte zum Kaufen einbeziehen\" und Rezepte hinter einem Goldpreis kommen ebenfalls auf die Liste: kaufbare Rezeptgegenstände als mitzubringende Zutat, Lehrmeister-Rezepte als bloße Notiz. Derselbe Materialblock erscheint jetzt auch unter der Routenplanung „was als Nächstes lernen\", mit dem aufzusuchenden Händler (Name, Zone, Koordinaten) und einer anklickbaren TomTom-Nadel, falls installiert.",
    ["Une recette sans réactif au prix connu (la poussière d'enchantement, par exemple) ne fait plus sauter tout un tronçon du plan de route : elle sert maintenant de repli marqué « ? » quand rien de mieux n'est disponible. Une table de désenchantement maison alimente aussi l'infobulle des poussières, essences et éclats affichés dans ces listes."] =
        "Ein Rezept ohne bepreiste Zutat (meist Verzauberungsstaub) wirft nun keinen ganzen Streckenabschnitt mehr aus der Route: es dient jetzt als mit „?\" markierter Notbehelf, wenn nichts Besseres verfügbar ist. Eine kuratierte Entzauberungstabelle liefert außerdem den Tooltip für Staub, Essenzen und Splitter in diesen Listen.",
    ["Deux corrections : un compte à plusieurs personnages se voyait parfois lister lui-même comme « joignable via » son autre perso dans son propre onglet Artisans, corrigé. Et le plan de route pouvait s'arrêter avant le vrai plafond de compétence après une formation chez le maître, à cause d'une assignation Lua qui perdait silencieusement sa seconde valeur."] =
        "Zwei Korrekturen: ein Konto mit mehreren Charakteren sah sich im eigenen Handwerker-Reiter manchmal selbst als „erreichbar über\" den eigenen Zweitcharakter gelistet, behoben. Und die Routenplanung konnte kurz vor der tatsächlichen Fertigkeitsobergrenze nach einer Lehrmeister-Beförderung stehen bleiben, weil eine Lua-Mehrfachzuweisung stillschweigend ihren zweiten Rückgabewert verlor.",
    -- v1.22.1
    ["Les alertes de commande vérifient enfin le métier, et un plan de route qui suit son propre badge"] =
        "Bestellbenachrichtigungen, die wirklich den Beruf prüfen, und eine Routenplanung im Einklang mit dem Abzeichen",
    ["Une commande à portée large (guilde, amis, tous) déclenchait un toast même chez un joueur sans le métier, du moment qu'elle arrivait par le relais de connexion (chuchotement) plutôt que par le canal : le filtre par métier ne couvrait que le canal. Il s'applique maintenant quel que soit le chemin réseau. Le toast gagne aussi un troisième texte : une commande à portée large n'affiche plus « pour TOI », ce qui donnait l'impression fausse d'une demande personnelle."] =
        "Eine breite Bestellung (Gilde, Freunde, alle) löste einen Hinweis auch bei Spielern aus, die den Beruf gar nicht hatten, sofern sie über die Login-Weiterleitung (ein Flüstern) statt über den Kanal ankam: der Berufsfilter galt bisher nur für den Kanal. Er gilt jetzt unabhängig vom Übertragungsweg. Der Hinweis bekommt außerdem einen dritten Text: eine breite Bestellung zeigt nicht mehr „für DICH\", was wie eine persönliche Anfrage wirkte, obwohl sie keine war.",
    ["Le plan de route « quoi monter ensuite » pouvait suggérer une recette différente du badge de coût de la liste, les deux lisant des données légèrement différentes. Le plan utilise maintenant la difficulté réelle de la fenêtre métier à ton rang actuel plutôt qu'une projection, et se rafraîchit au même rythme que le badge. La commande |cFFFFFFFF/co lvldump|r affiche le détail en cas de nouveau désaccord."] =
        "Die Routenplanung „was als Nächstes lernen\" konnte ein anderes Rezept vorschlagen als das Kosten-Abzeichen der Liste, weil beide leicht unterschiedliche Daten lasen. Die Route nutzt jetzt den tatsächlichen Schwierigkeitsgrad des Berufsfensters auf deinem aktuellen Rang statt einer Schätzung, und aktualisiert sich im selben Takt wie das Abzeichen. |cFFFFFFFF/co lvldump|r zeigt die Details bei einer erneuten Abweichung.",
    -- (clés v1.22.0 retirées à la v1.48.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.21.0 retirées à la v1.47.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.20.0 retirées à la v1.46.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.19.1 et v1.19.0 retirées à la v1.45.0 : versions sorties de la fenêtre glissante de l'onglet)
    -- (clés v1.18.0 et v1.17.1 retirées à la v1.44.2 : versions sorties de la fenêtre glissante de l'onglet)
    -- (clés v1.17.0 retirées à la v1.44.1 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.8.0/v1.7.0/v1.7.1/v1.6.0/v1.5.0/v1.4.0 retirées : ces versions ne sont plus listées dans l'onglet Nouveautés)
    -- (clés v1.13.0 retirées à la v1.41.1 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.12.1 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    -- (clés v1.12.0, v1.11.0 et v1.10.2 retirées à la v1.41.0 : versions sorties de la fenêtre glissante de l'onglet)
    -- (clés v1.16.0 retirées à la v1.44.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.15.1 retirées à la v1.43.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.15.0 retirées à la v1.42.1 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.14.0 retirées à la v1.42.0 : version sortie de la fenêtre glissante de l'onglet)
    -- (clés v1.9.0 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    ["VU"] = "GESEHEN",
    ["vu crafter (sans l'addon)"] = "beim Herstellen gesehen (ohne Addon)",
    ["vu crafter"] = "beim Herstellen gesehen",
    ["%d+ · vu crafter"] = "%d+ · beim Herstellen gesehen",
    -- Cooldowns de recettes (transmutations & co)
    ["%s : prête"] = "%s: bereit",
    ["%s : dans %s"] = "%s: in %s",
    ["(estimé)"] = "(geschätzt)",
    ["Transmutation"] = "Transmutation",
    ["%dj"] = "%dT", ["%dh"] = "%dh", ["%dmin"] = "%dMin",
    -- Relais partenaire
    ["via %s · il y a %s"] = "via %s · vor %s",
    ["RELAIS"] = "RELAIS",
    -- Rerolls (identité joueur multi-persos, /co alts — opt-in)
    ["rerolls : ACTIVÉS — ta liste de persos est annoncée au réseau."] =
        "Twinks: AKTIVIERT — deine Charakterliste wird im Netzwerk angekündigt.",
    ["rerolls : désactivés — rien n'est annoncé (opt-in : /co alts on)."] =
        "Twinks: deaktiviert — nichts wird angekündigt (Opt-in: /co alts on).",
    ["perso principal (vitrine) : %s"] = "Hauptcharakter (Aushängeschild): %s",
    ["persos du compte (%s) : %s"] = "Charaktere des Accounts (%s): %s",
    ["le lien n'est vérifié chez les autres qu'après une connexion de CHAQUE perso (addon actif)."] =
        "Andere bestätigen die Verknüpfung erst, wenn sich JEDER Charakter einmal eingeloggt hat (Addon aktiv).",
    ["rerolls activés — perso principal : %s (changer : /co alts main <nom>)"] =
        "Twinks aktiviert — Hauptcharakter: %s (ändern: /co alts main <Name>)",
    ["rerolls désactivés — dissolution annoncée au réseau."] =
        "Twinks deaktiviert — Auflösung im Netzwerk angekündigt.",
    ["perso inconnu sur ce compte : %s (connecte-le une fois avec l'addon)"] =
        "Unbekannter Charakter auf diesem Account: %s (einmal mit dem Addon einloggen)",
    ["regrouper tes rerolls (opt-in) : liste annoncée, commandes routées vers ton perso connecté"] =
        "Twinks gruppieren (Opt-in): Liste angekündigt, Aufträge zu deinem Online-Charakter geleitet",
    ["commande nommée pour %s : connecte ce perso, ou active /co alts on pour accepter d'ici."] =
        "Auftrag benannt für %s: logge diesen Charakter ein oder aktiviere /co alts on, um von hier anzunehmen.",
    ["|cFFFFCC00commande pour ton reroll %s|r de |cFFFFFFFF%s|r : %s%s%s"] =
        "|cFFFFCC00Auftrag für deinen Twink %s|r von |cFFFFFFFF%s|r: %s%s%s",
    ["En ligne via %s"] = "Online über %s",
    ["reroll : %s (%s)"] = "Twink: %s (%s)",
    -- v1.31.0
    ["Les cercles d'artisans, posés sur les communautés WoW"] =
        "Handwerkerkreise, auf WoW-Gemeinschaften aufgebaut",
    ["Le canal du royaume n'a ni mémoire ni liste de membres : qui n'était pas connecté quand tu as posté n'a rien vu, et chaque session recommence à chercher qui est là. Une communauté WoW répond aux deux. Marque-la avec /co circle et ses membres apparaissent sous « Cercle » dans l'onglet Artisans, avec leur présence, y compris ceux qui sont hors ligne. C'est toi qui crées la communauté et qui invites : un cercle est un petit groupe que tu as choisi, pas le royaume entier."] =
        "Der Realmkanal hat kein Gedächtnis und keine Mitgliederliste: Wer nicht eingeloggt war, als du gepostet hast, hat nichts gesehen, und jede Sitzung fängt wieder von vorn an. Eine WoW-Gemeinschaft löst beides. Markiere sie mit /co circle, und ihre Mitglieder erscheinen unter « Kreis » im Reiter Handwerker, mit ihrer Anwesenheit, auch die gerade offline sind. Du erstellst die Gemeinschaft und lädst ein, wen du willst: ein Kreis ist eine kleine Gruppe deiner Wahl, nicht der ganze Realm.",
    ["Rien n'est posté dans la communauté et rien n'en est lu. Ce qu'une communauté peut réellement porter a été mesuré avant qu'on s'appuie dessus, et c'est étroit : le texte d'un message de club est illisible depuis un addon, et un message addon envoyé sur son canal est accepté puis jeté. Le cercle te donne donc la liste et qui est en ligne ; les commandes et les niveaux de métier continuent de circuler exactement comme avant."] =
        "In die Gemeinschaft wird nichts gepostet und aus ihr nichts gelesen. Was eine Gemeinschaft wirklich tragen kann, wurde gemessen, bevor darauf gebaut wurde, und es ist wenig: der Text einer Klubnachricht ist von einem Addon aus nicht lesbar, und eine Addon-Nachricht an ihren Kanal wird angenommen und dann verworfen. Der Kreis liefert also die Liste und wer online ist; Aufträge und Berufsstufen laufen genau wie bisher.",
    ["Les métiers ne viennent pas non plus de la communauté : ces champs-là ne sont remplis que pour un roster de guilde. Un membre de cercle affiche ses métiers quand il répond à l'addon, comme tout le monde."] =
        "Die Berufe kommen ebenfalls nicht aus der Gemeinschaft: diese Felder werden nur für Gildenlisten gefüllt. Ein Kreismitglied zeigt seine Berufe, sobald es dem Addon antwortet, wie alle anderen auch.",
    -- v1.31.1
    ["Les nouveaux venus apparaissent tout seuls"] =
        "Neuzugänge tauchen von selbst auf",
    ["Quelqu'un qui venait d'installer l'addon restait invisible tant qu'il ne cliquait pas « Rafraîchir l'annuaire » — ce que personne ne pense à faire devant un annuaire qui a l'air vide, et avoir l'air vide était justement le problème."] =
        "Wer das Addon gerade erst installiert hatte, blieb unsichtbar, bis er auf « Verzeichnis aktualisieren » klickte — worauf niemand kommt, wenn das Verzeichnis leer aussieht, und genau das leere Aussehen war das Problem.",
    ["À la connexion, l'addon ne s'annonçait que sur le canal caché du royaume, le moins fiable de ses moyens d'atteindre les autres. L'annonce qui touche vraiment les inconnus n'a le droit de partir que juste après un clic ou une touche : à la connexion il n'y avait donc aucun moment pour l'envoyer, et elle était jetée au lieu d'être gardée. Elle attend maintenant, et part à ton premier clic ou ta première touche — quelques secondes, sans que tu fasses quoi que ce soit. La connexion sonde aussi directement les joueurs autour de toi, ce que le bouton « Rafraîchir » faisait déjà et pas elle."] =
        "Beim Anmelden kündigte dich das Addon nur im versteckten Realm-Kanal an, dem unzuverlässigsten seiner Wege, andere zu erreichen. Die Ankündigung, die Fremde wirklich erreicht, darf nur direkt nach einem Klick oder Tastendruck raus: beim Anmelden gab es also keinen Moment dafür, und sie wurde verworfen statt aufgehoben. Jetzt wartet sie und geht bei deinem ersten Klick oder Tastendruck raus — ein paar Sekunden, ohne dass du etwas tust. Beim Anmelden werden außerdem die Spieler um dich herum direkt angepingt, was der Aktualisieren-Knopf schon tat und das Anmelden nicht.",
    -- v1.32.0
    ["Forever lit enfin tes métiers et tes recettes"] =
        "Forever liest endlich deine Berufe und Rezepte",
    ["Sur WoW: Forever, l'addon ne voyait pas tes métiers : Forever tourne sur l'API du jeu moderne, et les fonctions qui lisaient tes compétences n'y existent pas. Rien ne plantait. L'annuaire t'annonçait simplement sans aucun métier, le clic droit disait que tu n'en avais pas, et « Mes artisans » restait vide. Tes recettes connues et leurs temps de recharge avaient le même problème. Tout est lu à la manière de Forever maintenant."] =
        "Auf WoW: Forever konnte das Addon deine Berufe nicht sehen. Forever läuft mit der API des modernen Spiels, und die Funktionen, die deine Fertigkeiten lasen, gibt es dort nicht. Es gab keinen Fehler. Das Verzeichnis kündigte dich einfach ohne Berufe an, der Rechtsklick behauptete, du hättest keine, und „Meine Handwerker“ blieb leer. Deine bekannten Rezepte und ihre Abklingzeiten hatten dasselbe Problem. Jetzt wird alles auf die Forever-Art gelesen.",
    ["Quand quelqu'un te cible dans l'onglet Commande, il voit ce que tu sais vraiment faire, plus une estimation. Et l'estimation elle-même était trop généreuse : une recette sans niveau connu comptait comme atteignable, si bien qu'un couturier niveau 13 se voyait proposer des pièces Stormcloth qui demandent le niveau 40. Un niveau inconnu veut dire « pas proposé » désormais."] =
        "Wenn dich jemand im Tab „Bestellen“ auswählt, sieht er, was du wirklich kannst, keine Schätzung mehr. Und die Schätzung war ohnehin zu großzügig: Ein Rezept ohne bekannte Stufe galt als erreichbar, sodass einem Schneider auf Stufe 13 Stormcloth-Teile angeboten wurden, die Stufe 40 verlangen. Unbekannt heißt jetzt: wird nicht angeboten.",
    ["La liste des recettes est celle de Forever : 2512 recettes tirées des pages Forever de Wowhead, au lieu des 1230 de vanilla. Forever a déplacé des choses, et les potions de soin sont maintenant en Secourisme, plus en Alchimie."] =
        "Die Rezeptliste ist die von Forever: 2512 Rezepte aus den Forever-Seiten von Wowhead statt der 1230 von Vanilla. Forever hat einiges verschoben, die Heiltränke stehen jetzt unter Erste Hilfe statt unter Alchemie.",
    ["Sur Forever, le clic droit sur le bouton de la minimap ouvre la fenêtre des métiers du jeu. Les métiers de tes rerolls se consultent désormais depuis « Mes artisans » (clic droit sur un métier). /co mute accepte les noms en prénom et nom, entre guillemets si l'addon n'a pas encore croisé le joueur."] =
        "Auf Forever öffnet ein Rechtsklick auf den Minimap-Button das Berufsfenster des Spiels. Die Berufe deiner Twinks findest du jetzt unter „Meine Handwerker“ (Rechtsklick auf einen Beruf). /co mute nimmt Vor- und Nachnamen an, in Anführungszeichen, wenn das Addon den Spieler noch nicht kennt.",
    -- v1.32.1
    ["La fenêtre de métier de Forever cesse de se plaindre"] =
        "Das Berufsfenster von Forever beschwert sich nicht mehr",
    ["Sur WoW: Forever, la colonne des commandes s'invite dans la fenêtre de métier du jeu. Elle y est l'hôte d'un cadre que le jeu protège, et presque tout ce qu'elle y faisait était refusé dès que tu étais en combat : ouvrir ou fermer la fenêtre pendant un combat déclenchait une volée d'erreurs « action bloquée », avec l'addon nommé au passage. La colonne ne touche plus au cadre pendant le combat, et reprend sa place à la fin."] =
        "Auf WoW: Forever sitzt die Auftragsspalte im Berufsfenster des Spiels. Sie ist dort Gast in einem geschützten Rahmen, und fast alles, was sie darin tat, wurde im Kampf verweigert. Das Fenster mitten im Kampf zu öffnen oder zu schließen warf eine Flut von Fehlern über blockierte Aktionen, mit dem Addon jedes Mal namentlich genannt. Im Kampf rührt die Spalte den Rahmen nicht mehr an und nimmt danach ihren Platz wieder ein.",
    ["Elle s'affiche aussi quand il faut. Il fallait deux passages : la fenêtre s'ouvre sur la page d'ensemble, où il n'y a aucun métier courant et donc rien à lister, si bien que la première visite semblait vide. Elle apparaît maintenant dès que tu es sur un métier, du premier coup."] =
        "Sie erscheint jetzt auch dann, wenn sie soll. Bisher brauchte es zwei Anläufe: Das Fenster öffnet auf der Übersichtsseite, wo es keinen aktuellen Beruf und also nichts aufzulisten gibt, weshalb der erste Besuch leer wirkte. Nun erscheint sie beim ersten Mal, sobald du auf einem Beruf bist.",
    ["Le reste : on ne peut plus la sortir de la fenêtre en la tirant, sa place appartient à son hôte ; les onglets de métier de Blizzard ne recouvrent plus son dernier onglet ; /co prof cuisine ouvre la Cuisine au lieu de la page d'ensemble ; et l'aide contextuelle n'entoure plus que ce qui est réellement affiché."] =
        "Der Rest: Sie lässt sich nicht mehr aus dem Fenster ziehen, ihr Platz gehört ihrem Gastgeber; die Berufsreiter von Blizzard verdecken ihren letzten Reiter nicht mehr; /co prof kochkunst öffnet die Kochkunst statt der Übersichtsseite; und die Hilfe umrahmt nur noch das, was wirklich zu sehen ist.",
    -- v1.32.2
    ["Tes barres d'action ne se bloquent plus en combat"] =
        "Deine Aktionsleisten werden im Kampf nicht mehr blockiert",
    ["Sur WoW: Forever, passer d'un onglet à l'autre dans la fenêtre de métier pendant un combat faisait refuser au jeu tout geste sur tes barres d'action, avec l'addon nommé à chaque fois. La fenêtre de métier n'y était pour rien. Deux petites pièces de l'addon l'étaient : ses menus déroulants et son aide « i » empruntaient des systèmes que le jeu partage avec sa propre interface, et s'en servir une seule fois suffisait à marquer cette interface à notre nom jusqu'au prochain rechargement. Les deux sont faits maison maintenant : même rendu, et le jeu n'a plus rien à redire."] =
        "Auf WoW: Forever hat ein Tabwechsel im Berufsfenster während eines Kampfes das Spiel dazu gebracht, jede Änderung an deinen Aktionsleisten zu verweigern, und jedes Mal wurde das Addon genannt. Am Berufsfenster lag es nicht. Schuld waren zwei kleine Teile des Addons: Seine Aufklappmenüs und seine Hilfe hinter dem i-Knopf nutzten Systeme, die das Spiel mit seiner eigenen Oberfläche teilt, und sie ein einziges Mal zu benutzen reichte, um diese Oberfläche bis zum nächsten Neuladen als unsere zu markieren. Beide sind jetzt Eigenbau: Sie sehen gleich aus, und das Spiel hat nichts mehr einzuwenden.",
    ["La colonne des commandes peut aussi se poser à côté de la fenêtre de métier plutôt que dedans : /co accole passe d'un mode à l'autre. Dedans reste le mode par défaut."] =
        "Die Auftragsspalte kann jetzt auch neben dem Berufsfenster stehen statt darin: /co accole wechselt zwischen beiden. Darin bleibt die Standardeinstellung.",
    ["Petites retouches : une longue liste de stats ne sort plus par le bas de l'écran, et chaque liste prend la largeur de sa plus longue entrée ; la liste des canaux de la fenêtre de partage des composants s'ouvre au-dessus d'elle et non plus dessous ; et l'aide suit la fenêtre si le jeu la déplace pendant qu'elle est ouverte."] =
        "Kleinere Korrekturen: Eine lange Werteliste läuft nicht mehr unten aus dem Bildschirm, und jede Liste ist so breit wie ihr längster Eintrag; die Kanalliste im Fenster zum Teilen der Reagenzien öffnet sich über diesem Fenster statt dahinter; und die Hilfe folgt dem Fenster, wenn das Spiel es verschiebt, während sie offen ist.",
    -- v1.33.0
    ["D'où vient une recette, sans MTSL"] = "Woher ein Rezept kommt, ohne MTSL",
    ["L'addon ne réclame plus MTSL. Sa base décrit Vanilla et TBC, or Forever a refait les tables d'objets dessous : 894 objets-recette qui n'existent que là, 173 disparus de Classic, et 24 identifiants communs qui désignent aujourd'hui un tout autre objet. Un annuaire périmé est pire qu'un annuaire absent, parce qu'il répond avec assurance. Les sources de recettes viennent maintenant de nos propres données, tirées des pages Forever de Wowhead."] =
        "Das Addon verlangt MTSL nicht mehr. Dessen Datenbank beschreibt Vanilla und TBC, doch Forever hat die Gegenstandstabellen darunter neu gebaut: 894 Rezeptgegenstände, die es nur dort gibt, 173 aus Classic, die verschwunden sind, und 24 gemeinsame IDs, die heute einen völlig anderen Gegenstand bezeichnen. Ein veraltetes Verzeichnis ist schlimmer als gar keines, weil es mit Überzeugung antwortet. Die Rezeptquellen stammen jetzt aus unseren eigenen Daten, erzeugt aus Wowheads Forever-Seiten.",
    ["Survole une recette que tu n'as pas apprise : elle te dit si le plan tombe en butin, s'il se vend ou s'il vient d'une quête, et elle nomme le PNJ et la zone quand elle les connaît. Sur Forever, le jeu le dit mieux que nous : sa formulation l'emporte dès qu'il en a une. Une recette de formateur est une déduction et non un fait, alors elle porte un « ? » plutôt que de faire semblant."] =
        "Fahre über ein Rezept, das du nicht gelernt hast: Es sagt dir, ob der Plan als Beute fällt, verkauft wird oder aus einer Quest stammt, und nennt NSC und Zone, wenn es sie kennt. Auf Forever sagt es das Spiel besser als wir, also gewinnt seine Formulierung, sobald es eine hat. Ein Lehrerrezept ist eine Schlussfolgerung und keine Tatsache, deshalb trägt es ein Fragezeichen, statt so zu tun als ob.",
    ["Le Plan de route remarche sur Forever, chiffré sur ton dernier scan Auctionator (Lazy Gold reste sur l'Era). Et la colonne des commandes change de contenu au lieu d'ouvrir des fenêtres par-dessus elle : trois onglets en haut, Commandes, Plan de route et Manquantes. Manquantes liste toutes les recettes que tu n'as pas apprises avec le rang qu'elles demandent, grisées tant que tu ne peux pas les prendre."] =
        "Die Aufstiegsroute funktioniert auf Forever wieder, berechnet aus deinem letzten Auctionator-Scan (Lazy Gold bleibt für Era). Und die Auftragsspalte wechselt ihren Inhalt, statt Fenster über sich zu öffnen: drei Reiter oben, Aufträge, Aufstiegsroute und Fehlende. Fehlende listet jedes Rezept, das du nicht gelernt hast, mit der nötigen Stufe, ausgegraut bis du es nehmen kannst.",
    ["Corrections : sur Forever la colonne comptait comme connues des recettes non apprises, et la route, les badges et ce que les autres artisans voyaient de toi reposaient là-dessus ; les prix sortaient vides ; la carte d'une commande sélectionnée était dessinée pour une fenêtre moitié plus large que la colonne, donc sa croix, son prix et le bord droit du panneau des composants étaient coupés ; une commande d'enchantement affichait « ? » au lieu de son nom."] =
        "Korrekturen: Auf Forever zählte die Spalte nicht gelernte Rezepte als gelernt, und Route, Abzeichen und das, was andere Handwerker von dir sahen, bauten darauf auf; Preise blieben leer; die Karte eines ausgewählten Auftrags war für ein Fenster gezeichnet, das deutlich breiter ist als die Spalte, sodass Schließkreuz, Preis und der rechte Rand der Komponentenliste abgeschnitten waren; ein Verzauberungsauftrag zeigte ein Fragezeichen statt seines Namens.",
    ["L'onglet Manquantes te dit enfin où aller"] =
        "Der Reiter „Fehlend\" sagt dir endlich, wohin",
    ["Survoler une recette que tu n'as pas te donnait son nom et son rang, c'est-à-dire ce que la ligne affichait déjà. Tu as maintenant l'infobulle de l'objet lui-même, puis ce qu'il te manque en points de métier, si la recette rapporte encore quelque chose à ton rang, et d'où vient le plan."] =
        "Ein Rezept, das du nicht kennst, zeigte dir beim Überfahren nur Namen und Rang, also genau das, was in der Zeile schon stand. Jetzt kommt zuerst der Gegenstands-Tooltip des Spiels, darunter wie viele Punkte dir fehlen, ob das Rezept auf deinem Rang noch einen Punkt bringt, und woher der Plan stammt.",
    ["Ce dernier point a beaucoup changé. L'addon connaissait un seul nom par plan et rien de son camp : « Recipe: Gingerbread Cookie » envoyait tout le monde chez Wulmort Jinglepocket, à Forgefer, Horde comprise. 1565 recettes nomment quelqu'un contre 337 avant, le marchand affiché est de ta faction, 719 donnent le prix réel du marchand sans aucun addon de prix, et 846 PNJ ont des coordonnées : un clic pose un repère, ce qui ne marchait plus depuis MTSL."] =
        "Genau dieser letzte Teil ist deutlich besser geworden. Das Addon kannte einen Namen pro Plan und nichts über dessen Fraktion, also schickte „Recipe: Gingerbread Cookie\" alle zu Wulmort Jinglepocket nach Eisenschmiede, Horde inklusive. 1565 Rezepte nennen jetzt jemanden statt 337, der gezeigte Händler gehört zu deiner Fraktion, 719 nennen den echten Händlerpreis ganz ohne Preis-Addon, und 846 NSCs haben Koordinaten: ein Klick setzt einen Wegpunkt, was seit MTSL nicht mehr ging.",
    ["Les formateurs. Aucune page ne dit « ça s'apprend au formateur » : l'addon le déduisait de l'absence d'objet-recette et affichait un point d'interrogation, sur 788 recettes. Wowhead le publie en fait sur la page du sort et pas celle de l'objet, ce qui en a nommé 398. Et quand tu parles à un formateur de métier, l'addon note ce qu'il enseigne et où il se tient : le point d'interrogation disparaît et tu récupères ses coordonnées. Si ta fenêtre de formateur filtre ce qu'elle affiche, il te le dit au lieu de n'en moissonner qu'un tiers en silence."] =
        "Und die Lehrer. Keine Seite sagt „das lernt man beim Lehrer\": das Addon schloss es aus dem Fehlen eines Rezeptgegenstands und zeigte ein Fragezeichen, bei 788 Rezepten. Wowhead verrät es doch, auf der Zauber- statt der Gegenstandsseite, was 398 davon einen Namen gab. Und wenn du mit einem Berufslehrer sprichst, notiert das Addon, was er lehrt und wo er steht: das Fragezeichen verschwindet und du bekommst seine Koordinaten. Filtert dein Lehrerfenster, sagt es dir das, statt still nur ein Drittel mitzunehmen.",
    ["Corrigé : un plantage en donjon (le client rend des valeurs « secrètes » pour certaines données d'unité, et l'une d'elles finissait en clé de table trois appels plus loin, dans une fonction d'annuaire qui n'avait aucune raison de se méfier d'un nom), et le changement d'onglet de métier qui laissait la liste d'un métier avec les infobulles d'un autre."] =
        "Behoben: ein Absturz in Dungeons (der Client liefert für manche Einheitendaten „geheime\" Werte zurück, und einer landete drei Aufrufe später als Tabellenschlüssel in einer Verzeichnisfunktion, die keinen Grund hatte, einem Namen zu misstrauen), und der Wechsel des Berufsreiters, der die Liste eines Berufs mit den Tooltips eines anderen stehen ließ.",
    -- v1.35.1
    ["Un niveau qu'on ne connaît pas n'est pas un niveau 0"] =
        "Eine Fertigkeitsstufe, die wir nicht kennen, ist keine Null",
    ["La vue Manquantes plaçait huit recettes de Couture en tête de liste en te disant qu'elles étaient à ta portée, affichées « niveau requis 0 ». 29 recettes réparties sur six métiers n'ont aucun niveau dans les données, et l'addon lisait cette absence comme un zéro — qui se classe en tête et passe tous les tests de « peux-tu l'apprendre »."] =
        "Die Ansicht Fehlende setzte acht Schneiderei-Rezepte an den Anfang der Liste und erklärte sie für erreichbar, alle mit „benötigter Skill 0“. 29 Rezepte aus sechs Berufen haben in den Daten überhaupt keine Stufe, und das AddOn las diese Abwesenheit als Null — die sortiert zuerst und besteht jede Prüfung „kannst du das schon lernen“.",
    ["Elles affichent « ? » maintenant, elles descendent en fin de liste, et l'addon ne les dit ni à ta portée ni hors de portée, puisqu'il l'ignore. L'infobulle le dit franchement. Les niveaux eux-mêmes manquent toujours : c'est un travail de données, pas d'affichage."] =
        "Jetzt zeigen sie ein „?“, sie rutschen ans Ende der Liste, und das AddOn behauptet weder, dass sie erreichbar sind, noch dass sie es nicht sind, denn es weiß es nicht. Der Tooltip sagt es. Die Stufen selbst fehlen weiterhin: das ist Datenarbeit, keine Anzeigefrage.",
    -- v1.35.0
    ["Enchanter la pièce d'un autre, depuis l'échange"] =
        "Fremde Ausrüstung verzaubern, direkt im Handelsfenster",
    ["Le panneau flottant d'enchantement a disparu : sur Forever, la fenêtre de métier se dessinait exactement par-dessus. Son rôle revient à la colonne de métier, qui passe en mode Échange dès qu'un échange s'ouvre avec ton Enchantement affiché — la silhouette du partenaire, la pièce qu'il a posée dans l'emplacement « ne sera pas échangé », et ce que ses composants désignent."] =
        "Das schwebende Verzauberungsfenster ist weg: Auf Forever wurde das Berufsfenster genau darüber gezeichnet. Seine Aufgabe übernimmt jetzt die Berufsspalte, die in den Handelsmodus wechselt, sobald ein Handel mit geöffneter Verzauberkunst beginnt — dein Partner, das Teil in dem Platz, der nicht gehandelt wird, und worauf seine Materialien hindeuten.",
    ["Clique un emplacement de la silhouette : il reçoit la demande de poser cette pièce (chuchotement, plus une invite d'un clic s'il a l'addon), et la liste de recettes de Blizzard se filtre sur cet emplacement. La main droite coche « Arme » et « Arme à deux mains » à la fois, faute de savoir ce qu'il tient."] =
        "Klicke auf einen Platz der Silhouette: Er wird um dieses Teil gebeten (Flüstern, dazu eine Abfrage mit einem Klick, wenn er das AddOn hat), und Blizzards eigene Rezeptliste filtert auf diesen Platz. Die Waffenhand hakt „Waffe“ und „Zweihandwaffe“ zugleich an, denn noch weiß das AddOn nicht, was er trägt.",
    ["Dès qu'une pièce est posée, la liste suit la pièce elle-même plutôt que ta demande. À la fin de l'échange elle retrouve tes filtres d'avant, y compris celui que tu avais posé toi-même, et la colonne revient sur l'onglet que tu regardais."] =
        "Liegt etwas auf dem Tisch, folgt die Liste dem Gegenstand selbst statt deiner Anfrage. Am Ende des Handels kehren deine vorherigen Filter zurück, auch der, den du selbst gesetzt hattest, und die Spalte kehrt zu deinem Reiter zurück.",
    ["S'il pose aussi des composants, la colonne nomme l'enchantement qu'ils désignent — elle lit ce qu'il pose, jamais tes sacs, et se tait quand plusieurs enchantements collent. Et si un échange s'ouvre alors que ton Enchantement est fermé, un onglet apparaît au bord droit de la fenêtre d'échange pour l'ouvrir."] =
        "Legt er auch Materialien dazu, nennt die Spalte die Verzauberung, auf die sie hindeuten. Sie liest, was er hinlegt, nie deine Taschen, und schweigt, wenn mehrere Verzauberungen passen. Und öffnet sich ein Handel bei geschlossener Verzauberkunst, erscheint am rechten Rand des Handelsfensters ein Reiter, der sie öffnet.",
    -- v1.34.1
    ["Plus d'erreur en entrant en ville"] =
        "Kein Fehler mehr beim Betreten einer Stadt",
    ["Avec la détection des artisans sans l'addon activée (/co crafters on), chaque entrée en ville déclenchait une erreur « action interdite » au nom de l'addon. Sur Forever, le jeu n'autorise plus les addons à écouter le journal de combat, et l'addon s'y abonnait quand même. C'est fini : la détection passe désormais par les messages de fabrication du chat (« Untel crée … »), qui restent ouverts aux addons."] =
        "Mit aktivierter Handwerker-Erkennung (/co crafters on) löste jedes Betreten einer Stadt einen Fehler „Aktion verboten“ mit dem Namen des Addons aus. Auf Forever dürfen Addons das Kampflog nicht mehr abhören, und das Addon hat es trotzdem versucht. Das ist vorbei: Die Erkennung läuft jetzt über die Herstellungsmeldungen im Chat („X stellt Y her“), die Addons weiterhin lesen dürfen.",
    ["Le panneau d'enchantement qui s'ouvre à côté de la fenêtre d'échange disait toujours « Ouvre ta fenêtre d'Enchantement », même ouverte : il cherchait une fenêtre qui n'existe pas sur Forever. Il liste maintenant tes enchantements pour la pièce posée, classés comme avant, et il remarque quand tu ouvres l'Enchantement en plein échange. Cliquer une ligne ne lance pas encore l'enchantement."] =
        "Das Verzauberungsfenster neben dem Handelsfenster verlangte immer „Öffne dein Verzauberungsfenster“, selbst wenn es offen war: Es suchte ein Fenster, das es auf Forever nicht gibt. Jetzt listet es deine Verzauberungen für das hingelegte Teil auf, sortiert wie bisher, und bemerkt, wenn du die Verzauberkunst mitten im Handel öffnest. Ein Klick auf eine Zeile wirkt die Verzauberung noch nicht.",
    ["Sous le capot : l'addon ne transporte plus rien du code de Classic Era (cette version reste figée en 1.30.0), et il lit ton journal de quêtes directement dans le jeu, sans passer par les copies des anciennes fonctions que Questie installe quand il est présent."] =
        "Unter der Haube: Das Addon enthält keinen Code von Classic Era mehr (diese Version bleibt bei 1.30.0 eingefroren) und liest dein Questlog direkt aus dem Spiel, statt über die Ersatzfunktionen zu gehen, die Questie installiert, wenn es vorhanden ist.",

    -- v1.36.0
    ["Ce qui rapporte, et dire au royaume que tu es dispo"] =
        "Was sich lohnt, und dem Realm sagen, dass du frei bist",
    ["La colonne de métier gagne un onglet, Profit : ce que tu sais faire qui vaut la peine d'être fait, la plus grosse marge en haut, avec le prix de vente face au coût des composants. Un clic sur une ligne amène la recette dans la liste de Blizzard. L'onglet n'apparaît que si Auctionator tourne, puisque les prix viennent de lui, et il le dit au lieu de t'afficher un zéro."] =
        "Die Berufsspalte hat einen neuen Reiter, Profit. Er listet auf, was zu fertigen sich lohnt, groesste Marge zuerst, mit dem Verkaufspreis gegen die Kosten der Reagenzien. Ein Klick auf eine Zeile springt in Blizzards eigener Liste zu diesem Rezept. Der Reiter erscheint nur, wenn Auctionator laeuft, denn von dort kommen die Preise, und er sagt es, statt dir eine Null zu zeigen.",
    ["« Chercher du travail » est revenu. Sur Forever le bouton avait disparu avec l'ancienne fenêtre à trois colonnes : il ne restait que /co lfw, et plus aucun moyen de régler ton offre. C'est maintenant une bande en bas de la colonne, qui affiche « Dispo — Forge » dans toutes les vues. Oublier qu'on est annoncé est exactement ce que le minuteur d'expiration existe pour rattraper."] =
        "'Arbeit suchen' ist zurueck. Auf Forever war der Knopf mit dem alten Dreispaltenfenster verschwunden, uebrig blieb nur /co lfw und keinerlei Moeglichkeit, dein Angebot zu aendern. Jetzt ist es ein Streifen am unteren Rand der Spalte, der in jeder Ansicht 'Verfuegbar, Schmiedekunst' anzeigt. Zu vergessen, dass man inseriert ist, ist genau der Grund, warum der Eintrag von selbst ablaeuft.",
    ["À côté, le bouton Offre ouvre ce que tu proposes : les composants de base, une commission par craft, ne prendre que ce qui te fait progresser, les réactifs que tu fournis. Nouveau, tu coches aussi les recettes précises que tu proposes, et qui te consulte les voit par leur nom. La liste des réactifs se limite désormais à ce que tu sais crafter — un travailleur du cuir à 82 ne se voit plus proposer de la Vigne de sang."] =
        "Daneben oeffnet ein Angebot-Knopf, wozu du bereit bist. Die Haendlerreagenzien stellen, eine feste Gebuehr pro Fertigung, nur Arbeit annehmen, die dich Fertigkeit bringt, welche Reagenzien du mitbringst. Neu ist, dass du die konkreten Rezepte ankreuzt, die du anbietest, und wer dich nachschlaegt, sieht sie beim Namen. Die Reagenzienliste zeigt nur noch, was du wirklich fertigen kannst, ein Lederer auf 82 bekommt also kein Blutrebe mehr angeboten.",
    ["Recharge ton interface et tu revois les annonces des autres en quelques secondes. Avant, personne ne se ré-annonçait à ton arrivée : tu pouvais rester devant un radar vide pendant huit minutes sans le savoir."] =
        "Lade deine Oberflaeche neu, und die Eintraege der anderen sind binnen Sekunden wieder da. Zuvor hat sich bei deiner Ankunft niemand erneut gemeldet, du konntest also acht Minuten vor einem leeren Radar sitzen, ohne es zu merken.",
    ["Plus petit. Le bouton d'aide « i » se posait sur la dernière languette et lui volait ses clics. L'onglet « Plan de route » s'appelle « Route », ce qui a fait la place au reste. Et l'addon relève le niveau qu'un formateur exige, donc les recettes affichées « ? » se remplissent à mesure que tu passes les voir."] =
        "Kleineres. Der Hilfeknopf 'i' sass auf dem letzten Reiter und schluckte dessen Klicks. Der Reiter 'Levelroute' heisst jetzt 'Route', was den Platz fuer den Rest geschaffen hat. Und das Addon liest die Fertigkeitsstufe, die ein Lehrer verlangt, sodass Rezepte mit '?' sich fuellen, waehrend du sie besuchst.",

    -- v1.36.1
    ["Une icône dans la liste des addons"] =
        "Ein Symbol in der Addon-Liste",
    ["L'addon a enfin sa propre icône dans la liste des addons, à la place du point d'interrogation. Rien d'autre ne change."] =
        "Das Addon hat endlich ein eigenes Symbol in der Addon-Liste statt des Fragezeichens. Sonst ändert sich nichts.",
    -- v1.36.2
    ["Les commandes trouvent leur destinataire"] =
        "Aufträge erreichen den richtigen Empfänger",
    ["Sur WoW Forever, chaque personnage a un nom de famille, et le jeu te désigne partout par « Prénom Nom ». L'addon t'appelait par ton prénom seul et ne se reconnaissait plus : une commande à ton nom arrivait puis était ignorée, une commande postée sur le canal était rejetée comme si quelqu'un postait à la place d'un autre, et tu pouvais te retrouver dans ta propre liste d'artisans. C'est réparé, y compris pour les commandes des joueurs restés en 1.36.1."] =
        "In WoW Forever hat jeder Charakter einen Nachnamen, und das Spiel nennt dich überall 'Vorname Nachname'. Das Addon benutzte nur deinen Vornamen und erkannte sich selbst nicht mehr: Ein Auftrag an dich kam an und wurde ignoriert, ein im Kanal geposteter Auftrag wurde verworfen, als würde jemand im Namen eines anderen posten, und du konntest in deiner eigenen Handwerkerliste auftauchen. Behoben, auch für Aufträge von Spielern, die noch 1.36.1 nutzen.",
    ["Une ligne du canal Commerce comme « dont need fire wand: [Lesser Magic Wand] » n'est plus prise pour une demande."] =
        "Eine Handelszeile wie 'dont need fire wand: [Lesser Magic Wand]' gilt nicht mehr als Anfrage.",
    -- v1.39.1
    ["Les commandes envoyées par courrier se terminent seules"] =
        "Verschickte Aufträge schließen sich selbst ab",
    ["Quand un artisan t'envoie ta commande par courrier, prendre l'objet dans ta boîte aux lettres la marque reçue, comme quand tu le ramasses. L'artisan est crédité tout de suite. Avant, elle restait « Remise » et il fallait cliquer « J'ai reçu » dans le Carnet."] =
        "Schickt dir ein Handwerker deinen Auftrag per Post, gilt er als erhalten, sobald du den Gegenstand aus dem Briefkasten nimmst, wie beim Plündern. Der Handwerker wird sofort gutgeschrieben. Bisher blieb er auf 'Geliefert' und du musstest im Auftragsbuch 'Erhalten' klicken.",
    ["Côté artisan, « Remplir depuis commande » pouvait joindre une pile entière à une commande plus petite : une commande de 1 partait avec 9. Il coupe maintenant la bonne quantité dans tes sacs et ne joint qu'elle ; sans case libre pour la coupe, le chat te dit combien séparer toi-même."] =
        "Auf Handwerkerseite konnte 'Aus Auftrag füllen' einen ganzen Stapel an einen kleineren Auftrag hängen: Ein Auftrag über 1 ging mit 9 raus. Jetzt wird die richtige Menge in deinen Taschen abgetrennt und nur sie angehängt; ohne freien Taschenplatz sagt dir der Chat, wie viele du selbst abtrennen musst.",
    -- v1.39.0
    ["La fenêtre prend l'allure du jeu"] =
        "Das Fenster sieht aus wie das Spiel",
    ["Les onglets de la fenêtre passent sur son bord droit, en icônes, comme dans la fenêtre de métier. Survole-les pour lire leur nom ; le titre dit où tu es, et l'icône du Carnet compte tes commandes en cours."] =
        "Die Tabs des Fensters sitzen jetzt als Symbole am rechten Rand, wie im Berufsfenster. Fahre darüber, um ihren Namen zu lesen; der Titel zeigt, wo du bist, und das Symbol des Auftragsbuchs zählt deine offenen Aufträge.",
    ["Toutes les listes et les pages défilent avec la barre fine du jeu, qui se cache quand tout tient : ressources de Récolte, Carnet, Aide, Nouveautés, et les vues Commandes, Route, Manquantes et Profit de la fenêtre de métier. Chaque bloc est posé dans un encart, comme dans la fenêtre de métier."] =
        "Alle Listen und Seiten scrollen mit der schmalen Bildlaufleiste des Spiels, die sich versteckt, wenn alles passt: Ressourcen in Sammeln, Auftragsbuch, Hilfe, Neues sowie die Ansichten Aufträge, Route, Fehlend und Gewinn im Berufsfenster. Jeder Block sitzt in einem Einsatz, wie im Berufsfenster.",
    ["Dans Commande, la commission est la case or, argent, cuivre du jeu, et la quantité a des flèches. Le Carnet se trie : clique l'en-tête d'une colonne, reclique pour inverser. Le Journal et la fiche « Poster en quête » prennent le cadre du journal de quêtes du jeu, livre et parchemin."] =
        "In Auftrag ist die Provision das Gold-, Silber- und Kupferfeld des Spiels, und die Menge hat Pfeile. Das Auftragsbuch lässt sich sortieren: Klicke auf einen Spaltenkopf, erneut zum Umkehren. Das Journal und das Blatt 'Als Quest erstellen' nutzen den Rahmen des Questlogs, mit Buch und Pergament.",
    ["Les panneaux de l'échange et du courrier prennent l'allure de ces fenêtres. Le courrier ne liste plus que ce qui se poste : un enchantement se fait à l'échange, où l'onglet Enchantement brille quand une commande d'enchant acceptée te lie à ton partenaire. L'Aide est réécrite, et ses flèches affichées en carrés sont réparées."] =
        "Die Panels an Handel und Post passen jetzt zu diesen Fenstern. Die Post listet nur noch, was sich verschicken lässt: Eine Verzauberung geschieht im Handel, wo der Verzauberkunst-Tab leuchtet, wenn dich ein angenommener Verzauberungsauftrag mit deinem Partner verbindet. Die Hilfe ist neu geschrieben, ihre als Quadrate angezeigten Pfeile sind repariert.",
    -- v1.38.0
    ["Un signe quand une mise à jour est là"] =
        "Ein Zeichen, wenn ein Update da ist",
    ["Quand le réseau signale une nouvelle version, le logo de Crafting Order apparaît en haut de la minicarte, là où Blizzard pose la lettre du courrier. Survole-le pour voir quelle version est sortie et laquelle tu as, clique pour le détail dans le chat. Il disparaît une fois la mise à jour faite."] =
        "Meldet das Netzwerk eine neuere Version, erscheint das Crafting-Order-Logo oben an der Minikarte, dort wo Blizzard den Postbrief anzeigt. Fahre darüber, um zu sehen, welche Version erschienen ist und welche du hast; ein Klick zeigt die Details im Chat. Es verschwindet, sobald du aktualisiert hast.",
    -- v1.37.0
    ["Les artisans se retrouvent dans une communauté"] =
        "Handwerker treffen sich in einer Gemeinschaft",
    ["Sur WoW Forever, le canal caché de l'addon, CraftLinkNet, est découpé en salles : deux joueurs côte à côte pouvaient ne jamais voir leurs commandes. L'addon ne l'utilise plus, et le quitte si tu y es encore. Les artisans se retrouvent dans la communauté « Crafting Order PVE », une par camp."] =
        "Auf WoW Forever wird der versteckte Kanal des Addons, CraftLinkNet, in getrennte Räume aufgeteilt: Zwei Spieler nebeneinander sahen womöglich nie ihre Aufträge. Das Addon nutzt ihn nicht mehr und verlässt ihn, falls du noch drin bist. Handwerker treffen sich jetzt in der Gemeinschaft 'Crafting Order PVE', eine pro Fraktion.",
    ["Sans cercle d'artisans, tu reçois à la connexion un whisper de toi-même avec un lien Rejoindre. Clique dessus, puis Rejoindre dans la fenêtre qui s'ouvre : l'addon en fait ton cercle tout seul. « /co circle nolink » coupe ce rappel."] =
        "Ohne Handwerkerkreis bekommst du beim Einloggen ein Flüstern von dir selbst mit einem Beitreten-Link. Klicke darauf, dann auf Beitreten im Fenster, das sich öffnet: Das Addon macht sie von selbst zu deinem Kreis. '/co circle nolink' schaltet diese Erinnerung ab.",
    ["Tout ce qui passait par le canal part en whisper aux joueurs de l'addon en ligne : ton profil, les commandes et leurs annulations, la recherche de travail. Les joueurs restés en 1.36 ne te joignent plus que par les amis, la guilde, un cercle commun ou une commande à leur nom : dis-leur de mettre à jour."] =
        "Alles, was über den Kanal lief, geht jetzt per Flüstern an Addon-Nutzer, die online sind: dein Profil, Aufträge und ihre Stornierungen, die Arbeitssuche. Spieler, die noch 1.36 nutzen, erreichen dich nur noch über Freunde, Gilde, einen gemeinsamen Kreis oder einen Auftrag auf ihren Namen: Sag ihnen, sie sollen aktualisieren.",
    ["L'onglet Artisans a une ligne par communauté, à son nom, et un joueur passe hors ligne dès que la communauté le dit parti. La ligne Confédération n'apparaît que si GreenWall tourne."] =
        "Der Reiter Handwerker hat eine Zeile pro Gemeinschaft, mit ihrem Namen, und ein Spieler wird offline angezeigt, sobald die Gemeinschaft meldet, dass er weg ist. Die Zeile Konföderation erscheint nur, wenn GreenWall läuft.",
    ["Aussi : les listes de Commande, Récolte, Artisans et Mes artisans défilent comme celle des métiers de Blizzard ; un artisan choisi depuis Artisans arrive sélectionné dans Commande ; le bouton d'aide passe au-dessus du portrait et ne se cache plus derrière la Route ; Manquantes n'affiche plus l'exemplaire de l'autre camp d'une recette jumelle ; la Route puise dans tes sacs avant l'hôtel des ventes ; ouvrir le lien de métier d'un autre joueur ne range plus ses recettes dans les tiennes."] =
        "Außerdem: Die Listen in Auftrag, Sammeln, Handwerker und Meine Handwerker scrollen wie Blizzards Berufsliste; ein aus Handwerker gewählter Handwerker ist in Auftrag vorausgewählt; der Hilfeknopf sitzt über dem Porträt und versteckt sich nicht mehr hinter der Route; Fehlende zeigt nicht mehr das Exemplar der anderen Fraktion eines Zwillingsrezepts; die Route nutzt erst deine Taschen, dann das Auktionshaus; der Berufslink eines anderen Spielers legt seine Rezepte nicht mehr unter deinen ab.",
    -- v1.40.0
    ["Tes commandes sur Commerce, et l'addon sans communauté"] =
        "Deine Aufträge im Handel, und das Addon ohne Gemeinschaft",
    ["Coche « Annoncer en Commerce » en postant une commande à tous : l'addon écrit aussi une ligne sur Trade (Services), dans une capitale, que tout le monde lit. Les joueurs de l'addon, même inconnus, reçoivent la vraie commande en quelques secondes ; les autres peuvent te chuchoter. Clic droit sur la commande dans le Carnet pour la rappeler, une fois par quart d'heure."] =
        "Kreuze „Im Handelskanal ankündigen“ an, wenn du einen Auftrag an alle postest: Das Addon schreibt zusätzlich eine Zeile in Handel (Dienstleistungen), in einer Hauptstadt, die alle lesen können. Addon-Nutzer, auch unbekannte, erhalten den echten Auftrag in wenigen Sekunden; alle anderen können dir flüstern. Rechtsklick auf den Auftrag im Auftragsbuch wiederholt ihn, einmal pro Viertelstunde.",
    ["La même case, dans l'offre de « Chercher du travail », annonce ta dispo : une ligne « LFW » sur Trade (Services) quand tu l'actives, et les joueurs de l'addon reçoivent ton profil."] =
        "Dasselbe Kästchen im Angebot von „Arbeit suchen“ kündigt deine Verfügbarkeit an: eine „LFW“-Zeile in Handel (Dienstleistungen), wenn du sie einschaltest, und Addon-Nutzer erhalten dein Profil.",
    ["L'addon marche sans la communauté Crafting Order PVE et ne t'en envoie plus le lien. Les artisans se trouvent par les amis, la guilde, tes cercles, les annonces sur Commerce et la salle de découverte, où les joueurs de l'addon se disent bonjour (« /co channel room off » pour la quitter)."] =
        "Das Addon funktioniert ohne die Gemeinschaft Crafting Order PVE und schickt dir ihren Link nicht mehr. Handwerker finden sich über Freunde, Gilde, deine Kreise, die Ankündigungen im Handel und den Entdeckungsraum, in dem sich Addon-Nutzer begrüßen („/co channel room off“ zum Verlassen).",
    ["Aussi : l'addon ne crie plus de ping, que Forever refusait sans rien dire ; « /co note » prépare le texte de tes métiers à coller dans ta note de membre d'une communauté, et l'onglet Artisans affiche la note des autres."] =
        "Außerdem: Das Addon schreit keinen Ping mehr, den Forever stillschweigend ablehnte; „/co note“ bereitet den Text deiner Berufe vor, den du in deine Mitgliedsnotiz einer Gemeinschaft einfügst, und der Reiter Handwerker zeigt die Notizen der anderen.",
}

for k, v in pairs(news) do L[k] = v end
