-- CraftingOrderClassic_Locale_News_deDE.lua — traductions de l'onglet « Nouveautés » (deDE).
-- Extrait de _Locale_deDE.lua (plafond anti-monolithe). Clé FR → texte DE, chargé APRÈS _Locale.lua.

local COC = CraftingOrderClassic
if (GetLocale and GetLocale() or "") ~= "deDE" then return end
local L = COC.L

local news = {
    -- Onglet Nouveautés (changelog en jeu)
    ["Nouveautés"] = "Neues",
    -- v1.22.1
    ["Les alertes de commande vérifient enfin le métier, et un plan de route qui suit son propre badge"] =
        "Bestellbenachrichtigungen, die wirklich den Beruf prüfen, und eine Routenplanung im Einklang mit dem Abzeichen",
    ["Une commande à portée large (guilde, amis, tous) déclenchait un toast même chez un joueur sans le métier, du moment qu'elle arrivait par le relais de connexion (chuchotement) plutôt que par le canal : le filtre par métier ne couvrait que le canal. Il s'applique maintenant quel que soit le chemin réseau. Le toast gagne aussi un troisième texte : une commande à portée large n'affiche plus « pour TOI », ce qui donnait l'impression fausse d'une demande personnelle."] =
        "Eine breite Bestellung (Gilde, Freunde, alle) löste einen Hinweis auch bei Spielern aus, die den Beruf gar nicht hatten, sofern sie über die Login-Weiterleitung (ein Flüstern) statt über den Kanal ankam: der Berufsfilter galt bisher nur für den Kanal. Er gilt jetzt unabhängig vom Übertragungsweg. Der Hinweis bekommt außerdem einen dritten Text: eine breite Bestellung zeigt nicht mehr „für DICH\", was wie eine persönliche Anfrage wirkte, obwohl sie keine war.",
    ["Le plan de route « quoi monter ensuite » pouvait suggérer une recette différente du badge de coût de la liste, les deux lisant des données légèrement différentes. Le plan utilise maintenant la difficulté réelle de la fenêtre métier à ton rang actuel plutôt qu'une projection, et se rafraîchit au même rythme que le badge. La commande |cFFFFFFFF/co lvldump|r affiche le détail en cas de nouveau désaccord."] =
        "Die Routenplanung „was als Nächstes lernen\" konnte ein anderes Rezept vorschlagen als das Kosten-Abzeichen der Liste, weil beide leicht unterschiedliche Daten lasen. Die Route nutzt jetzt den tatsächlichen Schwierigkeitsgrad des Berufsfensters auf deinem aktuellen Rang statt einer Schätzung, und aktualisiert sich im selben Takt wie das Abzeichen. |cFFFFFFFF/co lvldump|r zeigt die Details bei einer erneuten Abweichung.",
    -- v1.22.0
    ["L'aide contextuelle, des dépendances qu'on ne peut plus rater, et une touche Échap qui obéit"] =
        "Kontexthilfe, unübersehbare Abhängigkeiten, und eine Escape-Taste, die gehorcht",
    ["Un nouveau bouton « i » ouvre l'aide contextuelle du jeu, le même système que Blizzard utilise pour ses propres fenêtres : le fond s'assombrit et une bulle pointe directement sur ce dont il est question. Chaque onglet (Vue Métier, Commande, Récolte, Artisans, Mes artisans, Carnet) a sa propre visite guidée, donc le bouton explique ce qui est réellement affiché plutôt qu'une infobulle générique."] =
        "Ein neuer „i\"-Knopf öffnet die Kontexthilfe des Spiels, dasselbe System, das Blizzard für seine eigenen Fenster nutzt: der Hintergrund verdunkelt sich, und eine Sprechblase zeigt direkt auf das Element, um das es geht. Jeder Reiter (Berufsansicht, Auftrag, Sammeln, Handwerker, Meine Handwerker, Kontobuch) hat seine eigene Führung, sodass der Knopf erklärt, was tatsächlich zu sehen ist, statt eines allgemeinen Tooltips.",
    ["Lazy Gold et MTSL restent optionnels, mais rien ne signalait qu'ils manquaient. Les boutons qui en dépendent restent visibles et colorés même sans l'addon installé, et cliquer dessus sans l'avoir ouvre désormais une explication de ce qu'il fait et où le trouver, plutôt que de ne rien faire du tout."] =
        "Lazy Gold und MTSL bleiben optional, aber nichts zeigte an, wenn eines von beiden fehlte. Die Knöpfe, die sie brauchen, bleiben sichtbar und farbig, ob das Addon installiert ist oder nicht, und ein Klick ohne das Addon öffnet jetzt eine kurze Erklärung, was es tut und wo man es bekommt, statt nichts zu tun.",
    ["L'alerte « peut faire cette commande » se déclenchait même quand tu ne connaissais pas la recette, souvent des gemmes ou enchants dont tu avais les réactifs sans le plan. Elle vérifie maintenant tes recettes connues avant de te notifier sur tes propres commandes. Un ami en ligne sans l'addon ne s'affiche plus « Hors ligne » par erreur."] =
        "Der Hinweis „kann das herstellen\" löste auch aus, wenn du das Rezept gar nicht kanntest, meist Schmucksteine oder Verzauberungen, für die du die Reagenzien, aber nicht den Plan hattest. Er prüft jetzt deine bekannten Rezepte, bevor er dich wegen deiner eigenen Aufträge nervt. Ein Freund, der ohne Addon online ist, wird nicht mehr fälschlich als offline angezeigt.",
    ["Échap laissait souvent les fenêtres de métier ouvertes, et trois rapports différents pointaient la même cause : cacher ou désactiver la souris d'une fenêtre protégée en plein combat déclenche une erreur du jeu. Les fenêtres passent maintenant par un petit relais dédié, donc Échap les ferme proprement, en combat ou non."] =
        "Escape ließ Berufsfenster meistens offen, und drei getrennte Fehlerberichte zeigten auf dieselbe Ursache: ein geschütztes Fenster mitten im Kampf zu verstecken oder seine Maus zu deaktivieren, löst einen Spielfehler aus. Fenster laufen jetzt stattdessen über ein kleines Relais, sodass Escape sie sauber schließt, im Kampf oder nicht.",
    ["L'aide « quoi monter ensuite » affiche maintenant le coût par point de compétence, une pastille de prix Auctioneer, et une icône vers le PNJ qui vend une recette que tu ne connais pas encore, en plus d'un tri affiné."] =
        "Die Hilfe „was als Nächstes hochziehen\" zeigt jetzt die Kosten pro Fertigkeitspunkt, ein Auctioneer-Preisabzeichen und ein Symbol zum Händler, der ein Rezept verkauft, das du noch nicht kennst, dazu eine feinere Sortierung.",
    ["Cette même aide gagne un plan de route : clique le bouton carte et il déroule toute ta montée rang par rang, en choisissant à chaque étape la recette la moins chère (apprise ou achetable, plans compris) et en additionnant le coût total. Les recettes à cooldown ou avec un réactif sans prix connu sont exclues exprès, elles fausseraient le total. Demande Lazy Gold ; MTSL ajoute les prix de plans formateur et vendeur au calcul."] =
        "Dieselbe Hilfe bekommt jetzt einen Routenplaner: Klick den Kartenknopf, und er rechnet deinen ganzen Aufstieg Rang für Rang durch, wählt bei jedem Schritt das günstigste Rezept (gelernt oder kaufbar, Pläne eingeschlossen) und summiert die Gesamtkosten. Rezepte mit Abklingzeit oder einer Zutat ohne bekannten Preis werden absichtlich ausgeschlossen, sie würden die Summe verfälschen. Braucht Lazy Gold; MTSL fügt Händler- und Verkäuferpreise für Pläne hinzu.",
    -- v1.21.0
    ["L'enchant par emplacement, et un panneau d'échange qui ne cache plus rien"] =
        "Verzauberungen nach Platz, und ein Tauschfenster, das nichts mehr versteckt",
    ["Choisir un enchant demandait de fouiller des centaines de plans aux noms presque identiques. L'onglet Commande a maintenant une vue silhouette : clique l'emplacement à enchanter, tu obtiens ses stats, puis ses variantes de la plus forte à la plus faible. La bascule est dans la bande de filtres ; la liste reste pour tout ce qui n'a pas d'emplacement (huiles, baguettes, produits de désenchantement)."] =
        "Eine Verzauberung auszuwählen hieß, sich durch Hunderte fast gleich benannter Rezepte zu scrollen. Der Auftrag-Reiter hat jetzt eine Silhouetten-Ansicht: Klick auf den Platz, den du verzaubern willst, und du bekommst dessen Werte und dann die Varianten von stark nach schwach. Der Umschalter sitzt in der Filterleiste; die Rezeptliste bleibt für alles ohne Platz (Öle, Zauberstäbe, Entzauberungsmaterial).",
    ["Le panneau d'enchant de l'échange n'affichait que 8 lignes, et le « +N autre(s) » du bas n'était pas cliquable : au-delà de la 8ᵉ place, un enchant était tout bonnement inatteignable — c'est ainsi qu'un enchanteur à qui on avait passé les réactifs ne se voyait jamais proposer la bonne recette, noyée sous les variantes de haut rang. La liste défile à la molette, et elle est classée par ce qu'on te demande : d'abord les enchants dont ton partenaire vient de poser les réactifs, puis ce que tes sacs permettent, puis le reste."] =
        "Das Verzauberungsfenster beim Tauschen zeigte nur 8 Zeilen, und das „+N weitere\" unten war nicht anklickbar: ab dem neunten Eintrag war eine Verzauberung schlicht unerreichbar. So bekam ein Verzauberer, dem man die Reagenzien gereicht hatte, das richtige Rezept nie angeboten, begraben unter Varianten höheren Rangs. Die Liste scrollt jetzt mit dem Mausrad und ist danach sortiert, worum du gebeten wirst: zuerst die Verzauberungen, deren Reagenzien dein Partner gerade auf den Tisch gelegt hat, dann was deine Taschen schon hergeben, dann der Rest.",
    ["Tant que la case « ne sera pas échangé » est vide, le panneau ne disparaît plus : il montre la même silhouette, avec le modèle de ton partenaire, et cliquer un emplacement lui chuchote d'y poser cette pièce. La plupart des gens qui te tendent un objet ignorent que cette case existe."] =
        "Solange der Platz „Wird nicht gehandelt\" leer ist, verschwindet das Fenster nicht mehr: Es zeigt dieselbe Silhouette, mit dem Modell deines Tauschpartners darin, und ein Klick auf einen Platz flüstert ihm zu, das Teil dort hineinzulegen. Die meisten, die dir Ausrüstung reichen, wissen gar nicht, dass es diesen Platz gibt.",
    ["Deux correctifs : les enchants de poignets et de bâton de Wrath n'apparaissaient jamais dans le panneau d'échange (le jeu les écrit « Bracers » et « Staff » là où les autres extensions disent « Bracer »), et un enchant de bâton ne se propose plus que sur un vrai bâton. Le panneau ne touche plus non plus à ses boutons pendant un combat, ce que le jeu interdit."] =
        "Zwei Korrekturen: Wraths Verzauberungen für Handgelenke und Stäbe tauchten im Tauschfenster nie auf (das Spiel schreibt sie „Bracers\" und „Staff\", wo andere Erweiterungen „Bracer\" sagen), und eine Stab-Verzauberung bietet sich jetzt nur noch auf einem echten Stab an. Außerdem fasst das Fenster im Kampf seine Knöpfe nicht mehr an, was das Spiel ohnehin blockiert.",
    ["Plus discret : les lignes de chat « X sait faire cette commande captée » sont désactivées par défaut — la commande est poussée aux amis capables dans tous les cas, le message n'était que du bruit. |cFFFFFFFF/co verbose|r les remet."] =
        "Leiser: Die Chatzeilen „X kann diesen aufgefangenen Auftrag herstellen\" sind jetzt standardmäßig aus. Der Auftrag wird ohnehin an fähige Freunde weitergereicht, die Meldung war nur Rauschen. |cFFFFFFFF/co verbose|r holt sie zurück.",
    -- v1.20.0
    ["Enchante en un clic, trié par emplacement, et depuis l'échange"] = "Verzaubern per Klick, sortiert nach Platz, direkt beim Tauschen",
    ["Le bouton « Créer » de l'Enchantement avait un vieux bug intermittent : parfois rien ne se passait, et resélectionner la recette finissait par le faire marcher. Cause trouvée : sélectionner une recette n'arme pas le bouton natif de Blizzard, notre clic sécurisé tombait donc sur un bouton désactivé. Corrigé — ça devrait marcher du premier coup, à chaque fois."] =
        "Der „Erstellen\"-Knopf beim Verzauberkunst hatte einen alten, unregelmäßigen Fehler: manchmal passierte einfach nichts, und das Rezept mehrmals neu auszuwählen brachte es irgendwann zum Laufen. Ursache gefunden: Ein Rezept auszuwählen aktiviert nicht den nativen Knopf von Blizzard, unser gesicherter Klick landete also auf einem deaktivierten Knopf. Behoben — sollte jetzt jedes Mal sofort funktionieren.",
    ["Les recettes d'enchantement ne s'entassent plus dans un fourre-tout « Autres/Divers » : elles se rangent par emplacement (Poignets, Torse, Main gauche…) puis par stat de base (Force, Esprit, Déviation), le nom raccourci à la stat seule puisque l'emplacement est déjà dans l'en-tête."] =
        "Verzauberungs-Rezepte landen nicht mehr alle im Sammelbecken „Sonstiges\": Sie sind jetzt nach Ausrüstungsplatz sortiert (Handgelenk, Brust, Waffenhand…), dann nach Basiswert (Stärke, Willenskraft, Abwehr), mit gekürztem Namen, da der Platz schon in der Überschrift steht.",
    ["Sélectionner un enchant d'équipement affiche un bouton « Enchanter équipé » à côté de Créer : un clic l'applique directement sur la pièce que tu portes, sans avoir à cibler."] =
        "Wählst du eine Verzauberung für einen Ausrüstungsplatz aus, erscheint neben „Erstellen\" ein Knopf „Ausgerüstetes verzaubern\": Ein Klick wendet sie direkt auf das getragene Teil an, ohne manuelles Zielen.",
    ["Et quand quelqu'un te tend un objet à enchanter en échange, le poser dans la case « ne sera pas échangé » ouvre un petit panneau listant tes enchants pour cet emplacement, prêts à lancer sans fouiller ta fenêtre de métier (qui doit rester ouverte : le jeu ne renseigne tes recettes connues que pendant qu'elle l'est)."] =
        "Und wenn dir jemand beim Tauschen etwas zum Verzaubern gibt: Es in das Feld „wird nicht getauscht\" zu legen, öffnet ein kleines Fenster mit allen deinen Verzauberungen für diesen Platz, einsatzbereit, ohne im Berufsfenster zu suchen (das aber geöffnet bleiben muss: Das Spiel gibt deine bekannten Rezepte nur preis, solange es offen ist).",
    -- v1.19.1
    ["Correctif : l'icône « dispo » remarche sur la nouvelle UI des plaques"] = "Fehlerbehebung: Das Verfügbarkeits-Symbol funktioniert wieder mit der neuen Namensschild-UI",
    ["Sur le client TBC (et bientôt Era/Saison de la Découverte à la 1.15.9), l'icône « recherche de travail » au-dessus de la plaque d'un artisan cessait de s'afficher quand son statut changeait : la nouvelle interface de plaques a renommé un champ interne que l'addon lisait. Corrigé. Elle reste invisible en instance (donjon, raid) : le jeu verrouille les plaques amies aux addons là-bas, rien à faire de notre côté."] =
        "Auf dem TBC-Client (und bald auf Era/Season of Discovery mit Patch 1.15.9) zeigte das „Arbeit suchen\"-Symbol über dem Namensschild eines Handwerkers nicht mehr an, wenn sich dessen Status änderte: Die neue Namensschild-Oberfläche hat ein internes Feld umbenannt, das das Addon ausgelesen hat. Behoben. In Instanzen (Dungeon, Schlachtzug) bleibt es unsichtbar: Das Spiel sperrt Addons dort von befreundeten Namensschildern aus, daran können wir nichts ändern.",
    -- v1.19.0
    ["Propose des recettes précises, diffuse tes réactifs, et le LFW marche même sans l'addon"] = "Rezepte im Angebot, ein Teilen-Knopf, und Arbeit suchen auch ohne Addon",
    ["« Chercher du travail » propose maintenant des recettes précises, pas seulement des réactifs : coche des plans dans la liste et qui te consulte voit « propose : Bouclier de fer, Gilet de mailles de cuivre » à côté de ce que tu fournis déjà."] =
        "„Arbeit suchen\" lässt dich jetzt genaue Rezepte angeben, nicht nur Reagenzien. Hake Pläne in der Rezeptliste ab, und wer dein Angebot ansieht, sieht „bietet an: Eisenschild, Kupferkettenweste\" neben den Materialien, die du schon aufgelistet hast.",
    ["Un bouton « Diffuser » envoie la liste de réactifs d'une recette ou d'une commande dans un canal au choix (guilde, dire, groupe/raid, un canal numéroté), avec le lien de chaque objet — une liste de courses en un clic, depuis la vue métier, la carte de commande ou le panneau de publication."] =
        "Ein „Teilen\"-Knopf schickt die Reagenzienliste eines Rezepts oder Auftrags in einen Kanal deiner Wahl (Gilde, Sagen, Gruppe/Schlachtzug, ein nummerierter Kanal), mit einem Link für jeden Gegenstand — eine Einkaufsliste mit einem Klick, aus dem Berufsfenster, der Auftragskarte oder dem Ausschreibungsfeld.",
    ["Le LFW marche même sans l'addon : tape « LFW enchantement » en Commerce ou Général et tu apparais comme dispo, avec la même icône de plaque qu'un joueur qui a Crafting Order. Plus une correction : une recette déjà apprise ne s'affichait plus en double avec MissingTradeSkillsList."] =
        "„Arbeit suchen\" funktioniert jetzt auch ohne Addon: Tippe „LFW Verzauberkunst\" in Handel oder Allgemein, und du erscheinst als verfügbar, mit demselben Namensplaketten-Symbol wie jemand mit Crafting Order. Dazu ein Fix: Ein bereits erlerntes Rezept wurde mit MissingTradeSkillsList nicht mehr doppelt aufgeführt.",
    -- v1.18.0
    ["Chercher du travail : dis ce que tu offres, et trie par progression"] = "Arbeit suchen, jetzt mit Angebot, und nach Fertigkeitsfortschritt sortieren",
    ["« Chercher du travail » ne se contente plus de te signaler dispo. Clique l'engrenage à côté du bouton et dis ce que tu proposes : tu fournis les composants de base, tu fournis tel réactif précis, une commission fixe par craft, ou seulement les plans qui te font gagner un point de compétence. Ça s'affiche sur ta ligne [Dispo] et dans l'infobulle au-dessus de ta tête, avec une pièce s'il y a une commission et un sac si tu fournis des compos."] =
        "„Arbeit suchen\" macht mehr, als dich nur als verfügbar zu markieren. Klick auf das Zahnrad neben dem Knopf und sag, was du anbietest: Du bringst die Grundreagenzien mit, du lieferst eine bestimmte Komponente, ein fester Aufschlag pro Herstellung, oder nur Aufträge, die dir einen Fertigkeitspunkt geben. Es erscheint in deiner [Dispo]-Zeile und im Tooltip über deinem Kopf, mit einer Münze bei Aufschlag und einer Tasche, wenn du Materialien stellst.",
    ["L'icône « dispo » au-dessus de la plaque d'un artisan marche maintenant sur Era et Saison de la Découverte, plus seulement sur le client TBC. Active les plaques des amis (nameplateShowFriends) et l'icône du métier flotte au-dessus de qui cherche du travail à côté de toi."] =
        "Das „Verfügbar\"-Symbol über der Namensplakette eines Handwerkers funktioniert jetzt auf Era und Season of Discovery, nicht mehr nur auf dem Burning-Crusade-Client. Schalte Freundes-Namensplaketten ein (nameplateShowFriends), und das Berufssymbol schwebt über jedem in deiner Nähe, der Arbeit sucht.",
    ["Les recettes se trient par ce qui te fait encore progresser : un troisième bouton outil remonte en tête les plans qui donnent un point, d'orange à gris. Les commandes ont le même « ce qui me fait monter d'abord », avec un liseré de difficulté sur le côté de chaque ligne. Plus quelques corrections au passage."] =
        "Rezepte lassen sich danach sortieren, was dich noch verbessert: Ein dritter Werkzeugknopf hebt die Pläne, die einen Fertigkeitspunkt geben, nach oben, von Orange zu Grau. Aufträge bekommen dasselbe „was mich zuerst verbessert\", mit einem Schwierigkeitsstreifen an der Seite jeder Zeile. Dazu ein paar Korrekturen nebenbei.",
    -- v1.17.1
    ["Correctif : erreur au login en « Chercher du travail »"] = "Behoben: Fehler beim Anmelden bei „Arbeit suchen\"",
    ["Si tu avais activé « Chercher du travail », te connecter ou faire /reload pouvait déclencher une erreur rouge : l'addon annonçait ta disponibilité avant que le jeu n'autorise un addon à parler sur le canal. L'annonce attend maintenant ton prochain clic ou ta prochaine touche — plus d'erreur, et les autres te voient toujours dispo."] =
        "Wenn „Arbeit suchen\" aktiviert war, konnte das Anmelden oder /reload einen roten Fehler auslösen: Das Addon meldete deine Verfügbarkeit, bevor das Spiel einem Addon erlaubt, im Kanal zu sprechen. Die Meldung wartet jetzt auf deinen nächsten Klick oder Tastendruck — kein Fehler mehr, und andere sehen weiterhin, dass du verfügbar bist.",
    -- v1.17.0
    ["L'interface passe au style natif de WoW"] = "Das Fenster passt jetzt zum Spiel",
    ["La fenêtre n'a plus son habillage doré maison : elle emprunte le cadre du jeu (barre de titre, portrait rond, onglets, boutons). Elle se fond dans l'interface au lieu de ressembler à un addon posé par-dessus, et rien n'a bougé de ce que tu connais."] = "Das Fenster hat seine eigene goldene Optik gegen den Rahmen des Spiels getauscht (Titelleiste, rundes Porträt, Reiter oben, Schaltflächen). Es wirkt jetzt wie ein Teil der Oberfläche statt wie ein aufgesetztes Addon, und nichts hat sich verschoben, was du neu lernen müsstest.",
    ["La vue métier est refaite, avec une colonne Commandes en liste : une ligne par commande (demandeur, objet voulu, prix), et le clic ouvre la carte complète (composants fournis, coût des réactifs, Accepter / Refuser / Chuchoter) avec une croix pour revenir à la liste. Et les sous-catégories de récolte (Peaux, Écailles, Herbes, Poissons) sont enfin traduites hors client français."] = "Das Berufsfenster wurde neu gebaut, mit der Auftragsspalte als Liste: eine Zeile pro Auftrag (Besteller, gewünschter Gegenstand, Preis), und ein Klick öffnet die vollständige Karte (bereitgestellte Komponenten, Reagenzienkosten, Annehmen / Ablehnen / Flüstern) mit einer Schließen-Schaltfläche zurück zur Liste. Und die Sammelberuf-Unterkategorien (Felle, Schuppen, Kräuter, Fische) sind außerhalb eines französischen Clients endlich übersetzt.",
    -- v1.15.1
    ["Tes commandes n'appartiennent qu'à toi"] = "Deine Aufträge gehören nur dir",
    ["Recettes triées, et où est l'or"] = "Sortierte Rezepte, und wo das Gold ist",
    ["Fini le fourre-tout « Consommable » : les recettes sont regroupées par type (potions de soin, de mana, élixirs, flacons, transmutations…) et triées du plus haut niveau au plus bas. Une potion qui rend vie ET mana apparaît sous les deux. Le même classement s'applique partout — Commande, Mes artisans, et les métiers de récolte (minerais, herbes, cuirs, poissons)."] = "Kein Sammelbecken \"Verbrauchbar\" mehr: Rezepte werden nach Typ gruppiert (Heiltränke, Manatränke, Elixiere, Fläschchen, Transmutationen…) und vom höchsten zum niedrigsten Rang sortiert. Ein Trank, der Leben UND Mana wiederherstellt, erscheint unter beiden. Dieselbe Gruppierung gilt überall — Bestellen, Meine Handwerker und die Sammelberufe (Erze, Kräuter, Leder, Fische).",
    ["Si tu as Lazy Gold, chaque recette affiche sa rentabilité (pièces, étoiles au-delà de mille pièces d'or ; rien pour une perte). La pièce d'or au-dessus de la liste trie par profit, le bouton « 123 » bascule en valeurs exactes. L'onglet Commande a les deux boutons, plus la valeur HV et le coût des réactifs sur chaque commande entrante."] = "Mit Lazy Gold zeigt jedes Rezept seinen Gewinn (Münzen, Sterne über tausend Gold; nichts bei Verlust). Die Goldmünze über der Liste sortiert nach Gewinn, die Schaltfläche \"123\" wechselt zu exakten Beträgen. Der Tab Bestellen erhält beide Schaltflächen sowie den Auktionswert und die Reagenzienkosten bei jeder eingehenden Bestellung.",
    ["Dans l'annuaire, les métiers passent en icônes : un artisan avec un plan vraiment rentable a un contour doré, le survol nomme le plan, le clic ouvre la Commande déjà ciblée. « Mes artisans » gagne « Tous les plans du royaume » : tous tes persos (même faction) fusionnés et triés par profit — d'un coup d'œil, quel reroll fait des sous. Et si tu as MissingTradeSkillsList, un bouton montre tes recettes non apprises en rouge, avec leur source au clic."] = "Im Verzeichnis wurden Berufe zu Symbolen: ein Handwerker mit einem wirklich profitablen Plan erhält einen goldenen Rand, das Überfahren nennt den Plan, der Klick öffnet den Tab Bestellen bereits auf ihn ausgerichtet. Meine Handwerker erhält \"Alle Realm-Pläne\": alle Charaktere (gleiche Fraktion) zusammengeführt und nach Gewinn sortiert — auf einen Blick, welcher Twink Geld macht. Und mit MissingTradeSkillsList zeigt eine Schaltfläche deine nicht gelernten Rezepte in Rot, mit ihrer Quelle beim Klick.",
    ["Les identifiants de commande étaient devinables : n'importe qui pouvait réécrire la tienne (acheteur, prix, quantité). C'est fermé : seul son auteur peut la modifier. Le relais entre joueurs, lui, continue de fonctionner — c'est comme ça qu'une commande atteint quelqu'un que le canal n'a jamais touché."] =
        "Auftrags-IDs waren erratbar, und jeder konnte deinen umschreiben (Käufer, Preis, Menge). Das ist dicht: nur wer einen Auftrag erstellt hat, kann ihn ändern. Die Weitergabe zwischen Spielern funktioniert weiterhin, so erreicht ein Auftrag jemanden, den der Kanal nie erreicht hat.",
    ["On ne peut plus te faire mettre en sourdine en postant de fausses commandes en ton nom, et un acheteur dont les commandes sont relayées en rafale n'est plus muté par erreur. « X a refusé ta commande » et le rappel « tu sais le faire » ne se rejouent plus en boucle, et rien ne passe d'un joueur que tu as mis en sourdine."] =
        "Niemand kann dich stummschalten lassen, indem er gefälschte Aufträge in deinem Namen postet, und ein Käufer, dessen Aufträge im Schwall weitergegeben werden, wird nicht mehr versehentlich stummgeschaltet. „X hat deinen Auftrag abgelehnt“ und der Hinweis „du kannst das herstellen“ wiederholen sich nicht mehr endlos, und von jemandem, den du stummgeschaltet hast, kommt nichts mehr durch.",
    ["La vue métier n'affiche plus les commandes privées destinées à quelqu'un d'autre, ni les expirées. Ton compteur de crafts livrés ne peut plus être gonflé par un tiers. Et croiser un artisan coûte deux fois moins de messages : le bonjour porte maintenant tes métiers, ce qui règle aussi les artisans qui s'affichaient sans aucun métier."] =
        "Das Berufsfenster zeigt keine privaten Aufträge mehr, die für jemand anderen bestimmt sind, und keine abgelaufenen. Dein Zähler gelieferter Aufträge kann nicht mehr von Fremden aufgebläht werden. Und einem Handwerker zu begegnen kostet halb so viele Nachrichten: die Begrüßung trägt jetzt deine Berufe mit sich, was auch Handwerker behebt, die ganz ohne Berufe angezeigt wurden.",
    -- v1.15.0
    ["Recherche de travail : signale que tu es dispo"] = "Arbeitssuche: zeig, dass du verfügbar bist",
    ["Ouvre un métier et clique « Chercher du travail » : tout le royaume sait que tu es dispo, une icône d'artisan s'affiche au-dessus de ta tête pour ceux qui passent, et tu apparais « [Dispo] » dans leur annuaire. Ça s'éteint tout seul au bout d'un moment si tu oublies."] =
        "Öffne einen Beruf und klick „Arbeit suchen“: der ganze Realm weiß, dass du verfügbar bist, ein Handwerker-Symbol erscheint über deinem Kopf für Vorbeikommende, und du erscheinst als „[Sucht]“ in ihrem Verzeichnis. Es erlischt von selbst, wenn du es vergisst.",
    ["Au passage : les deux fenêtres ne s'emmêlent plus (un clic la ramène au premier plan), l'annuaire a un bouton partenaire et se limite à ta faction (pas d'échange cross-faction sur Classic), et un artisan ne s'affiche plus avec un métier qui n'est pas le sien."] =
        "Nebenbei: die zwei Fenster überlagern sich nicht mehr (ein Klick bringt eins nach vorne), das Verzeichnis hat einen Partner-Knopf und bleibt bei deiner Fraktion (kein fraktionsübergreifender Handel auf Classic), und ein Handwerker zeigt keinen Beruf mehr, der nicht seiner ist.",
    ["Sous le capot : mises à jour plus sûres"] = "Unter der Haube: sicherere Updates",
    ["Tes données sauvegardées portent désormais une version : une mise à jour qui doit les réorganiser ne tourne qu'une fois, tes recettes et commandes restent intactes."] =
        "Deine gespeicherten Daten tragen jetzt eine Version, sodass ein Update, das sie umbauen muss, nur einmal läuft und deine Rezepte und Aufträge unversehrt bleiben.",
    ["Protocole de commandes consolidé (mêmes échanges réseau) : ce build reste compatible avec les joueurs encore en 1.7.x."] =
        "Das Auftragsprotokoll wurde konsolidiert (gleiche Netzwerk-Kommunikation); dieser Build versteht sich weiterhin mit Spielern auf 1.7.x.",
    -- (clés v1.7.0/v1.7.1/v1.6.0/v1.5.0/v1.4.0 retirées : ces versions ne sont plus listées dans l'onglet Nouveautés)
    -- Onglet Nouveautés — v1.13.0
    ["Modération : mutes avec raison, temporaires, liste de confiance"] = "Moderation: Stummschaltungen mit Grund, temporär, Vertrauensliste",
    ["Un mute porte désormais une raison et une date, et peut être temporaire : |cFFFFFFFF/co mute Bob 1h spammeur|r se lève tout seul au bout d'une heure (|cFFFFFFFF/co mute|r seul liste les mutés avec raison et temps restant). Et |cFFFFFFFF/co trust <nom>|r marque un joueur de confiance, jamais mis en sourdine automatiquement — le mute manuel restant toujours possible."] =
        "Eine Stummschaltung trägt jetzt einen Grund und ein Datum und kann temporär sein: |cFFFFFFFF/co mute Bob 1h Spammer|r hebt sich nach einer Stunde selbst auf (|cFFFFFFFF/co mute|r allein listet die Stummgeschalteten mit Grund und Restzeit). Und |cFFFFFFFF/co trust <Name>|r markiert einen Spieler als vertrauenswürdig, nie automatisch stummgeschaltet — manuelles Stummschalten bleibt möglich.",
    -- (clés v1.12.1 retirées : version sortie de la fenêtre glissante de l'onglet Nouveautés)
    -- Onglet Nouveautés — v1.12.0
    ["Les recettes de la Saison de la Découverte"] = "Rezepte der Saison der Entdeckungen",
    ["304 recettes de la Saison de la Découverte entrent au catalogue : 80 en Travail du cuir, 65 en Forge, 57 en Couture, 48 en Enchantement, 29 en Ingénierie, 16 en Alchimie, plus la Cuisine, le Secourisme et le Minage. Elles apparaissent dans l'onglet Commande, avec leurs réactifs et leur palier d'apprentissage."] =
        "304 Rezepte der Saison der Entdeckungen kommen in den Katalog: 80 für Lederverarbeitung, 65 für Schmiedekunst, 57 für Schneiderei, 48 für Verzauberkunst, 29 für Ingenieurskunst, 16 für Alchemie, dazu Kochkunst, Erste Hilfe und Bergbau. Sie erscheinen im Auftrags-Tab, mit ihren Reagenzien und Fertigkeitsstufen.",
    ["Elles ne se chargent que sur un royaume Saison de la Découverte. Sur un royaume Era classique, rien ne change : l'addon voit exactement le même jeu de recettes qu'avant, et les recettes que tes amis t'ont déjà partagées restent lisibles."] =
        "Sie werden nur auf einem Realm der Saison der Entdeckungen geladen. Auf einem normalen Era-Realm ändert sich nichts: das Addon sieht genau denselben Rezeptsatz wie zuvor, und die von deinen Freunden geteilten Rezepte bleiben lesbar.",
    -- Onglet Nouveautés — v1.11.0
    ["Annuler une commande publique atteint tout le royaume"] = "Das Abbrechen eines öffentlichen Auftrags erreicht jetzt den ganzen Realm",
    ["Une commande publique voyage sur le canal du royaume depuis la v1.10.0, mais pas son annulation : un artisan que tu n'as jamais croisé la voyait « ouverte » pendant six heures, l'acceptait, et farmait les réactifs pour rien. L'annulation part désormais sur le même canal."] =
        "Ein öffentlicher Auftrag reist seit v1.10.0 über den Realm-Kanal, sein Abbruch jedoch nicht. Ein Handwerker, dem du nie begegnet bist, sah ihn bis zu sechs Stunden lang als offen, konnte ihn annehmen und sammelte die Reagenzien umsonst. Der Abbruch geht jetzt über denselben Kanal.",
    ["Poster et annuler ne perdent plus de messages. Le canal exige un clic ou une touche et n'accepte qu'une ligne par seconde : un |cFFFFFFFF/co post|r tapé au chat, ou deux commandes postées dans la même seconde, disparaissaient sans trace. Ces lignes patientent maintenant dans une file et partent à ton prochain clic."] =
        "Aufgeben und Abbrechen verlieren keine Nachrichten mehr. Der Kanal braucht einen Klick oder Tastendruck und nimmt eine Zeile pro Sekunde: ein im Chat getipptes |cFFFFFFFF/co post|r oder zwei Aufträge in derselben Sekunde verschwanden spurlos. Diese Zeilen warten nun in einer Warteschlange und gehen beim nächsten Klick raus.",
    ["Seules les commandes NOUVELLES et les ANNULATIONS voyagent sur le canal, et seulement les publiques. Guilde, amis et commandes nommées restent privées ; les acceptations restent entre les deux joueurs concernés."] =
        "Nur neue Aufträge und Abbrüche reisen über den Kanal, und nur öffentliche. Gilden-, Freundes- und benannte Aufträge bleiben privat; Annahmen bleiben zwischen den beiden beteiligten Spielern.",
    -- Onglet Nouveautés — v1.10.2
    ["Correctif : erreur en combat dans la vue métier"] = "Behoben: Fehler im Kampf in der Berufsansicht",
    ["Sélectionner une recette pendant un combat ne provoque plus d'erreur bloquée : le bouton « Créer » est un bouton sécurisé, que le jeu interdit de masquer en plein combat. L'addon attend maintenant la fin du combat pour l'afficher ou le masquer."] =
        "Ein Rezept während des Kampfes auszuwählen löst keinen blockierten Fehler mehr aus. Der Erstellen-Knopf ist ein geschützter Knopf, den das Spiel mitten im Kampf nicht verbergen lässt. Das Addon wartet nun das Kampfende ab, um ihn ein- oder auszublenden.",
    -- Onglet Nouveautés — v1.10.1
    ["Corrections : qui reçoit les alertes de commandes"] = "Korrekturen: wer Auftragsbenachrichtigungen erhält",
    ["Les alertes de commandes ne dépendent plus du réglage |cFFFFFFFF/co scan|r : le scanner de chat et le carnet partageaient une option par erreur. Une commande publique te prévient désormais dès que tu as le métier."] =
        "Auftragsbenachrichtigungen hängen nicht mehr von deiner |cFFFFFFFF/co scan|r-Einstellung ab. Der Chat-Scanner und das Auftragsbuch teilten sich versehentlich eine Option. Ein öffentlicher Auftrag benachrichtigt dich jetzt, sobald du den Beruf dafür hast.",
    ["Une commande publique portant un objet absent du catalogue arrivait en silence : elle te prévient maintenant, au lieu de dormir dans le carnet."] =
        "Ein öffentlicher Auftrag mit einem Gegenstand, der nicht im Katalog steht, kam bisher lautlos an. Jetzt benachrichtigt er dich, statt unbemerkt im Auftragsbuch zu liegen.",
    ["Démuter un joueur réarme la détection de spam le concernant ; revenir de la vue métier d'un reroll ne laisse plus les boutons Créer masqués ; et l'addon travaille nettement moins à chaque ligne de chat sur un royaume chargé."] =
        "Das Entstummschalten eines Spielers aktiviert die Spam-Erkennung für ihn wieder; die Rückkehr aus der Berufsansicht eines Twinks lässt die Erstellen-Knöpfe nicht mehr verborgen; und das Addon leistet pro Chat-Zeile auf einem stark besuchten Realm deutlich weniger Arbeit.",
    -- Onglet Nouveautés — v1.14.0
    ["Un panneau pour gérer les mis en sourdine"] = "Ein Panel zur Verwaltung von Stummgeschalteten",
    ["L'onglet Artisans a maintenant une section « En sourdine » : chaque joueur muté y apparaît avec sa raison et le temps restant (ou « permanent »), avec un bouton pour le rétablir directement — plus besoin de deviner qui est encore muté."] =
        "Der Handwerker-Reiter hat jetzt einen Bereich „Stummgeschaltet“: jeder stummgeschaltete Spieler erscheint dort mit Grund und verbleibender Zeit (oder „dauerhaft“), mit einem Knopf, um ihn direkt wieder freizuschalten — kein Rätselraten mehr, wer noch stummgeschaltet ist.",
    -- Onglet Nouveautés — v1.9.0
    ["Tes rerolls réunis : cooldowns partagés, une identité, l'onglet Mes artisans"] =
        "Deine Twinks vereint: geteilte Abklingzeiten, eine Identität, ein Tab „Meine Handwerker“",
    ["Cooldowns de recettes partagés : les autres voient « Transmutation : prête » ou « dans 14h » sur ton infobulle d'artisan — fini de demander en canal si ton Arcanite est dispo."] =
        "Geteilte Rezept-Abklingzeiten: andere sehen „Transmutation: bereit“ oder „in 14h“ in deinem Handwerker-Tooltip — kein Nachfragen im Chat mehr, ob dein Arkanit bereit ist.",
    ["Regroupe tes persos sous une identité (|cFFFFFFFF/co alts on|r) : une commande nommée pour ton alchimiste hors ligne arrive sur le perso où tu es connecté, et tu peux l'accepter depuis n'importe lequel. Vérifié des deux côtés (personne ne peut se faire passer pour le reroll d'autrui). Désactivé par défaut."] =
        "Gruppiere deine Charaktere unter einer Identität (|cFFFFFFFF/co alts on|r): ein Auftrag für deinen offline Alchemisten erreicht den Charakter, auf dem du eingeloggt bist, und du kannst ihn von jedem annehmen. Beidseitig bestätigt (niemand kann sich als fremder Twink ausgeben). Standardmäßig aus.",
    ["Nouvel onglet « Mes artisans » : tous les métiers de ton compte sur le royaume en une vue, comme un seul perso — niveau, recettes connues par catégorie, cooldowns en tête, et quel perso porte chaque recette."] =
        "Neuer Tab „Meine Handwerker“: alle Berufe deines Accounts auf dem Realm in einer Ansicht, wie ein einziger Charakter — Stufe, bekannte Rezepte nach Kategorie, Abklingzeiten oben, und welcher Charakter jedes Rezept kennt.",
    ["VU"] = "GESEHEN",
    ["vu crafter (sans l'addon)"] = "beim Herstellen gesehen (ohne Addon)",
    ["vu crafter"] = "beim Herstellen gesehen",
    ["%d+ · vu crafter"] = "%d+ · beim Herstellen gesehen",
    -- Cooldowns de recettes (transmutations & co)
    ["%s : prête"] = "%s: bereit",
    ["%s : dans %s"] = "%s: in %s",
    ["(estimé)"] = "(geschätzt)",
    ["Transmutation"] = "Transmutation",
    ["%dj"] = "%dT", ["%dh"] = "%dh", ["%dmin"] = "%dMin",
    -- Relais partenaire
    ["via %s · il y a %s"] = "via %s · vor %s",
    ["RELAIS"] = "RELAIS",
    -- Rerolls (identité joueur multi-persos, /co alts — opt-in)
    ["rerolls : ACTIVÉS — ta liste de persos est annoncée au réseau."] =
        "Twinks: AKTIVIERT — deine Charakterliste wird im Netzwerk angekündigt.",
    ["rerolls : désactivés — rien n'est annoncé (opt-in : /co alts on)."] =
        "Twinks: deaktiviert — nichts wird angekündigt (Opt-in: /co alts on).",
    ["perso principal (vitrine) : %s"] = "Hauptcharakter (Aushängeschild): %s",
    ["persos du compte (%s) : %s"] = "Charaktere des Accounts (%s): %s",
    ["le lien n'est vérifié chez les autres qu'après une connexion de CHAQUE perso (addon actif)."] =
        "Andere bestätigen die Verknüpfung erst, wenn sich JEDER Charakter einmal eingeloggt hat (Addon aktiv).",
    ["rerolls activés — perso principal : %s (changer : /co alts main <nom>)"] =
        "Twinks aktiviert — Hauptcharakter: %s (ändern: /co alts main <Name>)",
    ["rerolls désactivés — dissolution annoncée au réseau."] =
        "Twinks deaktiviert — Auflösung im Netzwerk angekündigt.",
    ["perso inconnu sur ce compte : %s (connecte-le une fois avec l'addon)"] =
        "Unbekannter Charakter auf diesem Account: %s (einmal mit dem Addon einloggen)",
    ["regrouper tes rerolls (opt-in) : liste annoncée, commandes routées vers ton perso connecté"] =
        "Twinks gruppieren (Opt-in): Liste angekündigt, Aufträge zu deinem Online-Charakter geleitet",
    ["commande nommée pour %s : connecte ce perso, ou active /co alts on pour accepter d'ici."] =
        "Auftrag benannt für %s: logge diesen Charakter ein oder aktiviere /co alts on, um von hier anzunehmen.",
    ["|cFFFFCC00commande pour ton reroll %s|r de |cFFFFFFFF%s|r : %s%s%s"] =
        "|cFFFFCC00Auftrag für deinen Twink %s|r von |cFFFFFFFF%s|r: %s%s%s",
    ["En ligne via %s"] = "Online über %s",
    ["reroll : %s (%s)"] = "Twink: %s (%s)",
}

for k, v in pairs(news) do L[k] = v end
